### PR TITLE
Reset MOUSE_RELEASED mode along with MOUSE_CLICKED on successful mouse click processing

### LINKED ISSUE #3368: Castle screen, closing of income window causes a split dialog to appear
Once we press OKAY here, split dialog window appears, even if there are no possibilities to split army. 
image
image
image
And all my Genies are gone...

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3368

Need to carefully retest drag&drop split mechanics after this change.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , could you please retest most of actions with mouse?

**Comment by Branikolog** [comment]
@ihhub 
Yes!

**Comment by ihhub** [comment]
Hi @Branikolog , could you please check this issue as the highest priority?

**Comment by Branikolog** [comment]
@ihhub 
Haven't found anything essential here.

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for fixing this issue!

**Pull request merged**
