### PR TITLE
Do not allow placing Ultimate Artifact on non-digable terrain in Editor

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR restricts map maker from placing Ultimate Artifact on non-digable tile.

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hi, @zenseii, could you please check the added phrase: `"Ultimate Artifact cannot be placed on non-digable terrain."`

**Comment by Branikolog** [comment]
Hi, @Districh-ru 
The applied changes work well.
However (I suppose it's not related to the PR), I can place UA and later place terrain object over it.
image

**Review by ihhub — APPROVED** [review]

**Comment by Districh-ru** [comment]
Thanks, @zenseii! I've applied your suggestion.

> However (I suppose it's not related to the PR), I can place UA and later place terrain object over it.

Hi, @Branikolog, thanks for testing. Yes, this PR do not add checks for placing other objects on the UA. :( 
Such check is a bit more complex so I suggest to move this task to the [Editor post 1.1 release changes](https://github.com/ihhub/fheroes2/issues/8589).

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this fix!

**Pull request merged**
