### PR TITLE
Fix the mechanics of Genie special ability

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Fix part of #8409 regarding a bug in the game logic.

### CODE REVIEW

**Comment by Alucard648** [comment]
The string that logs Genies ability to insta-kill half of enemy stack should be all caps to empasize extreme nature of creature`s absolute destruction.

**Comment by oleg-derevenetz** [comment]
> The string that logs Genies ability to insta-kill half of enemy stack should be all caps to empasize extreme nature of creature`s absolute destruction.

It contains an exclamation mark at the end :) In any case, this PR is intended to fix the logic of the Genie ability. I don't know for sure why is this message displayed in its current form, but I suppose that this can be corrected/improved later separately if there is such a need.

**Comment by ihhub** [comment]
I am sure @Branikolog is going to fight against changing Genie's special ability chances :)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I am sure @Branikolog is going to fight against changing Genie's special ability chances :)

But they were not changed. `_randomGenerator.Get( 1, 10 ) == 2` in the `master` branch is exactly 10% (one chance in 10). If only there was a `<=` comparison instead of `==`, then it would be a different matter.

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]
Everything works nice!
I hope chances for applying halving were left the same as before.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I hope chances for applying halving were left the same as before.

By the way, this is an ambiguous question :) According to the [game manual](https://handbookhmm.ru/2-monsters) and in fact it was 10%, but it was shown in unit's properties as 20%. Now it is in fact 10% and is shown as 10%.

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz 

> Hi @Branikolog
> 
> > I hope chances for applying halving were left the same as before.
> 
> By the way, this is an ambiguous question :) According to the [game manual](https://handbookhmm.ru/2-monsters) and in fact it was 10%, but it was shown in unit's properties as 20%. Now it is in fact 10% and is shown as 10%.

There was a discussion 1+year ago regarding genies ability. Some players complained, that in fheroes2 "halving" occurred too rare, comparing to the original game. After making 150+ fights I came to conclusion, that in the original game the ability triggered in more than 15% attacks. So that's why it was set to 20% in fheroes2. 
I'm not sure we should roll this change back, since players got used to more frequent triggering and the overall weakness of this troop without this special ability.

**Comment by oleg-derevenetz** [comment]
@Branikolog the funny thing is that change to 20% was obviously made in wrong way. Currently in the `master` branch the logic looks like this: `if ( _randomGenerator.Get( 1, 10 ) == 2) {... perform the having... }`, i.e. some random number in the range of 1...10 is taken and if this number is 2 (not less than or equal to 2!) then the halving is performed, so currently in the `master` branch the chance is still 10%. So in fact this PR changes nothing in regard to actual chance to trigger this ability, it just fixes the wrong chance displayed in the unit's properties. I can make the actual chance (as well as displayed chance) 20% if you wish.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

> @Branikolog the funny thing is that change to 20% was obviously made in wrong way. Currently in the `master` branch the logic looks like this: `if ( _randomGenerator.Get( 1, 10 ) == 2) {... perform the halving...}`, i.e. some random number in the range of 1...10 is taken and if this number is 2 (not less than or equal to 2!) then the halving is performed, so currently in the `master` branch the chance is still 10%. So in fact this PR changes nothing in regard to actual chance to trigger this ability, it just fixes the wrong chance displayed in the unit's properties. I can make the actual chance (as well as displayed chance) 20% if you wish.

To be honest, I don't remember, whether I've tested triggering chances in fheroes2. I was mainly focused on testing the original game leaving the implementation in fheroes2 to the development/contribution team.

I'm a bit busy this week, so I cannot perform deep tests. But I can try to make another set of Genies tests in the OG later to be assured, that 20% is an actual chance for triggering.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I'm a bit busy this week, so I cannot perform deep tests. But I can try to make another set of Genies tests in the OG later to be assured, that 20% is an actual chance for triggering.

Currently with this PR the chance of triggering is 10%, and it was 10% before merging of this PR too due to an implementation error. Judging by the fact that no one actually noticed this error, it seems that 10% is fine. I can change it to 20% if you want.

**Pull request merged**
