### PR TITLE
I1858 fix CanMove method

### PR DESCRIPTION
**Pull request by shprotru**
Fix of #1858

### CODE REVIEW

**Comment by shprotru** [comment]
Hi, @ihhub! Additionally, I noticed, that CanMove takes into account on `Skill::Secondary::PATHFINDING`, but not `Skill::Secondary::NAVIGATION`. Is it worth taking into account this skill in this method?

**Comment by idshibanov** [comment]
> 
> 
> Hi, @ihhub! Additionally, I noticed, that CanMove takes into account on `Skill::Secondary::PATHFINDING`, but not `Skill::Secondary::NAVIGATION`. Is it worth taking into account this skill in this method?

No need to take it into account. Navigation matches Logistics skill, and pathfinding check is special in this case. It is passed in because my pathfinder per-calculates all moves before you execute them and to determine shortest path you have to know if certain terrain is slower.

Good catch.

**Comment by ihhub** [comment]
Hi @idshibanov , do you have any comments on this change?

**Comment by ihhub** [comment]
@shprotru , excellent work! Well done!

**Pull request merged**
