### PR TITLE
Allow switching heroes in hero dialog if it was opened from meeting dialog

### LINKED ISSUE #3262: Hero Meeting, it should be possible to consult the other heroes when two heroes are in meeting
In fheroes2, it should be possible to consult the other heroes when two heroes are in meeting.

In original game:

https://user-images.githubusercontent.com/43583994/115888432-35fdd300-a453-11eb-974b-4f6586a2f35f.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/115888531-50d04780-a453-11eb-9a99-5352ae62418d.mp4

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3262

Also make dismiss button behavior more OG-like - in OG it is disabled only if this specific hero can't be dismissed due to map scenario, and is hidden in other cases.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hello, @oleg-derevenetz 
I hope, I understand you correctly...
Inactive "Dismiss" button was added some time ago, as it's more user-friendly to watch button inactive, rather then wonder, why it disappeared for some reason. New players cannot know the cases when they are not able to dismiss hero... #588
In the OG we're able dismiss quest hero: I've recently tested Archibald campaign, where I managed to dismiss him that lead to immediate lose of scenario. :)
While in my recent test of campaign in fheroes2 this button was in disabled state with a description in bottom info bar. It looked like: "Cannot dismiss hero, read scenario description for more info".
I find this so informative... I think in future I'll create a new thread for adding a similar description for the case, when player cannot dismiss visiting hero in a castle.
I believe, it should be hidden only for unhired (or allied) heroes...

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Currently we can't dismiss hero in the following cases:

1. If we open hero dialog for the hero in the castle. "DISMISS" button is hidden like in OG;
2. If we open hero dialog from the meeting screen. "DISMISS" button is hidden like in OG;
3. If we open hero dialog from hero level up dialog, troop recruit dialog or troop hire dialog. Ability to open such dialogs is absent in OG and "DISMISS" button is also hidden in this case;
4. If hero have the NOTDISMISS mode (starting hero in scenario with "Lose Hero" as loss condition). In this case "DISMISS" button is disabled and "Cannot dismiss hero, read scenario description for more info" description is shown for this button.

It's able to always disable "DISMISS" button in all cases 1-3 instead of hiding it (like in OG), but I think that description should be changed then.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz!
I think, it would be nice if we add a description for disabled button, while hero is in a castle, in future PRs... 
For all other cases the button can be hidden then.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I think, it would be nice if we add a description for disabled button, while hero is in a castle, in future PRs...

I added an appropriate description for this case in this PR.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank a lot for improving this logic!

**Pull request merged**
