### PR TITLE
Fix items list update after deleting an item: fix dismissing a hero from the Kingdom Overview dialog

### LINKED ISSUE #7989: Adventure map, hero list bug after dismissing a hero
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/96478c3d-a7b3-4f9e-a688-3b1cd5de4c43

Hero list has multiple issues when a hero is dismissed through kingdom overview window.

Current hero selection disappears. 
Hero list is not updated properly.

### Save file

[Hero list.zip](https://github.com/ihhub/fheroes2/files/13166232/Hero.list.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #7989

This PR:
- fixes update for all types of lists (in example, save file lists) after item remove;
- disables the forced rendering of game buttons (next hero, move hero, ...) on hero focus change and castle focus change;
- removes redundant `ResetFocus()` for every frame of hero movement: `ResetFocus()` is called by `~FocusUpdater()` in `Action()` method for move to each tile;
- adds hero/castle cursor setting when no hero or castle is in focus;
- fixes redraw type setting for heroes/castles icons: in master build both lists were updated regardless of which one was specified in redraw mask;
- changes icons and focus update behavior on hero recruitment (including rescuing from Jail) and dismiss/loss;
- includes minor code clean-up;
- fixes a bug of Kingdom Overview when a hero was dismissed and there are less than 4 heroes left in the kingdom:
bug

https://github.com/ihhub/fheroes2/assets/113276641/89e93106-a074-4789-b37b-a490d90e0e37

When testing this PR please pay attention to icons and slider rendering and ambient sound and music update when:
- selecting a hero/castle;
- switching heroes/castles opened from Kingdom overview;
- losing battles by hero/castle;
- recruiting/rescuing a hero;
- dismissing a hero;
- moving a hero.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hello, @Districh-ru 

For higher resolutions there's no need to update hero scrollbar before we exit kingdom overview window:

https://github.com/ihhub/fheroes2/assets/55348946/6e76b84b-f40f-40ca-a887-28ea8ed77874

Or the whole list should be updated (removing hero portraits on the go).

**Comment by Districh-ru** [comment]
Hello, @Branikolog, now the list and the scrollbar are updated only after the dialog is closed (the same for the Castle dialog).
This PR now includes more fixes (please check the updated PR topic). Could you please check them in your spare time.

**Comment by Districh-ru** [comment]
Hello, @drevoborod ! Could you please test this PR when you have time.

**Review by ihhub — APPROVED** [review]

**Comment by drevoborod** [comment]
Minor issue found: after the hero diggs, the "Hero movement" button doesn't change its state to disabled if it was active before digging.

**Comment by Districh-ru** [comment]
> Minor issue found: after the hero diggs, the "Hero movement" button doesn't change its state to disabled if it was active before digging.

@drevoborod, thanks for testing!
This bug also occurs in the master build. It will be addressed it in a separate PR.

**Comment by drevoborod** [comment]
I haven't found any issues.

**Review by Branikolog — APPROVED** [review]
@Districh-ru 
Great work!

**Comment by ihhub** [comment]
@Districh-ru , thanks a lot for these changes!

**Pull request merged**
