### PR TITLE
WorldPathfinder: implement "last move" logic, fix wrong penalty calculation algorithm

### LINKED ISSUE #1986: Adventure map, hero with 0 movement points selected with the "Next Hero" button, also the hero should be able to make his last move over all types of terrain
The hero Roxana has 0 movement points.
However the hero Roxanna is selected when the "Next Hero" button is pressed several times.

**Edit 2020/10/14.**
The hero should be able to make his last move over all types of terrain and in all directions from the road penalty.
And this should also be indicated in the hero's movement bar (a portion of the bar should be yellow) and the movement information should indicate "Move points: 1/85/1560".

Roxana move left fh2 coupé 01

In fheroes2:

Hero 0 move next hero fh2 01

Here is the save file:
[Hero 0 move next hero fh2 01.zip](https://github.com/ihhub/fheroes2/files/5372627/Hero.0.move.next.hero.fh2.01.zip)

**Edit 2020/10/18.**
Another save for this bug.

The hero Troyan is located on the Swamp terrain which has a 175% movement penalty.
Troyan has 138 movement points left.
For her last move, Troyan should not be able to move because it is the penalty for the terrain where she is located that is taken into account.
However, Troyan can make a move on the Lava terrain which has a 100% movement penalty when she shouldn't be able to.

In fheroes2:

Troyan move fh2 01

Troyan move fh2 02

Here is the save file:
[Troyan move fh2 01.zip](https://github.com/ihhub/fheroes2/files/5397833/Troyan.move.fh2.01.zip)

### LINKED ISSUE #2200: Adventure map, the hero's path is changed to a non-optimal path
In fheroes2, in the example, the path of the hero is changed to a non-optimal path.

In the first screenshot, the hero Ector can attack the hero Jezebel if the proposed path is validated.

In the second screenshot, the hero Ector has moved two squares to the west, and now the proposed path is not the same and the hero Ector cannot attack the Jezebel hero if the proposed path is validated.

However, in the third screenshot, the hero Ector can still attack the hero Jezebel if he first moves one square to the west.

In fheroes2:

Hero path change fh2 01

Hero path change fh2 02

Hero path change fh2 03

Here is the save file:
[Hero path change fh2 01.zip](https://github.com/ihhub/fheroes2/files/5511987/Hero.path.change.fh2.01.zip)

### LINKED ISSUE #2583: Pathfinding issue, not optimal path
Hero has enough movement points to reach the needed cell, but when there's other hero there, hero lacks movement points.
image
image

### LINKED ISSUE #4510: Adventure map, optimization of the hero's predefined path
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the hero's predefined path favors horizontal and vertical moves first, rather than diagonal moves, which allows the hero to benefit from the bonus given to the last move (if the hero can move horizontally or vertically then he can move diagonally).

In fheroes2, this is not the case, and it penalizes the hero by reducing his movement.

In the original game (the hero's predefined path favors horizontal and vertical moves first):

Optimize hero path 001

In fheroes2 (the hero's predefined path first makes a diagonal move and the hero cannot reach the last square):

Optimize hero path 002
Optimize hero path 003
Optimize hero path 004

In fheroes2 (by "manually" moving the hero horizontally as far as possible, the hero can move diagonally into the last square):
Optimize hero path 005
Optimize hero path 006

I noticed a lot of differences between the original game and fheroes2 in the hero's predefined path due to this during my test on passability.
Here are all screenshots for passibility and predefined path differences:
https://drive.google.com/file/d/12eG_uOTrI7wSsnGJBagfvu8AGQ-qxAD0/view?usp=sharing

### Save file

Here is the test scenario file:
[0 9953a4.zip](https://github.com/ihhub/fheroes2/files/7428913/0.9953a4.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #1986
fix #2200
fix #2583
fix #4510

Please note that, while this change applies to AI-controlled heroes too, sometimes AI uses the `AIWorldPathfinder` apart from the some specific hero (for some strategic planning I believe). In this case "last move" logic will not be used - due to natural reasons.

### CODE REVIEW

**Comment by ihhub** [comment]
I think this pull request also is related to #4464 .

**Comment by ihhub** [comment]
Hi @Branikolog , can you please test these changes?

**Comment by Branikolog** [comment]
Hi, @ihhub & @oleg-derevenetz !
It's actually so hard to test so huge part of game logic. (As well as reimplement it from a scratch, for sure!)
I've found one issue... Not sure it's the only one, but at least it is an essential one:
While trying to make one last move hero creates weird path:
image

**Comment by Branikolog** [comment]
Also, I've noticed, that comparing to the OG we can make one movement more:
fheroes2:
image
OG:
image

And diagonal path is not the same to OG.
fheroes2:
image
OG:
image

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> While trying to make one last move hero creates weird path:

Could you please attach a savefile?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Sure!
[Paths.zip](https://github.com/ihhub/fheroes2/files/7531875/Paths.zip)

**Comment by oleg-derevenetz** [comment]
@Branikolog Thank you! Could you please attach the map file itself so I can try to figure out how the OG calculates movepoints?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Here it is!
[Map_0086.zip](https://github.com/ihhub/fheroes2/files/7531899/Map_0086.zip)

**Comment by oleg-derevenetz** [comment]
> While trying to make one last move hero creates weird path:

This issue seems to be fixed now:

Screenshot 1
Screenshot 2
Screenshot 3

> Also, I've noticed, that comparing to the OG we can make one movement more:

Honestly, I don't get it. Hero has 75 move points on the penultimate cell (southwest from Stone Lith) and he's on the road (movement cost 75 mp), so he would be able to do this diagonal move. Another obscure rule I don't know? :)

> And diagonal path is not the same to OG.

These paths are equivalent in terms of move point consumption (both contains one move to the right over the sand and 2 diagonal moves, just in different order), so it is rather an accident that one was chosen and not the other.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Could you, please, look at the issue, I've just found?
For some reason path is different for one cell:
image
Other cells have diagonal path here:
image
image
[G-path.zip](https://github.com/ihhub/fheroes2/files/7532152/G-path.zip)

**Comment by oleg-derevenetz** [comment]
@Branikolog In current implementation, last move consumes all remaining move points of a hero, so sometimes, for example, when hero has 200MP, there is no difference for a pathfinder between "make a diagonal move from a road to a desert (200MP)" and "make a straight move on a road (75MP) and then a straight move to a desert (remaining 125MP), they are equivalent, so it is free to choose either of them.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Okay!
What about this move?
image

In the OG it looks more straight:
image

**Comment by oleg-derevenetz** [comment]
@Branikolog

> What about this move?

Hm-m. In this position:

Screenshot

hero have 400MP. So if he makes the diagonal move to the snow, he will have 400 - 175 * 1.5 = 138MP, while with two straight moves instead he will have 400 - 75 - 175 = 150MP, so it is more effective to make two straight moves. I have no idea why OG prefers diagonal move here.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu could you be so kind and clarify something for me? I have a few questions regarding pathfinding:

* **_At any step_**, it's the penalty of the **_from_** tile is accounted, not the penalty of the **_to_** tile, isn't it? For example, if hero stands on the grass and is going to move to the desert in the straight direction, then this will cost 100MP to him. Or, if hero stands on the desert and is going to move to the grass in the straight direction, then it will cost 200MP to him. Am I right?
* Road penalty (75 MP) applies **_only_** if hero moves from road tile to road tile? And if he moves in the diagonal direction, there is also 150% penalty applies?
* What if hero moves from regular tile to the road tile? Is there any reward for it? If he moves from desert to road in the straight direction, will it cost 200MP or less? What if this happens in diagonal direction?
* What if hero moves from the road tile to the regular tile? For example, if he moves from the road on the grass to the desert tile in straight direction? How many should this cost for him? What if the same happens in diagonal direction?

I have an impression that current pathfinding is wrong due to wrong costs. Currently there is the penalty of the **_to_** tile is accounted, not the penalty of the **_from_** tile. And it is hard to debug this in OG because nowhere to see the exact information about move points.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog and @LeHerosInconnu can I ask you to take a look at this PR once again? I have an impression that pathfinding should now become much more closer to OG than before.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> EDIT: aha, have read [this](https://handbookhmm.ru/2-logistics) and I was right. So this issue is solved (and many others I suppose that were related to wrong penalty source):

I was preparing a response for you, but I see you finally found the link to this famous site and edited your post. :D
I'm still putting the screens I prepared (but without the comments), the test scenario file, and links to answers on the same subject, just in case. :)
And yes, as you noticed, the terrain penalty related to the hero's path is not correctly applied in fheroes2 currently.
I thought it was clear to you. :)

@oleg-derevenetz.

> @LeHerosInconnu
> 
> > In fheroes2, this is not correct compared to the original game.
> > The square just south of the city entrance should not be a road and should not have the road penalty.
> > Tell me if it is preferable to open another issue for this.
> 
> It seemed to me that I already saw an issue about this (or at least a mention that town/castle exits are roads), but I wasn't able to find it so far. If this is wrong, then maybe it will be better to open a separate issue for this.

The square where the entrance to the city is located (the active square of the city) should not be confused with the square just south of the city entrance.
Yes, I will open another issue for that. (https://github.com/ihhub/fheroes2/issues/4632)

This is what you are looking for:
Related issue: https://github.com/ihhub/fheroes2/issues/2602.
Related discussion: https://github.com/ihhub/fheroes2/discussions/2606.

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/1986#issuecomment-968061408_

Hello @Branikolog,

> But in other part, when hero walks out of city we have penalty 75... Can't find out the root of this behaviour.

There is certainly a portion of road right under the entrance of the castle, so the 75% penalty of the road is applied.

Hello @ihhub,

Don't always trust the manual; it can sometimes be wrong or give approximate information.
(Often the manual is even written before the game is completely finished.)

For Snow the manual indicates:
Terrain: No Pathfinding - Basic Pathfinding - Advanced Pathfinding  - Expert Pathfinding
Snow: 175% - 150% - 100% - 100%
As you can see, the progression is not regular (100% instead of 125% for Advanced Pathfinding).
I don't know if this is intentional or a mistake (from the manual and/or during the game).

The penalties should be either:
Snow: 175% - 150% - 125% - 100%

Or:
Snow: 150% - 125% - 100% - 100%

Currently, unless I am mistaken, in fheroes2, it's:
Snow: 175% - 150% - 125% - 100%
Personaly, I'm okay with that (as the progression is more regular). :)

Again, it is the penalty of the terrain the hero is on before the move that must be taken into account and not the penalty of the terrain the hero will be on after making the move.
Take a look at this: https://handbookhmm.ru/2-logistics.

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/2602#issuecomment-809574279_

Comparison of the hero path between Heroes 2 and fheroes2:
Heroes 2 first, fheroes2 second.

Hero path penalty 001
Hero path penalty fh2 001

Hero path penalty 002
Hero path penalty fh2 002

Hero path penalty 003
Hero path penalty fh2 003

Hero path penalty 004
Hero path penalty fh2 004

Hero path penalty 005
Hero path penalty fh2 005

Hero path penalty 006
Hero path penalty fh2 006

Hero path penalty 007
Hero path penalty fh2 007

Hero path penalty 008
Hero path penalty fh2 008

Here is the test scenario file:
[0 9950.zip](https://github.com/ihhub/fheroes2/files/7542281/0.9950.zip)

> Hi @Branikolog and @LeHerosInconnu can I ask you to take a look at this PR once again? I have an impression that pathfinding should now become much more closer to OG than before.

I will look at this, but later tomorrow, it's time to leave. :)

**Comment by zenseii** [comment]
> Don't always trust the manual; it can sometimes be wrong or give approximate information. (Often the manual is even written before the game is completely finished.)
@LeHerosInconnu I've noticed in several of the Heroes games that the accompanying Readme file has comments from the devs on what errors the manual has, some patches sometimes add more info to the readme file if more errors are found. Have you looked at these to see if there are any answers?

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> I was preparing a response for you, but I see you finally found the link to this famous site and edited your post. :D

Thank you anyway :)

> And yes, as you noticed, the terrain penalty related to the hero's path is not correctly applied in fheroes2 currently.
I thought it was clear to you. :)

No, it wasn't, because this mistake was so obvious that it should have been fixed a long ago :) I was planning to fix just the issue with last move, and I didn't expect that basic tile penalty calculation is still so wrong.

> The penalties should be either:
> Snow: 175% - 150% - 125% - 100%
> 
> Or:
> Snow: 150% - 125% - 100% - 100%
> 
> Currently, unless I am mistaken, in fheroes2, it's:
> Snow: 175% - 150% - 125% - 100%

Now they are 150 - 125 - 100 - 100.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii and @oleg-derevenetz,

> > Don't always trust the manual; it can sometimes be wrong or give approximate information. (Often the manual is even written before the game is completely finished.)
> 
> @LeHerosInconnu I've noticed in several of the Heroes games that the accompanying Readme file has comments from the devs on what errors the manual has, some patches sometimes add more info to the readme file if more errors are found. Have you looked at these to see if there are any answers?

Yes, I checked the readme files and there is nothing about this.

> > And yes, as you noticed, the terrain penalty related to the hero's path is not correctly applied in fheroes2 currently.
> > I thought it was clear to you. :)
> 
> No, it wasn't, because this mistake was so obvious that it should have been fixed a long ago :) I was planning to fix just the issue with last move, and I didn't expect that basic tile penalty calculation is still so wrong.

It is mentioned here https://github.com/ihhub/fheroes2/issues/1986, for example. :)

> > The penalties should be either:
> > Snow: 175% - 150% - 125% - 100%
> > Or:
> > Snow: 150% - 125% - 100% - 100%
> > Currently, unless I am mistaken, in fheroes2, it's:
> > Snow: 175% - 150% - 125% - 100%
> 
> In this PR they are 150 - 125 - 100 - 100.

Okay, I'll take that into account.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

Some remarks after a quick test.
Heroes 2 first, fheroes2 second.

The arrow of the path positioned over the road should be shorter to indicate the road penalty (note that it is not the hero's movement penalty but the terrain penalty, although the hero's Pathfinding skill should be taken into account for the arrow length).
In the original game, there is a bug, this road is considered as "Grass" terrain.
In fheroes2, the road is correctly taken into account with the penalty of 75%.
Path penalty optimize 001
Path penalty optimize 002
Path penalty optimize 003
Path penalty optimize 004

The shorter arrow of the path over the road.
Path penalty optimize 001 a

In fheroes2, the predefined path does not privilege the horizontal movement in priority.
Path penalty optimize 005
Path penalty optimize 006

Not sure why this predefined path in Heroes 2, the one in fheroes2 seems better.
Path penalty optimize 007
Path penalty optimize 008

In fheroes2, the predefined path does not privilege the horizontal movement in priority, and the hero doesn't go as far.
Path penalty optimize 009
Path penalty optimize 010

It's all right. :)
Path penalty optimize 011
Path penalty optimize 012

In fheroes2, the predefined path does not privilege the horizontal movement in priority.
Path penalty optimize 013
Path penalty optimize 014

The arrow of the path positioned over the road should be shorter to indicate the road penalty.
Path penalty optimize 015
Path penalty optimize 016
Path penalty optimize 017
Path penalty optimize 018
Path penalty optimize 019
Path penalty optimize 022
Path penalty optimize 023

It's all right too. :)
Path penalty optimize 020
Path penalty optimize 021

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> In fheroes2, the predefined path does not privilege the horizontal movement in priority.

There are 1 straight movement sand->grass, 7 straight movements over the grass and 2 diagonal movements over the grass in both cases, just in different order. Both paths are equivalent, no reason to privilege the horizontal movement in this case, there is no benefit.

> In fheroes2, the predefined path does not privilege the horizontal movement in priority.

Again, there are 3 straight moves over the grass and 2 diagonal moves in both cases, just in different order, no benefit to privilege horizontal movement here.

> The arrow of the path positioned over the road should be shorter to indicate the road penalty.

I don't see any difference between OG and fheroes2 here (at least from mobile). I'm not really sure that there are shorter variants of rotated arrows BTW. 

> In fheroes2, the predefined path does not privilege the horizontal movement in priority, and the hero doesn't go as far.

This one seems strange, I'll take a look later today. BTW it looks like a mirror of OG's path from here:

> Not sure why this predefined path in Heroes 2, the one in fheroes2 seems better.

Just with different (equivalent) order of straight and diagonal movements.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> Not sure why this predefined path in Heroes 2, the one in fheroes2 seems better.

It seems that in fheroes2 last move benefits from road penalty on the penultimate tile, while in OG it does not.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > In fheroes2, the predefined path does not privilege the horizontal movement in priority.
> 
> There are 1 straight movement sand->grass, 7 straight movements over the grass and 2 diagonal movements over the grass in both cases, just in different order. Both paths are equivalent, both cost the same amount of movement points, no reason to privilege the horizontal movement in this case, there is no benefit.
> 
> > In fheroes2, the predefined path does not privilege the horizontal movement in priority.
> 
> Again, there are 3 straight moves over the grass and 2 diagonal moves in both cases, just in different order, paths are equivalent, there is no benefit to privilege horizontal movement here.

Except that if the player interrupts the hero's movement and defines a new destination, the points saved by the preference of horizontal or vertical movement can be useful.
It is necessary to think about everything. :)

> > The arrow of the path positioned over the road should be shorter to indicate the road penalty.
> 
> I don't see any difference between OG and fheroes2 here (at least from mobile).

As I wrote:
"In the original game, there is a bug, this road is considered as "Grass" terrain.
In fheroes2, the road is correctly taken into account with the penalty of 75%."
So yes, the arrows are the same length on the screenshots, but they should not be in fheroes2 because the road is considered as a road and not as a "Grass" terrain as in the original game.

> I'm not really sure that there are shorter variants of rotated arrows BTW.

Yes, there is.

In fheroes2:

Path road turn flèche 01

> > In fheroes2, the predefined path does not privilege the horizontal movement in priority, and the hero doesn't go as far.
> 
> This one seems strange, I'll take a look later today.

Okay.

> @LeHerosInconnu
> 
> > Not sure why this predefined path in Heroes 2, the one in fheroes2 seems better.
> 
> It seems that in fheroes2 last move benefits from road penalty on the penultimate tile in this particular case, while in OG it does not.

Ah yes, I see, and as I wrote:
"In the original game, there is a bug, this road is considered as "Grass" terrain.
In fheroes2, the road is correctly taken into account with the penalty of 75%." :D

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> Except that if the player interrupts the hero's movement and defines a new destination, the points saved by the preference of horizontal or vertical movement can be useful. It is necessary to think about everything. :)

I propose to take optimizations based on predicting the possible future beyond the scope of this PR for now :) Let's perform improvements step by step and start with more important fixes of penalty calculation first.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > Except that if the player interrupts the hero's movement and defines a new destination, the points saved by the preference of horizontal or vertical movement can be useful. It is necessary to think about everything. :)
> 
> I propose to take optimizations based on predicting the possible future beyond the scope of this PR for now :) Let's perform improvements step by step and start with more important fixes of penalty calculation first.

Okay.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> In fheroes2, the predefined path does not privilege the horizontal movement in priority, and the hero doesn't go as far.
> Path penalty optimize 009
> Path penalty optimize 010

This case is interesting. You see, OG's path costs 1000 + 200 * 1.5 = 1300MP, while fheroes2 path costs 1000 + 100 + 200 = 1300MP, so both paths are equivalent in terms of movement points. In both cases the remaining part of the path (which must be completed the next day) is equivalent as well (300MP in both cases).

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> The arrow of the path positioned over the road should be shorter to indicate the road penalty.

The arrow length on roads should be fixed now:

Arrow on road

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > In fheroes2, the predefined path does not privilege the horizontal movement in priority, and the hero doesn't go as far.
> > Path penalty optimize 009
> > Path penalty optimize 010
> 
> This case is interesting. You see, OG's path costs 1000 + 200 * 1.5 = 1300MP, while fheroes2 path costs 1000 + 100 + 200 = 1300MP, so both paths are equivalent in terms of movement points. In both cases the remaining part of the path (which must be completed the next day) is equivalent as well (300MP in both cases).

In Heroes 2, the hero has 1000 movement points (slowest troop speed 2).
The hero moves 9 steps horizontally (penalty 100 points from the "Grass" terrain), that is 900 points.
The hero has 100 points left.
The last step is done diagonally (penalty 150 points from the "Grass" terrain) but can be done because it is the last step of the hero and he can do a horizontal or vertical step (penalty 100 points from the "Grass" terrain)).

In fheroes2, the hero also has 1000 movement points (slowest troop speed 2).
The hero moves a first step diagonally (penalty 150 points from the "Grass" terrain).
Then the hero moves 4 steps horizontally (penalty 100 points from the "Grass" terrain).
Then a second step diagonally (penalty 150 points from the "Grass" terrain).
The hero moves again 3 more steps horizontally (penalty 100 points from the "Grass" terrain).
That is a total of 150 + (4 x 100) + 150 + (3 x 100) = 1000 movement points.

In Heroes 2, the next turn, the hero will move diagonally (penalty 300 from the "desert" terrain).
In fheroes 2, the next turn, to be on the same square, the hero will have to move one step horizontally (penalty 100 from the "Grass" terrain) and then a second step horizontally (penalty 200 from the "Desert" terrain).

So in fheroes 2, the next turn, to be on the same square, the hero will use 2 movement points against only one in Heroes 2 even if, in the end, the number of movement points spent remains the same.

But in the case where the player stops the hero's movement after 3 steps, the hero would have 50 extra movement points left in Heroes 2 compared to fheroes2.
And in the case where the player stops the hero's movement after 7 steps, the hero would have 100 extra movement points left in Heroes 2 compared to fheroes2.
Here, we can see the advantage of moving horizontally and vertically first. :)

> @LeHerosInconnu
> 
> > The arrow of the path positioned over the road should be shorter to indicate the road penalty.
> 
> The arrow length on roads should be fixed now:
> 
> Arrow on road

Nice, I will check this and other possible changes tomorrow.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> So in fheroes 2, the next turn, to be on the same square, the hero will use 2 movement points against only one in Heroes 2 even if, in the end, the number of movement points spent remains the same.

He will make two **_moves_** in fheroes2 against one **_move_** in OG, but the amount of **_movement points_** spent will be the same: 100 + 200 (300) in fheroes2 and 200 * 1.5 (300) in OG.

> But in the case where the player stops the hero's movement after 3 steps

Let's postpone the question "what if player stops movement ahead of time" for now :)

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Nice, I will check this and other possible changes tomorrow.

I did a quick test and started a scenario to test this PR.
I did find some other bugs as usual, :D but I have nothing to report for the moment regarding this PR.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hello @oleg-derevenetz,
> 
> > Nice, I will check this and other possible changes tomorrow.
> 
> I did a quick test and started a scenario to test this PR. I did find some other bugs as usual, :D but I have nothing to report for the moment regarding this PR.

I have completed my test scenario, and I have not encountered any problems.
I did, however, observe some weird paths compared to the original game.

Original game:

Path sawmill 001

Path sawmill 001a

In fheroes2:

Path sawmill 002

Here are the save files:
[Path to sawmill 01.zip](https://github.com/ihhub/fheroes2/files/7574793/Path.to.sawmill.01.zip)

Also, I couldn't test some problems I encountered in previous games because the save files are not compatible anymore.
Maybe you could wait if @Branikolog wants to do other specific tests.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> I did, however, observe some weird paths compared to the original game.

What's weird about this path? In both cases hero have an identical way first (2 moves to the road and 1 over the road), and then 5 diagonal moves and 3 straight moves over the same terrain, just in different order, 11 moves total. Both paths looks equivalent in terms of movement points (let's postpone the "what if hero will be prematurely stopped by the player" question).

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> Hi @LeHerosInconnu
> 
> > I did, however, observe some weird paths compared to the original game.
> 
> What's weird about this path? In both cases hero have an identical way first (2 moves to the road and 1 over the road), and then 5 diagonal moves and 3 straight moves over the same terrain, just in different order, 11 moves total. Both paths looks equivalent in terms of movement points (let's postpone the "what if hero will be prematurely stopped by the player" question).

I mean visually weird, the hero "zig-zagging" around the trees near the graveyard. :)

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu BTW, regarding the "cheaper moves first" optimization - in the general case, it is not possible (without some psychic powers in the game engine designed to predict the future). Consider the following case: there are two equivalent hypothetical paths to the same tile:

100 - 200 - 200 - 100
200 - 100 - 100 - 200

Both paths cost 600 MP. If a hero with 1000 MP was stopped on both paths after first move, he will have 900 MP on the first path and 800 MP on the second path. It would seem that the first path is more profitable? But it's not if the same hero will be stopped after third move, because on the first path he will have 500 MP, while on the second path he will have 600 MP.

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu BTW, regarding the "cheaper moves first" optimization - in the general case, it is not possible (without some psychic powers in the game engine designed to predict the future). Consider the following case: there are two equivalent hypothetical paths to the same tile:
> 
> 100 - 200 - 200 - 100
> 200 - 100 - 100 - 200
> 
> Both paths cost 600 MP. If a hero with 1000 MP was stopped on both paths after first move, he will have 900 MP on the first path and 800 MP on the second path. It would seem that the first path is more profitable? But it's not if the same hero will be stopped after third move, because on the first path he will have 500 MP, while on the second path he will have 600 MP.

I think a simple rule should be applied that says that if the cost in movement points is the same for two paths then choose the path that spends the least amount of movement points for the first step (re-calculated after each step).
In fact consider that the player will always stop the hero's movement the earliest.

**Comment by ihhub** [comment]
@oleg-derevenetz and @LeHerosInconnu , I was about to interfere and pause all future fixes and enhancements for this area. It's better to do step by step improvement rather than trying to fix everything in one shot. Let's do the rest of changes in a separate pull request. If we have a **better** code right now we should go with it.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz  and @LeHerosInconnu , my note in respect to the shape of a path: our main priority is to make the logic work first so I'm okay to accept the fact of different route which is resulting in the same amount of move points. Later once the logic is stable we can find a way to replicate (or not) the original game's way of making a path.

**Comment by ihhub** [comment]
@oleg-derevenetz , great work! Thank you so much for fixing these pathfinding issues!

**Pull request merged**
