### PR TITLE
Music: xmi2mid rework

### LINKED ISSUE #509: XMI2MID produces incorrect midi data
Current implementation is pretty bad, producing cacophony instead of beautiful soundtrack. Note length is the biggest issue. XMI is a known format used in other games, so it shouldn't be that hard to find more information on structure.

This is very evident when listening to the town music (especially Sorceress), however even in the main menu it is noticeable.

### PR DESCRIPTION
**Pull request by idshibanov**
Parsing MIDI metadata and adding it to the track.
Updating ppqn value based on the meta.
Parsing and using XMI duration correctly to make sure notes are turned off when supposed to.
Improved variable naming and added comments to make code more readable.

Fixes #509

### CODE REVIEW

**Comment by idshibanov** [comment]
I spent way too much time with hex editor for this one..

**Comment by ihhub** [comment]
Hi @idshibanov , sorry for a little stupid question but can we hear the difference in music (from demo) after the changes?

**Comment by ihhub** [comment]
> Hi @idshibanov , sorry for a little stupid question but can we hear the difference in music (from demo) after the changes?

Never mind, I checked myself :) It's huge difference!

**Comment by ihhub** [comment]
@idshibanov amazing work! Great thanks for your non-stop contribution!

**Pull request merged**
