### PR TITLE
Fix elements layout for oracle/thieves dialog

### PR DESCRIPTION
**Pull request by undef21**
This variant is more likely with OG.

Снимок экрана_2021-05-04_22-37-40

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, could you please check this UI changes?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, could you please check these UI changes?

All elements are present, but the position of all elements is not correct.
Also, for the flag sprite, in the original version there is a white dot in the top right corner of the flag pole which is not present in fheroes2, and the colored dots in the flags are not the same.

In original game:

Oracle H2 01

In fheroes2:

Oracle fh2 01

**Comment by undef21** [comment]
> Снимок экрана_2021-05-04_22-37-40

Hello, @LeHerosInconnu. Do you compare OG with this variant?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , if you need to download exactly the version with these changes please follow [this instruction](https://github.com/ihhub/fheroes2/wiki/Download-Windows-latest-compiled-packages-of-a-pull-request).

**Comment by LeHerosInconnu** [comment]
Hi @undef21 and @ihhub,

> Hello, @LeHerosInconnu. Do you compare OG with this variant?

I compared the English Gold version of the original game with the fheroes2 0.9.3 3370 version (Windows x64 build with SDL2 support).

All positions are correct in this version (pull request).
The graphical differences concerning flags are quite present.

In original game:

Oracle H2 recadré 01

In fheroes2 (pull request):

117061813-4d7a6d00-ad2b-11eb-93e6-9ff409cb2ba7 recadré

> Hi @LeHerosInconnu , if you need to download exactly the version with these changes please follow [this instruction](https://github.com/ihhub/fheroes2/wiki/Download-Windows-latest-compiled-packages-of-a-pull-request).

It's okay, I compared it with the included image.

**Comment by ihhub** [comment]
For flags we can create a separate pull request as this pull request was targeted to fix alignment of elements.

**Comment by ihhub** [comment]
@undef21 thank you so much for this improvement!

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> For flags we can create a separate pull request as this pull request was targeted to fix alignment of elements.

I have opened a new issue about it: https://github.com/ihhub/fheroes2/issues/3421.

**Pull request merged**
