### PR TITLE
Make logging for monster movement in battle more user-friendly

### PR DESCRIPTION
**Pull request by ihhub**
We still show coordinates in the battlefield but these values are useless.

### CODE REVIEW

**Review by zenseii — APPROVED** [review]

**Comment by zenseii** [comment]
Relates to https://github.com/ihhub/fheroes2/issues/1372

**Comment by oleg-derevenetz** [comment]
Hi @ihhub please resolve merge conflicts :)

> We still show coordinates in the battlefield but these values are useless.

Not quite useless, I've already gotten used to translating indexes into coordinates, but some skill is needed :)

**Comment by zenseii** [comment]
I should add that while testing this I noticed that 2-hex creatures like Dragons will report the x-/horizontal coordinate according to where they first land with their head cell. This means for the same pair of cells it might report `[1,1]` or `[1,2]` depending on whether it had to turn around before flying to this cell or not.

It took some time before I understood why this was happening, but this doesn't necessarily have to change.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz,
what if we display extra value in debug mode? I think it should help to preserve your adopted style of conversion.

Hi @zenseii ,

Actually for wide creatures we can display 2 sets of coordinates. Will it help?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> what if we display extra value in debug mode? I think it should help to preserve your adopted style of conversion.

I'm fine with new logic :)

**Comment by zenseii** [comment]
> Hi @oleg-derevenetz, what if we display extra value in debug mode? I think it should help to preserve your adopted style of conversion.
> 
> Hi @zenseii ,
> 
> Actually for wide creatures we can display 2 sets of coordinates. Will it help?

This would at least remove some ambiguity, since right now if you are playing "blind" and only looking at the coordinates, you  will have to remember that when moving sideways or forward the x-coordinate is where the head-end is, whereas if you move backwards the x-coordinate is where the tail-end will end up being.

I'm just thinking should we ever want to have a system where you can input the coordinates, like maybe for text support mode, then this might be a minor inconvenience.

**Review by oleg-derevenetz — APPROVED** [review]
Changes are fine, but merge conflicts should be resolved.

**Pull request merged**
