### PR TITLE
Rephrase various game dialogs

### PR DESCRIPTION
**Pull request by zenseii**
This changes some of the texts to be more correct in my opinion.

~~Boats can be summoned in lakes, which technically aren't oceans. Body of water sounds better to me than ocean location.~~
Nope, see discussion below.

### CODE REVIEW

**Review by Kazhuu — APPROVED** [review]
Hi @zenseii! Yes from my side these changes looks good to me :+1:

**Comment by Kazhuu** [comment]
Also include @LeHerosInconnu in this converstation.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii and @Kazhuu,

> > Also include @LeHerosInconnu in this converstation.
> 
> Sure! I changed a few more and I'll try to fix some other things too. I might change the elemental summoning phrase again since I have my doubts about some of it.

The word "ocean" is used on purpose because it corresponds to the type of terrain indicated in the terrain's right-click information window.

Related closed issue: https://github.com/ihhub/fheroes2/issues/4849.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@zenseii , huge thanks for improving texts!

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> I rephrased the strings now and adjusted a few others, @LeHerosInconnu. Please have a look if and when it suits you.

Isn't there a change for the texts concerning "you" and "the hero"?
I haven't been able to find it.

Here are some suggestions:

913 *msg = _( "There is no open space adjacent to your hero to summon an Elemental to." );
913  *msg = _( "There is no open space adjacent to your hero where you can summon an Elemental to." );

"There is no open space adjacent to your hero where he can summon an Elemental to."

To remain consistent with the phrasing in other sentences:
"There is no open space adjacent to your hero, so he cannot cast this spell."

427 *res = _( "This spell can be casted only nearby ocean." );
427 *res = _( "This spell can only be cast near an ocean." );

I think the word "an" could be removed:
"This spell can only be cast near ocean."

437 *res = _( "There is no boat available and no free ocean location near the hero to cast this spell." );
437 *res = _( "There are no boats available and no ocean adjacent to the hero where this spell will work." );

"There are no boats available and your hero is not near the ocean, so he cannot cast this spell."

468 *res = _( "You do not currently own any town or castle that is not occupied by a hero, so you can't cast the spell." );
468 *res = _( "You do not own any town or castle that is not currently occupied by a hero. You cannot cast this spell." );

"You do not own any town or castle that is not currently occupied by a hero, so your hero cannot cast this spell."

472 *res = _( "This hero is already in a town, so you can't cast the spell." );
472 *res = _( "This hero is already in a town, so you cannot cast this spell." );

"This hero is already in a town, so he cannot cast this spell."

To remain consistent with the phrasing in other sentences:
"Your hero is already in a town, so he cannot cast this spell."

539 *res = _( "You must be standing on the entrance to a mine (sawmills and alchemists don't count) to cast this spell." );
539 *res = _( "You must be standing on the entrance to a mine (sawmills and alchemist labs do not count) to cast this spell." );

"Your hero must be standing on the entrance to a mine (sawmills and alchemist labs do not count) to cast this spell."

**Pull request merged**
