### PR TITLE
Partially migrate Linux builds from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Recently I noticed that recent snapshot builds are not available for Linux anymore, latest available build is for commit from May 2020. This PR is intended to partially solve this problem (test builds and snapshot builds for x86 and PSV at least). Also it implements more readable description for macOS builds.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
We can then leave throw away most builds from Travis, except SonarCloud (it can also be migrated later) and ARM Linux builds (need to think about migrating them too). This will need to be done sooner or later [anyway](https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567).

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please remove these 3 builds from Travis otherwise we'll have a clash of deployment.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub As of now, it seems that there is no deployment from Travis in about a year. Or is there metadata just not updated (description with commit number stays the same as a year ago)?

**Comment by ihhub** [comment]
> Hi @ihhub As of now, it seems that there is no deployment from Travis in about a year. Or is there metadata just not updated (description with commit number stays the same as a year ago)?

Deployment works fine, juat metadata is not updated.

**Comment by oleg-derevenetz** [comment]
@ihhub

> Deployment works fine, juat metadata is not updated.

Ah, OK, removed them from Travis.

**Comment by ihhub** [comment]
Great work, @oleg-derevenetz ! I hope we'll have less troubles with Travis.

**Pull request merged**
