### PR TITLE
Avoid pirated translation which are applied on English version of the game

### PR DESCRIPTION
**Pull request by ihhub**
This causes all sorts of nasty rendering issues which we shouldn't take responsibility to fix.

### CODE REVIEW

**Review by Districh-ru — COMMENTED** [review]
Hi, @ihhub. Could you take a look at the next possible issue when you have time:
When I place data file from Fargus game version and try to launch fheroes2 on Windows the release version just closes its window right after opening it.
If I start a debug version I get this error:
изображение

With Buka and GOG game data the engine starts without any issues.

IMHO it'll be good to have a message like: "The game resources are corrupted. Please use resources from a licensed version of Heroes of Might and Magic II."
(`"Damaged game resources: invalid font."` does not appear anywhere)

**Comment by ihhub** [comment]
Hi @Districh-ru , I updated the message. I don't have such an error but a log entry in the console:
```
SDL_main:  Exception 'The game resources are corrupted. Please use resources from a licensed version of Heroes of Might and Magic II.' occurred during application runtime.
```

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , I updated the message. I don't have such an error but a log entry in the console:
> 
> ```
> SDL_main:  Exception 'The game resources are corrupted. Please use resources from a licensed version of Heroes of Might and Magic II.' occurred during application runtime.
> ```

My console window has only:
```fheroes2 engine, version: 1.0.3```

And the Windows release version has no console. So some users might be confused as there will be no message and the game will not start with no reason. :)
We already gave a message if there is no game data:
изображение
Maybe we should display it or add (in future PR) the new message about corrupted resources.

**Comment by oleg-derevenetz** [comment]
> My console window has only:

If you press Retry, debugger should show the exact place of that `abort()` call. Maybe it's due to some failed assertion somewhere.

> And the Windows release version has no console.

It has a logfile instead. in its `APPDATA` directory near the `fheroes2.cfg`.

**Comment by Districh-ru** [comment]
> > My console window has only:
> 
> If you press Retry, debugger should show the exact place of that `abort()` call. Maybe it's due to some failed assertion somewhere.

The debugger shows the next line after `throw std::logic_error()`:

изображение


> 
> > And the Windows release version has no console.
> 
> It has a logfile instead, in its `APPDATA` directory near the `fheroes2.cfg`. But I agree that the "data files not found" image is more informative.

In the log file I have only: `fheroes2 engine, version: 1.0.3`
Maybe it is something in my OS configuration. ;)

And not every user will go to a hidden `APPDATA` directory to read the log file. :)

**Comment by oleg-derevenetz** [comment]
> The debugger shows the next line after `throw`

What is the call stack in this case? `abort()` may be called if you throw an exception inside a function marked as `noexcept` (or some function directly or indirectly called from `noexcept` function) and let it leak outside that function (i.e. do not handle this exception locally).

**Comment by Districh-ru** [comment]
> What is the call stack in this case? `abort()` may be called if you throw an exception inside a function marked as `noexcept` (or some function directly or indirectly called from `noexcept` function) and let it leak outside that function (i.e. do not handle this exception locally).

I don't see `noexcept` in this function (`LoadModifiedICN()`) or the one that called it. The debugger, if I try to resume, wants to go to `minkernel\crts\ucrt\src\appcrt\internal\report_runtime_error.cpp` file which I don't have.

About two years ago I configured the system to fully disable any error reporting. Maybe this is the reason I don't get any error in the log. @ihhub wrote that he has an error message so I think that it is my system configuration issue.

**Comment by oleg-derevenetz** [comment]
@Districh-ru

> When I place data file from Fargus game version and try to launch fheroes2 on Windows the release version just closes its window right after opening it.

What's in the `fheroes2.log` on the release build (the one that closes immediately)?

**Comment by Districh-ru** [comment]
> @Districh-ru
> 
> > When I place data file from Fargus game version and try to launch fheroes2 on Windows the release version just closes its window right after opening it.
> 
> What's in the `fheroes2.log` on the release build (the one that closes immediately)?

Only: 
```
fheroes2 engine, version: 1.0.3

```
[fheroes2.log.zip](https://github.com/ihhub/fheroes2/files/11412738/fheroes2.log.zip)

**Comment by oleg-derevenetz** [comment]
> Only:

Then something is definitely going wrong. Properly handled exception is not an error by itself. This needs to be debugged.

**Comment by Districh-ru** [comment]
On Ubuntu I get in console:
```
fheroes2 engine, version: 1.0.3
terminate called after throwing an instance of 'std::logic_error'
  what():  The game resources are corrupted. Please use resources from a licensed version of Heroes of Might and Magic II.
Aborted (core dumped)
```

**Comment by oleg-derevenetz** [comment]
I was able to reproduce this issue with Fargus assets:

```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff663c406 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff662287c in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff72a4f26 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff72b6f2c in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff72b5ed9 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff72b6649 in __gxx_personality_v0 () at /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7f5ba89 in  () at /lib/x86_64-linux-gnu/libgcc_s.so.1
#10 0x00007ffff7f5c1b1 in _Unwind_RaiseException () at /lib/x86_64-linux-gnu/libgcc_s.so.1
#11 0x00007ffff72b71eb in __cxa_throw () at /lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00005555582d81ba in fheroes2::AGG::LoadModifiedICN(int) (id=248) at ../fheroes2/agg/agg_image.cpp:1942
#13 0x000055555831e217 in fheroes2::AGG::GetMaximumICNIndex(int) (id=248) at ../fheroes2/agg/agg_image.cpp:3562
#14 0x00005555583209bd in fheroes2::AGG::GetICN(int, unsigned int) (icnId=248, index=0) at ../fheroes2/agg/agg_image.cpp:3650
#15 0x00005555582aa3ba in (anonymous namespace)::OriginalAlphabetPreserver::preserve() (this=0x55555d8cc1a0 <(anonymous namespace)::alphabetPreserver>) at ../fheroes2/agg/agg_image.cpp:292
#16 0x000055555832173a in fheroes2::AGG::updateLanguageDependentResources(fheroes2::SupportedLanguage, bool) (language=fheroes2::SupportedLanguage::Russian, loadOriginalAlphabet=false) at ../fheroes2/agg/agg_image.cpp:3852
#17 0x00005555591f822c in fheroes2::updateAlphabet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (abbreviation="ru") at ../fheroes2/gui/ui_language.cpp:271
#18 0x00005555597056f4 in Settings::setGameLanguage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x55555d8d10c0 <Settings::Get()::conf>, language="ru")
    at ../fheroes2/system/settings.cpp:483
#19 0x00005555591f601a in fheroes2::LanguageSwitcher::~LanguageSwitcher() (this=0x7ffff3a989c0, __in_chrg=<optimized out>) at ../fheroes2/gui/ui_language.cpp:82
#20 0x0000555558d12df3 in Game::HotKeysLoad(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (filename="/home/oleg/.config/fheroes2/fheroes2.key") at ../fheroes2/game/game_hotkeys.cpp:435
#21 0x0000555558cb60e7 in Game::Init() () at ../fheroes2/game/game.cpp:170
#22 0x0000555558c5cff1 in main(int, char**) (argc=1, argv=0x7fffffffe208) at ../fheroes2/game/fheroes2.cpp:298
```

This issue is observed only if in-game language is **_not_** set to English and the cause of frame 19, where `~LanguageSwitcher()` is called (it is not called with English language):

```
#0  fheroes2::AGG::LoadModifiedICN(int) (id=248) at ../fheroes2/agg/agg_image.cpp:1942
#1  0x000055555831e217 in fheroes2::AGG::GetMaximumICNIndex(int) (id=248) at ../fheroes2/agg/agg_image.cpp:3562
#2  0x0000555558320f1c in fheroes2::AGG::getCharacterLimit(fheroes2::FontSize) (fontSize=fheroes2::FontSize::LARGE) at ../fheroes2/agg/agg_image.cpp:3755
#3  0x0000555559220d41 in (anonymous namespace)::CharValidator::CharValidator(fheroes2::FontSize) (this=0x7ffff37288a0, fontSize=fheroes2::FontSize::LARGE) at ../fheroes2/gui/ui_text.cpp:44
#4  0x00005555592225e4 in (anonymous namespace)::getMultiRowInfo(uint8_t const*, int32_t, int32_t, fheroes2::FontType const&, int32_t, std::deque<fheroes2::PointBase2D<int>, std::allocator<fheroes2::PointBase2D<int> > >&)
    (data=0x60400009cbd0 "fheroes2 Resurrection Team presents", size=35, maxWidth=500, fontType=..., rowHeight=33, offsets=std::deque with 1 element = {...}) at ../fheroes2/gui/ui_text.cpp:186
#5  0x0000555559227ec7 in fheroes2::Text::width(int) const (this=0x7ffff39c3cf0, maxWidth=500) at ../fheroes2/gui/ui_text.cpp:508
#6  0x0000555558d6f661 in fheroes2::showTeamInfo() () at ../fheroes2/game/game_logo.cpp:41
#7  0x0000555558c5d0bb in main(int, char**) (argc=1, argv=0x7fffffffe208) at ../fheroes2/game/fheroes2.cpp:303
```

Destructors are `noexcept` [by default](https://en.cppreference.com/w/cpp/language/destructor), so since there is no exception handler inside the `~LanguageSwitcher()` (or higher up the stack), the `std::logic_error` exception should not get out of this destructor and `std::terminate()` is called.

**Comment by Districh-ru** [comment]
> I was able to reproduce this issue with Fargus assets:

@oleg-derevenetz, thanks for the detailed explanation.
When I was testing this PR my language was set to Russian on both Windows and Ubuntu.
I changed language to English and with Fargus game data I got in console:
```
fheroes2 engine, version: 1.0.3
07.05.2023 07:20:06: [ERROR]    SDL_main:  Exception 'The game resources are corrupted. Please use resources from a licensed version of Heroes of Might and Magic II.' occurred during application runtime.
```

**Comment by ihhub** [comment]
Hi @Districh-ru and @oleg-derevenetz , the exception will not appear anymore during destructor.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub what do you think to perform special checks and display that "data files not found" image instead of throwing an exception that will not be even noticed under Windows (if the user does not guess to look into the logfile)?

**Comment by ihhub** [comment]
> Hi @ihhub what do you think to perform special checks and display that "data files not found" image instead of throwing an exception that will not be even noticed under Windows (if the user does not guess to look into the logfile)?

Done.

**Review by Districh-ru — APPROVED** [review]
👍 
Now it works correctly if other than English language is set in .cfg file.
I checked with Fargus game data - I got an image "Data files not found" and after closing it I got a text about corrupted resources in log file.

**Review by oleg-derevenetz — APPROVED** [review]

**Pull request merged**
