### PR TITLE
Rename variables to do not hide members of class

### PR DESCRIPTION
**Pull request by saul365**
I changed the local variable names described in the issue so they wouldn't hide class members. I added context to the names so they are legible.

relates to #158

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @saul365 thank you very much for your efforts to fix this issue. [There](https://travis-ci.org/ihhub/fheroes2/builds/595931481?utm_source=github_status&utm_medium=notification) are compilation errors due to your changes. Could you please take a look into them?

**Comment by saul365** [comment]
Sorry i haven't been in touch bit i'm woking on it.
________________________________
De: Ihar Hubchyk <notifications@github.com>
Enviado: viernes, 11 de octubre de 2019 12:37:02 a. m.
Para: ihhub/fheroes2 <fheroes2@noreply.github.com>
CC: SAUL ALEJANDRO BADILLO HERNANDEZ <saul_bh365@comunidad.unam.mx>; Mention <mention@noreply.github.com>
Asunto: Re: [ihhub/fheroes2] Issue158 (#161)


Hi @saul365<https://github.com/saul365> thank you very much for your efforts to fix this issue. There<https://travis-ci.org/ihhub/fheroes2/builds/595931481?utm_source=github_status&utm_medium=notification> are compilation errors due to your changes. Could you please take a look into them?

**Comment by ihhub** [comment]
@saul365 okay. When would you be able to finish it?

**Comment by saul365** [comment]
I hope by monday it should be up and running . I'm trying to figure out why ir won't build.
________________________________
De: Ihar Hubchyk <notifications@github.com>
Enviado: viernes, 18 de octubre de 2019 02:37:08 a. m.
Para: ihhub/fheroes2 <fheroes2@noreply.github.com>
CC: SAUL ALEJANDRO BADILLO HERNANDEZ <saul_bh365@comunidad.unam.mx>; Mention <mention@noreply.github.com>
Asunto: Re: [ihhub/fheroes2] Issue158 (#161)


@saul365<https://github.com/saul365> okay. When would you be able to finish it?

**Comment by saul365** [comment]
Hello, sorry iḿ bothering you but i have a problem. I can't compile it i tried with the master branch and followed the instructions but it still fails everytime. I'm using ubuntu 18.04
________________________________
De: Ihar Hubchyk <notifications@github.com>
Enviado: viernes, 18 de octubre de 2019 02:37 a. m.
Para: ihhub/fheroes2 <fheroes2@noreply.github.com>
CC: SAUL ALEJANDRO BADILLO HERNANDEZ <saul_bh365@comunidad.unam.mx>; Mention <mention@noreply.github.com>
Asunto: Re: [ihhub/fheroes2] Issue158 (#161)


@saul365<https://github.com/saul365> okay. When would you be able to finish it?

**Pull request closed without merging**
