### PR TITLE
Minor improvements to installation scripts

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Related to #4307

* Don't pack `extract_homm2_dos_anim.*` files in a ZIP archive - animations can be extracted by the `extract_homm2_resources.bat` alone even if ZIP file will be extracted to the directory with the OG;
* Mention the `extract_homm2_resources.bat` in `README.txt`;
* Rephrase some sentences.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , please check these changes and tell if you're happier with them :)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please squash all commits here so Appveyor will have the latest build ready for @Branikolog testings?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> Hi @oleg-derevenetz , could you please squash all commits here so Appveyor will have the latest build ready for @Branikolog testings?

It seems that it won't help because this PR changes only files mentioned in `skip_commits` section of `appveyor.yml` (it seems that `appveyor.yml` is implicitly included in this section too), so I'll to a bit different.

**Comment by ihhub** [comment]
@oleg-derevenetz , I think it's fine. We can merge and @Branikolog will review from master.

**Comment by oleg-derevenetz** [comment]
@ihhub Currently the build was triggered but it's failing because libsdl.org is down.

**Comment by ihhub** [comment]
> 
> 
> @ihhub Currently the build was triggered but it's failing because libsdl.org is down.

oh, no. Just before release :(

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you very much for these changes!

**Pull request merged**
