### PR TITLE
Move scrollbar background and button rendering code to 'ui_window'

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR optimizes `ui_window.cpp` code a bit and moves the scrollbar background generation and rendering code and button rendering code to `ui_window`. It slightly reduces the code duplication in dialogs with lists.
This PR also forces to update the dialog area on the screen on the next redraw call after the dialog is closed.

This PR affects all "Select ..." dialogs, including save/load and hotkeys dialogs: shadow and dialog rendering, dialog items (scrollbar, buttons) rendering and positioning.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru FYI: #7985

**Comment by Districh-ru** [comment]
> Hi @Districh-ru FYI: #7985

Hi @oleg-derevenetz, thanks.
Interesting, in one run IWYU suggested me to remove that headers: https://github.com/ihhub/fheroes2/actions/runs/6629246716/job/18008121328
I fixed the headers only in the files that are changed in this PR.

**Comment by oleg-derevenetz** [comment]
> Interesting, in one run IWYU suggested me to remove that headers

That's because this IWYU runs on one of those updated images. For now, the probability is ~12/100, but it will increase over time.

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you very much for these updates!

**Pull request merged**
