### PR TITLE
Changed captain's name

### LINKED ISSUE #4859: Combat screen, Captain's Options window, change the title
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the name of the city is indicated as if it was the name of the Captain.

In the original game, the title of the window is simply "Captain".

In original game:

Captain title combat H2 01

In fheroes2:

Captain info buttons 001

### Describe the possible solution

I suggest to change the title of the Captain's Options windows to "Captain of the 'name of the city'".

In the example:

"Captain of Fenton"

Instead of:

"Fenton the Barbarian"

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by felix642**
closes #4859

### CODE REVIEW

**Comment by yvesgurcan** [comment]
Why?

**Comment by yvesgurcan** [comment]
Wouldn't that make all similar dialog titles, even for heroes, "Captain of something?" Or does this only apply to captains?

**Comment by felix642** [comment]
> Wouldn't that make all similar dialog titles, even for heroes, "Captain of something?" Or does this only apply to captains?

Good catch, for some reasons I didn't think of that ?

**Comment by yvesgurcan** [comment]
Oh, ok! Would it be possible to use some logic to only apply the change in the string to situations where the player is looking at the info related to a captain, not a hero?

**Comment by yvesgurcan** [comment]
Awesome! I'm glad we were able to catch this. 🙂

**Review by yvesgurcan — APPROVED** [review]

**Comment by ihhub** [comment]
@felix642 , good job! Thanks a lot for this!

**Pull request merged**
