### PR TITLE
Fix interaction with Shipwreck object

### LINKED ISSUE #4542: The hero can't reach the shipwreck
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Troyan tries to attack the shipwreck:

https://user-images.githubusercontent.com/71143197/139945808-a210f9e5-8e01-465c-a63f-61aac4087215.mp4

### Save file

[bug1.zip](https://github.com/ihhub/fheroes2/files/7463775/bug1.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #4542

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog ,
could you please test all water object accessibility from water and from ground to make sure that the logic matches the original? Here's a test map for this.
[Waterobj.zip](https://github.com/ihhub/fheroes2/files/7472483/Waterobj.zip)

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, can you please test this pull request now?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, can you please test this pull request now?

Yes.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hello @ihhub,
> 
> > Hi @LeHerosInconnu, can you please test this pull request now?
> 
> Yes.

Here are the differences observed.

Mermaid:
Sea objetcs 001
Sea objetcs 008
Sea objetcs 004
Sea objetcs 009

Sirens:
Sea objetcs 002
Sea objetcs 006
Sea objetcs 010
Sea objetcs 013
Sea objetcs 007

Derelict Ship:
Sea objetcs 003
Sea objetcs 005

Derelict Ship passability:
Sea objetcs 011
Sea objetcs 012

Strange path:
Sea objetcs 014
Sea objetcs 015
Sea objetcs 016

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I've fixed extra issues with passabilities in #4570

**Pull request merged**
