### PR TITLE
Remove XML usage

### PR DESCRIPTION
**Pull request by ihhub**
Since we're going to shift to JSON there's no need to keep them anymore.

relates to #3477

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @ihhub, I suppose it's also worth to remove `Game::LoadExternalResource()` and all that stuff with `WITH_XML` called from it?

**Comment by ihhub** [comment]
> Hi @ihhub, I suppose it's also worth to remove `Game::LoadExternalResource()` and all that stuff with `WITH_XML` called from it?

You're absolutely right. I see no value in this and we're going to remove all XML support soon or later. Let me do this.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @idshibanov , I removed all usage of XML from the project. Please take a look.

**Comment by oleg-derevenetz** [comment]
@ihhub Oh, at last we can remove `WITHOUT_XML: "ON"` from clang analyzer workflow! :)

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by oleg-derevenetz** [comment]
I think we can also remove `USE_SYSTEM_TINYXML` option from `CMakeLists.txt`:

https://github.com/ihhub/fheroes2/blob/29a970b5cf0213dda8738c9660f9ae427fb460ef/CMakeLists.txt#L22

as well as `WITHOUT_XML: "ON"` from `scan-build.yml` workflow:

https://github.com/ihhub/fheroes2/blob/29a970b5cf0213dda8738c9660f9ae427fb460ef/.github/workflows/scan-build.yml#L23

**Pull request merged**
