### PR TITLE
Add a document for privacy policy for the project

### PR DESCRIPTION
**Pull request by ihhub**
It is required for Google Play Store. It is simple as we don't collect any personal information.

relates to #6822

### CODE REVIEW

**Comment by ihhub** [comment]
> This looks good to me, even if I have no prior experience with writing such policies.
> 
> It's a bit thought-provoking how **not** collecting any data seems to be a rare thing for apps on the play store.

That's a reality we live in. Most of apps collect personal information in one or another form.

**Review by Districh-ru — APPROVED** [review]
I have no experience in writing such documents, but its look good to me.

Maybe we can add a phrase (it's a copy-past from some other policy):
"fheroes2 is provided at no cost and is intended for use as is.
 This document is used to inform regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use fheroes2.
If you choose to use fheroes2, then you agree to this policy. 
We will not collect, use or share your information with anyone. We do not collect any personally identifiable information from children."

Also I don't know how it is organized, but Android possibly may create the error report (I use modded firmware with disabled error reporting on my cell phone, so I don't know how it works and if it works). If there may be such error report, then we can add something like:
"We want to inform you that whenever you use fheroes2, in a case of an error in the app the data and information can be collected (through third-party products) on your phone called Log Data. This Log Data may include information such as your device name, operating system version, the time and date of your use of fheroes2, and other statistics."

**Comment by oleg-derevenetz** [comment]
> Also I don't know how it is organized, but Android possibly may create the error report

Unlike iOS that [uploads crash reports to the AppStore automatically](https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs), Android doesn't do this by default and requires explicit integration of some crash reporting framework, for example, [Firebase Crashlytics](https://firebase.google.com/products/crashlytics) (Crashlytics is the Google's product, but nonetheless it requires explicit integration and doesn't work "silently").

**Comment by ihhub** [comment]
Hi @Districh-ru and @zenseii , I updated the document by adding @Districh-ru suggestion (not full but most of it). Please take a look when you have time.

**Review by idshibanov — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , if you have time please review this pull request by today so I can prepare everything for the Google Play Store release?

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @zenseii , if you think that the last change needs correction please comment and I can create another pull request for this.

**Pull request merged**
