### PR TITLE
Display the world date for save files, refactor the game I/O a bit

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Implement the proposal from #6707

screenshot

There were two main problems because of which it was impossible to make a "naive" implementation and which caused refactoring:

1. The world date is stored in the zipped part of the save file, so we can't just seek & read a few bytes, we should unzip this part first, which is relatively slow;
2. There was no infrastructure to use the save file version in the `struct Maps::FileInfo`, so it was impossible to just add a couple of fields there.

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]
Hi, @oleg-derevenetz 
Great work! I believe, this improvement is very useful.
I noticed, that you've used non white colour for file path string. Was it intended?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I noticed, that you've used non white colour for file path string.

What do you mean? It is white (see the screenshot in the PR description), but with smaller font size than before, because now there is less space for it, and I doubt that this information is really needed so often that it is worth writing it in large letters.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

> What do you mean? It is white (see the screenshot in the PR description), but with smaller font size than before, because now there is less space for it, and I doubt that this information is really needed so often that it is worth writing it in large letters.

Oh, sorry, it's white indeed. This font together with the background are not so commonly met in the game, so it made an impression for me, it was not white, but beige. Sorry, for bothering you.

I also agreed with your solution to make file path in a small font. This information is helpful only for the first time player knows about it :)

**Comment by oleg-derevenetz** [comment]
@Branikolog BTW I changed the font size for the map path in the map quick info window too - for consistency. The map name and type (SW/PoL) now goes first in large letters and then goes file path in small letters.

**Comment by ihhub** [comment]
@oleg-derevenetz , well done!

**Pull request merged**
