### PR TITLE
Cache Vita SDK to avoid build failures on SDK installation issues

### LINKED ISSUE #3214: Cache PSV build steps
PSV build step on GitHub Actions takes a lot of time in comparison with other builds. The build contains 2 steps for SDK download and installation. We would like to cache if possible such steps to improve build times.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
close #3214

### CODE REVIEW

**Comment by ihhub** [comment]
@oleg-derevenetz , great thanks for making the build more stable!

**Comment by oleg-derevenetz** [comment]
@ihhub It seems that this solution was just passed baptism by fire:

https://github.com/ihhub/fheroes2/runs/2648539470

**Comment by ihhub** [comment]
> @ihhub It seems that this solution just passed baptism by fire:
> 
> https://github.com/ihhub/fheroes2/runs/2648539470

Hmm... it still was downloading files :(

**Comment by oleg-derevenetz** [comment]
> Hmm... it still was downloading files :(

It will always download files to update cache by latest versions of libraries. However, it download or extraction fails (like in this case) it will use cached versions from previous run. Unfortunately, there is no way to find out in advance, is it worth to download libraries or not.

**Comment by ihhub** [comment]
At least if it doesn't fail then we're good.

**Pull request merged**
