### PR TITLE
AI: use the "cautious offensive" tactics only against melee-only armies without the distant attack potential (including damage spells)

### LINKED ISSUE #7973: Combat, AI is moving too safe while opposing army with strong ranged troops
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

https://github.com/ihhub/fheroes2/assets/55348946/518ab599-033d-4a6e-b62e-db8f405493b7

Current behaviour could be easily abused by players.

AI shouldn't use such "safe" approach in battles against ranged troops, placing his melee troops too far away . I expect the current approach be used against melee only army (with minimum ranged potential (considering attacking spells too)).

### Describe the possible solution

In the example above Pikemen could reach halflings on the second round already, but they prefer to stop out of boars range, so none of them could cover strong stack of halflings on the second round. 
Continuing the third round the majority of Pikemen stacks made only a single step forward, that allows halflings to shoot one more time on the next round (there's only one stack of Pikemen rushing, which could be killed by halflings.

I'm also concerned about the threat AI is considering now. Just a few pairs of boars are not such a strong rivals. AI decided to stay away from their range, but more effective tactic in this case is rushing ranged troops. AI has more stacks and player will potentially try to hide halflings behind boars. So Pikemen using the maximum movement range will do more efficiently, if they ignore boars here and walk forward. 
Even if player's army has strong enough melee troops, AI placing his troops out of enemy range will give the player a few more turns for spell casting or shooting the defending AI.

Probably, if there were some other slow stacks (like ogres or golems) Pikemen could took the cells which are not reachable by slow stacks, but at the same close enough, to cover ranged troops the upcoming round.

[Shivery AI.zip](https://github.com/ihhub/fheroes2/files/13060420/Shivery.AI.zip)

### Additional info

_No response_

### LINKED ISSUE #8070: Combat, enemy advancement issue
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Enemy is not using the whole movement range if I place my troops at the distance (move speed+2) in front of his troops.

https://github.com/ihhub/fheroes2/assets/55348946/afc90dd1-d9ef-4f9c-93bc-b64f192fab08

This could be highly abused by cheating humans allowing archers to shoot a few more turns.
I think there's no need to use such tactics if AI troops are slower than my.

Even if AI is going towards slower troops I can abuse this logic and slow down swordsmen for a few turns:

https://github.com/ihhub/fheroes2/assets/55348946/0499596d-5a72-4c35-9be2-6e58314ae5cd

I suggest swordsmen rush without slowing down in a case enemy army has strong shooters and/or weak troop standing in front of swordsmen.

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #8070
close #7973

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
This problem bothered me so much time. I'm so glad, here's the PR fixing it! :)
I've already started testing battles and here's one thing that I start thinking after a few dozens of battles:

https://github.com/ihhub/fheroes2/assets/55348946/dbdf3198-4be1-4d4c-9c1f-4793bd183729

I think 1 ranger is not a huge threat for minotaurs to switch off "cautious offensive" tactics. How do you think? I suggest comparing the overall shooters strength with defending melee army, If shooters make significantly less damage, than melee troops could do to attacking troops (minotaurs) AI can be a little bit more cautious. :)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I suggest comparing the overall shooters strength with defending melee army, If shooters make significantly less damage

So what should be the factor of archers strength vs total strength? 5%? 10%? 15%? Do you remember about the corner cases that are "attached" to each constant of this kind?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Corner cases... Sure! :D
What if we use the same value is used for defending archers? If their strength is not so high, comparing the melee defending troops, attackers shouldn't really bother much rushing them and be attacked by defenders.

**Comment by Branikolog** [comment]
But anyway, the value is up to you.
I hope, you agree, that 1 ranger is not really a reason for minotaurs to appear under attack of brave swordsmen? :)

**Comment by ihhub** [comment]
@Branikolog , as usual please be more specific. Give examples when N shooters matter but N - 1 don't. Also how about 1 Mage vs Minotaurs?

**Comment by oleg-derevenetz** [comment]
@Branikolog OK, for now, let's make such an assessment that we can resort to cautious offensive if the share of archers in the total power of the enemy army is no more than 15%.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Thanks! Now I feel it is working better. We can later adjust the value (maybe enemy can rush if shooters are 1-2% weaker, than the current value) , but now it's +/- adequate.

@ihhub 
Sorry, but I couldn't be more specific here, since we don't count on the number of troops, but on the strength. I'm not really good in calculations of troops threat. But @oleg-derevenetz made it well!

**Comment by Branikolog** [comment]
@oleg-derevenetz 
One more related thing I want to mention. It is probably out of the PR, but I would like to share it and hear your opinion.

https://github.com/ihhub/fheroes2/assets/55348946/09dacf45-89d6-4e7c-87fb-4b0a124c09c4

Champions are definitely much faster, than golems and they really don't need to advance ahead so much. 
I think it would be nice if champions try to position themselves out of the range of defending slow golems, even in "non-cautious" state.

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Champions are definitely much faster, than golems and they really don't need to advance ahead so much.

We need to develop a common algorithm, and this cannot be based on just one situation. What if there is also a faster stack in addition to golems? What if golem's stacks are stronger than this stack? What if that faster stack is stronger than stacks of golems? Etc, etc. The more complicated the logic, the worse, because with each new condition, a lot of new boundary situations and gray areas arise.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
 
> > Champions are definitely much faster, than golems and they really don't need to advance ahead so much.
> 
> We need to develop a common algorithm, and this cannot be based on just one situation. What if there is also a faster stack in addition to golems? What if golem's stacks are stronger than this stack? What if that faster stack is stronger than stacks of golems? What if they are roughly equal in power? Etc, etc. The more complicated the logic, the worse, because with each new condition, a lot of new boundary situations and gray areas arise.

Is it within the scope of this PR, or should we discuss it in a separate thread/PR-draft?

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Is it within the scope of this PR, or should we discuss it in a separate thread/PR-draft?

Since there is not even an approximate clarity on how exactly this should work right now, this is definitely beyond the scope of this PR :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 

> Since there is not even an approximate clarity on how exactly this should work right now, this is definitely beyond the scope of this PR :)

I have some approximate ideas. :D But the logic is going to consist of multiple rules, so lets hold it back or discuss somewhere else. :)
For now I would like to test this PR for several hours more to be sure I'm approving a 100% working improvement. :)

**Comment by oleg-derevenetz** [comment]
@Branikolog Just for your information, how exactly the "cautious offensive" mode works currently. The candidate path of the unit is taken and for each tile tile "threat level" is calculated, and the farthest cell of the path is chosen from those with the least threat level. For example, if such a path passes through tiles with indexes 1, 2, 3 and there is unit A with threat level 100 and unit B with threat level 200, but unit B can access tiles 2 and 3, while unit A can access tiles 1 and 2, then path should be cut to the tile 1. However, if unit B can access just tile 2, then the path does not need to be cut at all. Here is an example of a general solution (certainly not ideal, but it works well enough). Need to work out something like that.

**Comment by oleg-derevenetz** [comment]
> I have some approximate ideas.

It is necessary to have a common mathematical/logical model. E.g. "for each our unit we take the metric A (or calculate it in this way), then compare it with coefficient X, if it more than X, then we do Y, else we take another metric B for each enemy unit, ..." etc. Here's how computers behave :)

**Review by Branikolog — APPROVED** [review]
@oleg-derevenetz 
>It is necessary to have a common mathematical/logical model. E.g. "for each our unit we take the metric A (or calculate it in this way), then compare it with coefficient X, if it more than X, then we do Y, else we take another metric B for each enemy unit, ..." etc. Here's how computers behave :) Excluding maybe neural networks, but that's a completely different story.
Thank you for this explanation! I understand it better how it works. If I can, I come up with the proposal how we can improve the logic. Considering the explained current implementation.
The PR is OK for me. Haven't found any issues.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this improvement!

**Pull request merged**
