### PR TITLE
Improvements for Windows scripts

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Requested in #3582

* demo_windows.ps1: display a message at the startup to notify that downloading takes some time
* demo_windows.ps1: use Invoke-WebRequest if available (it shows download progress)
* Minor fixes

### CODE REVIEW

**Comment by ihhub** [comment]
@oleg-derevenetz , great thanks for improving the scripts!

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
I found, that after running .bat, we can find both archives of demo and wing32 in a root folder of demo.
I think, we should delete both these archives after the demo installation.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I prefer to retain archives (in demo_unix.sh as well BTW) in order for the user to always have all source files at hand if he wants to verify them or extract files by himself later. Downloading some files from the web and then deleting them looks like trying to hide something for my taste. But this is debatable, if there are some good reasons to remove them (Storage space? But these archives not that big these days).

**Comment by Branikolog** [comment]
@oleg-derevenetz 
In the end user doesn't need these archives, as they were unpacked already in the folder. He can always zip them himself again...
At least archives should be placed in a separate folder...

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> He can always zip them himself again...

He will not be able to generate archives with the same checksum, so, if he wants to verify downloaded archives by hand, we should retain them. This is mostly for geeks, of course (most regular users will not do that), but if this costs nothing, then why not? Hi @ihhub @idshibanov what's your opinions regarding this?

**Comment by ihhub** [comment]
From user perspective re-downloading or unzipping an archive doesn't make sense. A normal user would just reinstall the game. However, keeping zip files makes no harm. We could keep things as it is and decide once we recieve a feedback from users.

**Pull request merged**
