### PR TITLE
Corrected icons alignment on the meeting screen.

### LINKED ISSUE #7660: Meeting screen, morale and luck sprites, sprites of the hero on the right side are not correctly centered horizontally related to the portrait frame and the screen frame
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the sprites of the hero on the right side are not correctly centered horizontally related to the portrait frame and the screen frame.
Sprites should be shifted horizontally 4 pixels to the right.

In fheroes2:

Moral luck icons not centered right part 01

Enlarge the image.

Moral luck icons not centered right part recadré 01

### Save file

Not needed.

### Additional info

Related closed issue: https://github.com/ihhub/fheroes2/issues/1722.

### PR DESCRIPTION
**Pull request by dood-apo**
Shifted second hero's morale and luck indicators 4px to the right.

Fix #7660

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by Branikolog** [comment]
I had a look through the PR and tested the suggested alignment.

Some icons for the second (right) hero are not aligned in the center while we can place them with equal space to the right and to the left:
icons

Cannot tell that I feel much difference with this 1 pixel but still...

**Comment by dood-apo** [comment]
> Some icons for the second (right) hero are not aligned in the center while we can place them with equal space to the right and to the left

Fixed.

**Comment by Branikolog** [comment]
Hi, @dood-apo !
Now icons seem to aligned equally regarding window edges. 👍 
I think these changes should be applied for "battle only" mode window too, since it is 98% same to the subject of this PR..

**Comment by dood-apo** [comment]
> I think these changes should be applied for "battle only" mode window too

Thanks @Branikolog , addressed that also in the last commit.

**Comment by ihhub** [comment]
@dood-apo , thank you so much for the fix!

**Pull request merged**
