### PR TITLE
Add Ukrainian and Belarusian languages

### PR DESCRIPTION
**Pull request by zenseii**
This adds empty PO files to these langauges and adds their plural forms to `translations.cpp`.

### CODE REVIEW

**Comment by ihhub** [comment]
@zenseii , thanks a lot for handling translations!

**Comment by shprotru** [comment]
@zenseii prefix uk should be ua

**Comment by ihhub** [comment]
Hi @shprotru , are you sure about this? We are talking about language abbreviation, not internet domain :)

**Comment by shprotru** [comment]
@ihhub hm, by this standart used `uk` is correct: [List_of_ISO_639-1_codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Pull request merged**
