### PR TITLE
Fix a crash in scenario selection due to invalid pointer usage

### LINKED ISSUE #6024: Selecting any scenario in scenario selection dialog closes the app
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When trying to select any scenario from the scenario selection window the app immediately closes without any indication of crash or error.

For clarity's sake I'm talking about this window and selecting a map from that window:
image

I did a clean rebuild and reran the tools downloading script.

Testing the latest snapshot build I get the same message as reported by @LeHerosInconnu here
https://github.com/ihhub/fheroes2/issues/6017#issuecomment-1287889576:
image

Testing with the debug build and a breakpoint at the assert at line 102 of `ui_text.cpp` the breakpoint does not get triggered before the app quits.

### Save file

No need.

### PR DESCRIPTION
**Pull request by ihhub**
close #6024

For your information @HaveFun91 (we missed this).

### CODE REVIEW

**Review by zenseii — APPROVED** [review]
I've built and tested and it works as it should now.
Thanks for this quick fix!

**Review by oleg-derevenetz — APPROVED** [review]
Ahhh... classic - returning a pointer to a local data on the stack.

**Comment by HaveFun91** [comment]
@ihhub Yeah... apologies... :/

**Comment by ihhub** [comment]
@HaveFun91 , no issues. We are here to develop, not to blame anyone🙂

**Pull request merged**
