### PR TITLE
Add language choice to Windows installer

### PR DESCRIPTION
**Pull request by qarkai**
Screenshot 2021-08-04 141326

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @qarkai , I have a worry that this might mislead users thinking that once localization is installed fheroes2 can support these languages.

**Comment by qarkai** [comment]
Hi @ihhub, so what's your suggestion then?

**Comment by ihhub** [comment]
> Hi @ihhub, so what's your suggestion then?

We could keep as it is for now and introduce such change once we have a full support of all languages even those which were not officially supported.

@oleg-derevenetz , what do you think?

**Comment by qarkai** [comment]
@ihhub then why do we install them if we don't support these languages?

**Comment by oleg-derevenetz** [comment]
> > Hi @ihhub, so what's your suggestion then?
> 
> We could keep as it is for now and introduce such change once we have a full support of all languages even those which were not officially supported.
> 
> @oleg-derevenetz , what do you think?

I agree. People might think that as long as they are selected French or Russian language, they will get the whole game in that language, but they are unaware that they will need also localized versions of game assets, and this may be surprising.

**Comment by qarkai** [comment]
No comment, no option rename, nothing, just "leave as it is"? I remind that installer brings a bunch of unneeded files.

> they are unaware that they will need also localized versions of game assets
Let's make people aware what they need.

**Comment by oleg-derevenetz** [comment]
> @ihhub then why do we install them if we don't support these languages?

We have, but only partially - we still need at least fonts from official assets. Also IIRC there are images with pre-rendered localized text on them in these assets.

**Comment by oleg-derevenetz** [comment]
> @qarkai , we have a partial support of Polish, Russian and French languages. The rest of languages right now are not in use. If the problem is in extra files let's just copy these 2 languages for now but without the menu to select languages.

People still may edit fheroes2.cfg by hand and get another language... Well, sort of :)

**Comment by ihhub** [comment]
> > @qarkai , we have a partial support of Polish, Russian and French languages. The rest of languages right now are not in use. If the problem is in extra files let's just copy these 2 languages for now but without the menu to select languages.
> 
> People still may edit fheroes2.cfg by hand and get another language... Well, sort of :)

-_- That's why I suggested to leave as it is for now :)

**Comment by ihhub** [comment]
I'm moving this pull request to 1.0 release as we still don't have an ability to support multiple languages (for now) based on game's assets. I have a plan to generate language assets based on English letters but it'll take some time.

**Comment by ihhub** [comment]
I converted this pull request to Draft for now as we haven't agreed on the solution. Once we add support of other languages out of box we can add this change.

**Comment by ihhub** [comment]
Soon we're going to be able to support all languages so the question is whether we really want to allow users to select certain languages? I think in the current era of high volume discs 1 MB shouldn't matter much.

@qarkai  and @oleg-derevenetz , what do you guys think?

**Comment by oleg-derevenetz** [comment]
@ihhub

> Soon we're going to be able to support all languages so the question is whether we really want to allow users to select certain languages? I think in the current era of high volume discs 1 MB shouldn't matter much.

I believe this is not necessary.

**Comment by qarkai** [comment]
@ihhub I don't care. I'm tired of team's attitude.

**Comment by ihhub** [comment]
> @ihhub I don't care. I'm tired of team's attitude.
Oh, that's sad to hear. I didn't know that something went wrong but still thanks a lot for your contribution to the project.

**Comment by ihhub** [comment]
We are closing this pull request as we greatly expanded the list of languages by default.

**Pull request closed without merging**
