### PR TITLE
Fix attacking monster sprite behavior

### LINKED ISSUE #885: Screen moves a bit after visiting some objects
When hero visits any object, which has pop up window, when we close that window screen moves a few pixels to the direction hero made his last move. 
(On a screen hero visited windmill standing to the right from it)
move
move2

### LINKED ISSUE #1142: Neutral creature changes its sprite before hero appears nearby using "Dimension Door" spell
When you use "Dimension Door" spell to teleport hero to the neutral creature, Creature changes to attacking state before hero appears nearby. 
I think, neutrals should change its sprite after hero was completely drawn after spell.
Note that creatures attack hero in this case only when "only the first monster will attack(H2 bug)" option is switched off.
Attacking creature

### LINKED ISSUE #2377: World map, sprite of neutral creature freezes in attacking state
When hero visit some object on a world map, which is too close to a neutral creature, we can constantly watch an attacking sprite, until hero moves away.
image

### LINKED ISSUE #2537: Adventure map, attacking state of neutral creatures regarding option "the first monster will attack"
When we set the option, which makes only the first creature attack hero, on, creatures doesn't change to attacking sprite while being attacked by a hero.
On a screenshot hero attack a bunch of zombies, but none of them change to attacking sprite.
image
But when we set the option off, all of them are attacking and all of them change sprite.
image

Also, in the original game, attacking sprite appears only before a battle, and in fheroes2 we can watch them after a battle.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
In original game, sprite of a monster attacked by hero (or attacking hero) changed before battle to the "attacking" sprite. This was the case in fheroes2 too if "world: only the first monster will attack (H2 bug)" option wasn't enabled. Recently this option was removed, so I decided to make this "attacking" sprite work again (and properly).

fix #1142 (sprite change logic was fixed)
fix #885 (still should fix that! 😛)
fix #2537 
fix #2377

### CODE REVIEW

**Comment by ihhub** [comment]
The only issue with this approach is that the screen now moves twice instead of once :(

@Branikolog, what do you think? Please test these changes.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> The only issue with this approach is that the screen now moves twice instead of once :(

I can avoid calling of `I.Redraw()`, but in this case sprite change will be delayed until battle will be over. Need to think, may be there will be better ideas. I already noticed that screen slightly moves after closing of "quick battle results" dialog even without my changes.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , to solve the problem with moving screen after battle and before dialogs you should call `I.GetGameArea().SetCenter( hero.GetCenter() );`  and redrawing the screen before `if ( JOIN_FREE == join.first ) {`.

**Comment by oleg-derevenetz** [comment]
@ihhub

> and redrawing the screen before `if ( JOIN_FREE == join.first )`

The idea was to change sprite only when monster group was really attacked, not when it joins or flees, so it seems that we should do yet another redraw - one after `SetCenter()` and another one after `SetAttackedMonsterTileIndex()`. I'll try it.

**Comment by ihhub** [comment]
> @ihhub
> 
> > and redrawing the screen before `if ( JOIN_FREE == join.first )`
> 
> The idea was to change sprite only when monster group was really attacked, not when it joins or flees, so it seems that we should do yet another redraw - one after `SetCenter()` and another one after `SetAttackedMonsterTileIndex()`. I'll try it.

Yes, In this case we won't have any moving screen.

**Comment by ihhub** [comment]
I have even better idea: why can't we set the center and redraw inside `void Heroes::Action( int tileIndex, bool isDestination )` but it needs to be tested properly.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , the change looks good. The only drawback is that we draw one more frame per tile. We have very slow systems with ~14 FPS right now so 1 extra frame might be significant. Let me think please how to tackle this problem.

**Comment by oleg-derevenetz** [comment]
As far as I understand, `Heroes::Action()` is not called for most tiles, it called only if there is some object, monster or event.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , actually it's called for every tile as of now ;(

**Comment by oleg-derevenetz** [comment]
@let's make centering at the beginning of `ActionToMonster()` then.

**Comment by ihhub** [comment]
> @ihhub let's make centering at the beginning of `ActionToMonster()` then.

Sure. Let's do it and fix another issue later.

**Comment by oleg-derevenetz** [comment]
@ihhub How about this approach?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , if you don't mind could we please merge this pull request after tomorrow's release? Based on the experience we had in the past I would like to avoid potential bugs in release build without proper testing :)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub There is no hurry :) This issue is rather cosmetic anyway.

**Comment by ihhub** [comment]
#2377 might be fixed by this change as well.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for fixing it!

**Pull request merged**
