### PR TITLE
Fix position of left barbarian's captain quarters part

### LINKED ISSUE #6263: Castle screen, barbarian captain's quarters has shifted column
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
Recently added column ran away.

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by undef21**
fix #6263

### CODE REVIEW

**Comment by ihhub** [comment]
I think we have to fix assets instead of ignoring an invalid value from them. What do you think?

**Comment by undef21** [comment]
This bug is applying offsets twice. The first applying was in this file and the second one is [here](https://github.com/ihhub/fheroes2/blob/c33f389aaefcb0f1090caa08c50887ccf8321e55/src/fheroes2/gui/ui_castle.cpp#L289). The resources are correct.

Also, this regression was introduced in #5407.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Branikolog , please test this pull request for every castle.

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@undef21 , thank you so much for fixing this issue!

**Pull request merged**
