### PR TITLE
AI: implement the logic to transfer the slowest troops to the garrison at the end of the turn to try to get a movement bonus on the next turn

### LINKED ISSUE #8207: Teach AI to garrison slower troops in the castle at the end of turn
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently when the AI ends the turn and it has a hero visiting a castle, it will not garrison any troops, which means that the next day their movement points will be based on a potentially slow troop in that army. Instead, if it would garrison these troops, it would get a single-turn movement points boost that can be good for many reasons, like having a greater chance to reach nearby objects and get back to the castle in one turn, among many other things.

Additionally, since by default you get more detailed information about troops in a hero's army than a castle's garrison, not garrisoning is suboptimal. One exception being the times when you own 2 thieves guilds. Therefore, garrisoning troops would then improve this by hiding what troops the AI has to the human player.

This is an example of the hero visiting the castle and you can see that they have garrisoned 0 troops, keeping the very slow Golems in their army. The best way here would be to only keep the very fast boars in their army.

image
image

### Describe the possible solution

Teach the AI to garrison troops by leaving only the fastest troops in its army, whether that is a single troop type or several. The AI will need to garrison troops in the corresponding castle slot they would have wanted the troops to be in their army in case they get attacked.

I suggest to avoid making a very complex logic for it, since even just a simple one would bring big benefits. For example, there can be special cases where you could optimize more, like if your castle has ultra fast troops that you don't intend to keep in your army the next day, but you know that you are in no threat to be attacked, so you move them to your army just to get the movement points, and replace them with desirable troops the next day. However, I suggest not diving into such cases - They are few, and just doing the basic variant of this optimization will be much better than the average heroes 2 player from my experience (I've never seen a streamer do or be aware of this trick).

Ideally, the AI should keep the one, or the several troops, with the highest speed in its army, and "move up" in the garrison the troops that are slower, starting with the slowest one in case the castle has slots filled with creatures already.

Note that this should only be done at the end of the player turn for every hero the AI currently has in a castle, not for every visit to a castle. I suppose it would even be beneficial for heroes that are permanently stationed in a castle for the reason of concealing its actual army.

### Additional info

Relates to this https://github.com/ihhub/fheroes2/issues/6755

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
close #8207

Demo video:

https://github.com/ihhub/fheroes2/assets/32623900/dc1d3998-a340-4eab-ab07-5c9943f98ff3

In the `master` branch AI hero has not enough movement points to attack my hero after dismissing the Dragons:

https://github.com/ihhub/fheroes2/assets/32623900/9d076999-c7c2-4f62-a0a9-f5ae4c1806c8

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @zenseii

> This PR did disclose some behavior which some might consider "cheating" by the AI, and I'm not saying it has to be fixed here, hence the approval.

Please note that there are [different rules](https://github.com/ihhub/fheroes2/pull/6741#issuecomment-1454322499) for army merging in case of human-controlled and AI-controlled castles. It's been like this since the beginning.

**Comment by oleg-derevenetz** [comment]
> Ah, yes I had a vague memory of discussing this before. In this case I have nothing more to add and it works as it should right now.

Maybe someone will call this "cheating" and perhaps different rules for AI and human player can even be called such to some extent, BUT I should note that this was the easiest way to strengthen AI during the castle defense.

**Comment by oleg-derevenetz** [comment]
> This is luckily not the case in fheroes2 as far as I'm aware.

Yes, in fheroes2 AI army arrangement is not dependent on the composition of an enemy army, only on the composition on the AI army itself.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for these improvements!

**Pull request merged**
