### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by Arthusppp**
Update Polish translation

relates to #6822

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Arthusppp , could you please address these issues for Android build:
```
* What went wrong:
Execution failed for task ':app:lintDebug'.
>                 Lint found errors in the project; aborting build.
  
                  Fix the issues identified by lint, or create a baseline to see only new errors:
                  ```
                  android {
                      lint {
                          baseline = file("lint-baseline.xml")
                      }
                  }
                  ```

  
> Task :app:lintReportDebug
                  For more details, see https://developer.android.com/studio/write/lint#snapshot
Wrote HTML report to file:///home/runner/work/fheroes2/fheroes2/android/app/build/reports/lint-results-debug.html
  

> Task :app:lintDebug FAILED
Lint found 2 errors, 3 warnings. First failure:

/home/runner/work/fheroes2/fheroes2/android/app/src/main/res/values-pl/strings.xml:25: Error: For locale "pl" (Polish) the following quantities should also be defined: few (e.g. "2 miesiące"), many (e.g. "5 miesięcy") [MissingQuantity]
                  Lint found 2 errors, 3 warnings. First failure:
  
  /home/runner/work/fheroes2/fheroes2/android/app/src/main/res/values-pl/strings.xml:25: Error: For locale "pl" (Polish) the following quantities should also be defined: few (e.g. "2 miesiące"), many (e.g. "5 miesięcy") [MissingQuantity]
      <plurals name="activity_save_file_manager_delete_confirmation_title">
      ^
  
  The full lint text report is located at:
    /home/runner/work/fheroes2/fheroes2/android/app/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 15s
    <plurals name="activity_save_file_manager_delete_confirmation_title">
    ^

The full lint text report is located at:
```

I believe this is the case which you highlighted in Discord.

**Comment by Arthusppp** [comment]
> I believe this is the case which you highlighted in Discord.

I have updated according to the error message. 

How I can check if I have translated correctly? For example: "_please, download the apk related to your PR from Checks/Actions and run it on any android device_".

**Comment by ihhub** [comment]
> > I believe this is the case which you highlighted in Discord.
> 
> I have updated according to the error message.
> 
> How I can check if I have translated correctly? For example: "_please, download the apk related to your PR from Checks/Actions and run it on any android device_".

Hi @Arthusppp , do you mean check on the Android device? If yes then just download compiled version of APK from the artifacts of this pull request and run `fheroes2 Toolset` (this is a separate app) on your device with Polish language being set by default.

**Comment by ihhub** [comment]
I am marking this pull request as high priority as we need to complete all preparations for Google Play Store which is the highest goal at the moment.

**Review by oleg-derevenetz — APPROVED** [review]
I didn't tried this on real Android device, but looks OK.

**Comment by Arthusppp** [comment]
> For now my suggestion is to leave the best translation possible and then we'll adjust the code of the buttons instead.

Given above, this PR contains the best possible translation.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Arthusppp , a bunch of thanks for this update!

**Pull request merged**
