### PR TITLE
Add extended cursor icons from 4+ to 7+

### PR DESCRIPTION
**Pull request by ihhub**
relates to #3299

All numbers are rendered from scratch. Old icons have some defects like an overlapped digit over cursor.

image

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , could you please test these changes at first available time? I extended the range of numbers from (2, 3, 4+) to (2, 3, 4, 5, 6 ,7, 7+) for all hero-related cursor types.
There were few defects with the original implmenetation:
- some cursors have overlapped cursor by a digit
- cursor was `jumping` while switching from for example move to "move with 2" type.

These 2 issues should not be present in this implementation.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu and @Branikolog , could you please test these changes at first available time? I extended the range of numbers from (2, 3, 4+) to (2, 3, 4, 5, 6 ,7, 7+) for all hero-related cursor types.
> There were few defects with the original implmenetation:
> 
> * some cursors have overlapped cursor by a digit
> * cursor was `jumping` while switching from for example move to "move with 2" type.
> 
> These 2 issues should not be present in this implementation.

Maybe the numbers could be less "squared".

Look at the original "2" and "3" numbers.
The bottom part of the number "5" on the right could be "rounded", as for example for the original number "3".
Same for the number "6" on the top and bottom.
And for the number "7" put the bar that goes down in an oblique way.

Other than that, I did some tests on land and on the ocean and it seems to work fine. :1st_place_medal: 

Nothing planned for the numbers on the hero path graphics?
It would not be necessary to "hunt" the graphics along the path to see the number of turns required. :D

**Comment by ihhub** [comment]
> Hello @ihhub,
> 
> > Hi @LeHerosInconnu and @Branikolog , could you please test these changes at first available time? I extended the range of numbers from (2, 3, 4+) to (2, 3, 4, 5, 6 ,7, 7+) for all hero-related cursor types.
> > There were few defects with the original implmenetation:
> > 
> > * some cursors have overlapped cursor by a digit
> > * cursor was `jumping` while switching from for example move to "move with 2" type.
> > 
> > These 2 issues should not be present in this implementation.
> 
> Maybe the numbers could be less "squared".
> 
> Look at the original "2" and "3" numbers.
> The bottom part of the number "5" on the right could be "rounded", as for example for the original number "3".
> Same for the number "6" on the top and bottom.
> And for the number "7" put the bar that goes down in an oblique way.
> 
> Other than that, I did some tests on land and on the ocean and it seems to work fine. 
> 
> Nothing planned for the numbers on the hero path graphics?
> It would not be necessary to "hunt" the graphics along the path to see the number of turns required. :D

Could you please provide these modified numbers? I mean images so I could see how it will look like.

Numbers on turns are not implemented yet.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Could you please provide these modified numbers? I mean images so I could see how it will look like.

Something like this (the number "7" is the same in both cases):
I have a small preference for the first three.

  

  

Compare them to these numbers:

Compare numbers 01

[Cursors fh2 01.zip](https://github.com/ihhub/fheroes2/files/6495937/Cursors.fh2.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , number 7 was the same so I implemented based on the image in the archive. Number 6 is taken from the first case while 5 is from the second one to differentiate them easier.

**Pull request merged**
