### PR TITLE
Fix scrolling in full-screen mode in case of an aspect ratio mismatch

### LINKED ISSUE #5203: Fullscreen in MacOS does not fill up to the top of the screen
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

I'm reporting this from a supporter user "Hydd" from the Discord server. This animation they shared shows that the fullscreen does not reach the upper border of the screen, and therefore makes vertical panning upwards with the mouse cursor very inconvenient.
giphy

I'll report back when the user replies what exact version of MacOS, fheroes2 build and resolution they're using. They first reported this on March 3rd.

### Save file

No save file, just try fullscreen.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5203

It would be good to check this on multi-monitor systems as well.

https://user-images.githubusercontent.com/32623900/161856562-90697848-6300-4727-993a-2e51e413053c.mp4

### CODE REVIEW

**Comment by zenseii** [comment]
Hi @oleg-derevenetz ! Thanks for addressing this so quickly. If necessary I can ask the user to grab a build from here if or when it is ready for testing.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii please note that this PR doesn't fix the black bar itself, but it should fix the scrolling issue - it should become easier to scroll.

**Comment by zenseii** [comment]
> Hi @zenseii please note that this PR doesn't fix the black bar itself, but it should fix the scrolling issue - it should become easier to scroll.

That should be no problem, but I'll inform the user. Right now I'm having trouble finding out where someone could grab a build generated from the workflow of this PR? I realize that in Artifacts there are only the Windows MSVC generated builds. What approach do you suggest to take in order to share a testing build with the user?

**Comment by oleg-derevenetz** [comment]
Hi @zenseii now the build artifact should also be uploaded for Linux, macOS, PSV and Switch targets (at least in this PR).

**Comment by zenseii** [comment]
Fantastic! I've shared a link to the build to the user and hopefully they will be able to report back to us swiftly.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @zenseii , what's about locking the mouse cursor within the application area? For example, like [this](https://gamedev.stackexchange.com/questions/33519/trap-mouse-in-sdl).

**Comment by oleg-derevenetz** [comment]
Hi @ihhub this PR solves more general issue with scrolling in cases when app's aspect ratio doesn't match the screen aspect ratio. Mouse grab by window will not help here, because all these dark bars are already inside the game's window.

**Comment by oleg-derevenetz** [comment]
@ihhub

https://user-images.githubusercontent.com/32623900/162003734-d1a5e1dd-e080-428e-a0bb-17aabb8ef405.mp4

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for fixing this issue!

**Pull request merged**
