### PR TITLE
Fix java.nio desugaring on Android 7 and below

### LINKED ISSUE #7174: Toolset app crashes on trying to open to select archive
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

A user on Discord is reporting that the toolset app crashes without a message upon clicking on the option "extract homm2 assets" on their Android 7 tablet.

Version 1.0.3 worked fine.
### Save file

No file.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #7174

Plus various dependency updates. Tried this PR on Lenovo TAB 2 A10-70L with Android 6 and everything works fine.

### CODE REVIEW

**Comment by admmlk** [comment]
I'm still not able to run the game ('fheroes2 has been stopped') with the build spposedly containg this fix ( https://github.com/ihhub/fheroes2/releases/tag/fheroes2-android ) on my **Android 4.1.1** (Kiano Slimtab 10").

(I had no issues with running older 1.0.x versions of the game on that device.)

Here's my thread on The Forums https://heroes2.forumactif.com/t1049-1-0-4-unfortunatelly-app-fheroes2-has-been-stopped-on-android-5-1-1#9484

**Comment by admmlk** [comment]
@oleg-derevenetz  Omg sorry for confusion, it's 5.1.1 as mentioned on The Forum of course 😓

**Comment by oleg-derevenetz** [comment]
@admmlk we are currently discussing this issue in #7187. Please join the discussion and try https://github.com/ihhub/fheroes2/issues/7187#issuecomment-1548170179.

**Comment by admmlk** [comment]
@oleg-derevenetz I was able to run and play the game on 5.1.1 with use of the build mentioned there 👍 Thank you for quick reaction :)

**Comment by oleg-derevenetz** [comment]
@admmlk Unfortunately, it's a debug build without optimizations, so it may work significantly slower than the release build. But it seems that NIO emulation for older devices fails on release builds, and this problem has not been solved yet.

**Comment by admmlk** [comment]
Verified also on latest snapshot build, works fine and smooth now 👍
Thanks!

**Pull request merged**
