### PR TITLE
Update SDL to 2.0.22 version for Windows

### PR DESCRIPTION
**Pull request by ihhub**
- update SDL library from 2.0.12 to 2.0.22 for Windows
- add more error checks for rendering
- add TODO comments for the future rendering enhancement

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , do you observe the error with audio frequency on the last SDL Mixer version?

**Comment by oleg-derevenetz** [comment]
@ihhub yes, on Windows the frequency is always 48000.

**Comment by ihhub** [comment]
This is strange as this error doesn't appear on the older version of SDL.

**Comment by oleg-derevenetz** [comment]
@ihhub

> This is strange as this error doesn't appear on the older version of SDL.

Maybe the older version of SDL just don't try to get the "real" frequency after an attempt to set a new one? :)

**Comment by oleg-derevenetz** [comment]
@ihhub

> This is strange as this error doesn't appear on the older version of SDL.

This error is caused by [this code](https://github.com/libsdl-org/SDL/blob/cdf9010a19512dc84f6770d3617b848f5848876f/src/audio/wasapi/SDL_wasapi.c#L461-L470) in SDL:

```cpp
#if 1  /* we're getting reports that WASAPI's resampler introduces distortions, so it's disabled for now. --ryan. */
    this->spec.freq = waveformat->nSamplesPerSec;  /* force sampling rate so our resampler kicks in, if necessary. */
#else
    /* favor WASAPI's resampler over our own */
    if (this->spec.freq != waveformat->nSamplesPerSec) {
        streamflags |= (AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM | AUDCLNT_STREAMFLAGS_SRC_DEFAULT_QUALITY);
        waveformat->nSamplesPerSec = this->spec.freq;
        waveformat->nAvgBytesPerSec = waveformat->nSamplesPerSec * waveformat->nChannels * (waveformat->wBitsPerSample / 8);
    }
#endif
```

If I [replace](https://github.com/oleg-derevenetz/vcpkg/compare/sdl2-mixer-2.6.1...oleg-derevenetz:vcpkg:test) `#if 1` by `#if 0`, everything works as before:

https://github.com/oleg-derevenetz/fheroes2/actions/runs/2682976958#artifacts

SDL people claim that their resampler don't introduce distortions (unlike the WASAPI resampler). Are you sure about these distortions with rate 48000 and the latest SDL?

**Comment by oleg-derevenetz** [comment]
> SDL people claim that their resampler doesn't introduce distortions (unlike the WASAPI's resampler).

@zenseii tells that there is no noise even with mismatched rates, so it is possible to just turn the corresponding `ERROR_LOG` into the `DEBUG_LOG( DBG_ENGINE, DBG_WARN )` and left it as is.

**Comment by ihhub** [comment]
I found the source of audio issue for me: I set 3D audio on and when I open this save file water sounds are sometimes played in a way like the sound is distorted:
[-music.zip](https://github.com/ihhub/fheroes2/files/9127032/-music.zip)

I will make this ERROR as LOG to avoid player's confusion.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by oleg-derevenetz** [comment]
Hi @ihhub what about that issue with cursor?

**Comment by ihhub** [comment]
> Hi @ihhub what about that issue with cursor?

It's miraculously fixed. Probably they fixed it in the subsequent releases.

**Pull request merged**
