### PR TITLE
Fix a crash on deleting last save file

### PR DESCRIPTION
**Pull request by undef21**
Also replace `System::Unlink` with `std::filesystem::remove`

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @undef21 while using `std::filesystem` is fine of course, I still recommend to use it in the `engine` part and export some function (like `System::Unlink`, but maybe with different name, it's up to you) to avoid exposing implementation details when they are not really needed - for example, including the `<system_error>` header and using the `ec` variable.

What is usually needed is to remove some file and (optionally) find out if the deletion was successful, with such special function this can be done in one line.

Also this reduces the risk that someone will forget about the non-throwing overload and will use the overload without the `std::error_code` parameter.

What do you think?

**Comment by undef21** [comment]
Hi @oleg-derevenetz 
OK, I'll move std::filesystem-related changes to another PR.

**Comment by oleg-derevenetz** [comment]
BTW in this old code the result of `Unlink()` is not checked at all and save file is removed from the list even if it wasn't in fact deleted. This is of course is not directly related to the topic of this PR, but still looks not good :)

**Comment by undef21** [comment]
> BTW in this old code the result of `Unlink()` is not checked at all and save file is removed from the list even if it wasn't in fact deleted. This is of course is not directly related to the topic of this PR, but still looks not good :)

fixed in #7009

**Comment by ihhub** [comment]
@undef21 , thank you very much for the fix!

**Pull request merged**
