### PR TITLE
Android Toolset: add the ability to export and import save files (as a ZIP archive)

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Related to #7501

https://github.com/ihhub/fheroes2/assets/32623900/ebf186af-4559-4099-8fd3-67211a4db681

The types of saved files imported from the ZIP archive (single player, campaign, multiplayer) can be additionally adjusted by a switch at the top of the screen.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @zenseii

> However, perhaps in this case we should show a dialog saying something like "No fheroes2-compatible save files were found in the selected zip archive"?

To be honest, I don't like modal dialogs very much, especially when they are the not the result of a user's immediate actions, but a background processes. We can show the status of the latest action instead, like it's done with OG assets extraction, but IMHO this will be redundant as well, because the user will still see that the no newly imported save files were added to the list.

**Comment by oleg-derevenetz** [comment]
> Also I suggest mentioning #7501 since this is very relevant to it.

It is already mentioned in the first line of the PR description :)

**Comment by oleg-derevenetz** [comment]
Hi @zenseii I have implemented something like a status message that should be shown when something goes wrong:

Screenshot_20230805-181008

**Comment by oleg-derevenetz** [comment]
@zenseii

> The import and export icons are, to me at least, very easy to confuse with upload and download symbols.

I use icons from the Google Material Icons set (Apache license):

https://fonts.google.com/icons?icon.set=Material+Icons

You csn browse it and suggest icons that are more suitable in your opinion.

> I realized the save management button is enabled even when original assets aren't found right after installing the app.

I just see no reason to impose artificial restrictions on what user is able to do if there are no technical reasons for these restrictions. Save file management works just fine even without OG assets (exactly the same as on the desktop BTW), so why we should impose any restrictions? The user will figure out when and how best to use this opportunity.

**Comment by oleg-derevenetz** [comment]
@zenseii

> They are basically the same icons turned 90 degrees.

Yes, and thus they turned into doors :) IMHO it will be difficult for the user to understand how these doors are related to the import/export operations. "Upload/download" is a closer association IMHO.

> Alternatively:

ZIP folder icon - maybe, there is something in this, but I doubt that just a folder icon is a good association with the import operation :)

**Comment by oleg-derevenetz** [comment]
@zenseii

> I guess we could use a mix of the download icon and the zipped icon

So what the zipped icon should be used for? Import operation OPENS the ZIP file and export operation CREATES the ZIP file, so there is some uncertainty as well.

**Comment by oleg-derevenetz** [comment]
@zenseii

> I suppose we could use the zipped archive icon if we had a disabled state for the extract button, in case no file is selected, then enable it once a file is. This would give some feedback as to what button does what.

Currently there is dialog appears when you press the Export button and there are no files selected. I thought it would be better than just a disabled or doing nothing button, because the dialog explains exactly what needs to be done to make it work.

**Comment by oleg-derevenetz** [comment]
@zenseii OK, what do you think about these icons:

Screenshot_20230808-123924

?

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , great thanks for adding this feature!

**Pull request merged**
