### PR TITLE
Changed Titan cost

### LINKED ISSUE #127: Titans surrender cost is not like the original
Related to #56
From the FIXME in `src/fheroes2/battle/battle_army.cpp`.

Since I can't easily start the original Windows demo I'll guess that the original cost for the surrender of 3 Titans is 7500 golds. In the current version it's 5000 gold per Titan (plus 2 gems).

### PR DESCRIPTION
**Pull request by alx168**
should fix #127

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @alx168 it's incorrect fix for above issue. Would you mind to continue to work on it?

**Comment by alx168** [comment]
Sure. Could you provide me more details on what you mean?

**Comment by ihhub** [comment]
@alx168 what you changed is the cost of Titans to hire and how many of them grow in castle per week. What you need to fix is surrender cost during battle which is as mentioned in original issue locates in `u32 Battle::Force::GetSurrenderCost(void) const` function.

**Comment by ihhub** [comment]
Closing this pull request as it has been hanging for a very long time.

**Pull request closed without merging**
