### PR TITLE
Separate Abandoned and Haunted mines

### LINKED ISSUE #5651: Combat, Abandoned Mine, wrong number of ghosts, ghost groups and their positioning
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the Ghosts guarding an Abandoned Mine should always be divided into five groups, as in the original game.
Otherwise it's too easy to slow down the single group with an easily accessible Slow spell, compared to the Mass Slow spell.

In original game:

Abandoned mine 001

Abandoned mine 002

Abandoned mine 003

Abandoned mine 004

Abandoned mine 005

Abandoned mine 006

In fheroes2:

Abandoned mine 007

https://user-images.githubusercontent.com/43583994/179030233-f22e7f9e-933f-4a6b-882c-091cd585deb3.mp4

**Edit 2022/07/16.**

In fheroes2:

**Abandoned Mine:**
- The number of ghosts can evolve over the combats, unlike the original game.
- There is a different number of ghosts than in the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

In original game:

**Abandoned Mine:**

The ghosts can be divided into three configurations:
- 5 groups
- 4 groups
- 3 groups

In original game:

Abandoned Mine H2 001

Abandoned Mine H2 009

Abandoned Mine H2 003

The number of ghosts does not increase or decrease if the combat is not won and another combat is started on the same abandoned mine.
If there are 30 ghosts at the beginning of the combat and the hero reduces this number to 15 ghosts before fleeing, there will still be 30 ghosts at the next combat.
If there are 30 ghosts at the beginning of the combat and the number of ghosts is increased to 45 ghosts before the hero flees, there will still be 30 ghosts in the next combat.

The number of ghost groups and their positioning in the battlefield hexes is related to the position of the abandoned mine on the adventure map.
Repeating the combat in the same abandoned mine always gives the same number of groups and the same positioning of the ghosts, even if the scenario is completely restarted.
The number of ghosts is different when the scenario is completely restarted, but is always the same during the same scenario session.
This is certainly determined at the start of the scenario for all abandoned mines.

> @undef21 @LeHerosInconnu
> 
> It is mentioned here that the number of ghosts can be in the range of 30-60:
> 
> https://handbookhmm.ru/2-objects

This is consistent with what I have observed.

In original game:

30 ghosts:
Abandoned Mine H2 003

60 ghosts:
Abandoned Mine H2 001

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/5651#issuecomment-1185846862_

### Save file

Here are the save files:
[Abandoned mine 01.zip](https://github.com/ihhub/fheroes2/files/9113536/Abandoned.mine.01.zip)

### Additional info

Related issues: https://github.com/ihhub/fheroes2/issues/5662, https://github.com/ihhub/fheroes2/issues/5663.
Related discussion: https://github.com/ihhub/fheroes2/discussions/5664.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5651

### CODE REVIEW

**Review by Districh-ru — COMMENTED** [review]
Hi, @oleg-derevenetz, I checked the Abandoned and Haunted mine capture, including the case when both hero and ghosts are defeated, and all works perfect. These mines are also correctly displayed on radar and in the View World mode.
I just only encountered one save file incompatibility bug. Could you please check it:

If I load a save file made by the master build game I get a legion of ghosts in the mine guard:
изображение

изображение

Save file with Haunted and Abandoned mines:
[legion_ghosts.zip](https://github.com/ihhub/fheroes2/files/11032637/legion_ghosts.zip)

This issue is only with the save files. If I start the new game then all is OK.

**Comment by oleg-derevenetz** [comment]
@Districh-ru Yes, new Abandoned Mines are incompatible with old ones because new Abandoned Mines store the number of troops in the same place where old mines store their per-day income (1000 gold), so these mines looks like "over-protected". But in fact this is not vital for overall playability, because Abandoned Mines are "optional" objects. I don't know if it's worth doing any hotfixes for old savefiles with Abandoned Mines. @ihhub what do you think?

**Review by Districh-ru — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I believe that we can close #3725 and #3204 since we now have clear separation between two mine types. What do you think?

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for these changes!

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I believe that we can close https://github.com/ihhub/fheroes2/discussions/3725 and https://github.com/ihhub/fheroes2/pull/3204 since we now have clear separation between two mine types. What do you think?

Ghost animation is still present on both types of mines, but now it could be easily removed. I left it on the Abandoned Mines because I like it :)

**Pull request merged**
