### PR TITLE
Make the castle: allow guardians option by default

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Alternative approach to #6190
Related to #6161

This option is supported well enough both in the game logic and game UI, some efforts have been made to polish it and it would be a pity to throw it all away. AI doesn't know how to perceive its benefits for now, but at least it doesn't conflict with this feature.

After all, we already have changes in the core that affect the overall game balance even more - for example, the ability to hire non-upgraded units in the upgraded dwellings.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I think we need to fix at least these points to proceed with the pull request:
- [ ] `AIShouldVisitCastle()` function does not properly calculate strength. If both heroes are present in the castle we need to check whether it is possible to kill the first one without castle's strength calculation
- [ ] add TODO comments to improve AI to utilize this feature in the future (especially while hiring heroes to swap them if needed)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> `AIShouldVisitCastle()` function does not properly calculate strength

Could you please elaborate this a bit? `AIShouldVisitCastle()` compares attacker hero's strength with the result of `castle->GetGarrisonStrength()`:

```cpp
        return heroArmyStrength > castle->GetGarrisonStrength( &hero ) * advantage;
```

and `GetGarrisonStrength()` correctly accounts the strength of both guest and guardian heroes:

```cpp
    CastleHeroes heroes = world.GetHeroes( *this );
    if ( heroes.Guest() ) {
        totalStrength += heroes.Guest()->GetArmy().GetStrength();
    }
    if ( heroes.Guard() ) {
        totalStrength += heroes.Guard()->GetArmy().GetStrength();
    }
    else {
        totalStrength += army.GetStrength();
    }
```

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , actually you are right. Despite of fact that AI attacks guest first and then guardian the overall strength is the same.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
This option is nice, but I nevertheless think, that it changes original gameplay. Original game has a nice, unique mechanic of castle captains which would become useless. I'd rather prefer improving this mechanic, than copy-paste H3-like garrison heroes.
I agree with statements of @zenseii , mentioned in his https://github.com/ihhub/fheroes2/issues/6161#issuecomment-1313383139 , and I agree it should exist as an option at least.

>After all, we already have changes in the core that affect the overall game balance even more - for example, the ability to hire non-upgraded units in the upgraded dwellings.

I consider this as minor option, that hardly anyone is using. This changes nothing in gameplay, and especially after our recent 2x upgrade cost implementation, I even doubt do we still need to have it. :)

**Comment by oleg-derevenetz** [comment]
> Original game has a nice, unique mechanic of castle captains which would become useless.

Castle guardians do not make captains useless. Each and every castle may have a captain, while number of guardian heroes is limited - they are accounted in the total number of heroes, which is 8.

> copy-paste H3-like garrison heroes

This is not a copy-paste.

> I consider this as minor option, that hardly anyone is using. This changes nothing in gameplay.

In fact, this changes the gameplay and affects the game balance. You see, non-upgraded units are cheaper, so now you have a choice - you can buy a few upgraded units or several non-upgraded. Where you could only buy a Titan in the original game, now you can buy a Giant even if you don't have money or resources for a Titan.

**Comment by zenseii** [comment]
Hi, @oleg-derevenetz and @Branikolog.

I've given this feature a considerable amount of thought and as @oleg-derevenetz pointed out there is no concern about captains as long as the garrisoned heroes count towards the maximum of 8 heroes. Actually I would argue you almost never want to have a hero garrisoned, if you read on.

The way I see it there are two things that need to be addressed with this:
1. It is a good Heroes 2 strategy to garrison slow creatures and have the guest hero keep only the fastest creatures so that the hero gains max movement points the next day. Example: Have phoenixes in the guest heroes army with all other slots empty and unicorns, druids etc in the castle garrison. This lets your hero automatically get these creatures if attacked but also ensures you get more movement points. Is this still possible with this feature if you have a guest hero and no guardian hero? If yes then there is no problem here.

2. This feature is mostly a convenience feature of getting to recruit creatures to two heroes while in the castle screen (if the gates were wider you could have 8 heroes visiting for a real party). However, a big change is the visual one. This feature will feel very familiar to players coming from later heroes games (maybe too familiar?), but unfamiliar to players who've only played Heroes 2. I'm not saying it will look bad for them, but consider the impression it would give Heroes 3 fans if you could enter a battle with only a hero and no creatures and only get to cast one spell provided your speed is high enough, i.e. the equivalent of the well-known heroes 3 tactic of having 1 fast unit only to cast armageddon, just made visually closer to Heroes 4. Some might not like such a change.

**Comment by oleg-derevenetz** [comment]
> Is this still possible with this feature if you have a guest hero and no guardian hero?

Yes, of course. If there is no guardian hero, usual mechanics are applied - units from garrison will join the guest hero's army.

> This feature will feel very familiar to players coming from later heroes games (maybe too familiar?), but unfamiliar to players who've only played Heroes 2. I'm not saying it will look bad for them, but consider the impression it would give Heroes 3 fans if you could enter a battle with only a hero and no creatures and only get to cast one spell provided your speed is high enough, i.e. the equivalent of the well-known heroes 3 tactic of having 1 fast unit only to cast armageddon, just made visually closer to Heroes 4. Some might not like such a change.

Let's say so: fans of the "pure" HoMM2 are not obligated to use this feature at all. Regarding HoMM3, there is a special tactics, so-called "propping up", when your main hero is in the castle (sort of), but it "propped up" by the guardian hero. There are two profits:

1. Your main hero fights outside of the castle walls and may retreat if he wants to;
2. Your main hero still replenish the full mana if there is a Mage Guild in the castle.

**Comment by zenseii** [comment]
> Yes, of course. If there is no guardian hero, usual mechanics are applied - units from garrison will join the guest hero's army.

Great, then we are really only talking about a visual/UI and convenience change, unless I'm missing something.

> Let's say so: fans of the "pure" HoMM2 are not obligated to use this feature at all.

I see. In other words make it an option. I personally might start using this instead of currently having to buy creatures on the guest hero, leave the castle screen and open the heroes meeting screen with the second hero etc. Again, a matter of convenience.


> Regarding HoMM3, there is a special tactics, so-called "propping up", when your main hero is in the castle (sort of), but it is "propped up" by the guardian hero. There are two profits:
> 
> 1. Your main hero fights outside of the castle walls and may retreat if he wants to, BUT...

In other words the same as Heroes 2 when you have one guest hero and another placed behind.

> 2. Your main hero still replenish the full mana if there is a Mage Guild in the castle.

Hmm.. I'm not sure if this is a gameplay change or not. In normal Heroes 2 you would have to spend movement points to accomplish this. I imagine guardian heroes do indeed replish spell points with this feature?

**Comment by Branikolog** [comment]
@oleg-derevenetz 

> Castle guardians do not make captains useless. Each and every castle may have a captain, while number of guardian heroes is limited - they are accounted in the total number of heroes, which is 8.

In our future expansion we planned to improve captain mechanics, making it possible to increase some stats, to make castle defending more fun in late game. So allowing to place a hero into each castle makes this improvement a bit questionable. Placing even 1lvl hero looks more beneficial, than having a captain. Allowing garrison heroes makes captains look rudimental feature...

Also, I want to note, that UI of the game is not designed for having both captain and garrison hero together in the same castle. It looks not well, when hero portrait covers captain's icon. This makes player think, there's no captain in castle. You also have to enter castle menu, to check captain's stats.
I personally prefer playing without this option enabled, and will be a little upset with it made as default. 

> In fact, this changes the gameplay and affects the game balance. You see, non-upgraded units are cheaper, so now you have a choice - you can buy a few upgraded units or several non-upgraded. Where you could only buy a Titan in the original game, now you can buy a Giant even if you don't have money or resources for a Titan.

I believe such cases happen 1/100 sieges. Having a titan in army is much more beneficial, than cheaper Giant. I would exchange some resources trying to afford titans in such cases. I believe players won't use this feature really often. 
If you'd give me a choice to remove both options or make them default, I'd rather prefer first. :)

Could it happen now, that we've come to the situation we need to implement some sort of adjustable options for our project (Something close to experimental we have currently)?
If so, could we focus more on polishing the engine and leave such options for future extended new options menu? I mean not to remove the code, but temporary make this option unavailable.

Anyway, this is my personal point. If all you, guys, decide, this option should be a default one, I won't complain... Too much. :)

**Comment by zenseii** [comment]
@Branikolog, as @oleg-derevenetz pointed out, captains will play the same role as before. Even with normal heroes 2 you can buy lvl1 heroes and they will replace the Captain's function in a siege, and with our without this change you would have to sacrifice 4 possible heroes to stay in your 4 castles if you want this.

Your concerns about the visual changes are the ones I have raised too and are the ones that are of the biggest concern.

**Comment by oleg-derevenetz** [comment]
> In our future expansion we planned to improve captain mechanics, making it possible to increase some stats, to make castle defending more fun in late game. So allowing to place a hero into each castle makes this improvement a bit questionable.

That's what I'm talking about: you cannot put a guardian hero in each castle, because if you have, say, two "champion" heroes and two courier heroes for each of these champions, there is just no heroes left for the guardian roles :) So captains will always have a job to do, don't worry about that.

> I mean not to remove the code, but temporary make this option unavailable.

If the code becomes "not available" (or even "optional"), it tends to become "rusty" over time. Just look at "soft wait" and "castle guardian" options - AI still have no idea how to use them, because "pfft, they are optional, let's pretend they didn't exist".

**Comment by Branikolog** [comment]
> That's what I'm talking about: you cannot put a guardian hero in each castle, because if you have, say, two "champion" heroes and two courier heroes for each of these champions, there is just no heroes left for the guardian roles :) So captains will always have a job to do, don't worry about that.

So, player will be limited to 8 heroes, even if all of them would be inside castle garrisons, right? I thought, it was planned to make H3-like, where you could place a hero into **every** castle.
But still, we need a pleasant visual implementation for transferring hero to garrison, hero meeting initiation, castle captain visual representation and nice, well-looking garrison icon for heroes list.

> Just look at "soft wait"

Oh, I'd definitely say "No-no-no" for this option. :) I wish it never exist in Heroes2 game. :)

**Comment by zenseii** [comment]
> In normal HoMM2 you will need two castles - one for each individual hero :)

Yes, so this is a big change in gameplay because you get full magic point refill on both heroes the following day after having been sieged during the enemy turn. Objectively, this makes sieging during several days harder because every day the guardian hero gets mana refilled.

I'm trying to think of a way we can have the quick way of recruiting creatures to both heroes, but avoiding the magic point refill.

Actually, there is one way that might be the best compromise between Heroes 2 purists and saving time, even improving upon all later heroes games functioning here. I'll need some time to write it down.

**Comment by oleg-derevenetz** [comment]
> So, player will be limited to 8 heroes, even if all of them would be inside castle garrisons, right? I thought, it was planned to make H3-like, where you could place a hero into every castle.

No, this is not a copy-paste from HoMM3.

> But still, we need a pleasant visual implementation for transferring hero to garrison, hero meeting initiation, castle captain visual representation and nice, well-looking garrison icon for heroes list.

I'm not an artist, so maybe I fully convinced with the current UI. But specific suggestions are welcome.

**Comment by oleg-derevenetz** [comment]
> Objectively, this makes sieging during several days harder because every day the guardian hero gets mana refilled.

If there was only a guest hero in the castle, he would to get mana refill every day as well.

**Comment by zenseii** [comment]
> > Objectively, this makes sieging during several days harder because every day the guardian hero gets mana refilled.
> 
> If there was only a guest hero in the castle, he would to get mana refill every day as well.

Yes I wrote wrong the first time, I meant to refer to the second external defending hero. This hero would not get the magic points refilled. Regarding the guardian hero there is no problem, the problem is the second hero, who with the castle guardian feature would get its magic points refilled when in the original Heroes 2 this would not happen. This is what I'm concerned about.

**Comment by zenseii** [comment]
> I'm not an artist, so maybe because of this I'm fully convinced with the current UI. But specific suggestions are welcome.

I have some ideas already for how to make this nice. I'll post some concepts.

**Comment by ihhub** [comment]
I am grabbing popcorn... (just kidding)😄

I have few ideas how to make visualisation of such feature more user-friendly on the Adventure Map itself. I will post my ideas in the upcoming days🙂

**Comment by zenseii** [comment]
Hi everyone.

I did some quick test and realized that there are more gameplay altering issues with this than only the mage guild replenishing both heroes' spell points. All buildings that give the defending army a boost, like Arena (+ 2 morale) or Rainbow (+ luck), gives both guardian and guest hero this boost. This is too much of a benefit and really changes things from the original with regards to sieging.

We need to make sure only a guardian hero or a guest hero in case there is no guardian gets these boosts, even the one for replenishing spell points because if not we are adding more spell points to a game in which we already have ridiculous spells like Dimension Door and Town Portal.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii while I agree that battle-time castle bonuses for guest hero are arguable, because guest hero battle is performed outside of castle walls, mana replenishment is different, because in fact both heroes are in castle at the end of the day, so both should replenish their mana points.

**Comment by zenseii** [comment]
> mana replenishment is different

I think to solve the mana replenishment we can simply state in the mage guild right click info "There is only enough mana to replenish one hero per night" - this would be very familiar with how you have other mana replenishers that can only be visited by one hero per week etc.

> because guest hero battle is performed outside of castle walls

Unless we want to imagine the tavern owner running outside the castle to provide the troops with beer :grin:

**Comment by Branikolog** [comment]
> Hi @zenseii while I agree that battle-time castle bonuses for guest hero are arguable, because guest hero battle is performed outside of castle walls, mana replenishment is different, because in fact both heroes are in castle at the end of the day, so both should replenish their mana points.

I think, Mage guilds are quite mysterious places. It's not a place for free public tours. :) That's why there's a place only for a single hero inside. :D 
I agree with @zenseii , mana points in H2 is a valuable resource. Allowing two heroes to replenish mana at the same time is quite game breaking.

Looking at our discussion I'm coming to a conclusion, that implementing this mechanics, as a default one, requires a lot of work regarding game design, UI, logic etc. I'd better prefer leaving this for expansion routine. :)

**Comment by oleg-derevenetz** [comment]
> Looking at our discussion I'm coming to a conclusion, that implementing this mechanics, as a default one, requires a lot of work regarding game design, UI, logic etc. I'd better prefer leaving this for expansion routine. :)

I should say that amount of work that was already invested into this mechanics is much more than the remaining amount of work. Most of the poorly made experimental mechanics have already been thrown out of the game, only the most working ones remain.

**Comment by oleg-derevenetz** [comment]
> Strange refocus while switching between castle and garrison hero on the adventure map is among them...

This is not a bug, this is by design. Since one tile can hold just one hero, castle guardian is shifted one tile higher than the castle entrance.

**Comment by zenseii** [comment]
I'd like to add that I think this is a welcome improvement as would make repetitious tasks in the game less tedious.

This feature could become very slick if combined with the future drag-and-drop interaction which would quite possibly remove the need to make a bunch of new buttons and assets.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

Why not push the idea further?
When the captain's quarters are built, the captain can also have his own army, thus creating the possibility of a third combat.
And when the captain has been defeated, the castle becomes neutral and all available creatures in the creature dwellings gather to defend their castle.

"Castle: allow guardians" is acceptable as an option but absolutely not as the default operation of the game.
It changes too much the way the original game works, to make it look like Heroes 3 (and that is a bit of a flawed feature for me in Heroes 3), for it to become a default operation of the game.

I have planned some optional improvements for the captain in my mod more in line with the spirit of Heroes 2.
Here are some of them: https://github.com/ihhub/fheroes2/discussions/2975, https://github.com/ihhub/fheroes2/discussions/2980, https://github.com/ihhub/fheroes2/discussions/2972, https://github.com/ihhub/fheroes2/discussions/2973.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu well, some other people consider this as a [desirable improvement](https://github.com/ihhub/fheroes2/issues/5606#issuecomment-1312524857) :)

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu well, some other people consider this as a [desirable improvement](https://github.com/ihhub/fheroes2/issues/5606#issuecomment-1312524857) :)

I could agree as long as it remains an option. :)

But I find the optional improvements for the captain in my mod more interesting, and in a way it is similar to the idea of both heroes joining the battle at the same time. :)

Besides it doesn't block a hero in the castle who could be more useful on the adventure map.

**Comment by ihhub** [comment]
Looks like I opened a Pandora Box by creating a topic about experimental options rework.

To avoid non-stop debates for now let's please pause the work and discussions on these options. I will try to come up with a solution which would satisfy most of people.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I will try to come up with a solution which would satisfy most of people.

The problem here is that the whole "experimental options" thing was a mistake from the previous team. New features can be "experimental" for a while (usually not for long), but then they should be at last either removed or integrated into the game core, otherwise they will always be "half-baked". If there are serious objections to the integration of the experimental option, then let's remove it and spend the time remaining before the release to test everything thoroughly once again.

**Comment by ihhub** [comment]
I think to make everyone happy lets do this way:
- options which everyone agrees should be a part of the game must have their own UI elements in 1.0 release
- options which everyone agrees to remove we remove
- the rest of options rename the same within the code but we cut the way to enable them as of now (just don't load fheroes2.bin file)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I think to make everyone happy lets do this way:
> - options which everyone agrees should be a part of the game must have their own UI elements in 1.0 release
> - options which everyone agrees to remove we remove
> - the rest of options remain the same within the code but we cut the way to enable them as of now (just don't load fheroes2.bin file)

I propose to have just two options: either an option should be the part of the game or not, and in the latter case it should be removed completely. Having a lot of the dead unused code is not good. We have the commit history after all, so we will be able to restore/rewrite the removed code later if we need to. So I propose the following changes in your proposal:

- options which everyone agrees should be a part of the game must have their own UI elements in 1.0 release;
- the rest of the options will be removed, one separate PR per option.

**Comment by ihhub** [comment]
I am closing this pull request as we decided to go with another approach.

**Pull request closed without merging**
