### PR TITLE
Update the resource panel immediately after a purchase.

### LINKED ISSUE #4732: Castle screen, update the remaining resources at the bottom right of the screen before launching the building construction animation
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the remaining resources at the bottom right of the screen are updated before launching the building construction animation.

In original game:

https://user-images.githubusercontent.com/43583994/144237754-d10f89f2-3cef-40ff-acb9-74c8fd48ef49.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/144237816-4eeb9c7a-0408-42ff-b83e-0a1506e21a7d.mp4

### Save file

Not needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by dood-apo**
Fix #4732

### CODE REVIEW

**Comment by dood-apo** [comment]
Rebased the PR so the Nintendo Switch build passes.

**Review by ihhub — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @dood-apo !
I've found an issue with the resource panel:

https://github.com/ihhub/fheroes2/assets/55348946/9c6709f9-1d75-4592-bd70-6544f5d1114c

Could you, please, look of you can fix it?

**Comment by dood-apo** [comment]
Hi @Branikolog , the issue with buying boats should be fixed now.

**Comment by Branikolog** [comment]
Hi, @dood-apo 
Sorry for the late response, as I was really busy with our release activity these days.

I've checked your PR once again and here's one more issue I've experienced in this build:

https://github.com/ihhub/fheroes2/assets/55348946/219c3962-487c-4ef5-960f-711eff65879f

**Comment by dood-apo** [comment]
Hi @Branikolog ,

> here's one more issue I've experienced

Fixed the issue with upgrading to a castle.

**Review by Branikolog — APPROVED** [review]
No more issues found. 
👍

**Comment by ihhub** [comment]
@dood-apo , thank you so much for the fix!

**Pull request merged**
