### PR TITLE
Multiple CMake-related improvements

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
* Replace `FindSDL2_image.cmake` and `FindSDL2_mixer.cmake` modules by their modern versions to temporary use them until the OS distributions start shipping a newer versions of `SDL_mixer` and `SDL_image` that provide their own CMake config files;
* Remove the `USE_SYSTEM_LIBSMACKER` option. It is hardly usable because bundled `libsmacker` is patched by us;
* Disable `ENABLE_IMAGE` option by default. It is only usable for tools (to support PNG images) and not for the game itself, but it adds extra dependencies on `SDL_image` and `libpng`;
* Various minor cleanups.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I removed SDL1 checks for pull request merge requirements.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I removed SDL1 checks for pull request merge requirements.

Thank you!

**Comment by ihhub** [comment]
I also marked all SDL1 pre-releases as **deprecated** since we aren't going to push any commit for them anymore.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , is it possible for you to verify #3216 if your changes fix it?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> is it possible for you to verify https://github.com/ihhub/fheroes2/issues/3216 if your changes fix it?

I cannot reproduce issue described in #3216. I have build fheroes2 in debug mode:

```bash
cmake.exe --build build --config Debug
```

this is the list of files in the `build\Debug` directory:

```
25.08.2023  11:44           353 792 82m2wav.exe
25.08.2023  11:44         2 748 416 82m2wav.pdb
25.08.2023  11:45           312 832 bin2txt.exe
25.08.2023  11:45         2 633 728 bin2txt.pdb
25.08.2023  11:45           493 056 extractor.exe
25.08.2023  11:45         3 461 120 extractor.pdb
25.08.2023  11:48        11 149 824 fheroes2.exe
25.08.2023  11:48        34 983 936 fheroes2.pdb
25.08.2023  11:48           732 160 h2dmgr.exe
25.08.2023  11:48         4 517 888 h2dmgr.pdb
25.08.2023  11:48           563 712 icn2img.exe
25.08.2023  11:48         3 633 152 icn2img.pdb
25.08.2023  11:23           423 424 libpng16d.dll
25.08.2023  11:23            88 064 ogg.dll
25.08.2023  11:48           520 704 pal2img.exe
25.08.2023  11:48         3 354 624 pal2img.pdb
25.08.2023  11:24         4 384 768 SDL2d.dll
25.08.2023  11:24           260 608 SDL2_imaged.dll
25.08.2023  11:25           203 776 SDL2_mixerd.dll
25.08.2023  11:48           537 600 til2img.exe
25.08.2023  11:48         3 379 200 til2img.pdb
25.08.2023  11:23           988 672 vorbis.dll
25.08.2023  11:23            96 256 vorbisfile.dll
25.08.2023  11:48           495 104 xmi2midi.exe
25.08.2023  11:48         3 313 664 xmi2midi.pdb
25.08.2023  11:23           208 896 zlibd1.dll
```

i.e. only debug versions of direct dependencies are present, and yet `fheroes2.exe` runs just fine (as well as tools).

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for these changes!

**Pull request merged**
