### PR TITLE
Integrate "battle: show damage info" into the game

### PR DESCRIPTION
**Pull request by ihhub**
Battle options dialog was expanded by 3 more options:
- audio settings
- hotkey dialog
- damage info setting

Adventure Map dialog wasn't saving settings if you change one of options and open audio settings dialog and then quit.

On top of this first opening of battle options dialog was calling screen rendering twice.

relates to #6161

image

### CODE REVIEW

**Comment by ihhub** [comment]
@oleg-derevenetz , have you noticed some unstable behavior of CI pipeline in the last few days?

**Comment by oleg-derevenetz** [comment]
@ihhub

> have you noticed some unstable behavior of CI pipeline in the last few days?

I hope Microsoft is not running out of money :)

**Review by oleg-derevenetz — APPROVED** [review]

**Review by zenseii — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @ihhub 
I've noticed, while adjusting sound setting I start hearing adventure map sounds, like water, mine etc. Also, It seems to me, that changing music volume from 5 to higher doesn't affect music loudness. (0-5 works well)

**Comment by ihhub** [comment]
Hi @Branikolog , I fixed the issue. Please check again.

**Review by Branikolog — APPROVED** [review]

**Pull request merged**
