### PR TITLE
Delete script/packaging/debian directory

### PR DESCRIPTION
**Pull request by undef21**
fheroes2 is on its way into Debian repository so I suggest to remove this scripts

### CODE REVIEW

**Comment by undef21** [comment]
Hi, @oleg-derevenetz .
Yes. fheroes2 package is in NEW queue now.

**Comment by ihhub** [comment]
I suggest to wait till the package **is** in the repository, not before.

**Comment by undef21** [comment]
Mark as draft until the package goes to the repository.

**Comment by ihhub** [comment]
Hi @undef21 , what's the state of the Debian repo? Is it still pending the package approval?

**Comment by undef21** [comment]
Hi @ihhub. Yes, the package is still awaiting in NEW queue.

**Comment by undef21** [comment]
Hello @ihhub , @oleg-derevenetz.
fheroes2 package is in Debian [unstable](https://packages.debian.org/sid/fheroes2) repository now.

**Comment by ihhub** [comment]
Hi @undef21 , I am curious when they are going to update it? It is a 2 months old version.

**Comment by ihhub** [comment]
@undef21 , I also noticed that the description is incorrect:
```
implementation of classic game Heroes of Might and Magic II
```
It must be:
```
Recreation of the Heroes of Might and Magic II game engine.
```

The most important word is engine as we aren't redeveloping all resources.

**Comment by undef21** [comment]
> Hi @undef21 , I am curious when they are going to update it? It is a 2 months old version.

The first uploading of the new packages is really long, the future versions will be uploaded faster, because the package already in the repository. The next uploaded version will be 1.0.12.

**Comment by undef21** [comment]
> It must be:
> 
> ```
> Recreation of the Heroes of Might and Magic II game engine.
> ```

Ok, in the next version

**Review by ihhub — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
@undef21 , thank you very much for these changes!

**Pull request merged**
