### PR TITLE
Fix Editor instruments buttons rendering

### LINKED ISSUE #8734: Editor: Randomly, switching between object categories does not work correctly
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

Sometimes while browsing different categories of map objects:
A) previously selected category button remains pressed, leading to multiple buttons in pressed state, while the menu box content (with subcategories) is correctly updated

For example:
- select terrain -> terrain button is pressed, menu contains terraint types
- then select landscape objects -> now both terrain and landscape obj buttons are pressed, menu content is updated to landscape (mountains, trees etc.)

B) also randomly, but LESS OFTEN , it could happen that menu content is not refreshed and old category options are still in the menu box

For example:
- select terrain -> terrain button is pressed, menu contains terraint types
- then select landscape objects -> now both terrain and landscape obj buttons are pressed, menu content is NOT updated and TERRAIN types are still there

Issue happens randomly and there are moments it works fine but then it can happen multiple times in a row, it looks to be related to opening popup windows like unit lists etc, but I was not able to find any dependencies.

### Save file

N/a

### Additional info

1.1.0 on Android 5.1.1

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #8734

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hi, @admmlk, could you please check the android build from this PR if it fixes the object category switch issue, if you have time?
[fheroes2_android.zip](https://github.com/ihhub/fheroes2/actions/runs/9236548881/artifacts/1537590790)

**Comment by admmlk** [comment]
Hey, it looks fine on this build - I was not able to reproduce it any longer while playing with the editor for 20-30 minutes so far.

**Comment by Districh-ru** [comment]
> Hey, it looks fine on this build - I was not able to reproduce it any longer while playing with the editor for 20-30 minutes so far.

@admmlk , many thanks for testing!

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this fix!

**Pull request merged**
