### PR TITLE
Put the Graveyard object to the correct category, "hide" the ugly versions of Graveyard sprites

### LINKED ISSUE #8784: [Scenario Editor] Graveyard is in the wrong category
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the graveyard is in the wrong category.
The graveyard is in the "Dwelling" list when it should be in the "Adventure Object" list.

In fheroes2:

Graveyard wrong list 001

Graveyard wrong list 002

### Save file

Not needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #8784

Also related to #8785.

However, I am not sure about the logic of ordering in the objects list (did I put the Graveyard on the list to the correct place?).

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , according to
https://github.com/ihhub/fheroes2/blob/829cb34ef4cea3f7f7ec5ea0920f47a07beb798f/src/fheroes2/maps/map_object_info.h#L120

we simply cannot move objects from one place to another because it breaks map format.

What we need to do is:
- bump the current map version:

https://github.com/ihhub/fheroes2/blob/829cb34ef4cea3f7f7ec5ea0920f47a07beb798f/src/fheroes2/maps/map_format_info.cpp#L40

- add migration code from version 2 to version 3 (`bool loadFromStream( StreamBase & msg, MapFormat & map )` method, after this line:
https://github.com/ihhub/fheroes2/blob/829cb34ef4cea3f7f7ec5ea0920f47a07beb798f/src/fheroes2/maps/map_format_info.cpp#L257

we can call a function simply `migrateV2toV3()` or something like this, and there we need to change **objects** for each tile and more specifically their group and their index.

- we **must** preserve all objects as they might appear in the existing maps created with version 2. I suggest to put the objects at the end of the list. If the alternative graveyards are not pleasant for looks we can move them after the normal ones.

Please let me know if you have any questions about this.

**Comment by oleg-derevenetz** [comment]
> I suggest to put the objects at the end of the list.

I would not like to put Graveyards after Barriers and Traveller's Tents, so I left them at the beginning. However, as for "ugly" versions of Graveyards, I put them at the end to hide them in a way.

**Review by ihhub — APPROVED** [review]

**Review by Districh-ru — APPROVED** [review]
The Editor gives the ability to choose any Graveyard appearance and do not force the map maker to choose one variant instead of the other. The map maker may select any Graveyard that better fits his map. :)

**Comment by oleg-derevenetz** [comment]
> The map maker may select any Graveyard that better fits his map. :)

I have a suspicion that these crude Graveyards are just mock-ups accidentally left from some alpha versions of the game. They are frankly poorly drawn (totally not in the style of the game as a whole), not used in the original editors and do not appear in any known map. I don't really think there's a need to encourage map makers to use them. Unfortunately, they are apparently no longer so easy to delete by converting them into "proper" Graveyards, because "proper" Graveyards are larger objects than those mock-ups.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this change!

**Pull request merged**
