### PR TITLE
Add Hotkeys categories for the future UI improvements

### PR DESCRIPTION
**Pull request by ihhub**
Based on the feedback from players.

image

### CODE REVIEW

**Review by Districh-ru — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @Branikolog , the idea is to add category names within the list to make it more understandable but for now we at least show like this as a temporary solution.

**Review by Branikolog — APPROVED** [review]
@ihhub 
Okay! 👍

**Comment by ihhub** [comment]
Hi @zenseii , could you please just take a look at category names if you have time?

**Comment by ihhub** [comment]
Thanks @zenseii !

**Pull request merged**
