### PR TITLE
Properly track the Mirror Image spell duration, fix necromancy and calculation of casualties with mirrors

### LINKED ISSUE #6796: Combat, Mirror Image spell duration is incorrect
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the Mirror Image spell is effective for a number of turns corresponding to the Spell Power of the hero.
In fheroes2, the spell lasts for the duration of the combat.
This should be corrected.

In original game:

https://user-images.githubusercontent.com/43583994/224072315-46c16a76-c03e-422c-82db-9d2028721fc7.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/224072088-265b2f13-696c-4cb1-bc3e-2b499f9f2428.mp4

### Save file

Here are the save files:
[Mirror Image spell duration.zip](https://github.com/ihhub/fheroes2/files/10933280/Mirror.Image.spell.duration.zip)

### Additional info

_No response_

### LINKED ISSUE #6801: Combat, Mirror Image spell, mirror image troops decimated should always be displayed in the casualty report
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, decimated mirror troops created by the mirror image spell are displayed in the casualty report, regardless of whether the mirror troops were decimated by attacking them directly or by decimating the original troop targeted by the mirror image spell.
In fheroes2, mirror image troops are only displayed when they have been decimated by attacking them directly.
The decimated mirror troops should always be displayed in the casualty report as in the original game.

After the mirror image spell was cast on all the defender's troops, the initial troops of the hero's army were decimated and the mirror troops disappeared without being attacked:

In original game:
H2 troop first 01
H2 troop first 02
Note: Not all troops are displayed in the original game, this is a GUI "bug".

In fheroes2:
Fheroes2 troop first 01
Fheroes2 troop first 02

After the mirror image spell has been cast on all the defender's troops, the mirror image troops were decimated first and then the initial troops of the hero's army:

In original game:
H2 mirror first 01
Note: Not all troops are displayed in the original game, this is a GUI "bug".

In fheroes2:
Fheroes2 mirror first 01

### Save file

Here are the save files:
[Test mirror image 01.zip](https://github.com/ihhub/fheroes2/files/10935304/Test.mirror.image.01.zip)

### Additional info

_No response_

### LINKED ISSUE #6803: Combat, Necromancy Report window, number of skeletons raised after using the mirror image spell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the decimated mirror troops are taken into account for the calculation of the number of skeletons raised by the Necromancy skill, regardless of whether the mirror troops were decimated by attacking them directly or by decimating the original troop targeted by the mirror image spell.
In fheroes2, mirror image troops are only taken into account when they have been decimated by attacking them directly.
The decimated mirror troops should always be taken into account for the number of skeletons raised as in the original game.

After the mirror image spell was cast on all the defender's troops, the initial troops of the hero's army were decimated and the mirror troops disappeared without being attacked:

In original game:
H2 troop first 01
H2 troop first 02
Note: Not all troops are displayed in the original game, this is a GUI "bug".
H2 troop first 03

In fheroes2:
Fheroes2 troop first 01
Fheroes2 troop first 02
Fheroes2 troop first 03

After the mirror image spell has been cast on all the defender's troops, the mirror image troops were decimated first and then the initial troops of the hero's army:

In original game:
H2 mirror first 01
Note: Not all troops are displayed in the original game, this is a GUI "bug".
H2 mirror first 02

In fheroes2:
Fheroes2 mirror first 01
Fheroes2 mirror first 02

### Save file

Here are the save files:
[Test mirror image 01.zip](https://github.com/ihhub/fheroes2/files/10935304/Test.mirror.image.01.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/6801.

### LINKED ISSUE #6804: Combat, Mirror Image spell, A glorious victory window, taking into account the experience points related to the decimated mirror troops
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In the original game, the hit points of decimated mirror troops are not taken into account, regardless of whether the mirror troops were decimated by attacking them directly or by decimating the original troop targeted by the mirror image spell.
In fheroes2, the hit points of decimated mirror troops are only taken into account when they have been decimated by attacking them directly.

In this case, I suggest that the hit points of decimated mirror troops should always be taken into account, a kind of trade-off to the use of the spell for the one using it. :)
As opposed to what happens in the original game.
In original game, decimated mirror troops are taken into account for the skill Necromancy to raise skeletons, why not also for experience points.

After the mirror image spell was cast on all the defender's troops, the initial troops of the hero's army were decimated and the mirror troops disappeared without being attacked:

In original game:
H2 troop first 01
H2 troop first 02
Note: Not all troops are displayed in the original game, this is a GUI "bug".

In fheroes2:
Fheroes2 troop first 01
Fheroes2 troop first 02

After the mirror image spell has been cast on all the defender's troops, the mirror image troops were decimated first and then the initial troops of the hero's army:

In original game:
H2 mirror first 01
Note: Not all troops are displayed in the original game, this is a GUI "bug".

In fheroes2:
Fheroes2 mirror first 01

### Describe the possible solution

In this case, I suggest that the hit points of decimated mirror troops should always be taken into account, a kind of trade-off to the use of the spell for the one using it. :)
As opposed to what happens in the original game.
In original game, decimated mirror troops are taken into account for the skill Necromancy to raise skeletons, why not also for experience points.

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/6801.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #6796
fix #6801
fix #6803

close #6804

~~Should be merged after other my battle-related PRs (#6787, #6789, #6790) because it seems that there may be merge conflicts.~~

### CODE REVIEW

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

I did a quick test, seems to work.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , please fix merging conflicts and mark this pull request ready for review if it is :)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> please fix merging conflicts and mark this pull request ready for review if it is :)

This PR is ready for review, but I recommend to postpone it after 1.0.2 release to test it properly.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu this PR should fix also issues with necromancy and casualties calculation reported by you, could you please take a look and check this when you have time?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
I've experienced and assertion while attacking mirrored creature:
assert

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I've experienced and assertion while attacking mirrored creature:

Should be fixed now.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu this PR should fix also issues with necromancy and casualties calculation reported by you, could you please take a look and check this when you have time?

Everything seems to be working properly, good work. :)

But I noticed that sprites of decimated mirror creatures are not always placed in the same order according to the order in which they were decimated.

In fheroes2:

Casualty sprites order 001
Casualty sprites order 003
Casualty sprites order 005
Casualty sprites order 006
Casualty sprites order 007

Casualty sprites order 008
Casualty sprites order 009

Casualty sprites order 011

Maybe it would be better if this is the case to have an easier reading of the casualty report window.
The order could be always the same according to the order of the initial troops of the hero's army.

For example:
Initial Army:
5 Titans, 25 Rangers, 100 peasants, 10 peasants

Casualty report window:
5 Titans, 25 Rangers, 100 peasants, 10 peasants, first 5 mirror Titans, first 25 mirror Rangers, first 100 mirror peasants, first 10 mirror peasants, second 5 mirror Titans, second 25 mirror Rangers, second 100 mirror peasants, second 10 mirror peasants, etc.

What do you think?
If necessary I can open another issue on this subject.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> But I noticed that sprites of decimated mirror creatures are not always placed in the same order according to the order in which they were decimated.

They never did :)

> The order could be always the same according to the order of the initial troops of the hero's army.

Well, that's exactly how it currently works - the order of appearance matches the initial order of troops. If there are additional troops appear during battle (due to Summon Elemental or Mirror Image spells), they are added to the end of the list in the order of their appearance (NOT in the order of their elimination).

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > But I noticed that sprites of decimated mirror creatures are not always placed in the same order according to the order in which they were decimated.
> 
> They never did :)
> 
> > The order could be always the same according to the order of the initial troops of the hero's army.
> 
> Well, that's exactly how it currently works - the order of appearance matches the initial order of troops. If there are additional troops appear during battle (due to Summon Elemental or Mirror Image spells), they are added to the end of the list in the order of their appearance (NOT in the order of their elimination).

Okay, I see.
So let's keep this operation of sprites displayed in the casualty window related to the order of appearance of troops on the battlefield for now. :)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , enormous thanks for these fixes!

**Pull request merged**
