### PR TITLE
Home screen, Adjustement of window text on first game launch (#4789)

### LINKED ISSUE #4789: Home screen, windows sequence of the first launch of the game and adjustment of windows titles and texts
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The sequence of windows for the first launch of the game it is no longer appropriate.
Some titles and texts should also be adjusted.

### Describe the possible solution

The sequence of windows for the first launch of the game should be changed to show the "Greetings!" window first.

In fheroes2, current windows sequence:
Game first launch sequence 001
Game first launch sequence 002
Game first launch sequence 003
Game first launch sequence 004

The end of the text in the "Greetings!" window should also be adapted:

"...please **select** language and game resolution."

Instead of:

"...please choose game resolution."

The text in the "Please Remember" window should also be adapted:

"You can always change language, resolution and settings of the game by clicking on the door on the left side of main menu, or with the "CONFIG" button from the "NEW GAME" menu."

Instead of:

"You can always change game resolution by clicking on the door on the left side of main menu."

I would also change the title of the language selection window to:
(With the first letter in uppercase for the words "Game" and "Language" and the word "Select" to stay consistent with the title of the resolution selection window "Select Game Resolution" and the title of the "Please Remember" window.)

"Select Game Language:"

Instead of:

"Choose game language:"

For the resolution selection window, the colon ":" is missing at the end of the title (to be consistent with the colon ":" at the end of the title of the language selection window:

"Select Game Resolution:"

Instead of:

"Select Game Resolution"

The modified sequence of windows should be:
Game first launch sequence 002
Game first launch sequence 001
Game first launch sequence 003
Game first launch sequence 004

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by jerbear1235**
Before the changes:
image
image

After the changes:
image
image

This PR modifies existing text and requires translations.

close #4789

### CODE REVIEW

**Comment by ihhub** [comment]
I am moving this pull request to 1.0.10 release as 1.0.9 is going to be very soon and we will have to update translations for this change.

**Comment by ihhub** [comment]
Hi @jerbear1235 , please fix code style issues.

**Review by Branikolog — APPROVED** [review]
Hi! There're too many yellow accents in the second window in my opinion. 
But if everyone is OK with that, then let it be. :)

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog,

> Hi! There're too many yellow accents in the second window in my opinion. But if everyone is OK with that, then let it be. :)

Personally, I think it's okay.
It's not a window that pops up all the time. :)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@jerbear1235 , thank you so much for your contribution to the project!

**Pull request merged**
