### PR TITLE
Fix View World default adventure map position

### LINKED ISSUE #6618: View World screen, crosshair position and the portion of the adventure map displayed is not correct
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, at the highest zoom level, the crosshair position and the portion of the adventure map displayed is not correct compared to the original game.

Select a castle from the list of castles.
Display the View World screen.

In original game;

Icons View World 001

In fheroes2:

Icons View World 002

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

Icons View World 013 Icons View World 014

Also, the crosshair is not displayed in the other zoom levels in the original game, while in fheroes2, the crosshair is displayed by framing the whole minimap.

In original game;

Icons View World 003

Icons View World 005

In fheroes2:

Icons View World 004

Icons View World 006

### Save file

Not needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #6618

- [x] Center the adventure map on current tile center, like on OG.
- [x] Do not draw cursor if it is bigger than the mini-map.
- [x] Position the mini-map cursor like in the OG.
- [x] Position the adventure map for View World like in OG.

It seems that the lower right corner of the mini-map cursor in fheroes2 is drawn more properly than in the original game. This can be discussed.

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hello @LeHerosInconnu,  could you please check this PR when you have time.

**Review by ihhub — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
Not sure, it's related to current PR, but I couldn't reproduce it on master branch:

https://user-images.githubusercontent.com/55348946/219156571-ae414245-170a-4cc7-af67-8ceda3f43845.mp4

While dragging crosshair to bottom or right edge, it squeezes for ~1 px. Other two sides work as expected.

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru ! Not sure, it's related to current PR, but I couldn't reproduce it on master branch:
> While dragging crosshair to bottom or right edge, it squeezes for ~1 px. Other two sides work as expected. This happens only for the smallest visible area. Bigger crosshairs dont have such issue.

Hi, @Branikolog!
As you may notice in master build you can move cursor on mini-map near the borders anв the adventure map moves only by half a tile and the cursor remains unmoved. In this PR I've changed the cursor position calculation so now it moves near bottom and right borders.

https://user-images.githubusercontent.com/113276641/219427775-0e345050-d83f-4e96-833e-0b39fc40cdd3.mp4


The issue is in that half a tile movement (in fact the positioning by mini-map should be shifted by half a tile).
I'll try to fix this.

**Review by Branikolog — APPROVED** [review]
Well done!

**Comment by ihhub** [comment]
Hi @Districh-ru , could you please solve merge conflicts here?

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , could you please solve merge conflicts here?

Hi, @ihhub. Done, but there were errors in MSVC workflows:
`Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (503) Server Unavailable."`

**Comment by ihhub** [comment]
Hi @Districh-ru , CI/CD pipeline failed not due to your changes. I've restarted the failed jobs.

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for the fix!

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hello @LeHerosInconnu, could you please check this PR when you have time.

I checked this, it seems to work fine.

**Pull request merged**
