### PR TITLE
Differentiate Random Castle and Town names

### PR DESCRIPTION
**Pull request by ihhub**
relates to #6845

image

image

### CODE REVIEW

**Comment by Districh-ru** [comment]
We could also differentiate "Town Army" and "Castle Army" than. :)

**Review by Districh-ru — APPROVED** [review]
As I mentioned earlier we can also apply such change to change the text in the lower-right part of this dialog "Castle Army" (line 391) to show "Town Army" when we are editing Town properties.
It can be done in this or in a new PR.

**Comment by ihhub** [comment]
Let's move it for 1.1.1 release. It is a very minor change and we need to go with translations.

**Comment by ihhub** [comment]
Hi @Districh-ru and @zenseii , I am just thinking whether it's worth doing such granular differentiation. What do you think?

**Pull request merged**
