### PR TITLE
Extra virtual keyboard language support for Russian

### PR DESCRIPTION
**Pull request by ihhub**
This was the easiest to do.

image

I might not have the latest translation files for Russian so buttons might be translated for users.

relates to #6924

### CODE REVIEW

**Review by Districh-ru — COMMENTED** [review]
Hi, @ihhub.
Well done!
I have two suggestions which can be discussed and one issue. Could you take a look when you have time.

1. Possibly we don't need a Language Change button in a numeric keyboard as id does no change to the input characters.


https://github.com/ihhub/fheroes2/assets/113276641/a943983e-1f58-4409-9c76-469d920ce8b1



2. IMHO the SPACE button should have a translated text according to the game selected language, not the current keyboard layout.

3. We miss the "_" sign at the end of the input phrase. This is not the issue of Change Language implementation and can be addressed in a new PR.
изображение
изображение

**Comment by Branikolog** [comment]
Hi, @ihhub !
I think it would be better to remember selected language, how do you think? In a case we want to enter 6 player's names we need to press each time [...] button to switch the language.
Also, I've noticed than when the text exceeds the available amount of symbols for some places it is not showed, until we delete enough symbols...

https://github.com/ihhub/fheroes2/assets/55348946/2b165fe6-4235-47f2-9874-3a389f97c1f6

And I agree with all points of @Districh-ru .

**Comment by ihhub** [comment]
Hi @Branikolog , @Districh-ru and @oleg-derevenetz , I addressed all given comments. Please take a look.

**Review by Districh-ru — APPROVED** [review]
Works great!

Let's postpone polishing the virtual keyboard for the next release:
- fix the miss of the cursor "_" sign: изображение ;
- add the ability to place a cursor at any place of the string to add/remove characters there;
- implement a long press of a button (for example, to delete a phrase by holding the "<=]" button instead of pressing it multiple times);
- implement button double-click to separate Shift (only the next character entered will be uppercase) and Caps Lock;
- and make cursor blinking in all input fields (not only in Virtual Keyboard).

*edited*

**Comment by oleg-derevenetz** [comment]
> fix the miss of the cursor "_" sign

What is the purpose of this cursor sign would be? Currently you can only add characters to the end of the string or remove them from the end, you cannot add or remove characters in the middle of the string for example.

**Comment by Districh-ru** [comment]
> What would be the purpose of this cursor sign? Currently you can only add characters to the end of the string or remove them from the end, you cannot add or remove characters in the middle of the string for example.

If I press the Space button I don't see a feedback where the next character will be placed and I cannot check if I accidentally pressed Space many times before entering the next word.
изображение изображение

The cursor character do not always mean that it can be placed not only at the end of the string. :)
And it'll be good to implement the ability to place the cursor in any place to add/remove characters there.

**Review by Branikolog — APPROVED** [review]

**Pull request merged**
