### PR TITLE
split ghosts to 5 stacks in a abandoned mine

### LINKED ISSUE #5651: Combat, Abandoned Mine, wrong number of ghosts, ghost groups and their positioning
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the Ghosts guarding an Abandoned Mine should always be divided into five groups, as in the original game.
Otherwise it's too easy to slow down the single group with an easily accessible Slow spell, compared to the Mass Slow spell.

In original game:

Abandoned mine 001

Abandoned mine 002

Abandoned mine 003

Abandoned mine 004

Abandoned mine 005

Abandoned mine 006

In fheroes2:

Abandoned mine 007

https://user-images.githubusercontent.com/43583994/179030233-f22e7f9e-933f-4a6b-882c-091cd585deb3.mp4

**Edit 2022/07/16.**

In fheroes2:

**Abandoned Mine:**
- The number of ghosts can evolve over the combats, unlike the original game.
- There is a different number of ghosts than in the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

In original game:

**Abandoned Mine:**

The ghosts can be divided into three configurations:
- 5 groups
- 4 groups
- 3 groups

In original game:

Abandoned Mine H2 001

Abandoned Mine H2 009

Abandoned Mine H2 003

The number of ghosts does not increase or decrease if the combat is not won and another combat is started on the same abandoned mine.
If there are 30 ghosts at the beginning of the combat and the hero reduces this number to 15 ghosts before fleeing, there will still be 30 ghosts at the next combat.
If there are 30 ghosts at the beginning of the combat and the number of ghosts is increased to 45 ghosts before the hero flees, there will still be 30 ghosts in the next combat.

The number of ghost groups and their positioning in the battlefield hexes is related to the position of the abandoned mine on the adventure map.
Repeating the combat in the same abandoned mine always gives the same number of groups and the same positioning of the ghosts, even if the scenario is completely restarted.
The number of ghosts is different when the scenario is completely restarted, but is always the same during the same scenario session.
This is certainly determined at the start of the scenario for all abandoned mines.

> @undef21 @LeHerosInconnu
> 
> It is mentioned here that the number of ghosts can be in the range of 30-60:
> 
> https://handbookhmm.ru/2-objects

This is consistent with what I have observed.

In original game:

30 ghosts:
Abandoned Mine H2 003

60 ghosts:
Abandoned Mine H2 001

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/5651#issuecomment-1185846862_

### Save file

Here are the save files:
[Abandoned mine 01.zip](https://github.com/ihhub/fheroes2/files/9113536/Abandoned.mine.01.zip)

### Additional info

Related issues: https://github.com/ihhub/fheroes2/issues/5662, https://github.com/ihhub/fheroes2/issues/5663.
Related discussion: https://github.com/ihhub/fheroes2/discussions/5664.

### PR DESCRIPTION
**Pull request by undef21**
fix #5651

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
I still have not figured yet what determines the number of stacks. In other cases the `Troops::ArrangeForBattle()` is used, in which the number of stacks depends on the total number of units, but it seems that for Ghosts the rules are different. We can temporarily use `ArrangeForBattle( false )` for abandoned mine as well, but the exact rules for determining the number of stacks for Ghosts have yet to be determined.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> I still have not figured yet what determines the number of stacks. In other cases the `Troops::ArrangeForBattle()` is used, in which the number of stacks depends on the total number of units, but it seems that for Ghosts the rules are different. We can temporarily use `ArrangeForBattle( false )` for abandoned mine as well, but the exact rules for determining the number of stacks for Ghosts have yet to be determined.

For Abandoned mine, Shipwreck and mine with Haunt spell, the number of groups and their positioning is determined by the position of the location on the adventure map.
If the same scenario is replayed completely from the beginning, these places will have exactly the same number of groups and the same positioning, only the number of ghosts will be different (for the Abandoned mine and the shipwreck, for the haunted mine the number of ghosts is determined by the hero's spell power).

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > In original game, for Abandoned mine, Shipwreck and mine with Haunt spell, the number of groups and their positioning is determined by the position of the location on the adventure map.
> 
> I mean, are they random or they are dependent on the number of units on tile, for example "5-10 - 3 stacks, 10-20 - 4 stacks, otherwise 5 stacks". Both of these variants are suitable (if there is not a big difference in a number of ghosts), but I don't know which one is really used.

The number of groups and their positioning is not related to the number of ghosts.
They are not random.
It is the position of the location on the adventure map that is used to determine the number of groups and their position on the battlefield.
Take a look at these screenshots:
[Groups number and position 01 part 1.zip](https://github.com/ihhub/fheroes2/files/9130494/Groups.number.and.position.01.part.1.zip)
[Groups number and position 01 part 2.zip](https://github.com/ihhub/fheroes2/files/9130544/Groups.number.and.position.01.part.2.zip)

Here is the test scenario file:
[0 9930.zip](https://github.com/ihhub/fheroes2/files/9123469/0.9930.zip)

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> @LeHerosInconnu
> 
> > They are not random.
> 
> By "random" I mean "random based on seed". This means that although it is deterministic, it is still not easily predictable - just like with obstacles. BTW I'm going to implement the same logic as with obstacles - they depend not just on the tile's position, but also on the map's initial seed which adds more randomness. I still believe that randomness in the original game was implemented poorly.

Since you're talking about logic with obstacles, have you seen this: https://github.com/ihhub/fheroes2/discussions/5667?

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> Since you're talking about logic with obstacles, have you seen this: https://github.com/ihhub/fheroes2/discussions/5667?

Yes, this is just another example of poorly designed random in OG, and I agree with @Branikolog regarding suffering replayability.

**Comment by ihhub** [comment]
Closing this pull request in favor for #5668 .

**Pull request closed without merging**
