### PR TITLE
Add executable file description and icon on Windows

### PR DESCRIPTION
**Pull request by hgdagon**
Only implemented in the Makefile (for MinGW).

### CODE REVIEW

**Comment by hgdagon** [comment]
We should also remove the `TARGET` definition from the Makefile (line 73) if we're not using it.

**Comment by ihhub** [comment]
> We should also remove the `TARGET` definition from the Makefile (line 73) if we're not using it.

Hi @hgdagon , please wait a little :) I haven't finished yet...

**Comment by ihhub** [comment]
@hgdagon , please add (unzip it from the archive) this icon to `src/resources` directory and uncomment the line in **fheroes2.rc** file. Visual Studio will automatically pick the icon up.
[fheroes2.zip](https://github.com/ihhub/fheroes2/files/6136020/fheroes2.zip)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@hgdagon , thank you so much for your changes! Could you please update your original pull request to include these changes?

**Pull request merged**
