### PR TITLE
fix(world): lighthouse doesn't reveal additional squares

### PR DESCRIPTION
**Pull request by pathway27**
To fix https://github.com/ihhub/fheroes2/issues/132

Is this what's required or should it be like the other structures as `scoute = 2` ?

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, could you please advise about this change? Do we even need it?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, could you please advise about this change? Do we even need it?

In the original game, each Lighthouse gives an ocean movement bonus of 5 moves (500 points) for all heroes on a boat, and nothing else.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @pathway27 , this is just a partial fix. Please search for VIEW_LIGHT_HOUSE and places where it's used. You need to remove these places, such enumeration entry and modify `overview_distance` static array.

**Comment by pathway27** [comment]
Removed.

What about the `overview_distance` should I change?

**Comment by ihhub** [comment]
> Removed.
> 
> What about the `overview_distance` should I change?

Yes please. Right now it contains the value for removes enumeration entry and even in comments we don't specify what this value for.

**Comment by ihhub** [comment]
@pathway27 thank you very much for your contribution to the project!

**Pull request merged**
