### PR TITLE
Reset sound only if battle is shown

### LINKED ISSUE #1051: Music stops playing during the AI turn, after enemy has made any battle
When AI hero fights anyone music stops.
Also, I'm curious, if we have any music theme for AI turn. As during AI turn always plays last theme, we can hear during player turn.

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #1051 .

### CODE REVIEW

**Comment by ihhub** [comment]
@idshibanov , thanks a lot for fixing this issue!

**Comment by Branikolog** [comment]
After loosing a battle with AI there's still silence until other soundtrack starts. (initiated by turn of a AI hero placed on another terrain)

**Comment by idshibanov** [comment]
> 
> 
> After loosing a battle with AI there's still silence until other soundtrack starts. (initiated by turn of a AI hero placed on another terrain)

Can't reproduce on my build. Music restarts after either mine or AI's battle. Are you on MIDI version? Did you wait a bit for music fade in (on grass or desert for example)?

**Comment by Branikolog** [comment]
Oh, forgot to mention, that I test now with CD music...

**Pull request merged**
