### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by Districh-ru**
- Removed `#, fuzzy` marks added after  #7755 because the translated text does not have double spaces.
- Corrected the translation for the Steelskin spell description.
- Updated the copyright year ... after 9 months. :)

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
Why have you decided to take away amount of defense increased by these spells? I find this information useful. The same as the exact damage dealed by attacking spells or the number of HP restored by Cure or Resurrection spells which were added in the descriptions over the original.

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru ! Why have you decided to take away amount of defense increased by these spells? I find this information useful. The same as the exact damage dealed by attacking spells or the number of HP restored by Cure or Resurrection spells which were added in the descriptions over the original.

Hello, @Branikolog! 
I did this to make the translation more consistent with the original text. :)
But we may keep the amount info. I reverted the these changes in the translation.
If we think that this information is useful in spell descriptions than probably we should add it to the original English text. What do you think? Was it discussed with the team?

**Comment by Branikolog** [comment]
Hi, @Districh-ru 

>If we think that this information is useful in spell descriptions than probably we should add it to the original English text. What do you think? Was it discussed with the team?

I don't remember we had such discussion.
English version doesn't have such description indeed. I find it really useful to know, what is the exact values of these spells.

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you very much for the update!

**Pull request merged**
