### PR TITLE
Update of the Slovak Translation

### PR DESCRIPTION
**Pull request by agiat86**

### CODE REVIEW

**Review by Roxterat — APPROVED** [review]
Good work.

**Comment by ihhub** [comment]
Hi @agiat86 , could you please resolve merge conflicts here?

**Comment by ihhub** [comment]
Hi @zenseii , I restarted failed builds.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @agiat86 , we cannot merge this pull request as your changes contain either a "bad" symbol or some special symbols is missing. Please find the root of the problem and fix it so we can proceed with your changes.

**Comment by ihhub** [comment]
@agiat86 , thank you very much for the update!

**Pull request merged**
