### PR TITLE
Use 22050 sound sample rate for PS Vita to fix high CPU load

### LINKED ISSUE #7176: During battle, the moving animation is jerky
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

PlayStation Vita

### Describe the bug

During battle, the moving animation is jerky, especially flying creatures. It was smooth until 1.0.2, but from 1.0.3 it became like this. And the latest 1.0.4 also has this problem.

### Save file

This happens in all battles.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #7176
On the battlefield on high speed the move sound is played for every cell move which ends in multiple simultaneous sound playbacks. The PS Vita sound resampler loads the CPU to resample and play these sounds. This result in game lags and jerky animation.

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hi @kazenoyouni.
Could you please check this fix on PlayStation Vita hardware when you have time. Here is the [compiled PS Vita binary.](https://github.com/ihhub/fheroes2/suites/13028517499/artifacts/705922555)

I tested this fix only with [Vita3K emulator](https://github.com/Vita3K/Vita3K).

**Comment by kazenoyouni** [comment]
@Districh-ru 
Cpu usage fluctuates between 65-80% during battle. This build works as smoothly as ver 1.0.2.
Thank you very much for your great work!

**Comment by Districh-ru** [comment]
> @Districh-ru Cpu usage fluctuates between 65-80% during battle. This build works as smoothly as ver 1.0.2. Thank you very much for your great work!

@kazenoyouni, thank you for testing!

**Review by ihhub — APPROVED** [review]
Hi @Districh-ru , this looks fine to me. In the future we might need to come up with a strategy to count the number of the same sound samples being played simultaneously and not to play more than N at once.

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for the fix!

**Pull request merged**
