### PR TITLE
Fix saving of Maps::Tiles and Maps::TilesAddon enums

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Follow-up to #6567 which fixed not all cases.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I added static cast for a reason that in the future we are going to extend enumerations, at least for main object type.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I added static cast for a reason that in the future we are going to extend enumerations, at least for main object type.

All static casts are still in place, but the new ones were added for `TilesAddon` to help choosing a proper `operator<<()` overload.

**Comment by ihhub** [comment]
Oops, I meant static assert :)

**Comment by oleg-derevenetz** [comment]
> Oops, I meant static assert :)

I left `static_assert()` on reading, because that's where we should add compatibility shims if underlying type of `enum` will be changed. What would be the purpose of `static_assert()` on writing?

**Comment by ihhub** [comment]
You're right, no purpose.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for this hot fix!

**Pull request merged**
