### PR TITLE
Fix too many free slots in cross-army splitting

### LINKED ISSUE #4015: Not correct splitting of stack into 6 parts
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Splitting is not working correctly when we split hero's army into 6 stacks, and there's already one slot is occupied in a castle.
image
image

### Save file

[Split issue.zip](https://github.com/ihhub/fheroes2/files/6988000/Split.issue.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by eos428**
fix #4015

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this change for all cases?

**Comment by Branikolog** [comment]
@ihhub 
Everything seems to be ok now.

**Comment by ihhub** [comment]
@eos428 , thanks a lot for the fix!

**Comment by oleg-derevenetz** [comment]
I believe this will break #3621 once again.

**Comment by ihhub** [comment]
Okay, I'll check today every case.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I've tested as intensely, as I could... I've managed to find another issue, but the problem you've pointed above doesn't occur.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I managed to reproduce the #3621 on the latest build:

bug

Try to drag&drop Archers to the garrison.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
True!
Rare case, when we try to split the only stack in hero army... My fault... Missed this problem...
The maximum result stack number lacks 1 in a case we split the only troop in army.
Splitting orcs, which are NOT the only troop in hero army:
image
Splitting orcs, which are the only troop in hero army:
image

**Pull request merged**
