### PR TITLE
Mask the tavern tile in Necromancer's castle

### PR DESCRIPTION
**Pull request by bjauny**
So basically the tavern tile is redrawn with a rectangle of the background texture. On top of that the tavern tile events are not managed, just in case it may cause unwanted side-effects.

### CODE REVIEW

**Comment by bjauny** [comment]
At this point, either I revert my changes to the first commit and we leave the complexity as is, or I refactor the whole `castle_town.cpp` file to clean the mess it is currently (before my changes I mean).
Defining structures to embed the multiple parameters is a starting point. Using STL algorithms on `BuildingInfo` vectors could be helpful too for the status messages at least.
Anyway, strictly speaking this solves issue #52 but it can be improved with a few more hours of work.

**Comment by ihhub** [comment]
Hi @bjauny , I will take a look into this pull request little later. I have few ideas how to make it better.

**Comment by bjauny** [comment]
> Hi @bjauny , I will take a look into this pull request little later. I have few ideas how to make it better.

OK so I'll hold this until I have more input from you then.

**Comment by ihhub** [comment]
Closing this pull request as we found a proper fix for it.

**Pull request closed without merging**
