### PR TITLE
iwyu.map: add new private header mappings for newer Ubuntu image version, speed up IWYU workflow a bit

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Fix migration of Ubuntu 22.04 image from 20221027.1 to 20221119.2 with the newer compiler.

See [this run](https://github.com/ihhub/fheroes2/actions/runs/3525606072/jobs/5912534513) and [this comment](https://github.com/ihhub/fheroes2/pull/5983#issuecomment-1324094001) for details.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , mostly likely the answer is no but is there a way to cache IWYU to improve performance?

**Comment by oleg-derevenetz** [comment]
@ihhub you see, IWYU doesn't have any intermediate database. It just parses the sources and included headers using LLVM backend. But I need to think about that.

**Comment by oleg-derevenetz** [comment]
@ihhub I reworked the workflow a bit to use the `iwyu_tool` script bundled with IWYU instead of `cmake`. The difference is `cmake` also runs compiler along with `include-what-you-use` to perform all build stages (if it didn't do this, the project would only be partially built, because there would be no object files and therefore nothing to link), while `iwyu_tool` runs just IWYU itself using `compile_commands.json` generated by CMake on the project generation stage. It became faster but not much - about 1/3 maybe.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you very much for this improvement!

**Pull request merged**
