### PR TITLE
Implement the secure way to run clang-tidy checks from forks

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Run the analysis itself on `pull_request` event with minimal permissions and then run the separate workflow on `workflow_run` event with elevated permissions to perform the PR decoration.

Currently the `clang_tidy_comments.yml` uses my own fork of Action to perform the PR decoration because original Action ([platisd/clang-tidy-pr-comments](https://github.com/platisd/clang-tidy-pr-comments)) is not able to accept the PR id as a parameter, but I made the https://github.com/platisd/clang-tidy-pr-comments/pull/4 PR, and I'll update this workflow once it will be merged. @ihhub or, if you wish, you can make your own fork of this Action (with my changes) to be able to fully control it.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I can make the fork to prevent any security flows. I'll inform you once it's done.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I proposed also this improvement to the upstream: https://github.com/platisd/clang-tidy-pr-comments/pull/5

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I made the fork - https://github.com/fheroes2/clang-tidy-pr-comments

**Comment by oleg-derevenetz** [comment]
Hi @ihhub 

> I made the fork - https://github.com/fheroes2/clang-tidy-pr-comments

Excellent! Let's introduce necessary changes (I made two PRs to this fork identical to the corresponding PRs to upstream) and we are ready to go.

**Comment by ihhub** [comment]
@oleg-derevenetz , great work! Thanks a lot for these changes!

**Comment by oleg-derevenetz** [comment]
@ihhub That's how PR decoration with this workflow looks like: #3868. You can even apply auto-fixes (if available) right from the GitHub UI :)

**Comment by oleg-derevenetz** [comment]
@ihhub BTW both changes are already in the upstream, so you can sync the  [fheroes2/clang-tidy-pr-comments](https://github.com/fheroes2/clang-tidy-pr-comments) with the upstream if you wish.

**Pull request merged**
