### PR TITLE
Fix polish encoding

### PR DESCRIPTION
**Pull request by undef21**
addition to #3971

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Arthusppp , could you please take a look at this pull request as well? I think some letter from Polish alphabetic are incorrectly shown in the game.

**Comment by dimag0g** [comment]
@undef21 If the Polish version uses CP1250 encoding, you should remove the conversion from utf-8 to ascii//TRANSLIT from the makefile: this will replace all Polish letters with their ASCII equivalents. A direct conversion from utf-8 to CP1250 should do a much better job.

**Comment by undef21** [comment]
> A direct conversion from utf-8 to CP1250 should do a much better job.

That's what i do.)

**Comment by dimag0g** [comment]
@undef21 Sorry, you're right. I didn't pay attention.

**Comment by Arthusppp** [comment]
To sum up the pull request: 
- the pl.po file remains utf-8
- there is an addtional step during the build process that converts the pl.po file from utf-8 to CP1250

**Comment by ihhub** [comment]
@undef21 , thanks a lot for this fix!

**Pull request merged**
