### PR TITLE
Fix Oasis passability

### LINKED ISSUE #8298: Path behind oasis not passable
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

Path behind an oasis is not passable. Situation:

Screenshot 2024-01-18 at 08 13 29

The gems (random resource) are not reachable, can not proceed further east.

The original game:

Screenshot 2024-01-18 at 08 13 34

... resources taken, can proceed east.

### Save file

[a_War_to_end_all_BUG.sav.zip](https://github.com/ihhub/fheroes2/files/13973280/a_War_to_end_all_BUG.sav.zip)
[War.MX2.zip](https://github.com/ihhub/fheroes2/files/13973283/War.MX2.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #8298

### CODE REVIEW

**Review by Districh-ru — APPROVED** [review]
Well done!
Now it is passable almost like in the original game:
изображение

And the original game has some weird passabilities. MHO we should not repeat this logic fully:
изображение

**Comment by Branikolog** [comment]
Hi, @ihhub 
Here's passability in the OG:
image

And here is in fheroes2:
image

**Comment by ihhub** [comment]
Hi @Branikolog and @Districh-ru  , I suggest to address the second problem separately as this is not an object specific rule but overall passability rule which I am not aware of. This PR at least will unblock broken gameplay.

**Comment by ihhub** [comment]
Hi @Branikolog  and @Districh-ru , I also made the same passability for Oasis object within out Editor.

**Review by Branikolog — APPROVED** [review]
Now that place is passable.
Passability is still differs from the original one and I hope we can improve the logic in this regard soon.

**Pull request merged**
