### PR TITLE
Fix redrawing some objects near hero

### PR DESCRIPTION
**Pull request by vasilenkoalexey**
If we redraw top objects on tile near hero, we should also redraw some top objets below this tile.
Before
h2
After
h1

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this change at highest priority?

**Comment by Branikolog** [comment]
@ihhub 
Sure!

**Comment by vasilenkoalexey** [comment]
possible fix #1940 too

**Comment by Branikolog** [comment]
Seems, that flags on objects are no longer disappearing with this fix.

**Comment by ihhub** [comment]
@vasilenkoalexey , thank you very much for the fix!

**Pull request merged**
