### PR TITLE
Show upgrade button if there's not enough money

### LINKED ISSUE #1199: Upgrade creature button cannot be seen, if player has not enough gold
"Disabled" status button "Upgrade" should be added, if there's not enough money to upgrade unit.
Currently this button disappears:
Upgrade creature

### PR DESCRIPTION
**Pull request by Moiman**
Fixes #1199

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Moiman , I'll complete review of all your pull request once I finish basic testing of my code so my apologies of a little delay, Everything will be done within maximum few days.

**Comment by ihhub** [comment]
Hi @Moiman , does this button appear during battle as well?

**Comment by Moiman** [comment]
> Hi @Moiman , does this button appear during battle as well?

No, there is check for troop.isBattle()

**Comment by ihhub** [comment]
Hi @Moiman , thanks a lot for your efforts. However, right now the button is not disabled. You could see on the screenshot below that there is only 200 gold which is not enough for the upgrade but the button is still enabled:
image

**Comment by Moiman** [comment]
Yes, that is how it works in original game too. If you click it it tells you how much it would cost.

**Comment by ihhub** [comment]
Hi @Branikolog , is it correct that the initial intention was to show disabled **UPGRADE** button?

**Comment by Branikolog** [comment]
> If you click it it tells you how much it would cost.

That's true.
In the OG we can see a window, after pressing "UPGRADE" button:
image
I think we should do the same message.

**Comment by ihhub** [comment]
Hi @Moiman , thanks a lot for your contribution! My apologies for such long delay as we've been working on a new engine which we integrated just yesterday so all pull requests were postponed till today.

**Pull request merged**
