### PR TITLE
SP now calculated with SPR after mouse click on icon

### LINKED ISSUE #6838: Magic Book, cost in spell points is not correct in the spell information window when the hero has the artifact that reduces the cost of elemental spells
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the cost in spell points is not correct in the spell information window when the hero has the artifact that reduces the cost of elemental spells.
The cost should be adjusted to "15".

In fheroes2:

Cost summon spell 001

Cost summon spell 002

Cost summon spell 003

### Save file

Here is the save file:
[Cost summon elemental 01.zip](https://github.com/ihhub/fheroes2/files/10970672/Cost.summon.elemental.01.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by autoexecbatman**
fix #6838 
Now the '_hero' is passed in the 'draw()' 
* Have not checked if it has any impact on the overall code.

### CODE REVIEW

**Review by thestahan — COMMENTED** [review]
I think you should also pass the hero in line 435, which is used to calculate the width of the area.

**Comment by autoexecbatman** [comment]
@thestahan honestly I would only add one change at a time . What you are referring to makes sense, but I am also not sure what this function does in the ctor and it seems that `nullptr` is passed explicitly to that function in many cases.
I can't see any visible effect currently either if I pass a nullptr or the _hero. 
might need to test with a 2 digit value becoming a 1 digit value

**Comment by autoexecbatman** [comment]
@thestahan I've tested that change and it changes the spell points in the mage guild to get calculated with reduction . 
I apologize if I was too hasty about posting the second commit. I prefer to not add it .

**Comment by thestahan** [comment]
> Any advice on how to delete this change ? I don't want to make a mess in git .

Yes, you can just revert the commit - it'll create a new commit that reverts the changes.

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@autoexecbatman , thank you so much for your contribution to the project!

**Pull request merged**
