### PR TITLE
Correcting text errors

### LINKED ISSUE #1701: Combat screen, log list, the information displayed in the log list should be written in a more understandable and correct way
The information displayed in the log list should be written in a more understandable and correct way, and with a period at the end of each sentence.

A complet and enhanced remake of Heroes of Might and Magic 2 does not deserve lazy programming.
Does fheroes2 have to?

In fheroes2:

Log list understandable and correct 01

- "1 Champion rise(s) from the dead!"

The sentence must be adapted directly to the number of creatures:
"1 Champion rises from the dead!"
"10 Champions rise from the dead!"

- "Gargoyle skipping turn"

Correct and understandable sentences should be used:
"The Gargoyle skips her turn."
"Gargoyles skip their turn."

- "Green cast spell: Fireball"
"Wrathmont casts Fireball on the Veteran Pikeman."

Is the first sentence really necessary?
"Wrathmont casts Fireball on the Veteran Pikeman."

- "The Fireball does 30 damage."
"one creature perishes."

These sentences should be combined in one sentence on the same line, and the name of the creature clearly indicated.
And the word "one" should be replaced by the number "1":
"The Fireball does 30 damage, 1 Ranger perishes."

In fheroes2:

Log list understandable and correct 02

- "Moved Champion: 27, 9"

Correct and understandable sentences should be used, and with more understandable hexagon positions (https://github.com/ihhub/fheroes2/issues/1372):
"The Champion moves from C6-7 to A10-11."
"Champions move from C6-7 to A10-11."

- "Champion do 13 damage. one Peasant perishes."

These sentences should be combined in one sentence on the same line, and the word "one" should be replaced by the number "1":
"The Champion does 13 damage, 1 Peasant perishes."
"Champions do 13 damage, 1 Peasant perishes."

- "Champion do 9 damage."
"Champion do 5 damage."

These sentences describe an attack and a retaliation from the attacked troop.
This should be specified:
"The Champion does 9 damage."
"The Champion retaliates and does 5 damage."
"Champions do 9 damage."
"Champions retaliate and do 5 damage."

### PR DESCRIPTION
**Pull request by morgane-du-tweize**
fix #1701
This PR will correct issues from issue n°1701
https://github.com/ihhub/fheroes2/issues/1701

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @morgane-du-tweize please don't do this. Use `_n()` instead.

**Comment by morgane-du-tweize** [comment]
Hi @oleg-derevenetz
I'm totally newbie, hope it's better.

**Comment by oleg-derevenetz** [comment]
Hi @morgane-du-tweize your code doesn't even compile, please fix this and make sure that it actually works and passes all the required checks. Also there is no need to use `_()` and `_n()` simultaneously.

**Comment by morgane-du-tweize** [comment]
Hope the problem is fixed.
If it's still not good I just lack proper c++ coding skills.
I don't mind this PR closed.

**Comment by ihhub** [comment]
> Hope the problem is fixed. If it's still not good I just lack proper c++ coding skills. I don't mind this PR being closed.

Hi @morgane-du-tweize , what @oleg-derevenetz  meant is that you need to look in Code style check which fails right now and correct the code according its suggestion. Click on Details of the failed stage in our pipeline (just below this message) and see what is needed to be done.

**Comment by ihhub** [comment]
@morgane-du-tweize , essentially you need to add an extra space before `_n(`.

**Comment by ihhub** [comment]
Hi @morgane-du-tweize , now the compilation almost completed I need to ask you to change the title of your pull request to make it more readable. You don't need to mention the original issue ID in the title and usually a PR's title starts from a capital letter :)

**Comment by ihhub** [comment]
@morgane-du-tweize , also in order to connect and close the issue you need to modify your first message to include one of these phrases:
```
close #1234
fix #1234
```
Then GitHub will automatically connect this pull request to the corresponding issue.

**Comment by Districh-ru** [comment]
Hi @morgane-du-tweize 
You use `GetCount()`, wich gest the count of troops after resurrection. There is `resurrect` constant in this code, which contains the number of resurrected troops. So, I can suggest you to use this constant in '_n()':
`std::string str( _n( "%{count} %{name} rises from the dead!", "%{count} %{name} rise from the dead!" , resurrect ) );`
:
изображение
изображение

But here comes the next problem: `GetName()` returns the name for the troops count after resurrection, not for the count of resurrected ones.
To fix this the line `StringReplace( str, "%{name}", GetName() );` could be changed to `StringReplace( str, "%{name}", Monster::GetPluralName( resurrect ) );`. It works, but I don't know is the use of 'Monster::GetPluralName' good.

изображение

**Comment by morgane-du-tweize** [comment]
Everybody, thank you.
Took account of your comments.

**Comment by zenseii** [comment]
> fix #1234 This PR will correct issues from issue n°1701 #1701

Hi, @morgane-du-tweize.

You are linking to fix the wrong issue in the opening message. @ihhub wrote issue nr. 1234 as an example name, but you should write the actual issue you're fixing with this PR. I believe that is the issue you wrote on the bottom of your opening text.

**Review by zenseii — APPROVED** [review]
Hi, @morgane-du-tweize.

This looks good to me. I edited my post above with some comments about improving the PR title. Please have a look if you have the time to.

**Comment by ihhub** [comment]
@morgane-du-tweize , thank you very much for fixing this issue!

**Comment by morgane-du-tweize** [comment]
Initially, bug #1701 was describing several bugs, including lack of period at the end on some log sentences.
I was willing to fix these problems too.
Is it possible to maintain the branch to further work with ?

**Comment by zenseii** [comment]
> Initially, bug #1701 was describing several bugs, including lack of period at the end on some log sentences. I was willing to fix these problems too. Is it possible to maintain the branch to further work with ?

At this point I suggest just creating a new branch with the latest updates and then making a new PR. This is fine and probably the only possibility. The fheroes2 master will anyways have all your relevant changes from this branch. If you made anything else after that you can always just cherry pick them into a new branch.

**Pull request merged**
