### PR TITLE
Add Graphics option icon and update Hotkeys icon

### LINKED ISSUE #6550: Add a new icon for Graphics Settings
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

We utilize many existing icons and this is bad. Every option should have its own unique icon. This is how the graphics settings icon look like and the same icon is used for mixed Interface type in the original game:
image

### Describe the possible solution

Add a brand new icon which is suitable for this option.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6550

all credits go to @golden-lining

image

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Umm, CRT monitor... Nostalgia...

**Comment by ihhub** [comment]
> Umm, CRT monitor... Nostalgia...

In 1995 it was the best programmer's friend ;)

**Comment by ihhub** [comment]
Hi @zenseii , we chose black because all electronic device icons are black in the game.

**Review by Districh-ru — COMMENTED** [review]
A CRT monitor perfectly fits the game 👍 

I'm not an artist, but for me the edges of monitor icon looks too sharp at the bottom side. If you look at other icons, you can see the soft edges (like MSAA 4x :)) )
Maybe we cloud also give this icon more soft edges on its bottom side:
изображение

**Comment by Districh-ru** [comment]
> It seems like the shadow is smaller than for all the other icons?

On other icons it is about twice  bigger at the bottom side...

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by oleg-derevenetz** [comment]
> How about we display something simple like the fheroes2 logo shield?

I strongly doubt that someone will look at what's on that icon's screen at 1080p (or even 720p) in-game resolution. Overly detailed icons are actually not as good as it might seem.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !

> I strongly doubt that someone will look at what's on that icon's screen at 1080p (or even 720p) in-game resolution. Overly detailed icons are actually not as good as it might seem.

If you look at loudspeakers icon, you can notice that original artists managed to draw there netting over speakers and even 8 or 16 digits to show music bitrate I suppose. :)

Hi, @Districh-ru !

> I'm not an artist, but for me the edges of monitor icon looks too sharp at the bottom side. If you look at other icons, you can see the soft edges (like MSAA 4x :)) )
> Maybe we cloud also give this icon more soft edges on its bottom side:

I think it's not really an easy task to make this tiny picture which is ~50x50px more smooth, since we're limited in colours too. :) 
But yes, new image looks more sharp... Making it blurry with H2 palette would be a headache, while composing those colours. :)

Hi, @zenseii !

> Also, this is my final nitpick. I can see that the monitor is turned on because of the green light, but the screen is still black. How about we display something simple like the fheroes2 logo shield? Or anything else that comes to mind that would obviously be allowed.

That's why I previously proposed to change green to orange, which is commonly used for standby mode of moitor. :)

**Comment by ihhub** [comment]
Hi @zenseii and @Districh-ru , I uploaded a new icon. Please take a look. @Branikolog , approved it in Discord.

**Review by Districh-ru — APPROVED** [review]
👍

**Pull request merged**
