### PR TITLE
Event details window implementation

### PR DESCRIPTION
**Pull request by idshibanov**
image

relates to #6845

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @zenseii , can you please take a look at newly added strings?

**Review by ihhub — APPROVED** [review]

**Comment by Stisen1** [comment]
image


image

- "Evnt"? Not "Event"?

- Why does it prompt that I can't have another Magic Book, before I get the actual event log?
 
image

**Review by Districh-ru — APPROVED** [review]

**Comment by ihhub** [comment]
@Stisen1 , "evnt" is an image which is a part of the original resources. fheroes2 didn't generate it.

Regarding the Magic Book window: can you share a map which contains the event?

**Comment by Stisen1** [comment]
@ihhub is that really nescesary? Have a hero with a magic book step into an event that reward you a magic book. And there you have it 🙂 

I wonder if Spell Scroll messes things up too 😉

**Comment by Branikolog** [comment]
Hello, I've made a couple of tests and found a few small issues.
- "Delete" button has no pressed state. I mean there's no animation of this button when clicking on it.
- Artifact icon, buttons, fields and checkboxes have no info hints on right click.
- Resource reward field looks too large (too much space between resource sprites), and I personally love the same field in the sphinx window more:
image
image

- The event does not trigger anymore after one visit without activated option "cancel event after the first visit". (in the OG it triggers each time your hero steps on this event.

- Event triggers for a human player, when I adjust this event to trigger only for a computer players.
image

**Comment by Branikolog** [comment]
It would be nice to have an option to trigger the event once per player.

**Comment by ihhub** [comment]
> It would be nice to have an option to trigger the event once per player.

All enhancements are after 1.1.

**Comment by Branikolog** [comment]
Magic book warning is still the case.

https://github.com/ihhub/fheroes2/assets/55348946/e565a3cf-92ee-4c38-bf73-47fdb0178b30

[Book map.zip](https://github.com/ihhub/fheroes2/files/15322874/Book.map.zip)

**Comment by Districh-ru** [comment]
Hi, @zenseii!
Could you please check the recently added right-click phrases (https://github.com/ihhub/fheroes2/pull/8647/commits/c094c76b37c113dddefde366f57c2a4733939fe2) when you have time?

**Comment by Districh-ru** [comment]
Hi, @Branikolog 
- Now if there is a warning about inability to pick-up an artifact (it also causes when hero's artifact bag is full) the message occurs only after the event message.
- Dialog is now a little more compact and has more right-click messages:
изображение

Could you please review the changes when you have time?

**Comment by Branikolog** [comment]
Hi, @Districh-ru !

Can you, please, try to squeeze new window a little? There's not enough space for right and left frames on 640x480:
image

**Comment by Districh-ru** [comment]
> @Districh-ru. I left some small suggestions. Please have a look.

Many thanks, @zenseii!

**Comment by Districh-ru** [comment]
> Can you, please, try to squeeze new window a little? There's not enough space for right and left frames on 640x480:

@Branikolog, thanks for pointing this out. Now all dialog borders are shown in 640x480 resolution.
изображение

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I think IWYU is misbehaving again.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I think IWYU is misbehaving again.

There is a newer Ubuntu image version has been rolled out recently by Github, probably with a newer compiler version, so I just added all those `#include <type_traits>` in my PR. You can do the same, there are about 5 places or so, or I can create a separate PR for this later today.

**Comment by ihhub** [comment]
@oleg-derevenetz , could you please create a separate PR for it?

**Comment by ihhub** [comment]
@idshibanov and @Districh-ru , many thanks for this feature!

**Pull request merged**
