### PR TITLE
Reformat sources

### PR DESCRIPTION
**Pull request by andrey-starodubtsev**
There's `.clang-format` file under the source control, but a lot of source code files aren't formatted according it. So this PR is a result of

```
clang-format -style=file -i $(find . \( -name '*.cpp' -o -name '*.h' \))
```

If you're suspicious with large amount of changes please execute this command manually and compare results.

### CODE REVIEW

**Comment by andrey-starodubtsev** [comment]
```
curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o clang-format-diff.py && chmod +x clang-format-diff.py && ./clang-format-diff.py -p1 -style=file
```

shows empty diff now

**Comment by andrey-starodubtsev** [comment]
Several problems were uncovered after all sources were reformatted:

- fixed: quotes were used to include standard header `SDL.h` instead of `<>`
- fixed: some headers relied on certain order of inclusion and used types without including corresponding header files, so after clang-format reordered includes, project couldn't be compiled anymore
- fixed: .clangformat set C++11 as used language, but types which are represented by templates-inside-templates (e.g.  `std::vector<std::pair<int, int>>`) used `> >` as closing angualr brackets. C++11 allows `>>` to be used in these cases, and C++03 doesn't; neigher Linux nor OSX use '-std=c++11' in CFLAGS, no C++11 features are used in the code, so when clang-format removed space in `> >`, build on Travis CI starts to fail. For now used C++ version in `.clang-format` changed to C++03.
- fixed: returned types for `Luck::String` and `Luck::Description` changed from `const std::string` to `const std::string&` to avoid extra allocation

**Comment by andrey-starodubtsev** [comment]
Some changes required to build on Windows were made:

- fixed: clang reorders includes, so `shlapi.h` gets before `windows.h`
- fixed: `realloc` is defined as macro on Windows, so using it as a
    method name conflicts with CRT implementation

**Comment by ihhub** [comment]
Hi @andrey-starodubtsev I'm not suspicious about large amount of unformatted code. The project was cloned from sourceforge, hence has a lot of issues with formatting. I copied `clang-format` from my another project which by default C++11 that's why we have such mistake.

I really appreciate this pull request but let's do it little wiser: we fix all **real** problems with code as formatting the code is not such big issue (I am fan of clean source code by the way).

My suggestion if you don't mind:
1. Fix SDL.h inclusion
2. Fix C++03 support by clang-format
3. fixed: returned types for Luck::String and Luck::Description changed from const std::string to const std::string& to avoid extra allocation
4. fixed: realloc is defined as macro on Windows, so using it as a
method name conflicts with CRT implementation

What do you think?

**Comment by ihhub** [comment]
Another way to do reformatting is step by step but we need to keep in mind that not all format options are mandatory. For example this code looks nicer to read rather than what clang proposes:
```cpp
const int castleCount   = 10;
const int creatureCount = 5;
const int heroCount     = 2;
```
So we need to find a solution not to do such reformatting in one shot.

**Comment by andrey-starodubtsev** [comment]
Well, I force-formatted the code cause I think it's easier to execute one command before commit to reformat changed files rather than reformat files to understand program logic, do actual changes, revert reformatting, fix conflicts, check if changes are compliant with current `.clang-format` with `clang-format-diff`.

Also, at the moment committer must perform formatting changes in the code she/he touches, and these changes may obscure meaningful changes in commit, that impedes code review process.

From my experience related to supporting old projects without prior code formatting, it's better to rip band aid off at once rather that hit it on and on again :smile:

Please let me know if I haven't convinced you, and I'll remove re-formatting changes from this PR in this case.

About aligning by `=`: may be you should consider [Uncrustify](https://github.com/uncrustify/uncrustify) - it has much more options to control source code formatting, and, in particular, it aligns variable declarations/definitions.

**Comment by ihhub** [comment]
@andrey-starodubtsev I got some ideas what we can do in one shot. I'll explain tomorrow.

**Comment by andrey-starodubtsev** [comment]
Here's an example of the problem which is brought by unformatted sources:

I've got little patch which fixes an actual issue: #172. It has actual changes (f6cd08e), and after that I have to apply

```
git diff HEAD~ -U0 --no-color | clang-format-diff -p1 | patch -p0
```

several times just to pass CI check.

**Comment by ihhub** [comment]
@andrey-starodubtsev let's do this way as it there is no other way to do :)

**Comment by ihhub** [comment]
Hi @andrey-starodubtsev this commit caused a lot of conflicts in pull requests. I reverted it back for now. We could do this after we have a little number of pull requests :(

**Pull request merged**
