### PR TITLE
Fix ICN::MINIHERO issues

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR fixes original heroes sprites that are used in Editor. These issues are fixed:
- all Knight heroes have two leftmost columns cut;
- green Knight, Sorceress and Warlock, and all Yellow heroes have cycling colors in their sprite;
- orange Random hero has purple flag;
- blue Random hero and orange Necromancer heroes have a shifted flag.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @Districh-ru 
There's still a few purple pixels on orange random hero sprite:
image

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru There're still few purple pixels on orange random hero sprite: image

Hi, @Branikolog , Thanks for noticing this! Now it is fixed.

изображение

**Review by Branikolog — APPROVED** [review]
Great!

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for these fixes!

**Pull request merged**
