### PR TITLE
Implement Landscape Miscellaneous (non action) objects placing in Editor

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR adds Landscape (non action) miscellaneous objects to editor database.
There are lots of such objects, currently they are added (and shown) in the order of their appearance in game ICNs. I hope I didn't miss any non-action objects. :)
Later we well make a new dialog to show these objects by groups (lake, cactus, flowers, ... ). Suggestions for this dialog are accepted.

eidtor

### CODE REVIEW

**Comment by Districh-ru** [comment]
In original game there are some objects called "Nothing Special".
изображение
But we have no unused object types to give these object the new names. :(
(in example: Swampy Lake, Reed, Rotten Roots)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @Branikolog , please prioritize this pull request.

**Comment by Branikolog** [comment]
Hi, @Districh-ru 

Here are few issues I've found. Could you, please, look if they are valid and could be fixed?

I believe, that we should always place "no objects" like ground cracks under roads, streams and all other objects.
image

The hole, though, looks well placed both under or above roads/streams, but while placing some streams over it we should preserve the overlay of the existing stream nearby:
image

Cracks and holes shouldn't be allowed to be placed on a water:
image

**Comment by Branikolog** [comment]
@Districh-ru 
Not sure, it's relarted to the current PR, but after loading the map, that I was used for testing this PR, any info terrain except ocean is stated as "beach":
image

[22.zip](https://github.com/ihhub/fheroes2/files/13956570/22.zip)

**Comment by Districh-ru** [comment]
> Not sure, it's related to the current PR, but after loading the map, that I was using for tests of this PR, any info terrain except ocean is stated as "beach"

While reading map from file we read each tile one by one and if tile contains an object then we also update passabilities on map, but at this time not all tile are loaded and have tile image index reset to 0 (zero). And this is an index of water tile, so the pass updater sees that near the tile there is a "water" and also sets it as Beach (OBJ_COAST).

Hi, @ihhub, should we first set all terrain image index data for all tiles and then load objects or change `setObjectOnTile()` to call `world.updatePassabilities();` only if a boolean parameter (e.g. `const bool doUpdatePassabilities`) is set to true and while loading a map set it to `false` and update passabilities only after the whole map is loaded only once (it will be also faster). What do you think?

I also suggest to fix it in a separate PR, because this issue occurs on any map with any objects.

**Comment by ihhub** [comment]
Hi @Districh-ru , yes, let's fix map loading in a separate pull request. @Branikolog , if you don't have other comments please approve this pull request.

**Comment by Branikolog** [comment]
Hi, @Districh-ru 

I've noticed some objects have differences in passabilities with the OG. Could you, please, check if I was wrong?

1. 
image

image

2. 
image

image

3.
image

image

4. 
image

image

5. 
image

image

6.
image

image

7. 
image

image

image

8.
image

image

Also, I couldn't find this cactus in the original editor: 
image

:)

**Comment by Branikolog** [comment]
@Districh-ru 

>We have some situations to discuss, that is why I suggest to fix it separately.

Sure. But I had to mention them so we are aware of that problems. :)

**Comment by Branikolog** [comment]
Hi, @Districh-ru 

> 1. Yes, originally this tile is not passable: изображение
>    But it looks like a bug: this tile is a part of the ground and a hero in this tile will look like standing on the ground so it looks more like a passable:
>    изображение
>    We have already changed some passabilities for mountains, so I decided to make passavilities here more correspond to the object look.

Maybe horse's legs are too close to the swamp lake? I cannot test it, but it seems to me that with the proposed passability for this tile hero can make a diagonal move to the left. While doing that he will partially step over a lake, which is not good. Probably a green tile with red corner would be more proper here?
But actually, the OG have its own issues that seem even more broken, and in my personal opinion they require even more attention from our side.
image


I think we can find even more such controversial passability issues (I mean in the original editor to be fixed). I've just found the differences with fheroes2 engine. I'm not against that fixes, but discussing it here could make this PR postponed for really long time.


> * Nice catch: this is a difference between our engine and the original game. An map made by the original editor:
>   изображение
>   You can open an issue, showing these differences between original game and our engine to discuss what passability should we use for the original maps.
>   This impassable tile part may break some maps done by the original editor. :(
> *

Well, hero actally steps too close to the water in this case, so current fheroes2 passability seems even more proper to me. If we forget original maps, I'd rather prefer current passing rules for that tile in our future editor.

> 4\. Another nice catch: this is also a difference between our engine and the original game:
>     изображение
>     It cannot be fixed in editor. But IMHO this passability better suits this object and should not be change.

Agreed.


> 5\. This passability was changed by the same reason as in 1.

Won't hero be standing too close to the hot lava then?



> 7\. The same as 4, this is a map created by the original engine:
>     изображение
>     But do we need to change this passability? This is a single blooming cactus and do not need extra walk around. :)

This one just stands out from the other cactuses, that's why I've noticed it. Actually, I was more intrigued, why do other cactuses have such wide walkaround area... Maybe cactuses are so spiky, so hero just doesn't want to come too close to them? :)
If we follow such logic, I'd prefer to have such excessive walkaround area around all cactuses. :)

> 8\. The same as 4, this is a map created by the original engine:
>     изображение
>     In this case for me the passability in our engine is more consistent with the object's image, but it may break some maps done by the original editor. :(

Agreed. With the original passability hero just steps over the crack, which looks bad.

> 9\. This cactus is the only cactus for the Wasteland terrain :)
>     изображение

Ah found it! Thanks. 
It works fine, btw. :)

**Comment by Branikolog** [comment]
> 3\. Nice catch: this is a difference between our engine and the original game. An map made by the original editor:
>     изображение
>     You can open an issue, showing these differences between original game and our engine to discuss what passability should we use for the original maps.
>     This impassable tile part may break some maps done by the original editor. :(

Actually, this one was mentioned by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/4495#issue-1035322069 , but was not fixed yet.

Hey, @ihhub , could you, please, tell us your opinion on these issues? Do we need to fix the passability in the original maps for objects I've mentioned above?

**Comment by ihhub** [comment]
@Districh-ru and @Branikolog , passabilities of individual objects must be the same as in the original **Editor** which actually displays them. This involves 4 types of terrain layers and nothing more. For some objects we can fix obvious cases.

For the game passabilities we have to fix outside the scope of this pull request and the Editor. I was suspecting that we did not fix some cases and there they are. @Branikolog , please document them in #4495 issue.

**Comment by ihhub** [comment]
> Hi @Districh-ru , yes, let's fix map loading in a separate pull request. @Branikolog , if you don't have other comments please approve this pull request.

Terrain problem has been fixed.

**Comment by ihhub** [comment]
> Hi, @Districh-ru
> 
> Here are few issues I've found. Could you, please, look if they are valid and could be fixed?
> 
> I believe, that we should always place "no objects" like ground cracks under roads, streams and all other objects. image
> 
> The hole, though, looks well placed both under or above roads/streams, but while placing some streams over it we should preserve the overlay of the existing stream nearby: image
> 
> Cracks and holes shouldn't be allowed to be placed on a water: image

This should be fixed now.

**Comment by ihhub** [comment]
@Districh-ru and @Branikolog , I also fixed very slow map loading. Now it should be instant.

**Comment by ihhub** [comment]
Hi @Branikolog ,
> The hole, though, looks well placed both under or above roads/streams, but while placing some streams over it we should preserve the overlay of the existing stream nearby:

This is fixed as well.

**Comment by Districh-ru** [comment]
Hi, @Branikolog, issues # 1 and 5 are fixed to match the original editor.
We will discuss the needed passability changes later and apply them in a new PR.

**Comment by Districh-ru** [comment]
> This one just stands out from the other cactuses, that's why I've noticed it. Actually, I was more intrigued, why do other cactuses have such wide walkaround area... Maybe cactuses are so spiky, so hero just doesn't want to come too close to them? :)
> If we follow such logic, I'd prefer to have such excessive walkaround area around all cactuses. :)

The passability logic differs for tall objects (1 object tile and one tile above it in the top level passable by hero) and for low objects (without the upper tile). We can see the same difference in example for the Ork's Watch Tower on snow and other terrains. So currently it is defined by engine according to the rule: is there an upper passable object tile (not empty) image.

**Comment by Branikolog** [comment]
Hi, @ihhub 

I've still experience an issue with streams and holes:

https://github.com/ihhub/fheroes2/assets/55348946/78d96960-4dc5-4e86-a019-fceb273e6e18

**Comment by ihhub** [comment]
Hi @Branikolog , it works as expected. The patch was put first and the river second. I see no issues with this. What you are asking is to do unnecessary work for object placement conditions where we need to handle special cases like expanding an existing river. This must not be handled by the Editor.

**Comment by Branikolog** [comment]
Hi, @ihhub 
It actually looks bad. In my personal opinion we shouldn't allow players such placing, that looks like a bug. We're not allowed to place road on the ocean, right?

Maybe it should better to make a straightforward logic then, that always places such objects under a road or a stream?

**Comment by ihhub** [comment]
> Hi, @ihhub It actually looks bad. In my personal opinion we shouldn't allow players such placing, that looks like a bug. We're not allowed to place road on the ocean, right?
> 
> Maybe it should better to make a straightforward logic then, that always places such objects under a road or a stream?

@Branikolog , no, this is not true. As a map maker I might choose to put an object either under a stream or above. What you are suggesting is to force some objects appear **always** under a stream and to add extra unnecessary logic to the engine's Editor to facilitate this "special" case.

Here you go the same behavior in the original Editor:
image

So no, we are **not** going to do this.

**Comment by Branikolog** [comment]
@ihhub 
I agree with you, that handling such edge cases is a huge pain and I am ready to approve this pr, as everything else works fine. But I personally consider such cases as bugs, when occuring in the released editor. Even the possibility to place any object into won't place or work visual flaws makes an impression of half-baked and not well-polished product.
To not to postpone this PR even more we can merge it, but I hope there could be something name with issue in the future.

**Comment by ihhub** [comment]
> @ihhub I agree with you, that handling such edge cases is a huge pain and I am ready to approve this pr, as everything else works fine. But I personally consider such cases as bugs, when occuring in the released editor. Even the possibility to place any object into wrong place or work visual flaws makes an impression of half-baked and not well-polished product. To not to postpone this PR even more we can merge it, but I hope there could be something name with issue in the future.

You can add a comment in #6845 issue to possibly address this problem in the future.

**Review by Branikolog — APPROVED** [review]
Okay.

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this gigantic work!

**Comment by Branikolog** [comment]
@ihhub 

>You can add a comment in https://github.com/ihhub/fheroes2/issues/6845 issue to possibly address this problem in the future.

There's already a reposted message by @Districh-ru including a screenshots of broken streams.

**Pull request merged**
