### PR TITLE
Hero fight cursor offset fix (#4157, #1307)

### LINKED ISSUE #1307: Attacking cursor is shifted down
Comparing to the OG, attacking cursor is shifted.
On a screenshot we move mouse to left to point Arch Magi. It changes from a "horse" state to a "sword" state. 
Cursor shifting
Cursor shifting2
You can notice, that "sword" appears on a lower level.

While in OG in the same case "sword" cursor appears much higher:
Cursor shifting3
Cursor shifting4

### LINKED ISSUE #4157: Adventure map, there is something wrong with the management of the mouse cursor position according to the destination square
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is something wrong with the management of the mouse cursor position according to the destination square.

In fheroes2 :
In the example, with a different predefined hero path if the position of the mouse cursor is different by a few pixels when clicking on the destination square.
Path shorter 01
Path shorter 02

In the example, with the mouse cursor changing according to the mouse placement, attack cursor over the sprite of the hero who initiates the attack, attack cursor changing to arrow cursor in relation to the position over the boat.
Cursor attack position 01
Cursor attack position 02

https://user-images.githubusercontent.com/43583994/132094996-71f0ea44-2b24-4a98-8956-b4e5666addb3.mp4

### Save file

Here are the save files:
[Mouse cursor management 01.zip](https://github.com/ihhub/fheroes2/files/7109773/Mouse.cursor.management.01.zip)

### Additional info

Version 0.9.6 4111

### PR DESCRIPTION
**Pull request by HaveFun91**
Close #4157
Close #1307

This needs to be verified by @LeHerosInconnu more knowledgeable, but i think now cursor is placed more or less in right place.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @HaveFun91 Unfortunately, GitHub doesn't support the comma-separated list of issues, you need to make the separate "close #XXX" entry for each auto-linked issue.

**Review by ihhub — APPROVED** [review]
Hi @HaveFun91 , the change is very straightforward so I approve it.

Hi @Branikolog , could you please verify the changes?

**Comment by Branikolog** [comment]
Hi, @ihhub , @HaveFun91 
Currently horizontal alignment looks correct, while vertically cursor was shifted too much within this PR:
OG:

https://user-images.githubusercontent.com/55348946/196420653-eb46a4ee-fc45-4a75-bcc3-d4f4ca26b4fc.mp4

Current PR:

https://user-images.githubusercontent.com/55348946/196420583-7c0ef198-17af-418a-87af-85aacecec684.mp4

**Comment by HaveFun91** [comment]
@Branikolog Could you provide me save where you i could test change and compare with video?

**Comment by Branikolog** [comment]
@HaveFun91 
Sure!
[cursor save.zip](https://github.com/ihhub/fheroes2/files/9812416/cursor.save.zip)

**Comment by HaveFun91** [comment]
@Branikolog Ok i have checked and seems that now it should work better. Please check if everything is ok now.

**Comment by Branikolog** [comment]
Hello, @HaveFun91 
There's still a little difference in sword coordinates.
Here's the original game:
ezgif com-gif-maker (83)
Here's fheroes2:
ezgif com-gif-maker (84)
Here comparison between them:
ezgif com-gif-maker (85)
I tried to make as minimum movement, as I could. I moved from "horse cursor" leftwards I hope for 1 pixel (2 maximum), so there's a bit difference still.
If you wish I can provide separate screenshots as well.

**Comment by Branikolog** [comment]
@HaveFun91 
It seems to me that it must be 2 and 3 accordingly.
Swords
(Top left is original image.)

**Comment by HaveFun91** [comment]
@Branikolog ok i moved cursor 2px to the left and 3 pixels to the top.

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@HaveFun91 , thank you so much for your contribution to the project!

**Pull request merged**
