### PR TITLE
Rework the logic of re-calculating the paths of heroes on the adventure map

### LINKED ISSUE #4838: Adventure map, path changes each time hero moves one cell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Path is constantly changes, when hero moves. Right during movement.
image
image
image

### Save file

[Path.zip](https://github.com/ihhub/fheroes2/files/7775105/Path.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #4838

Alternative approach to the #4839 (more risky in terms of possible breaking changes). Fixes also the following cases:

---

Before this change:

Obstacle of Heroes Before 1
Obstacle of Heroes Before 2

After this change:

Obstacle of Heroes After 1
Obstacle of Heroes After 2

---

Before this change:

Obstacle of Monsters Before 1
Obstacle of Monsters Before 2

After this change:

Obstacle of Monsters After 1
Obstacle of Monsters After 2

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , we have a plenty of time till the next release. I'd choose the way to fix more things.

@Branikolog and @LeHerosInconnu, could you please if possible to test these changes?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @ihhub,

> Hi @oleg-derevenetz , we have a plenty of time till the next release. I'd choose the way to fix more things.
> 
> @Branikolog and @LeHerosInconnu, could you please if possible to test these changes?

I did some tests, the hero's path does not change anymore when he moves on the adventure map (https://github.com/ihhub/fheroes2/issues/4838).
And the hero's path is also updated according to the elements that were in the way in his predefined path and that are no longer present afterwards.

Maybe @Branikolog would like to do some specific tests for this. :)

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz & @LeHerosInconnu !
I've also done some tests. No issues found.
Good work, Oleg!

**Comment by oleg-derevenetz** [comment]
Thank you @Branikolog and @LeHerosInconnu! I hope this doesn't break anything... :)

**Comment by ihhub** [comment]
Good job, @oleg-derevenetz ! Let's see how these changes will impact the gameplay😀

**Pull request merged**
