### PR TITLE
Fix build with older Xcode versions

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Issues caught by MacPorts buildbot:

1. `#include <cstdlib>` is required for `std::abs()` with int argument and `std::div()`: [buildbot log](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/145739/steps/install-port/logs/stdio)

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I'm curious where all other compilation flags? It suppose to have many of them to check warnings.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I'm curious where all other compilation flags? It suppose to have many of them to check warnings.

I use CMake in Portfile, may be there is some special CMake configuration on buildbot.

**Comment by ihhub** [comment]
@oleg-derevenetz , it seems like flags for that compilation are incorrect. For example, Os flag is not the best application optimization.

**Comment by oleg-derevenetz** [comment]
@ihhub It looks like cmake portgroup use special build type by default - `MacPorts`, which sets those flags:

https://github.com/macports/macports-ports/blob/master/_resources/port1.0/group/cmake-1.1.tcl

I can try to use `Release` instead, but let's fix the build on older Xcode versions first. There is also one issue was found with older Clang versions (in addition to missing headers), but I don't want to fix this here, because it's a defect of an older compiler, so I will just provide a patch for it along with Portfile. Let's wait for merging another Portfile iteration and see what will fail once again... :)

**Comment by ihhub** [comment]
@oleg-derevenetz , sure! Please let me know once this pull request is ready for review.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub it seems that there will be no more changes - fheroes2 is now successfully built on almost all macOS versions supported by MacPorts (except 10.6, but it's a different story with an [absence](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/59703/steps/install-port/logs/stdio) of `___cxa_thread_atexit()` support, so I don't think any changes in fheroes2 code itself will be necessary).

**Comment by oleg-derevenetz** [comment]
Hi @ihhub regarding build flags: I was able to change compilation flags to the following:

```
cd /opt/local/var/macports/build/_Users_oleg_ports_games_fheroes2/fheroes2/work/build/src/engine && /usr/bin/clang++ -DWITH_ICONV -DWITH_IMAGE -DWITH_TTF -DWITH_ZLIB -I/opt/local/include/SDL2 -I/opt/local/var/macports/build/_Users_oleg_ports_games_fheroes2/fheroes2/work/fheroes2-0.9.4/src/engine -I/opt/local/var/macports/build/_Users_oleg_ports_games_fheroes2/fheroes2/work/fheroes2-0.9.4/src/thirdparty/libsmacker -isystem /opt/local/include -pipe -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11.0 -std=gnu++11 -o CMakeFiles/engine.dir/audio_cdrom.cpp.o -c /opt/local/var/macports/build/_Users_oleg_ports_games_fheroes2/fheroes2/work/fheroes2-0.9.4/src/engine/audio_cdrom.cpp
```

by setting `cmake.build_type` to `Release` and `configure.optflags` to `""` in the Portfile. So now we have `-O3`, but warnings are still off (I think it's done for a reason by MacPorts, because there is no benefit from them on user's machines, and in most cases user even don't see the build process, just a fancy progress bar instead).

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you very much for this fix!

**Pull request merged**
