### PR TITLE
The screen doesn't move smoothly during AI hero turn

### PR DESCRIPTION
**Pull request by shprotru**
Fix for #903

### CODE REVIEW

**Comment by idshibanov** [comment]
Excellent, I really needed this one :)

**Comment by ihhub** [comment]
Hi @shprotru , without SetCenter call we have weird behavior. I'm attaching a save to show this. Just load it and end human's turn. Once orange player ends its turn you would see that screen moves trice to left during purple player's turn. Here is a place where the screen will move after:
image

[Broken_Alliance_0032.zip](https://github.com/ihhub/fheroes2/files/4871963/Broken_Alliance_0032.zip)

**Comment by shprotru** [comment]
Hi @ihhub each time on AI controlled hero changes focus `SetCenter` will be called [here](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/ai/ai_hero_action.cpp#L1908). Turn of the `purple` player should not bee seen in this situation?

**Comment by ihhub** [comment]
> Hi @ihhub each time on AI controlled hero changes focus `SetCenter` will be called [here](https://github.com/ihhub/fheroes2/blob/master/src/fheroes2/ai/ai_hero_action.cpp#L1908). Turn of the `purple` player should not bee seen in this situation?

Turn must be seen as purple hero makes its move.

**Comment by shprotru** [comment]
Can't understand this moment visually, no sense, to me, to talk about values in debugger.

**Comment by idshibanov** [comment]
Reproduced it, I think the bug is in `AIHeroesShowAnimation`. Code does center the camera on AI hero most of the time, but fails sometimes. We need a `const bool` determining if we show hero movement or no and every if condition should be using new variable.

Also `display.Flip()` here is super expensive, same situation as in with mouse cursor.

**Comment by idshibanov** [comment]
@shprotru I fixed the behaviour locally using this approach. First, new variable like this:
`const bool hiddenMovement = conf.AIMoveSpeed() == 0 || !AIHeroesShowAnimation( hero );`

Replaced this if condition with new variable ( !hiddenMovement ) https://github.com/ihhub/fheroes2/blob/88873467bd094d8619bf2cd590983eed9d8682d5/src/fheroes2/ai/ai_hero_action.cpp#L1906


And then inside AIHeroesShowAnimation we should return true if **either** tile is not fog, like so:
`return !tile_from.isFog( colors ) || !tile_to.isFog( colors );`

**Comment by shprotru** [comment]
Inside while loop: `bool hide_move`, below, outside the loop: `bool hide_move`, every static c++ check system should warn on this. Names should be different or declaration should be done once. @ihhub how to fix this or simply ignore? Such places makes me dizzy.
Name `AIHeroesShowAnimation` hints that somewhere should be present `HeroesShowAnimation`, `PlayerHeroesShowAnimation` or `HumanHeroesShowAnimation`, but search gives nothing. I think I can't fix this, because these code need much deeper changes.

**Comment by idshibanov** [comment]
> 
> 
> Inside while loop: `bool hide_move`, below, outside the loop: `bool hide_move`, every static c++ check system should warn on this. Names should be different or declaration should be done once. @ihhub how to fix this or simply ignore? Such places makes me dizzy.
> Name `AIHeroesShowAnimation` hints that somewhere should be present `HeroesShowAnimation`, `PlayerHeroesShowAnimation` or `HumanHeroesShowAnimation`, but search gives nothing. I think I can't fix this, because these code need much deeper changes.

I know that variable/function names are bad. This is an ongoing issue; created by the original author. We try to rename as we slowly refactor the code, but there's still a lot of bad examples around. AIHeroesShowAnimation is just a local function in that file, we don't need a similar one for player because you always see your own turns.

@shprotru If you not sure how to fix it I can create a new PR with yours and mine changes combined.

**Comment by shprotru** [comment]
Hi @idshibanov create, please, I don't know how I can test that

**Comment by idshibanov** [comment]
No problem, new PR created with some refactoring included.

**Pull request closed without merging**
