### PR TITLE
Fix extra fade when switching heroes by interface buttons, fix hero dismiss UI bugs

### LINKED ISSUE #7255: Hero screen, switching from one hero to another with the arrows at the bottom of the screen displays the adventure map or the Kingdom Overview screen or the hero meeting screen briefly during the transition (1.0.4 7247)
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, switching from one hero to another with the arrows at the bottom of the screen displays the adventure map or the Kingdom Overview screen or the hero meeting screen briefly during the transition.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/28268681-0b66-4551-ab84-48743cdf6b4b

### Save file

Here is the save file:
[Dominion_0064.zip](https://github.com/ihhub/fheroes2/files/11615881/Dominion_0064.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #7255

This PR also fixes a bug when dismissing hero after opening hero dialog from the castle:

https://github.com/ihhub/fheroes2/assets/113276641/9ad6ce7b-623b-44f3-86ad-d90adfb3aad1

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hello @LeHerosInconnu. Could you please check this fix when you have time?

**Comment by ihhub** [comment]
Hi @Districh-ru , could you please also check this situation:
- open Kingdom Summary
- switch to Towns / Castles
- open any castle
- close the castle window

I can notice some weird frame at the end.

**Comment by ihhub** [comment]
This is what I see:

https://github.com/ihhub/fheroes2/assets/19829520/4d5231fb-f3a5-45b6-a1b9-74d5002748c8

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hello @LeHerosInconnu. Could you please check this fix when you have time?

In this PR, the problem of switching between heroes is solved.

I noticed that when I clicked on the second hero to initiate a meeting, something happened graphically to that hero.
It seems the arrow cursor is displayed before the transition to the hero meeting screen.
The two red arrows cursor should disappear, the hero meeting screen should fade in, and the two red arrows cursor should only appear afterwards.
Also, when clicking on the "EXIT" button on the hero meeting screen, the mouse cursor briefly changes to the meeting cursor (the two red arrows cursor).
This also happens in the latest versions of fheroes2.
I don't know if it's related to changes in this area and I could open another issue if necessary.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/8e98319d-4c56-4a4d-8301-ced4dda1af5a

**Comment by Districh-ru** [comment]
> Hello @Districh-ru,
> 
> > Hello @LeHerosInconnu. Could you please check this fix when you have time?
> 
> In this PR, the problem of switching between heroes is solved.
> 
> I noticed that when I clicked on the second hero to initiate a meeting, something happened graphically to that hero. It seems the arrow cursor is displayed before the transition to the hero meeting screen. The two red arrows cursor should disappear, the hero meeting screen should fade in, and the two red arrows cursor should only appear afterwards. Also, when clicking on the "EXIT" button on the hero meeting screen, the mouse cursor briefly changes to the meeting cursor (the two red arrows cursor). This also happens in the latest versions of fheroes2. I don't know if it's related to changes in this area and I could open another issue if necessary.


Many thanks for testing, @LeHerosInconnu!

You mean that the cursor should disappear while doing fade animation?)

**Comment by Districh-ru** [comment]
> Do you mean that the cursor should disappear while doing fade animation?)

It will flicker.

https://github.com/ihhub/fheroes2/assets/113276641/954b25c1-9981-44e4-878d-1ec563bed3ea

 IMHO it's better to force it to be a standard cursor pointer. I made the corresponding commit:
  

https://github.com/ihhub/fheroes2/assets/113276641/7a6734cc-55a5-43f1-9544-5bee8a02505e


But after closing the Hero meeting dialog and after the fade animation a cursor is changed to red arrows and sundial for a short time.
We should fix the issue with cursor in a separate PR as it touches other places than fade animation and probably we need to polish it in other places.

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> > Hello @Districh-ru,
> > > Hello @LeHerosInconnu. Could you please check this fix when you have time?
> > 
> > 
> > In this PR, the problem of switching between heroes is solved.
> > I noticed that when I clicked on the second hero to initiate a meeting, something happened graphically to that hero. It seems the arrow cursor is displayed before the transition to the hero meeting screen. The two red arrows cursor should disappear, the hero meeting screen should fade in, and the two red arrows cursor should only appear afterwards. Also, when clicking on the "EXIT" button on the hero meeting screen, the mouse cursor briefly changes to the meeting cursor (the two red arrows cursor). This also happens in the latest versions of fheroes2. I don't know if it's related to changes in this area and I could open another issue if necessary.
> 
> Many thanks for testing, @LeHerosInconnu!
> 
> Do you mean that the cursor should disappear while doing fade animation?)

> > Do you mean that the cursor should disappear while doing fade animation?)
> 
> It will flicker.
> 
> https://github.com/ihhub/fheroes2/assets/113276641/954b25c1-9981-44e4-878d-1ec563bed3ea
> 
> IMHO it's better to force it to be a standard cursor pointer. I made the corresponding commit:
> 
> https://github.com/ihhub/fheroes2/assets/113276641/7a6734cc-55a5-43f1-9544-5bee8a02505e
> 
> But after closing the Hero meeting dialog and after the fade animation a cursor is changed to red arrows and sundial for a short time. We should fix the issue with cursor in a separate PR as it touches other places than fade animation and probably we need to polish the cursor change in other places.

I made a mistake in the text.
I meant to write:

"The two red arrows cursor should disappear, the hero meeting screen should fade in, and the **arrow cursor** should only appear afterwards."

Anyway, do I have to wait for this PR to be merged to open another issue about "parasitic" cursors, or doesn't it matter?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , cursor is a separate issue. I agree with this enhancement but let's do it in a separate pull request.

**Comment by ihhub** [comment]
@Districh-ru , thank you very much for the fix!

**Comment by Districh-ru** [comment]
> Anyway, do I have to wait for this PR to be merged to open another issue about "parasitic" cursors, or doesn't it matter?

@LeHerosInconnu, could you please open the issue about cursors.

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru and @ihhub,

> Hi @LeHerosInconnu , cursor is a separate issue. I agree with this enhancement but let's do it in a separate pull request.

> > Anyway, do I have to wait for this PR to be merged to open another issue about "parasitic" cursors, or doesn't it matter?
> 
> @LeHerosInconnu, could you please open the issue about cursors.

Issue opened here: https://github.com/ihhub/fheroes2/issues/7272.

**Pull request merged**
