### PR TITLE
Fix the triggering of invalid drag events for the game area in certain cases

### LINKED ISSUE #6347: Adventure map, issues with mouse clicks processing during Town Portal spell activation
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

After confirming of the selected town and holding mouse button engine either experiences scrollbar bug or screen refocus.

https://user-images.githubusercontent.com/55348946/206898215-980d03fc-1c39-49ec-b96d-9dd5d0f78e13.mp4

To reproduce the bug:
In the first case right after confirming teleportation right mouse button should be held.
In the second case right after confirming teleportation left mouse button should be held.

### Save file

[5 guild.zip](https://github.com/ihhub/fheroes2/files/10201913/5.guild.zip)

### Additional info

_No response_

### LINKED ISSUE #9084: Adventure map, shifting of the adventure map when casting the dimension door spell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Sometimes I have this problem of the adventure map shifting when casting the dimension door spell, and I've also seen it in let's play videos, but I haven't been able to reproduce it in a consistent way.
I'm opening this issue to point out the problem and to serve as a reminder on the subject.

You can observe the problem here:
https://youtu.be/Ca5bbwKArOQ?t=191

### Save file

See the video above, the bug is not easily reproducible.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #9084
fix #6347

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru while I was testing this PR, I found the following issue (it is reproducible on `master` as well):

https://github.com/user-attachments/assets/192b3708-d730-4cd9-90d6-716f7db17cb0

How to reproduce:

* Select the "fill mode";
* Move the mouse cursor to the radar area and press the left mouse button;
* Scroll the editor area a bit using the radar;
* Without releasing the left mouse button, move the cursor to the editor area and back to the radar;
* Release the left mouse button while mouse cursor is on radar;
* Radar does not respond to new left-click and mouse cursor movement, scrolling does not work;
* After releasing the left mouse button again, everything starts working again.

This is observed only in the fill mode both with this PR and on the `master` branch.

**Review by Branikolog — APPROVED** [review]

**Comment by Branikolog** [comment]
Btw, scroll bug from https://github.com/ihhub/fheroes2/issues/6347  is not reproduceable anymore (in the master branch too). So after merging of this PR issue https://github.com/ihhub/fheroes2/issues/6347 could be closed. 👍

**Comment by oleg-derevenetz** [comment]
> Btw, scroll bug from https://github.com/ihhub/fheroes2/issues/6347  is not reproduceable anymore (in the master branch too). So after merging of this PR issue https://github.com/ihhub/fheroes2/issues/6347 could be closed. 👍 

That's good, probably it has been fixed some time ago in an unknown PR as a side effect.

**Review by Districh-ru — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this fix!

**Pull request merged**
