### PR TITLE
Sorting Headers in alphabetical order in src/fheroes2/objects

### PR DESCRIPTION
**Pull request by rsathya4802**
relates to #88

### CODE REVIEW

**Comment by rsathya4802** [comment]
My travis CI checks failed for some commits . Can you help me out ?

**Comment by ihhub** [comment]
Hi @rsathya4802 , Travis-CI passes so far. Could you please revert changes for `Heroes of Might and Magic 2` replacement. It's always good to have one pull request per issue to track the project?

**Comment by rsathya4802** [comment]
Ok . I did it

**Comment by ihhub** [comment]
Great! Once compilation on AppVeyor is completed I'll make pull request merge. :+1:

**Comment by ihhub** [comment]
@rsathya4802 thank you very much for your contribution to the project!

**Comment by rsathya4802** [comment]
Woah !! Thank You !!

**Pull request merged**
