### PR TITLE
Add Homebrew install instructions

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

### CODE REVIEW

**Comment by yurikoles** [comment]
https://formulae.brew.sh/formula/fheroes2

**Comment by ihhub** [comment]
Hi @yurikoles , before merging these changes we need to modify Homebrew formulae itself. I see some issues with it according to [this file](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fheroes2.rb):
- we must copy **files/data** directory to installation root path
- we must copy **changelog.txt** and **LICENSE** to installation root path
- we must copy **README.txt** file from `docs` directory to installation root path

Can you please help to do these changes as you're one of contributors to this formulae?

**Comment by yurikoles** [comment]
Hi @ihhub,

Don't get me lazy, but I think that this should be done at cmake level, so every new packager don't need to repeat this steps in their package specs.

**Comment by ihhub** [comment]
> 
> 
> Hi @ihhub,
> 
> Don't get me lazy, but I think that this should be done at cmake level, so every new packager don't need to repeat this steps in their package specs.

You're right. Let us modify it...

**Comment by ihhub** [comment]
@yurikoles , actually CMake should install all these files. I don't have MacOS with Homebrew on my hand to check what files are in the installation directory :(

**Comment by yurikoles** [comment]
BTW, in Unix FS conventions there's no `installation root path`. A better place for those files is `/usr/[local/]share/fheroes2/`.

Homebrew's Cellar is special case, all apps are installed in own prefixes, that is later being symlinked to `/usr/local` (default on Intel Mac, but differs on arm64, Linux and can be custom). Same approach is used by Nix, GNU Guix and some others. 

But in general Unix apps should install such files in common locations. E.g. on Debian and derivatives, user expects to see license at this path: `/usr/share/doc/fheroes2/copyright`

**Comment by yurikoles** [comment]
Here's what I see on my machine:

```
tree /usr/local/Cellar/fheroes2/0.9.9
/usr/local/Cellar/fheroes2/0.9.9
├── INSTALL_RECEIPT.json
├── LICENSE
├── README.md
├── bin
│   ├── fheroes2
│   └── fheroes2-install-demo
├── changelog.txt
└── share
    ├── doc
    │   └── fheroes2
    │       ├── LICENSE
    │       ├── README.txt
    │       ├── changelog.txt
    │       └── demo
    │           └── download_demo_version.sh
    └── fheroes2
        ├── fheroes2.key
        └── files
            ├── data
            │   └── resurrection.h2d
            └── lang
                ├── cs.mo
                ├── de.mo
                ├── es.mo
                ├── fr.mo
                ├── hu.mo
                ├── it.mo
                ├── lt.mo
                ├── nb.mo
                ├── nl.mo
                ├── pl.mo
                ├── pt.mo
                ├── ru.mo
                ├── sv.mo
                └── tr.mo

9 directories, 26 files```

**Comment by yurikoles** [comment]
I see the same on macOS GH Action in this PR.

**Comment by ihhub** [comment]
@yurikoles , thank you so much for your contribution to the project!

Regarding Linux: we might not have an ideal solution so yes, we can change paths as well :)

**Comment by yurikoles** [comment]
From macOS SDL2 runner:

```
-- Install configuration: "Release"
-- Installing: /usr/local/bin/fheroes2
-- Installing: /usr/local/share/fheroes2/files/data/resurrection.h2d
-- Installing: /usr/local/share/doc/fheroes2/README.txt
-- Installing: /usr/local/share/doc/fheroes2/LICENSE
-- Installing: /usr/local/share/doc/fheroes2/changelog.txt
-- Installing: /usr/local/share/doc/fheroes2/demo/download_demo_version.sh
```

**Comment by ihhub** [comment]
Yes, as I wrote later CMake indeed copies files during installation.

**Comment by yurikoles** [comment]
I posted this as proof that files are in the right place.

**Comment by ihhub** [comment]
Thank you so much for this!

**Comment by yurikoles** [comment]
I did only a few bits to help this project spread to the world, you are the person who does the real hard work maintaining this project. I didn't played it a lot, but the HMM series is legendary here, in ex-USSR, I heard about the project from [this post](https://www.opennet.ru/opennews/art.shtml?num=55922).

[This guy](https://www.opennet.ru/~sirDranik) keeps us informed about new releases for one year already.

**Comment by ihhub** [comment]
@yurikoles , I'm not the only person who is maintaining this project, we have many people contributing to it :)

This guy is essentially @Branikolog .

**Pull request merged**
