### PR TITLE
Cannot summon boats close to some objects on a world map #2935

### LINKED ISSUE #2935: Cannot summon boats close to some objects on a world map
110632397-a230ba00-81b8-11eb-8f9d-fd41e4d269ab
Hero can summon only one boat (the upper cell) and cannot do it for other free cells on a beach.
Interesting thing: if at the beginning of a game these both cells contain boats, hero can summon boats here  later.

### PR DESCRIPTION
**Pull request by felix642**
fix #2935 

Since a lighthouse can't be on water we simply consider the tile to be empty and allow players to summon a boat.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @felix642 , I think the better solution for this problem would be to use `isClearGround` method once #3756 is merged. This function will always return the correct value.

**Comment by felix642** [comment]
> Hi @felix642 , I think the better solution for this problem would be to use `isClearGround` method once #3756 is merged. This function will always return the correct value.

I will then wait for #3756  to be  merged.

**Comment by ihhub** [comment]
Hi @felix642 , could you please update this pull request?

**Comment by felix642** [comment]
> Hi @felix642 , could you please update this pull request?

Hi @ihhub I updated the pull request using the clearGround function.

**Comment by ihhub** [comment]
@felix642 , thank you so much for fixing this bug!

**Pull request merged**
