### PR TITLE
Fix issue when Blind or Paralyze has been applied to a hypnotized unit during its turn

### LINKED ISSUE #8283: Assertion failed: (pos.isValidForUnit( currentUnit ))
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

While trying to attack computer hero the game crashed with:

```
fheroes2 engine, version: 1.0.11
Assertion failed: (pos.isValidForUnit( currentUnit )), function getUnitMovementTarget, file ai_normal_battle.cpp, line 475.
```

Reproducible. Commit: 618cfd9c3aa9c8a4748d0f625e4d274a5cd00f42
OS: MacOS 14

Situation screenshot:

Screenshot 2024-01-14 at 20 33 53

### Save file

[Ancient_Magic_0073.sav.zip](https://github.com/ihhub/fheroes2/files/13932892/Ancient_Magic_0073.sav.zip)

### Additional info

MacOS crash report:

[report.txt](https://github.com/ihhub/fheroes2/files/13932883/report.txt)

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #8283

It's really an interesting bug. AI blinds the hypnotized unit during the turn of this very unit (this action is perfectly legal - maybe also stupid, but that's another question), like this:

https://github.com/ihhub/fheroes2/assets/32623900/9f6a8d5a-3c9e-43c9-855e-f9b3d3e77599

Since unit is now immovable, when AI tries to move this unit, one of the security assertions fail. Since the original game is also behaving incorrectly in this case:

https://github.com/ihhub/fheroes2/assets/32623900/e8c3f304-95e1-4d3c-a0d0-aa38bd53db86

I decided to mark such a unit as having completed a turn (although formally it did not perform any actions on its turn), and if the enemy hero then will use Dispel Magic on it on the current turn, then this unit will only act on the next turn:

https://github.com/ihhub/fheroes2/assets/32623900/9b1a6067-ccdb-4a96-b420-56eb706c4f21

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 

Since you're working on hypnotize spell logic, I would lke to share one curious case i found. :)

If you play against AI he can do one funny thing with your hero:

https://github.com/ihhub/fheroes2/assets/55348946/b59b7509-d3f3-4d81-a020-525b42dcfc42

This also works vs human player.


> AI blinds the hypnotized unit during the turn of this very unit (this action is perfectly legal - maybe also stupid, but that's another question)

Well, AI is definitely obsessed with blinding hypnotized troops:

https://github.com/ihhub/fheroes2/assets/55348946/01df4a33-3d4d-4e55-b798-2b84c6fcb038


The new logic you've applied within this PR works fine. 👍

**Comment by oleg-derevenetz** [comment]
> If you play against AI he can do one funny thing with your hero

Well, why not. This unit has not performed any actions yet and it is not immovable, so when you dispel the Hypnotize spell, control is transferred to the opposing player. This is at least more logical than fully operational "blinded" unit in OG, like shown in my video above.

> Well, AI is definitely obsessed with blinding hypnotized troops

Please note that this PR doesn't fix the AI decisions, it just fixes the "hole" in the general game logic related to the operation of hypnotized units.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

>Well, why not. This unit has not performed any actions yet and it is not immovable, so when you dispel the Hypnotize spell, control is transferred to the opposing player. This is at least more logical than blinded, but nevertheless fully operational unit in OG, like shown in my video above.

So you find it acceptable, that AI retreated by **my hero**, making me lose those 50 vampires into nowhere, don't you? 😆 

>Please note that this PR doesn't fix the AI decisions, it just fixes the "hole" in the general game logic related to the operation of hypnotized units.

I know, I know. :)
Maybe I should open a separate thread for this issue? And maybe for the first one where my own hero cowardly ran away? :D

**Comment by oleg-derevenetz** [comment]
> And maybe for the first one where my own hero cowardly ran away? :D

No, I suppose it's because Arena's currently active color is not updated properly after dispel. I'll take a look tomorrow, it fits into the scope of this PR, because it's related to the core game logic.

What about AI love of blinding hypnotized troops, this may be addressed someday separately, since it's just another potential AI improvement, and AI can be improved forever.

**Comment by oleg-derevenetz** [comment]
The problem with controlling the wrong hero after applying Dispel on the hypnotized unit should also be fixed.

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for these fixes!

**Pull request merged**
