### PR TITLE
Implement the "faster monster of opposite army goes first" logic in the battle mode

### LINKED ISSUE #395: Incorrect turns of monsters in the battle
We do not have "faster monster of opposite army goes first" logic in the game. For example, in this battle:
image

Wolves go first, then 5 elves have their turns. Next we use Trolls turn and by logic Elves should go next as they have the same speed as Wolves but instead Wolves have the first turn again, which is wrong in comparison with the original game's logic.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #395

As usual: needs to be thoroughly tested in different situations, with AI and human-controlled players, with and without soft wait option (with and without reverse wait order), with and without "show army order option" and so on.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Also fixed older issue (wasn't able to find it in Issues): when hero cast any spell while a unit that previously soft-skipped a turn is active, this unit immediately skips the turn and is added to the turn queue again

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test these changes?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I just noticed (while watching Twitch stream on HoMM3, hehe) that the turn order of units after wait in my PR isn't quite the same as in HoMM3. Suppose we have 3 units with the same speed on the same side - 1, 2 and 3 (from top to bottom). If we press "wait" button for all of them, then in HoMM3 order will be 1-2-3, while here order will be 3-2-1 (reverse order as for units with different speed). I really don't know how is better, and whether should we replicate HoMM3 behavior here. Personally, I think the reverse order is more logical.

**Review by idshibanov — APPROVED** [review]
Tested changes myself, so far looks good to me.

> I really don't know how is better, and whether should we replicate HoMM3 behavior here. Personally, I think the reverse order is more logical.

I agree that reverse order is much better in this case.

**Comment by ihhub** [comment]
> Hi @ihhub I just noticed (while watching Twitch stream on HoMM3, hehe) that the turn order of units after wait in my PR isn't quite the same as in HoMM3. Suppose we have 3 units with the same speed on the same side - 1, 2 and 3 (from top to bottom). If we press "wait" button for all of them, then (after the turn returns to the units in waiting) in HoMM3 order will be 1-2-3, while here order will be 3-2-1 (reverse order as for units with different speed). I really don't know how is better, and whether should we replicate HoMM3 behavior here. Personally, I think the reverse order is more logical.

Hi @oleg-derevenetz , we do not need to replicate H3 for this and logically we should do in in reverse order.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
I know, this could be a not related issue...
Waited troops never get their positive morale triggered. While negative morale could be triggered for waited troop. Is this behaviour intended?
I'm just curious about troops with triggered morale: in HoMM3 such troop always (after waiting) is always goes in front of the queue. No matter what speed he has. Shall we implement any rule for such scenario?
Also, "Wait" button is always active... I'm always confused whether my troop has waited already or not. :) Was it generated by our engine, btw?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> Waited troops never get their positive morale triggered. While negative morale could be triggered for waited troop. Is this behaviour intended?

I don't know, I (almost) didn't touch movement logic of particular troop, just the logic related to movement order. But yes, according to what I see in the code, troop after waiting can't currently get a positive morale.

> I'm just curious about troops with triggered morale: in HoMM3 such troop always (after waiting) is always goes in front of the queue. No matter what speed he has. Shall we implement any rule for such scenario?

I think it's possible to trigger a positive morale for troop after waiting, but I would prefer to do it as a separate PR after merging of this one.

> Also, "Wait" button is always active... I'm always confused whether my troop has waited already or not. :)

Yes, for some reason it was done this way: it works as "wait" if troop makes his move for the first time, and as "skip" if troop has already waited.

> Was it generated by our engine, btw?

I don't know :)

**Comment by oleg-derevenetz** [comment]
@Branikolog

> I'm just curious about troops with triggered morale: in HoMM3 such troop always (after waiting) is always goes in front of the queue. No matter what speed he has. Shall we implement any rule for such scenario?

At the time it's only unit speed (with modifiers like Haste and Slow spells) is taken into account. Morale doesn't affect unit speed and doesn't affect its position in waiting queue. May be later :)

**Comment by Branikolog** [comment]
@oleg-derevenetz 
No problem!
I just made my post to make us both keep in memory this issue with morale. So we can return to it after merging of current. ;)

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for fixing this logic!

**Pull request merged**
