### PR TITLE
Implement Cross army drag split

### PR DESCRIPTION
**Pull request by eos428**
Solves #2389. Also #2682 because turns out it shouldn't be much work to do (logic for this is done in LeftMouseSingleClick()

A bit wary on the cross army drag split fix/feature since I'm editing a base interface.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this change?

**Comment by Branikolog** [comment]
Hello, @eos428 
I've found a few issues. Could you, please, take a look?

1) I've selected genies, pressed shift and tried to split them to the nearest slot. Genies moved. 
image
image
Here we should have standart split dialog (the same logic if we selected genies and the pressed right click over empty slot):
image
image
Note, that splitting with shift button doesn't work also in hero meeting screen and kingdom view window.
But it works well while splitting between hero and castle garrison.

2) I'm trying to split stack of genies over the nearest using Shift button. 
image
But game just splitted second stack with 2 genies into two (1+1)
image
Here standart split-over-the-same-type dialog should appear (the same logic when we select troop and then right click over the same type stack):
image
image
Note, that splitting with shift button doesn't work also in hero meeting screen and kingdom view window.
But it works well while splitting between hero and castle garrison.

In a case we select genies and try to split them over not the same type stack (ex. peasants) with shift button pressed - the selection should be cancelled. Currently it works well only while splitting between armies (heroVSgarrison or heroVShero)

3) The opposite happened to right click splitting logic.
Now I cannot split a stack of genies over any empty slot in castle garrison.
image
Note that right click splitting also doesn't work in hero meeting screen (while splitting between heroes).
It works well only within single army.

4) Drag and drop doesn't work when we're trying to split one creature over another:
image
Here standart dialog split-over-the-same-type should appear (the same logic when we select troop and then right click over the same type stack):
image
Note that the issue happens everywhere: within single army, in hero meeting screen and in kingdom overview window.

5) When we select any troop and then press Alt button and try to unite creatures in meeting army (between heroes or between hero and castle garrison) game doesn't consider button and act like nothing was pressed:
Here we select genies, press Alt button and then press one of the genies in castle garrison.
image
image
In this case game should cancel selection and unite two upper genies:
image
Note, that within single army it works well.

**Comment by eos428** [comment]
Hi @Branikolog , can you test again the latest changes? All issues you pointed out should be fixed, but I would say a few of them would be more like tweaks instead of fixes ;)

**Comment by Branikolog** [comment]
Hello, @eos428 
Almost everything was fixed.
But...
1) I still cannot drag and drop creatures over-the-same-type between armies (heroVShero and heroVSgarrison)

2) The selection of a troop does not cancel while right clicking on the other type of creatures in cross army cases (garrisonVShero and heroVShero).
Example:
We select Genies and try to do right click over Titans.
image
On a first click nothing happens, but selection is still on. When we try to press right click again - the selection cancels.
Also in this case after the first right click on Titans we can make any other click everywhere (I mean in army window) but this just proceeds with cancelling of Genies' selection.
We should cancel the selection of Genies by the first right click.

3) Also we have not optimal logic for pressing Ctrl and Alt buttons while one troop was selected.
Example:
Here we select Genies and press Alt or Ctrl on one of garrison stacks of Genies.
image
image
Everything works fine.
But, when we have Phoenixes selected - left click over Genies (Holding Ctrl or Alt) causes swapping of creatures.
image
image
In this case we should proceed an action:
(on pressing Alt) - If there are some same-type stacks of creatures they should be united on left-clicking with Alt or the selection should be cancelled in a case there's the only creature of that type in garrison (or meeting hero).
(on pressing Ctrl) - The selection should be cancelled and 1 creature should be detached out of a stack we're left-clicking at.
Note that this logic should work both cross-armies and within single army.

**Comment by eos428** [comment]
Hi @Branikolog, I've just pushed another set of fixes and tweaks based on your latest feedback.

Here's the current logic applied when clicking on a different troop type (doesn't matter whether in the same or different army)
- Shift -> resets troop selection and nothing happens, since we'd count this as an attempt to split to a different troop type
- Ctrl and Alt -> target troop with split or unite depending on which hotkey pressed, also resets troop selection even if those operations actually can't be performed (too few troops, no different stack to unite with)
- Just the LMB click -> Swap the two troops

Let me know if there's anything missing or bugged as of the latest commit :)

**Comment by Branikolog** [comment]
@eos428 
Now, everything I mentioned above is fixed!

I have only one little addition:
Currently, we can drag-and-drop 1 creature: it simply changes it place. But we cannot move it over the stack of the same type. I think we should add that 1 creature to the stack we're dropping it over.
Example:
image
Here we should be able to drag and drop 1 Bone Dragon over the another stack (Without any dialog being appeared)
image
Note, that it should work in cross-army dragging and within single army.

**Comment by eos428** [comment]
Done :)

**Comment by Branikolog** [comment]
@eos428 
Now everything seem to work well! Nice work!

**Comment by ihhub** [comment]
@eos428 , thanks a lot for implementing these new features!

**Pull request merged**
