### PR TITLE
Bulgarian Translation Update 10

### PR DESCRIPTION
**Pull request by Effektus**
66% translated

### CODE REVIEW

**Comment by zenseii** [comment]
Hi, @Effektus.

Please request a review once this PR is ready.

**Comment by Effektus** [comment]
> Hi, @Effektus.
> 
> Please request a review once this PR is ready.



> Hi, @Effektus.
> 
> Please request a review once this PR is ready.

I'm sorry, but I can't find where it was made

**Comment by zenseii** [comment]
> > Hi, @Effektus.
> > Please request a review once this PR is ready.
> 
> > Hi, @Effektus.
> > Please request a review once this PR is ready.
> 
> I'm sorry, but I can't find where it was made

It should be here:
image

Anyways if that doesn't work then just write a message.

**Comment by Effektus** [comment]
It is not there

**Comment by zenseii** [comment]
> It is not there 

Ah, I see. Then that means that only collaborators have access to it. Anyways as I said you can just write a comment here when it's ready.

**Comment by Effektus** [comment]
> > It is not there 
> 
> Ah, I see. Then that means that only collaborators have access to it. Anyways as I said you can just write a comment here when it's ready.

My previous message is not enough?

**Comment by zenseii** [comment]
> > > It is not there
> > 
> > 
> > Ah, I see. Then that means that only collaborators have access to it. Anyways as I said you can just write a comment here when it's ready.
> 
> My previous message is not enough?

I see. I hope you can understand that I want to avoid starting to review and then have an update come to things I've already spent time reviewing.

I'll try to have a review up soon.

**Review by zenseii — COMMENTED** [review]
Hi @Effektus,
I left a minor comment here. If it's wrong then just disregard it.

**Comment by Effektus** [comment]
> Hi @Effektus,
> I left a minor comment here. If it's wrong then just disregard it.

What happened with this PR. Have we problem or not?

**Comment by zenseii** [comment]
> > Hi @Effektus,
> > I left a minor comment here. If it's wrong then just disregard it.
> 
> What happened with this PR. Have we problem or not?

Hi @Effektus.

There is no way for me to know that you are done making commits or just taking a break before adding more fixes. I hope this is reasonable to you. I will come back to you with a review shortly. I kindly ask you to leave me some kind of clue that you want a review of your additions next time and then I will do my best to review it earlier 👍

**Review by zenseii — APPROVED** [review]

**Comment by ihhub** [comment]
@Effektus , great work on the translation!

**Comment by Effektus** [comment]
image

**Comment by Effektus** [comment]
> image

Why?

**Comment by zenseii** [comment]
> Why?

Hi @Effektus,

This has a relatively simple explanation and solution, luckily. Basically what you should do when your PR has been merged is to delete the branch you have of that PR, in this case `Effektus:effektusBG`, and when you want to start working towards making a new PR you create a new Branch based off of your `Master`.

This explains why for example in this PR it shows that you have made 30+ commits even if the only change you made since your last PR got merged from that branch was make one commit with changes to the bg.po.
This is what I am referring to:

image

In other words the steps you should take are:
1. Make a new branch that is based on master - This branch will every update of your bg.po file up to the changes in this PR
2. Commit any new changes to your bg.po file there. 
- To bring changes from one branch to another you can just copy the bg.po file and paste it over as soon as you've switched branches with github desktop, if you are using that program.
4. Make a new PR from the new branch.
5. Effektus::effektusBG should be possible to remove.
6. When this new PR has been merged you should delete it. There is a button to do that on the bottom of every merged PR for this very reason to simplify this process.

**Comment by Effektus** [comment]
Ok now y will delete old branches

**Pull request merged**
