### PR TITLE
Fix the retaliation of archers attacked by an ally under the influence of Berserker or Hypnotize spells, improve the AI usage of Hypnotize spell in general

### LINKED ISSUE #8339: Ranged units attacked by a berserk ally in melee respond by shooting
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When under the effects of Berserk, an enemy unit will attack its nearest available target, prompting a retaliation when possible.  I've observed that when the nearest available target is a _ranged_ unit, the retaliation is, quite oddly, a ranged retaliation.  This includes the unusual use of the ranged-attack animation for the retaliating unit, but also (per a spot check on damage numbers) full ranged damage without melee penalty!

Here is an instance in action: https://clips.twitch.tv/FilthyPricklyPterodactylDxCat-3gP4Bn_UhnlI-JpQ

Ranged units attacked by "friendly" Berserk troops should never retaliate with their ranged attacks.  Retaliations can only occur when making melee attacks of distance 1, and a ranged unit must act accordingly.

### Save file

N/A

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #8339

https://github.com/ihhub/fheroes2/assets/32623900/8588d4e2-7a30-4da9-9ac1-76c2424ae453

Also this PR improves the logic of using the Hypnotize spell by AI in general:

https://github.com/ihhub/fheroes2/assets/32623900/d1001694-9df9-464a-8869-497d49b739a9

There is no more inappropriate behavior like [blinding hypnotized troops](https://github.com/ihhub/fheroes2/pull/8284#issuecomment-1899455117), etc.

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , as far as I know @Branikolog is busy till weekends. I believe he should test this pull request before merge as he is a vivid battle AI tester :)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub

> I believe he should test this pull request before merge as he is a vivid battle AI tester :)

Well, there's no hurry so far. AFAIK there is more than a week left until the next milestone.

**Review by Branikolog — APPROVED** [review]
Great work, @oleg-derevenetz !
Thanks for fixing this.

**Comment by ihhub** [comment]
@oleg-derevenetz , many thanks for these improvements!

**Pull request merged**
