### PR TITLE
Generate correct letters for French language

### PR DESCRIPTION
**Pull request by ihhub**
For non-French copies of the game.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, as a member of French community could you please verify the changes of this pull request? You need to check that the non-French version of the game has almost identical letters to which the GoG French version has. I made some small corrections for letter generations as the original images had some defects.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, as a member of French community could you please verify the changes of this pull request? You need to check that the non-French version of the game has almost identical letters to which the GoG French version has. I made some small corrections for letter generations as the original images had some defects.

I don't have the French GoG version.
I only have the English GoG version, but I use it more for testing.
I use the English Gold version 2.1 and the English standard version 1.3.
I also have the standard French version and Deluxe French version (which corresponds to the English Gold version), but these versions are not installed on my system and there is a problem to install them on a 64-bits system with the original installer (I use Windows 7 64-bits).
Only the French scenario editor can be launched without installation (when the .exe file is put in the English game folder).
The English versions have the most recent patches which have not been adapted for the French Deluxe version which has remained in version 2.0.
I will look for the French GoG version.
Otherwise, I will be able to look if it is in an understandable French from the English version of fheroes2 with the setting for the French language.
But I will see that tomorrow, as I stop for today. :D

**Comment by zenseii** [comment]
> Hello @ihhub,
> 
> > Hi @LeHerosInconnu, as a member of French community could you please verify the changes of this pull request? You need to check that the non-French version of the game has almost identical letters to which the GoG French version has. I made some small corrections for letter generations as the original images had some defects.
> 
> I don't have the French GoG version. I only have the English GoG version, but I use it more for testing. I use the English Gold version 2.1 and the English standard version 1.3. I also have the standard French version and Deluxe French version (which corresponds to the English Gold version), but these versions are not installed on my system and there is a problem to install them on a 64-bits system with the original installer (I use Windows 7 64-bits). Only the French scenario editor can be launched without installation (when the .exe file is put in the English game folder). The English versions have the most recent patches which have not been adapted for the French Deluxe version which has remained in version 2.0. I will look for the French GoG version. Otherwise, I will be able to look if it is in an understandable French from the English version of fheroes2 with the setting for the French language. But I will see that tomorrow, as I stop for today. :D

Do you not just have to choose French language in the English gog version in game settings?

**Comment by LeHerosInconnu** [comment]
Well, I have already spotted some problems that I will report tomorrow. :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub and @zenseii,

> I will look for the French GoG version.
> Otherwise, I will be able to look if it is in an understandable French from the English version of fheroes2 with the setting for the French language.

> @LeHerosInconnu
> 
> Do you not just have to choose French language in the main menu settings? I think it doesn't matter if you're using English gog version or something else. The French version is only needed for the various buttons to be in French, while this is about the normal text.
> 
> Also the French language used in fheroes2 will be the same no matter what Heroes 2 version you used for the resources since it uses the translation made for fheroes2 in any case.

So I looked for the French GoG version.
The DosBox installation of GoG offers a French installation but the game is in English after the installation.
The installation of the Windows version of GoG does not propose the installation in French.

> Well, I have already spotted some problems that I will report tomorrow. :)

So, here are the problems I noticed.

The letter "é" in "Résolution" and "Expérimental".
The word "Language" should be "Langage".
The word "Experimental" should be "Expérimentaux".
All words certainly not translated.
French translation 001

In the scenario description text, the period "." at the end of the sentence has been replaced by a "ï".
French translation 003

Problem with "Random".
French translation 008

The word "Connaissance" is too long.
French translation 009

The "ä" should be "â" in the word "Dégâts" with the small font.
French translation 015

The "ä" should be "â" in the word "dégâts" with the small font, it's correct with the big font.
There is a horizontal bar "_" at the top with the "%" character.
French translation 017

The word "Plusieurs" is too long.
(It would be better to use the corresponding numbers "5-9".) :D
French translation 018

Apart from that, there are still texts in English, errors with masculine and feminine forms, articles "le", "la" not accorded with the noun, etc.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , this pull request doesn't touch any aspects on French translation. It only adds missing letters to be used in French translation. I'll take a look at some problematic places with incorrect letters.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , this pull request doesn't touch any aspects on French translation. It only adds missing letters to be used in French translation. I'll take a look at some problematic places with incorrect letters.

Yes, I know, it was just for information, I understood that only the letters problems were related to this issue. :)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I've fixed small â letter in generated font. Could you please put all your findings into a separate issue related to French language? All of them are reproducible with French GoG version as well.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , I've fixed small â letter in generated font. Could you please put all your findings into a separate issue related to French language? All of them are reproducible with French GoG version as well.

Okay, tomorrow I will open a specific issue (only one issue is better?) to the French language with all the reported problems not concerning the display of letters.

**Comment by zenseii** [comment]
> Hello @ihhub,
> 
> > Hi @LeHerosInconnu , I've fixed small â letter in generated font. Could you please put all your findings into a separate issue related to French language? All of them are reproducible with French GoG version as well.
> 
> Okay, tomorrow I will open a specific issue (only one issue is better?) to the French language with all the reported problems not concerning the display of letters.
> 
> **Edit.**
> 
> Also (for other problems, for example, spelling mistakes and gender accords), is it possible to edit directly the "fr.mo" file, with Notepad++ for example, for the correction of the mistakes? It would be simpler and faster than to report all the mistakes found. :)

To edit the language you have to edit the fr.po file you can find in this repository in the files/lang folder. You can edit with notepad++ but the recommended way is with a program called poedit which makes the editing process a lot more tidy. Editing the fr.mo, while possible, makes no sense since it isn't part of the source files but is compiled when fheroes2 is built.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub and @zenseii,

> > > Hi @LeHerosInconnu , I've fixed small â letter in generated font. Could you please put all your findings into a separate issue related to French language? All of them are reproducible with French GoG version as well.
> > 
> > 
> > Okay, tomorrow I will open a specific issue (only one issue is better?) to the French language with all the reported problems not concerning the display of letters.

Done here: https://github.com/ihhub/fheroes2/issues/4797.

> > **Edit.**
> >
> > Also (for other problems, for example, spelling mistakes and gender accords), is it possible to edit directly the "fr.mo" file, with Notepad++ for example, for the correction of the mistakes? It would be simpler and faster than to report all the mistakes found. :)
> 
> To edit the language you have to edit the fr.po file you can find in this repository in the files/lang folder. You can edit with notepad++ but the recommended way is with a program called poedit which makes the editing process a lot more tidy. Editing the fr.mo, while possible, makes no sense since it isn't part of the source files but is compiled when fheroes2 is built.

Okay thanks, I'll take a look at Poedit for the couple of problems I noticed. :)

**Pull request merged**
