### PR TITLE
Add confirmation message in Alchemist Tower

### LINKED ISSUE #1479: Adventure map, Alchemist's Tower, add a confirmation window to the Alchemist's Tower
Add a confirmation window to the Alchemist's Tower to indicate to the player that the Cursed Artifacts have been removed.

### PR DESCRIPTION
**Pull request by ihhub**
close #1479

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu  and @Branikolog , are you okay with this message? :)

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu and @Branikolog , are you okay with this message? :)

Nice to have added a sound when the operation is done. :)
I think that the text should be adapted when there are only one and several artifacts.
I would write this:

"After you consent to pay the requested amount of gold, the alchemist grabs the cursed artifact and throws it into his magical cauldron."

"After you consent to pay the requested amount of gold, the alchemist grabs all cursed artifacts and throws them into his magical cauldron."

Also the claim text should be adapted according to the number of artifacts:

"...1 cursed item.
For 750 gold, the alchimist will remove it for you. Do..."

"...3 cursed items.
For 750 gold, the alchimist will remove them for you. Do..."

In fheroes2:

Alchemist tower pay 002

Alchemist tower pay 001

Alchemist tower pay 003

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I've updated the message to have plural and non-plural forms. The sound should be played as for Good Luck event.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , I've updated the message to have plural and non-plural forms. The sound should be played as for Good Luck event.

Is it normal that you have not changed the beginning and the end of the text, and not adapted the plural and non-plural forms of the text in the claim window?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , doesn't it work for you? It should work.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , doesn't it work for you? It should work.

My concern was about these proposals:

> I would write this:
> 
> "After you consent to pay the requested amount of gold, the alchemist grabs the cursed artifact and throws it into his magical cauldron."
> 
> "After you consent to pay the requested amount of gold, the alchemist grabs all cursed artifacts and throws them into his magical cauldron."
> 
> Also the claim text should be adapted according to the number of artifacts:
> 
> "...1 cursed item. For 750 gold, the alchimist will remove it for you. Do..."
> 
> "...3 cursed items. For 750 gold, the alchimist will remove them for you. Do..."

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , done. Please check again.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> Hi @LeHerosInconnu , done. Please check again.

The letter "t" is missing at the end of the word alchemist for singular and plural sentences.

In fheroes2:

Alchemist text 001
Alchemist text 002

Do you really want to use the word "pot" instead of "cauldron"?

Write the words in this online translator: https://www.deepl.com/translator.

Here is the sentence that is proposed by default with the word "pot":
She put the flowers in a pretty pot.

The word is also used for herbs that make you laugh:
Smoking pot is legal in certain countries.

Here is the sentence that is proposed by default with the word "cauldron":
The witch stirred the potion in the cauldron.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , I added the letter and changed the pot to cauldron.

**Pull request merged**
