### PR TITLE
Implement town and castle placing in the Editor

### PR DESCRIPTION
**Pull request by Districh-ru**
изображение

https://github.com/ihhub/fheroes2/assets/113276641/6686551e-669f-4a94-b9bb-6d9f239480b5

### CODE REVIEW

**Comment by Districh-ru** [comment]
> @Districh-ru would it be possible to increase the height of the window or atleast more space between the castle and the race name. If a translation of the sorceress need to be split into two lines, then it would be over the castles tower and would not look very nice.

Hi, @Mr-Bajs.
Of course I'll increase the height of the dialog. Thanks for noticing this!

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @Branikolog , please review this pull request as the highest priority.

@Districh-ru , I'm done with changes in this pull request. Please take a look at them and correct the code if it is necessary.

**Comment by Districh-ru** [comment]
> @Districh-ru , I'm done with changes in this pull request. Please take a look at them and correct the code if it is necessary.

Hi, @ihhub, I reviewed the code. All is OK. Many thanks for help with this PR!
I also made some changes to fix some minor issues.

**Comment by Branikolog** [comment]
@ihhub 

Castles are shown not properly on the minimap. 
Castle minimap

Is this a bug or it was planned to be added later?

**Comment by ihhub** [comment]
> @ihhub
> 
> Castles are shown not properly on the minimap. Castle minimap
> 
> Is this a bug or it was planned to be added later?

Hi @Branikolog , this is going to be fixed later. Mini-map as well as right clicking on objects is partially broken due to missing information.

**Comment by ihhub** [comment]
Hi @Branikolog , all the issues have been addressed. Please note that the maps with saved castles are not suitable. Please create a new map for your tests.

**Comment by Branikolog** [comment]
@Districh-ru and @ihhub 
Thanks for fixing those issues.

The only tiny issue I've found is that frame of colour and class icons is not included into clickable area.
image

It's quite minor and could be fixed later, if you wish.

**Comment by Districh-ru** [comment]
> The only tiny issue I've found is that frame of colour and class icons is not included into clickable area. 

Hi, @Branikolog
I made the requested changes. Could you, please, check it.

**Review by Branikolog — APPROVED** [review]
Thanks for fixing this, @Districh-ru 
Now everything is OK.
Found out a small delay for frames to appear on my working PC, but I suppose we can fix it later.

https://github.com/ihhub/fheroes2/assets/55348946/978a852a-d6fa-4b42-8a9e-026a15e11f28

**Comment by ihhub** [comment]
Hi @Branikolog , lets focus on optimizations in a separate pull request.

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for these valuable changes!

**Pull request merged**
