### PR TITLE
Update the dependency package hash for Windows

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
See https://github.com/fheroes2/fheroes2-prebuilt-deps/pull/25 for details.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I suggest to freeze any library updates from now till 1.0 unless it's a critical update. We need to make sure that we test everything thoughtfully before this major release.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I usually do this just once a month. Previous update was rolled back due to that famous issue with music distortions, which was then fixed, and only yesterday I was able to finally push my [PR](https://github.com/microsoft/vcpkg/pull/28113) to get the fixed version in the VCPKG repo :) So this update was like delayed for a month. I do not plan to get another updates during this month :)

**Comment by ihhub** [comment]
@oleg-derevenetz , got it. Thank you for explanation!

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog since you was able to reproduce that [issue with sound](https://github.com/ihhub/fheroes2/issues/5984) very well, could you please confirm that is was **_really_** fixed and doesn't appear with the latest build anymore?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz .
Now during campaign video I don't hear any horrible sounds. 👌

**Pull request merged**
