### PR TITLE
[WiP] Better cache locality in image Copy()

### PR DESCRIPTION
**Pull request by a1exsh**
First copy the image layer part, then the transform part, if any.
I find that this way the code is also slightly easier to read.

### CODE REVIEW

**Comment by a1exsh** [comment]
This is purely theoretical, of course, I have not tried to use profiler to check if there is any difference, or, for that matter — improvement.

If someone has a profiling setup, esp. for low-end hardware, it'd be nice to test it. There are other places in image.cpp that could see the same treatment, if it turns out to be beneficial.

**Comment by felix642** [comment]
I haven't done any test either but looking at the code it is probably slower than what we already have. 

If we look at the new method we have to define a new variable transformInYEnd (which it not a big deal), but we have to iterate through the image twice instead of once. Which means that your method is probably slower than what we already have. 

I do not think it really changes the readability of the code (doesn't improve it nor worsen it from my point of view).

I'm sorry to say that but I do not think we should merge this pull request 😢 unless there's something I've missed? (And I would be really happy to know if so)

**Comment by ihhub** [comment]
Hi @a1exsh , theoretically it might benefit but I have doubts about this. As you mentioned we have to do the profiling. The application has an ability to display FPS counter. This is the best indicator for performance. The most critical place for performance is hero's movement on speed 9 which must give 120 FPS at maximum. The bigger resolution you set the slower application becomes. So you can test with fullHD resolution before and after your changes for hero's movement on exactly same file save.

**Comment by ihhub** [comment]
This change will only affect cases when a destination image is **not** single layer image. Display image is a single layer image. There are some cases when destination image is not single layer image. These cases can be divides into 2 groups:
- those which should be single layer image but we just forgot to mark them
- those which must remain double layer images

If we want to speed up some places without assumptions and relying on CPU cache (the size of CPU cache depends on CPUs as well) we might need to focus on the first group of images and just mark them single-layer images.

**Comment by a1exsh** [comment]
@ihhub good points, thank you.  I've tested it on 1920x1080 resolution and I see no performance difference: both versions give me ~100 FPS, which is probably expected, according to your explanation about single layer images.

So, I'd say this is just something to keep in mind if we come to a point where need to squeeze extra bit of performance. ;)

**Comment by a1exsh** [comment]
> but we have to iterate through the image twice instead of once. Which means that your method is probably slower than what we already have.

@felix642 well, we iterate through the first half once, and then once through the second half, so it's still the same number of iterations in total. ;)

**Comment by ihhub** [comment]
@a1exsh , let's for now make this pull request as WIP till we find places where these changes improve performance.

**Comment by ihhub** [comment]
Hi @a1exsh , shall we still keep this pull request or close it for now?

**Comment by a1exsh** [comment]
Let's close it — doesn't look like we have performance issues at the moment.

**Pull request closed without merging**
