### PR TITLE
Fix fog rendering horizontal offset. Adventure map.

### LINKED ISSUE #4255: Adventure map, default in the Fog of War (0.9.7 4208)
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is default in the Fog of War.

In fheroes2:

Default fog of war 01

### Save file

Here is the save file (AI instant combat bad 02.sav):
[AI instant combat bad choice.zip](https://github.com/ihhub/fheroes2/files/7229837/AI.instant.combat.bad.choice.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #4255

game

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hello @LeHerosInconnu.
Could you please check when you have time that the fog rendering issue is fixed.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @Branikolog , could you please retest all fog cases?

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this fix!

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hello @LeHerosInconnu. Could you please check when you have time that the fog rendering issue is fixed.

I tested, the defect is no longer present.

**Comment by Districh-ru** [comment]
> Hello @Districh-ru,
> I tested, the defect is no longer present.

Many thanks, @LeHerosInconnu !

**Pull request merged**
