### PR TITLE
Fix town passability for some cases

### LINKED ISSUE #3802: Evil Campaign 10 can't reach last castle
With #3756 I noticed that we can no longer reach the enemy's castle.

https://user-images.githubusercontent.com/60141446/124408782-fa19a080-dd14-11eb-9996-10cbc7276601.mp4

[passability.zip](https://github.com/ihhub/fheroes2/files/6761151/passability.zip)

### LINKED ISSUE #3814: Good_2 campaign passability bug
Upon starting the second scenario of the original good campaign, the hero is stuck in the castle.

It's possible to move to three three tiles outside of the castle shown here, but no further. Reproduces with all 3 possible starting castles.

image

Version 0.9.5.

### PR DESCRIPTION
**Pull request by ihhub**
close #3802
close #3814

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , could you please deeply test this change to make sure that we didn't introduce any problems?

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, could you please help us to test these changes as few people already faced some issues with passabilities with castles?

**Comment by ihhub** [comment]
I changed the way how we fix the original issue. First of all, we have to fix certain objects only like Tows and Castles. Secondly, we were doing som hacks for castle's area by reducing it. I removed this hack and now castle's area is exactly the same as in the original game.
Now we check a type of object whether it is attachable (I don't know how to name them properly). This is true for castles and Wagon Camp which fixes few issues found by @LeHerosInconnu in initial round of testings.

I made multiple checks and both issues with castles are fixed.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

I tested the passability of the castles in some scenarios of the original game. No problems encountered.
I noticed that some locations in front of the castle entrance had no square displayed and some locations had a green square displayed with only one red top corner, I don't know if this matters, just in case.
[Castle entrance 01.zip](https://github.com/ihhub/fheroes2/files/6780544/Castle.entrance.01.zip)

Here are the differences I've spotted with the scenario "Broken Alliance".
(One image from the original game with one image from fheroes2.)
[Passability differences 10.zip](https://github.com/ihhub/fheroes2/files/6780552/Passability.differences.10.zip)
[Passability differences 11.zip](https://github.com/ihhub/fheroes2/files/6780568/Passability.differences.11.zip)

**Comment by ihhub** [comment]
@LeHerosInconnu , thank you very much for your testings!

**Pull request merged**
