### PR TITLE
Remove old Rect, Point and Size classes

### PR DESCRIPTION
**Pull request by ihhub**
to allow to use proper types and fix a lot of compilation warnings.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @idshibanov ,

This pull request is made to complete our long term transition from old engine to new engine, which we initially introduced in **0.8.1** version. Old Rect, Size and Point classes were based on 16-bit values, causing a lot of compilation warnings. This was one of the reasons why we disable implicit type casting checks during compilation.
Since we remove the old classes we can freely use 32-bit computations everywhere, including `localevent` class.

Could you please review it as it's a huge one and I might missed something or overdid?

**Review by idshibanov — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]
LGTM. Just curious - is it worth to move such base classes like Point, Size and Rect to separate namespace and add `fheroes2::` everywhere?

**Comment by ihhub** [comment]
> LGTM. Just curious - is it worth to move such base classes like Point, Size and Rect to separate namespace and add `fheroes2::` everywhere?

That's what we have right now. Old classes were outside any namespace while new Point, Size and Rect classes within fheroes2 namespace. They both existed before.

**Comment by oleg-derevenetz** [comment]
> That's what we have right now. Old classes were outside any namespace while new Point, Size and Rect classes are within fheroes2 namespace. They both existed before.

I mean, is it justified? Why not move new classes to global namespace instead of adding `fheroes2::` everywhere? It's not a library after all that should co-exist with another unknown libraries that may have symbols with popular names like Point or Rect :)

**Comment by ihhub** [comment]
> 
> 
> > That's what we have right now. Old classes were outside any namespace while new Point, Size and Rect classes are within fheroes2 namespace. They both existed before.
> 
> I mean, is it justified? Why not move new classes to global namespace instead of adding `fheroes2::` everywhere? It's not a library after all that should co-exist with another unknown libraries that may also have symbols with popular names like Point or Rect :)

We already had a lot of places using `fheroes2` namespace so it was easier to just add namespace to the rest of places.

**Pull request merged**
