### PR TITLE
Add code to modify Spell Scroll artifact

### PR DESCRIPTION
**Pull request by ihhub**
relates to #6845

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @ihhub !
Scroll editing works nice.
But all random spell scrolls appear as "Set Water Guardian" on the adventure map.

**Comment by ihhub** [comment]
Hi @Branikolog , was it the same before my changes?

**Comment by Branikolog** [comment]
@ihhub 
Yeah. All random scrolls behaved like that on several previous builds I've checked.

**Comment by ihhub** [comment]
@Branikolog , we will fix this issue outside this pull request. Let's focus on what was changed here.

**Review by Districh-ru — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]

**Pull request merged**
