### PR TITLE
Speed up getting a list of files on PS Vita

### LINKED ISSUE #9309: Openning New Game menu lags on PS Vita
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

PlayStation Vita

### Describe the bug

This issue is from Discord channel from **Pønytail**.
He has reported that in v. 1.1.3 and 1.1.4 there is about 40 seconds hang when opening the New Game menu and about 2.5 minutes lag to open Standard Game menu. It happens on the first time menu open and there is no lag until the game is restarted.
He has 1199 maps in maps folder.
In v. 1.1.2 and earlier it takes almost no time to open the New Game menu and about 20 seconds to open Standard Game menu.

The original issue description in Russian:
    "Пока что из замеченного, при нажатии на "новую игру" приложение всё так же зависает примерно на 40 секунд, после чего нажатие на эту кнопку становится адекватным до следующего перезапуска приложения. Такое поведение тоже началось с версии 1.1.3."
    "Всего у меня 1199 карт, на версии 1.1.2 отклик на нажатие кнопки "новая игра" в меню моментальная, при выборе "обычная игра" отклик примерно 20 секунд. На последних версиях отклик "новой игры" порядка 40 секунд, "обычной игры" 2.5 минуты. Т.е. скорость реакции приложения стала явно меньше. Заранее спасибо за работу!"

### Save file

No save file, just put more than 1000 maps in maps folder and open the New Game and Custom Game menus.

### Additional info

On Vita3K emulator with old CPU backend (Unicorn, without optimizations) and about 1500 maps it takes about 2 seconds to open Standard Game on v.1.1.2 and about 3 seconds on v.1.1.4, latest build. And on v.1.1.4 there is a noticeable lag (about 0.5 seconds) when opening New Game menu.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #9309

* Don't try to find the actual case-sensitive path using its case-insensitive variant;
* Use the native filesystem API to get the list of files in a directory instead of `std::filesystem::directory_iterator`;
* Place the fheroes2 version info into the `param.sfo`;
* Optimize the `ListFiles::FindFileInDir()`.

### CODE REVIEW

**Comment by Districh-ru** [comment]
The last commits show New Game menu load speed-up: about 560 ms on Vita3K emulator. It is faster than master build (~850 ms), but a little slower than v.1.1.2 (~350 ms).

**Comment by oleg-derevenetz** [comment]
> The last commits show New Game menu load speed-up: about 560 ms on Vita3K emulator. It is faster than master build (~850 ms), but a little slower than v.1.1.2 (~350 ms).

Well, we also can make a "special case" for `System::IsFile()` and `System::isDirectory()`, but originally on PS Vita they didn't verify that the given name is really a file or a directory, they only verified that the file with the given name exists. Now it is all verified.

**Comment by Districh-ru** [comment]
I've asked **Pønytail** on Discord to test the new build when he have time. I've added the load time estimation to the New Game menu:
```cpp
    fheroes2::Time counter;
    counter.reset();
    
    // Code to estimate execution time.

    const double timeMs = counter.getS() * 1000;
    fheroes2::showStandardTextMessage( "Time for menu", std::to_string( timeMs ) + " ms.", Dialog::OK );
 ```
 
 Lets check the real hardware. If the load time of New Game is normal (less then a couple of seconds) then it is better to keep file verification in cost of some commutation time.

**Comment by Districh-ru** [comment]
The https://github.com/ihhub/fheroes2/pull/9310/commits/99e4c1edcd078eb881fa22e53381bf2a336cd731 commit has no affect on menu load speed on Vita3K emulator.

**Comment by oleg-derevenetz** [comment]
> The https://github.com/ihhub/fheroes2/commit/99e4c1edcd078eb881fa22e53381bf2a336cd731 commit has almost no affect on menu load speed on Vita3K emulator. It is about 560 ms.

Well, if it doesn't give anything on a real device as well, it would be better to roll it back. The less "special" code, the better.

**Comment by Districh-ru** [comment]
> Well, if it doesn't give anything on a real device as well, it would be better to roll it back. The less "special" code, the better.

I've asked Pønytail to test this change as well. Let's wait for his response on Discord (most probably tomorrow).

**Comment by Districh-ru** [comment]
**Pønytail** reported that both versions (with https://github.com/ihhub/fheroes2/commit/99e4c1edcd078eb881fa22e53381bf2a336cd731 and without it) act the same and are close to v 1.1.2:
>Попробовал обе версии! Отклик "новой игры" 430мс, отклик "обычной игры" 56с. Результат аналогичный версии 1.1.2.

So we can revert the last commit since it has no benefits.

Also to properly show version number in PS Vita I recommend to update the **Makefile.vita**.
Add after line 31:
`PROJECT_VERSION := $(file < version.txt)`
and update line 59:
`vita-mksfoex -s TITLE_ID="$(PROJECT_TITLEID)" -s APP_VER="$(PROJECT_VERSION)" "$(PROJECT_TITLE)" param.sfo`

изображение

Currently it is always 0.00
изображение

What do you think?

**Review by Districh-ru — APPROVED** [review]
Tested with Vita3K emulator - New Game menu load time is OK (~550 ms).

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , many thanks for this fix!

**Pull request merged**
