### PR TITLE
Tavern info updated

### LINKED ISSUE #188: Tavern information should show correct info about project
Open a castle with built tavern. Right now it show old information about the project:
Screenshot 2019-10-22 at 2 28 20 PM
We should display information about current project, not about the old one.

### PR DESCRIPTION
**Pull request by swarupe**
Fixes #188 Updated tavern information to the current repo URL.

Screenshot (39)

### CODE REVIEW

**Comment by andrey-starodubtsev** [comment]
@swarupe, could you please run

```
$ git diff HEAD~ -U0 --no-color | clang-format-diff -p1 | patch -p0
```

to conform with `clang-format` requirements?

**Comment by swarupe** [comment]
Tried that but still could not pass travis

**Comment by andrey-starodubtsev** [comment]
You did something very different cause your PR has more than 400 changed files now.

**Comment by swarupe** [comment]
I will redo it and raise PR

**Pull request closed without merging**
