### PR TITLE
Add a shortcut to go to the Main Menu from the Editor

### PR DESCRIPTION
**Pull request by ihhub**
relates to #6845

Hotkey as well as description are subject for discussion.

### CODE REVIEW

**Review by Districh-ru — APPROVED** [review]
In future we might want to add a hotkey to save map and start it as a new game (to test it without going through many menus and finding a map in a map list). And a hotkey to return back to this map edit (it it was started from editor). :)

**Comment by Stisen1** [comment]
EDITOR

- Hitting N opens dialog: "Are you sure you want to create a new map? (Any unsaved changes to the current map wil be lost.)" => hit YES and return to Editor Main Menu - New Map

- Hitting M opens dialog: "Do you want to open game's Main Menu? All unsaved changes will be lost." => Hit YES and return to the Game Main Menu. 

GAME

- Hitting N opens dialog: "Are you sure you want to restart? (Your current game will be lost)". => Hit YES and return to Game Main Menu - New Game

- Hitting M does nothing

SUGGESTIONS

- Have consistency in text strings that prompts the user of risking lost process (unsaved changes...)
- Create a hotkey inside GAME leading the user straight to EDITOR Main Menu instead of GAME Main Menu. With this logical mirroring of hotkey inputs, it will be faster to make changes to a custom map in EDITOR, try it out in GAME, then return to map editor to make further changes, and so on and so forth. It will make a convenient and motivating workflow to any user getting their hands on the EDITOR.

**Comment by ihhub** [comment]
Hi @Stisen1 , **M** on the Adventure Map is used to move a hero.

**Comment by Stisen1** [comment]
Sure. Then change the editor hotkey "M" into an available default hotkey
for adventure mode :-)

ons. 24. apr. 2024 02.55 skrev Ihar Hubchyk ***@***.***>:

**Review by Branikolog — APPROVED** [review]
Hotkey returning to main menu works nice!
I hope some day we have an option of returning to main menu from the game, instead of that inconvenient "New Game" action. Instead of the "New Game" it would be nice to have an instant restart...
By the way, freshly added dialog "Main Menu" has a fancy title, and I like it. Unfortunately, it's the only dialog that has a title. It would be nice to have something similar for others (load/save/new-map) and for in-game dialogs too...
I can also suggest to have personalized titles for each action, so player can see what action is going to be performed on confirmation (Instead of unified and uninformative "Editor"). Maybe this dialog could have "Main Menu" title, or "Return to Main Menu". Not sure about wording...

**Pull request merged**
