### PR TITLE
Fix musical effects for various objects, move auxiliary functions to the anonymous namespace

### LINKED ISSUE #6633: Witch hut sound issue
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Currently Witch Hut plays wrong sound while attending. It should be the same to current Gazebo sound.
Also, the sound shouldn't be played in a case hero has the skill or has no free space for a new skill.

### Save file

[Witch Hut.zip](https://github.com/ihhub/fheroes2/files/10732088/Witch.Hut.zip)

### Additional info

_No response_

### LINKED ISSUE #6634: Adventure map, Barrier sound is missing
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When a hero comes to a barrier the game plays the sound, same to the sound when visiting a tent in the original game.
In fheroes2 it's not the case.
Note, the sound plays only if player previously visited a proper tent. Without visiting a tent, no sound happens.

### Save file

[Tents.zip](https://github.com/ihhub/fheroes2/files/10733586/Tents.zip)

### Additional info

_No response_

### LINKED ISSUE #6637: Adventure map, trying to press spacebar standing on a lighthouse or moving on it causes music pause for a while.
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

While trying to visit lighthouse again I can hear a small pause during .ogg music playback.

https://user-images.githubusercontent.com/55348946/218782882-2be2be97-c74f-4523-9da7-edcddba2ecc7.mp4

(I hit spacebar multiple times here)

MIDI music doesn't have such issue.

### Save file

[Lighthouse.zip](https://github.com/ihhub/fheroes2/files/10734008/Lighthouse.zip)

### Additional info

_No response_

### LINKED ISSUE #6647: Adventure map, hut of the magi action sound is missing
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

magi hut

Currently, hut of the magi has no sound, while in the OG we can hear action sound while interacting with this object.
The sound should be the same to action sound of dwellings (Halfling hole or goblin hut etc).
In the OG we can hear the sound each time we visit this object, but I believe, it should be played only for the first time we visit this object, as revealing (focus on eyes) happens only for the first time.

### Save file

[Magi hut.zip](https://github.com/ihhub/fheroes2/files/10742124/Magi.hut.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #6633
fix #6634
fix #6637
fix #6647

Also I couldn't resist and did what I wanted for a long time - moved all auxiliary functions in `ai_hero_action.cpp` and `heroes_action.cpp` to the anonymous namespace.

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]
Great! Thanks for the fix, @oleg-derevenetz !
So nice, that you've also fixed the issue with barrier fading sound. I was going to create an issue for it too. :)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I fixed also the issue with Hut of the Magi sound here, but I implemented the OG behavior (sound is played each time when the object is visited), because I believe this sound is related to the dialog window, and this dialog window is shown regardless of whether the object has already been visited.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !

> I implemented the OG behavior

Okay. 👍 

Can I ask you to fix a few more sound issues I've found?

All Elementals Altars and Barrow Mounds should have action sound same to common dwelling (Halfling hole etc)
Alchemist's tower also has the same sound when you come with bad artifact. Interesting, but when you succeeded in removing artifacts, we can hear luck sound. While in the OG there plays nothing. How do you think, should we take this sound away?

Desert Tent has currently wrong sound. In the original game it's the same to hill fort upgrade sound.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog OK, I'll do this later today.

**Comment by oleg-derevenetz** [comment]
@Branikolog

> All Elementals Altars and Barrow Mounds should have action sound same to common dwelling (Halfling hole etc)

Should be fixed now.

> Alchemist's tower also has the same sound when you come with bad artifact.

Should be fixed now as well.

> Interesting, but when you succeeded in removing artifacts, we can hear luck sound. While in the OG there plays nothing. How do you think, should we take this sound away?

As far as I can see, OG doesn't show an additional dialog when cursed artifacts were removed, while fheroes2 shows it. Let it also be accompanied by sound.

> Desert Tent has currently wrong sound. In the original game it's the same to hill fort upgrade sound.

According to this comment:

https://github.com/ihhub/fheroes2/blob/99986ef5033060d9ddbf62960e526b369dab7018/src/fheroes2/agg/mus.cpp#L212-L215

this sound was deliberately changed.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I see another two recently opened sound-related issues, I have no plans to fix them in this PR - just in case :) They will need to be dealt with another time.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !

> 
> > All Elementals Altars and Barrow Mounds should have action sound same to common dwelling (Halfling hole etc)
> 
> Should be fixed now.
> 
> > Alchemist's tower also has the same sound when you come with bad artifact.
> 
> Should be fixed now as well.
> 

Well done!

> > Interesting, but when you succeeded in removing artifacts, we can hear luck sound. While in the OG there plays nothing. How do you think, should we take this sound away?
> 
> As far as I can see, OG doesn't show an additional dialog when cursed artifacts were removed, while fheroes2 shows it. Let it also be accompanied by sound.

Agreed!

> > Desert Tent has currently wrong sound. In the original game it's the same to hill fort upgrade sound.
> 
> According to this comment:
> 
> https://github.com/ihhub/fheroes2/blob/99986ef5033060d9ddbf62960e526b369dab7018/src/fheroes2/agg/mus.cpp#L212-L215
> 
> this sound was deliberately changed.

Oh yes! I forgot about that! Thanks for pointing me on this issue!


> Hi @Branikolog I see another two recently opened sound-related issues, I have no plans to fix them in this PR - just in case :) They will need to be dealt with another time.

Sure! That's why I haven't mentioned them here. :)

**Review by Branikolog — APPROVED** [review]
Many thanks for your help, @oleg-derevenetz ! :)

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for these fixes and the code cleanup!

**Pull request merged**
