### PR TITLE
Update Town Portal dialog

### PR DESCRIPTION
**Pull request by ihhub**
relates to #1184

special thanks to @ghostBot

Town Portal before:
image

Town Portal after:
image
image

@LeHerosInconnu could you please give your opinion as well?

### CODE REVIEW

**Comment by Branikolog** [comment]
@ihhub 
Looks much better. I like, that right clock is working over a castle!
I think we can add a little more space between castle icons and names... Not mush. Something like 3-5 pixels.
Also, it would be nice to make list larger, so one more castle would be seen in this list at the same time.

**Comment by ihhub** [comment]
> @ihhub
> Looks much better. I like, that right clock is working over a castle!
> I think we can add a little more space between castle icons and names... Not mush. Something like 3-5 pixels.
> Also, it would be nice to make list larger, so one more castle would be seen in this list at the same time.

Hi @Branikolog , I've updated the position of the text. Please refer to the first post for screenshots.

**Comment by ihhub** [comment]
This is the look of Town Portal in the original game which is around 280 by 250 pixels:
image

Our current window is 310 by 230 pixels.

**Comment by Branikolog** [comment]
I think it's a good step of improving UI of this spell.
Actually, I don't like too bright background of the list (Hard to read names with such non-contrasting font and background) but i don't sure if we can do something with its color not to make it unnatural for the whole interface.

**Comment by ihhub** [comment]
> I think it's a good step of improving UI of this spell.
> Actually, I don't like too bright background of the list (Hard to read names with such non-contrasting font and background) but i don't sure if we can do something with its color not to make it unnatural for the whole interface.

We could stick to this UI (proposed in this PR) design for now if everyone agrees.

**Comment by LeHerosInconnu** [comment]
@ihhub.

> @LeHerosInconnu could you please give your opinion as well?

I suggest adding a frame around the city sprites and leaving a space around the frames, as is the case for the list of city sprites in the adventure map screen.

Castle sprite list fh2 01

Suggestions for use:
- in the list, mark the cities that are already occupied by another hero.
- when the user positions the mouse cursor over a city in the list, add an additional crosshair on the minimap to indicate the position of the city.

**Comment by idshibanov** [comment]
> in the list, mark the cities that are already occupied by a hero.

These shouldn't be displayed in the list in the first place.

Otherwise I think with frames and position fixed it will be a very nice addition to the game!

**Comment by Branikolog** [comment]
I agree with the statement, that occupied city should be in this list, but with special mark. 
As I always getting confused, while searching needed city in "Town Portal" list, which is occupied and not shown at all. (As well as current city occupied by current hero)

**Comment by LeHerosInconnu** [comment]
Yes, Branikolog, just as I was writing it. :)
The player may have forgotten to remove one of his heroes before using the spell and he will search in the list for the city where he wants to send his hero but can't find it because it is not displayed.

**Comment by Branikolog** [comment]
> I suggest adding a frame around the city sprites and leaving a space around the frames, as is the case for the list of city sprites in the adventure map screen.

On the other hand this will cause list increase it's height. Also names of the cities will be shown with the large gaps, which will look not so good...

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> > I suggest adding a frame around the city sprites and leaving a space around the frames, as is the case for the list of city sprites in the adventure map screen.
> 
> On the other hand this will cause list increase it's height. Also names of the cities will be shown with the large gaps, which will look not so good...

Yes, but the aesthetic aspect is also important and must be taken into consideration, and the player is used to seeing the city sprites displayed this way, which reinforces the consistency aspect of the interface.

**Comment by LeHerosInconnu** [comment]
> Suggestions for use:
> 
> * in the list, mark the cities that are already occupied by a hero.

The sprite of the hero's portrait present in the city can be displayed on the right side of the city list (so after the name of the city).
Right-clicking on the hero's portrait displays the hero information window.
A left click on the hero's portrait closes the Town Portal spell window (as if the user had pressed the "CANCEL" button) and directly selects the hero on the adventure map so that the player can move the hero occupying the city.

**Comment by ihhub** [comment]
@Branikolog , @idshibanov , @LeHerosInconnu this is how it looks with frames:
image

I am not going to add extra occupied castles and positions on radar. Let's focus only on the UI right now. We'll improve this window step by step.

If you are okay with the latest design I'll make these changes.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> @Branikolog , @idshibanov , @LeHerosInconnu this is how it looks with frames:
> 
> I am not going to add extra occupied castles and positions on radar. Let's focus only on the UI right now. We'll improve this window step by step.
> 
> If you are okay with the latest design I'll make these changes.

It's much better this way for now. :)

**Review by idshibanov — APPROVED** [review]
I like the most recent version! Definitely looks good.

**Comment by Branikolog** [comment]
:+1:

**Pull request merged**
