### PR TITLE
Fix shooters projectile position. Battlefield.

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR adds using of sprite `x` and `y` data to adjust the projectile render position.

This PR:

https://user-images.githubusercontent.com/113276641/212488158-278cb45b-7ef7-4621-bdd8-8a3344753733.mp4

<details><summary>Video of shooting from right to left</summary>

https://user-images.githubusercontent.com/113276641/212488789-0af4edb0-838e-4d60-bfe4-96c51a92dd6c.mp4

</details>

Currently in fheroes2 the archers arrows are shifted in direction from archers so the last animation frame renders the arrow behind the target:
arrow1 arrow2

<details><summary>Video</summary>

https://user-images.githubusercontent.com/113276641/212488176-d472dc9f-62e1-4127-8549-61231bfb18d1.mp4

</details>

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @Districh-ru 
I've noticed, that Titan's thunder goes a bit through target. All arrows and stones seem to work correct now.

https://user-images.githubusercontent.com/55348946/213147789-4ffe811b-69ee-411c-be29-fae13a9ef6b5.mp4

Is this PR fixes only finish of projectile position? During my tests I've noticed that sometimes arrows start their flight too far away from the shooting troop.

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru I've noticed, that Titan's thunder goes a bit through target. All arrows and stones seem to work correct now.

Hi @Branikolog, I'll try to fix Titan's thunder soon: I'll try to change the `x` and `y` sprite parameters.

> Is this PR fixes only finish of projectile position? During my tests I've noticed that sometimes arrows start their flight too far away from the shooting troop.

This PR changes the rendering of all projectile positions: it takes into account the `x` and `y` parameters of original sprite. It makes all projectiles to render closer to the shooter.
But we can also add an extra offset to these coordinates, like we did for Golem movement sprites. :)
If you think that we need to shift some projectiles position, please write.

**Comment by Districh-ru** [comment]
> Could you, please look at the next examples?

I'll correct the projectile start positions (this data is located in BIN file for each creature and can be corrected, like we did for the Well animations).

> Not sure it's related to current PR, but I've found an issue, when I point different hexes of wide creature, and this makes shooter sprite keep different orientation. In some cases, it results in not aesthetically pleasing trajectory:
> How do you think, should I open a separate issue for that?

I'll check this issue and if the fix will be to big, then I'll ask you to open a separate issue.

Let's try to fix all possible projectile rendering and trajectory issues in current PR.

**Comment by Districh-ru** [comment]
Hello, @Branikolog!
I've made the suggested corrections for all shooters, including the wide target shooting issue. Could you please check it when you have time.

**Comment by Branikolog** [comment]
Hi, @Districh-ru ! 
Nice work! I love the changes.
I'm testing the PR currently....
I've noticed, that some shooters doesn't have proper animations for vertical ranged attacks. :( Like elves or trolls.

https://user-images.githubusercontent.com/55348946/214937292-f1136b5b-d6dc-4e32-8bf7-41d05fb9de19.mp4

I think for the case with trolls, stone starting position should be closer to his hands.

**Comment by Branikolog** [comment]
@Districh-ru 
Some vertical attacks of Archers seem to have different arrow starting position. Was it intended? I think for both cases arrow should start from the same place regarding Archer sprite.

https://user-images.githubusercontent.com/55348946/214940072-b1ba7361-9839-453c-88b3-6f69f5a86fa9.mp4


https://user-images.githubusercontent.com/55348946/214940095-36769a86-a428-471f-b269-8ce60b9f14bf.mp4

**Comment by Branikolog** [comment]
Hi, @Districh-ru 
Could you, please, look at Titan lightning starting position for some cases?
Depending on the angle, it sometimes looks nice, but sometimes appears on the sprite itself:

https://user-images.githubusercontent.com/55348946/214948393-5be51dda-3f93-4cef-9a10-1c90344dc085.mp4

The same for upper targets:

https://user-images.githubusercontent.com/55348946/214950822-7127a6e0-b9e1-44f4-b8ba-73ff00d1ee28.mp4

**Comment by Districh-ru** [comment]
> @Districh-ru Some vertical attacks of Archers seem to have different arrow starting position. Was it intended? I think for both cases arrow should start from the same place regarding Archer sprite. Or is this due to arrow being tilted more for this angle of attack?

Hi, @Branikolog !
For Archers (and Elves, Orcs, Centaurs) we have 1 or 3 shooting animations and about 9 arrow sprites with different arrow angles:
        

So we have to find a compromise in its starting position.
And this PR makes a render of arrow only starting from its second position, so it start position has a little dependence of shooting angle. This looks IMHO better than rendering an arrow in front of the bow and then send it up/down.

**Comment by Districh-ru** [comment]
Hi, @Branikolog!
I've made some changes to the Troll and Titan projectile starting positions. Could you check these changes when you have time.

**Comment by Branikolog** [comment]
Hi, @Districh-ru 
Great job!
Every creature except druids seem to have proper projectile animation now.
Issue is valid only for such shooting angle:

https://user-images.githubusercontent.com/55348946/215755877-2c450ab1-558c-4699-81b6-10f73a7aabdd.mp4

While other attacks look properly:

https://user-images.githubusercontent.com/55348946/215756182-1156a99a-814b-4800-80e6-3f0b535b7a1b.mp4

It's not critical in my opinion. If it's not possible to shift starting position for this angle I'd gladly accept the current fix!

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , huge thanks for these improvements!

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru Great job! Every creature except druids seem to have proper projectile animation now. Issue is valid only for such shooting angle:
> 2023-01-31.13-48-42.mp4
> 
> While other attacks look properly:
> 2023-01-31.13-50-03.mp4
> 
> It's not critical in my opinion. If it's not possible to shift starting position for this angle I'd gladly accept the current fix!

Hi, @Branikolog!
I've opened a new PR to fix this. :)
Please check it when you have time.

**Pull request merged**
