### PR TITLE
Replace scrollbar in Experimental Settings dialog

### LINKED ISSUE #1420: Game Settings window, scroll bar graphic border
The border of the buttons and the scroll bar does not have a yellow border on the left (1 pixel wide).

Game settings window 05

### PR DESCRIPTION
**Pull request by a1exsh**
Fix #1420

### CODE REVIEW

**Comment by a1exsh** [comment]
Screenshot from 2021-09-28 09-15-07

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

Nice, I prefer this way :)
Could the top of the scrollbar be aligned with the top of the first checkbox and the bottom of the scrollbar aligned with the bottom of the last checkbox?
For a perfect position of the scrollbar, we should also move the scrollbar 1 pixel to the left to have the same distance between, the left edge of the checkbox and the left edge of the window, and the right edge of the scrollbar and the right edge of the window. :)

**Comment by shprotru** [comment]
Hi, @LeHerosInconnu! Aligning to the bottom of the last checkbox is strange, because people always expect smooth scrolling, while this condition will bring ragged scrolling.

**Comment by LeHerosInconnu** [comment]
Hello @shprotru,

> Hi, @LeHerosInconnu! Aligning to the bottom of the last checkbox is strange, because people always expect smooth scrolling, while this condition will bring ragged scrolling.

Okay, the best possible has to be done. :)

**Comment by ihhub** [comment]
@a1exsh , thanks a lot for this fix!

**Comment by a1exsh** [comment]
@LeHerosInconnu we could also drop the shadow from the scrollbar, to make it look even closer to the original.  Too late to do that in this PR, but maybe sometime later. ;)

**Pull request merged**
