### PR TITLE
Interrupt auto combat on mouse click anywhere.

### PR DESCRIPTION
**Pull request by slawomir-witkowski**
fix: #4387

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Currently this PR works like this:

https://user-images.githubusercontent.com/32623900/224969252-3bdabadd-872e-4301-84bc-f47fb814b843.mp4

There is no any auto battle in progress, but it still asks to interrupt the auto-battle if I press `Esc` even during the human player turn. Also we shouldn't even ask to interrupt the auto battle on AI vs AI battles (e.g. in debug mode). Also the case "human vs human" should be verified for sanity, i.e. the question should be asked (and auto-battle is cancelled) only for a current human player (that is, the one whose unit is having its turn at the moment), just like it happens now in the `master` branch.

**Comment by slawomir-witkowski** [comment]
Thank you for your feedback. I wanted to add the ability to cancel auto-combat when it's AI's turn. For players it's not obvious that you can only cancel during your turn. But for now, I only did a small change allowing you to click anywhere to cancel.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please express your opinion about this pull request?

**Comment by Branikolog** [comment]
Hi, @slawomir-witkowski and @ihhub 
The idea to make mouse click to interrupt auto battle is nice, but in the current PR it happens without dialog window with message. I think for both cases (we press Esc button or we press mouse buttons) the same message should appear.
Also, auto battle interruption with Esc button or mouse click should be possible while enemy AI turn. Now you can do it only during your own turn which makes you unable to stop the battle up to the moment the creature you want to control manually starts makes an action.

**Comment by slawomir-witkowski** [comment]
Ok guys, I will close this PR not to block others from picking up this issue. @Branikolog's requirements are perfectly reasonable. It will require some effort to do this right.  I may revisit this in the future.

**Pull request closed without merging**
