### PR TITLE
Restructure the code to allow adding new artifacts

### LINKED ISSUE #7099: Set Unknown Artifact ID to 0 or 255
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The current ID for Unknown Artifact is 103. This isn't bad as it is the last value in an enumeration. However, this carries a lot of problems when we start adding new artifacts essentially increasing this number and making a mess when users load old saves.

### Describe the possible solution

Either we set the artifact ID to 0 or to some high value like 255. Since we don't want to handle extra cases from map loading let's just increase the value.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #7099

- dummy artifacts won't appear in the list of artifacts for Battle Only mode

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @Districh-ru , this is a low priority pull request at the moment as we will merge it only after 1.0.4 to avoid extra testing rounds.

**Review by oleg-derevenetz — APPROVED** [review]

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi @ihhub. I made a short test and found some bugs. Could you take a look in your spare time.

**1.** I can not start a new map - I get "array subscript out of range" in the begin of `World::ProcessNewMap()`:
изображение

**2.** In Battle Only the list of artifacts (if I want to add one to a Hero) is empty.

**3.** The loaded save represents artifacts correctly on the map and artifacts has their correct effects, but when picking them up or viewing in a hero's bag they hav a description and an image from the next artifact.
One part of this bug can be fixed by placing info for the UNKNOWN artifact from the end to front of **artifactData** (`populateArtifactData()`, file artifact_info.cpp). And the other one - by removing `+1` in `IndexSprite64()` (in artifact.h, line 234).

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @Districh-ru , I added many changes in this pull request including fixes found by @Districh-ru . Could you please take a look again?

**Review by Districh-ru — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @LeHerosInconnu can you please help to test this pull request? This pull request changes the order of artifact IDs but for players it should be transparent. It means that loading old saves doesn't changes artifacts on map, in hero's bag or winning conditions. I did all these tests but since the change is very sensitive it would be awesome to verify again.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu can you please help to test this pull request? This pull request changes the order of artifact IDs but for players it should be transparent. It means that loading old saves doesn't changes artifacts on map, in hero's bag or winning conditions. I did all these tests but since the change is very sensitive it would be awesome to verify again.

I tested this.

There is a problem with the random artifact of random level (the yellow spherical artifact without number in the scenario editor):
The yellow spherical artifact appears on the adventure map.

Fheroes2 1.0.4:
Artifact test PR 7126 001

Fheroes2 PR 7126:
Artifact test PR 7126 002

Heroes 2 scenario editor:
Artifact test PR 7126 003

There is a problem with the reward artifact in the sphinx:
The artifact given as a reward in the sphinx is not the one indicated in the scenario editor.

Fheroes2 1.0.4:
Artifact test PR 7126 004

Fheroes2 PR 7126:
Artifact test PR 7126 005

Heroes 2 scenario editor:
Artifact test PR 7126 006

There is a problem with the artifacts given by the events on the adventure map:
The artifact given by the events is not the one indicated in the scenario editor.
Fheroes2 1.0.4:
Artifact test PR 7126 007
Artifact test PR 7126 009
Artifact test PR 7126 011
Artifact test PR 7126 013

Fheroes2 PR 7126:
Artifact test PR 7126 008
Artifact test PR 7126 010
Artifact test PR 7126 012
Artifact test PR 7126 014

Heroes 2 scenario editor:
Artifact test PR 7126 015
Artifact test PR 7126 016
Artifact test PR 7126 017
Artifact test PR 7126 018
Artifact test PR 7126 019

Here are the save files:
[Artifact test PR 7126 01.zip](https://github.com/ihhub/fheroes2/files/11524948/Artifact.test.PR.7126.01.zip)

Here is the scenario test file:
[0 9953a10.zip](https://github.com/ihhub/fheroes2/files/11397997/0.9953a10.zip)

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub,
I tested once more this PR and encountered an assertion (yesterday it did not happen) on the line 897 in `maps_tiles_helper.cpp`:

```
[DBG_GAME] Artifact::FromMP2IndexSprite:  Unknown Artifact object index: 207
Assertion failed: 0, file G:\Games\heroes2\git\src\fheroes2\maps\maps_tiles_helper.cpp, line 897
```
            
I happens rare, not on every load of this test map: [221.zip](https://github.com/ihhub/fheroes2/files/11524984/221.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Districh-ru , I addressed your comments as well as fixed campaign save files. Could you please take a look again?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu and @Districh-ru , I addressed your comments as well as fixed campaign save files. Could you please take a look again?

I tested with the test scenario and a save from version 1.0.4, everything seems to work fine.

**Review by Districh-ru — APPROVED** [review]

**Pull request merged**
