### PR TITLE
Fixdisplay

### PR DESCRIPTION
**Pull request by morgane-du-tweize**
Hi.
I'm trying to fix this issue :
https://github.com/ihhub/fheroes2/issues/1701

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @morgane-du-tweize , you committed a lot of non related files. Please revert these changes. Also Please rename your pull request to be readable by others.

**Comment by morgane-du-tweize** [comment]
Hi @ihhub 
I don't understand for the files I pushed, I think I've missed
I don't know how to reverse changes

**Comment by zenseii** [comment]
> Hi @ihhub I don't understand for the files I pushed, I think I've missed I don't know how to reverse changes If it isn't bothersome : is it possible to delete this PR ?

It depends on your setup, but I think it would be useful for you to figure out how to do that instead of closing this PR.
If you're using github desktop then just right click and choose revert this commit.

**Comment by morgane-du-tweize** [comment]
How do I revert changes on distant github ?
On my local git, did git reset --hard 9fc9d3c to cancel bad commit. 
But if I git push again it is rejected.

**Comment by zenseii** [comment]
> How do I revert changes on distant github ? On my local git, made a git reset --hard [9fc9d3c](https://github.com/ihhub/fheroes2/commit/9fc9d3c4cbdc36f7718150577f6de1e268d72378) to cancel bad commit. But if I git push again it is rejected.

I believe the first thing you need to do is to sync your fork against the latest changes to master.
You can do this by clicking "Sync fork":
image.

After that I would just create a new fresh new branch and then bring only the changes you intend over to that and then make a new PR and close this current one. I'm not familiar with distant github so I can't help you with it unfortunately.

**Comment by ihhub** [comment]
> How do I revert changes on distant github ? On my local git, made a git reset --hard [9fc9d3c](https://github.com/ihhub/fheroes2/commit/9fc9d3c4cbdc36f7718150577f6de1e268d72378) to cancel bad commit. But if I git push again it is rejected.

```
git push -f
```

**-f** flag serves to override existing commit history.

**Comment by zenseii** [comment]
> How do I revert changes on distant github ? On my local git, made a git reset --hard [9fc9d3c](https://github.com/ihhub/fheroes2/commit/9fc9d3c4cbdc36f7718150577f6de1e268d72378) to cancel bad commit. But if I git push again it is rejected.

Actually you might be unable to push that change because you have a unresolved merge conflict here:
image

**Pull request closed without merging**
