### PR TITLE
Add ability to place Ocean Objects within the Editor

### PR DESCRIPTION
**Pull request by ihhub**
This pull request adds all ocean objects that can be placed within the Editor (relates to #6845 ). Also this PR contains the following changes:
- add animation frame support for objects and their proper rendering
- rework object placement logic in regards to object name on tile
- highlight occupied area for multi-tile objects while moving cursor around the map
- add map border checks while placing an object
- add terrain type checks while placing an object

Erase tool does not work with these new objects.

image

image

relates to #6845

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @ihhub !
I've made a few tests of your PR.
Here're few issues I've noticed. Sorry, I'm really busy these days, so I cannot give more feedback the next 2 days.

I think Reefs shouldn't be allowed to be placed over the objects in such manner:

https://github.com/ihhub/fheroes2/assets/55348946/12b5dc24-760e-4306-a4c0-f8d3db4fb00c

One wide object could be placed too closed from the left side. But at the same time it cannot on the right side:

https://github.com/ihhub/fheroes2/assets/55348946/0b344e18-ce6a-44ee-9388-27cd4db54be3

Here's an assertion when I place large object too close to the edge of the map:

https://github.com/ihhub/fheroes2/assets/55348946/690697ee-fe19-4661-b392-e2e82d8e7f0a

**Comment by ihhub** [comment]
Hi @Branikolog , @oleg-derevenetz and @Districh-ru , this PR is ready for re-review.

**Review by oleg-derevenetz — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]
A few minor issues to fix later, but a good work!

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub. I left two comments regarding object placing. Could you check them when you have time, please.

**Comment by ihhub** [comment]
Hi @Districh-ru , I addressed all your comments and did some code based on them. Please take a look again.

**Review by Districh-ru — APPROVED** [review]

**Pull request merged**
