### PR TITLE
Use OG Prerequisistes for Upgraded Jousting Arena and Upgraded Cathedral

### LINKED ISSUE #4548: Wrong prerequisites for the upgraded Jousting Arena and Cathedral
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The upgraded Jousting Arena and Cathedral dwellings of the Knight castle have prerequisites that are not present in OG:

OG:
image
fheroes2:
image

This was tested by loading the same custom-made map. I do not know if there is an original map that makes use of this, but this difference would inevitably change the intent of such a map.

### Save file

I can't share the map I made since it was made using the OG map maker and I am not sure if such a map exists among the OG maps or campaigns.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by zenseii**
This fixes #4548 .

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @zenseii , according to [this page](http://www.heroesofmightandmagic.com/heroes2/buildings_knight.shtml) there are different requirements. Do you think that the page contains incorrect information?

**Comment by zenseii** [comment]
> Hi @zenseii , according to [this page](http://www.heroesofmightandmagic.com/heroes2/buildings_knight.shtml) there are different requirements. Do you think that the page contains incorrect information?

That wouldn't be the first time but maybe it is due to different version? I tested these with the English DOS version from GOG. I can test with the Windows version too if deemed necessary.

The Upgraded Jousting Arena on that page has the requirements that this PR changes:
image

Meanwhile the Upgraded Cathedral is indeed different. Maybe it is suspicious that it is exactly the same as the non-upgraded Cathedral?  Blacksmith, Armory

**Comment by zenseii** [comment]
Just tested the Windows version too and it has the same requirements that this PR wants to implement.

**Comment by ihhub** [comment]
@zenseii , a bunch of thanks for fixing this logic! The website mentioned by me contains incorrect information.

**Pull request merged**
