### PR TITLE
Update the Hungarian translation

### PR DESCRIPTION
**Pull request by big4billy**
These are the first steps to upgrade the Hungarian language file to 1.0.7. and extend the translated titles with the first UPPERCASE menu elements. Further improvements coming soon.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @big4billy , please remove 12KB file.

**Comment by big4billy** [comment]
> 
Dear @ihhub I'm new here. Which 12KB file do you think of? I uploaded just a hu.po file and yesterday the .pot file. These aren't 12KB size.

**Comment by ihhub** [comment]
@big4billy , go to files section in this pull request and observe.

**Comment by big4billy** [comment]
> Hi, @big4billy. The reason your PR has some English strings that are removed is lost likely because you generated the POT file locally and grabbed changes from it, but your local source of fheroes2 was outdated when you generated it.
> 
> We have a bot that does all the work with the POT file so for the next time you do not need to do this. You only need to make a new branch and its hu.po will be up to date, provided you have set up your repo's behavior to be to contribute to ihhub/fheroes2 and not your own fheroes2 fork.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@big4billy , thank you very much for your contribution to the project!

As a side note: in the files we never specify personal information so I had to revert that change.

**Pull request merged**
