### PR TITLE
Enhancement, add feature to click and drag to swap monsters

### LINKED ISSUE #4850: Hero screens, enhancement to "click and hold and move" the mouse cursor
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, since it is possible to click and hold and move the mouse cursor to another location to perform an action (e.g. to split a troop into two troops by moving the mouse cursor to a free location), I suggest that when the player performs this action, by moving the mouse cursor to a troop of another type and releasing the mouse button, the two troops are swapped.

In the example, by clicking and holding on the Liches troop and moving the mouse cursor to the Phoenixes troop and releasing the mouse button, the two troops are swapped.

In fheroes2:

Clic and move over other troop 01

Clic and move over other troop 02

### Describe the possible solution

Allow to "click and hold and move" the mouse cursor to a troop of another type to swap these two troops.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by felix642**
closes #4850

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this issue since you know all possible cases for it?

**Comment by Branikolog** [comment]
Hi, @ihhub, @felix642 and @LeHerosInconnu.
Operating in a manner, @LeHerosInconnu proposed in #4850, became not so consistent now regarding to other army reorganizing logic. Definitely, Drag-and-drop is quite comfortable in way it was implemented in current PR. But while we "drop" monster into an empty slot game initiates fast split dialog, which offers completely other experience, comparing to implemented here. 
I suggest to advance the logic to the case we drag-and-drop target monster into empty slot.  So we can reorganize army much faster. Also we should initiate fast split dialog for the cases, it was implemented before, but only with "Shift" button being pressed. In this way it will be operating in the same, traditional manner (I mean holding Shift to split stacks), all players got used to. Also, while drag-and-drop on the same type we should unite both stacks. So, in other words, I expect drag-and-drop working in a completely same manner, single left click works.

Returning to PR.
I've found a few issues. @felix642, could you, please, look?
If we select one stack and then try to move it over another - the army slot still keep being selected:
image
image
I think we should cancel selection, while using drag-and-drop for any cases.

Also, when one stack is being selected in garrison or hero army and we try to drag-and-drop creatures in other army - nothing happens. 
image
image

**Comment by felix642** [comment]
> Hi, @ihhub, @felix642 and @LeHerosInconnu. Operating in a manner, @LeHerosInconnu proposed in #4850, became not so consistent now regarding to other army reorganizing logic. Definitely, Drag-and-drop is quite comfortable in way it was implemented in current PR. But while we "drop" monster into an empty slot game initiates fast split dialog, which offers completely other experience, comparing to implemented here. I suggest to advance the logic to the case we drag-and-drop target monster into empty slot. So we can reorganize army much faster. Also we should initiate fast split dialog for the cases, it was implemented before, but only with "Shift" button being pressed. In this way it will be operating in the same, traditional manner (I mean holding Shift to split stacks), all players got used to. Also, while drag-and-drop on the same type we should unite both stacks. So, in other words, I expect drag-and-drop working in a completely same manner, single left click works.
> 
> Returning to PR. I've found a few issues. @felix642, could you, please, look? If we select one stack and then try to move it over another - the army slot still keeps being selected: image image I think we should cancel selection, while using drag-and-drop for any cases.
> 
> Also, when one stack is being selected in garrison or hero army and we try to drag-and-drop creatures in other army - nothing happens. image image While it still works for cross army dragging.

I completely agree with what @Branikolog suggested. We should be able to move units around using drag-and-drop and to split them using shift+drag-and-drop. This way we will stay consistent with what we have and still allow players to easily split their army if needed.

I will wait for @ihhub and @LeHerosInconnus opinions before implementing this change.

**Comment by LeHerosInconnu** [comment]
Hello everyone,

> > Hi, @ihhub, @felix642 and @LeHerosInconnu. Operating in a manner, @LeHerosInconnu proposed in #4850, became not so consistent now regarding to other army reorganizing logic. Definitely, Drag-and-drop is quite comfortable in way it was implemented in current PR. But while we "drop" monster into an empty slot game initiates fast split dialog, which offers completely other experience, comparing to implemented here. I suggest to advance the logic to the case we drag-and-drop target monster into empty slot. So we can reorganize army much faster. Also we should initiate fast split dialog for the cases, it was implemented before, but only with "Shift" button being pressed. In this way it will be operating in the same, traditional manner (I mean holding Shift to split stacks), all players got used to. Also, while drag-and-drop on the same type we should unite both stacks. So, in other words, I expect drag-and-drop working in a completely same manner, single left click works.
>
> I completely agree with what @Branikolog suggested. We should be able to move units around using drag-and-drop and to split them using shift+drag-and-drop. This way we will stay consistent with what we have and still allow players to easily split their army if needed.
> 
> I will wait for @ihhub and @LeHerosInconnus opinions before implementing this change.

Since it is also possible to proceed to the separation and reorganization of the troops by selecting a troop and using the right mouse button (so not only by using the left click or "drag and drop" with the "shift" key), I think it could be possible to change this although I am used to the current operation (the use of the right mouse button must be maintained).
Otherwise having to go back to using only the "shift" key for the separation operation would be a step backward for me (any operation should be able to be done only with the use of the mouse).
I think it would be better to test this in normal use (during a game) to see if it is not too difficult to adapt to this change.
It should also be taken into account that it has been working this way for a long time now and that the players have integrated this into their way of using the interface.

**Comment by Branikolog** [comment]
Hi, @LeHerosInconnu.

>Otherwise having to go back to using only the "shift" key for the separation operation would be a step backward for me (any operation should be able to be done only with the use of the mouse).

Same for me. But game logic should be consistent and predictable for players. That's why I suggested the above. Anyway, for fast splitting with drag-and-drop we can implement later the same operation for right click as well.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> Hi, @LeHerosInconnu.
> 
> > Otherwise having to go back to using only the "shift" key for the separation operation would be a step backward for me (any operation should be able to be done only with the use of the mouse).
> 
> Same for me. But game logic should be consistent and predictable for players. That's why I suggested the above. Anyway, for fast splitting with drag-and-drop we can implement later the same operation for right click as well.

The right click already works for the use of fast separation into slots, it should not be removed.

**Comment by Branikolog** [comment]
@LeHerosInconnu 

> The right click already works for the use of fast separation into slots, it should not be removed.

I mean allow to hold right mouse button, move cursor to an empty slot to initiate fast splitting dialog, the same, as it works with single clicking on a troop proceeded with right click on empty slot.

**Comment by LeHerosInconnu** [comment]
@Branikolog.

> @LeHerosInconnu
> 
> > The right click already works for the use of fast separation into slots, it should not be removed.
> 
> I mean allow to hold right mouse button, move cursor to an empty slot to initiate fast splitting dialog, the same, as it works with single clicking on a troop proceeded with right click on empty slot.

But right-clicking and holding on a troop displays the creature's information window as long as the right click is held. :)

**Comment by Branikolog** [comment]
> @Branikolog.
> 
> > @LeHerosInconnu
> > > The right click already works for the use of fast separation into slots, it should not be removed.
> > 
> > 
> > I mean allow to hold right mouse button, move cursor to an empty slot to initiate fast splitting dialog, the same, as it works with single clicking on a troop proceeded with right click on empty slot.
> 
> But right-clicking and holding on a troop displays the creature's information window as long as the right click is held. :)

Completely forgot about that "rarely" used feature. :D
Need to open the second can of beer to think about that thoughtfully.

**Comment by felix642** [comment]
I will close this pull request for now since we're not 100% sure to know how we want to implement this. If anyone is interested you can take a look at #4855 where @Branikolog and @LeHerosInconnu have started to discuss a possible implementation of this new logic. When we all agree on the new implementation I will open a new pull request with the requested changes.

**Pull request closed without merging**
