### PR TITLE
More contrast for player objects on the minimap

### PR DESCRIPTION
**Pull request by a1exsh**
Follow-up to #5998

Before:
Screenshot from 2022-10-22 18-59-38

After:
Screenshot from 2022-10-22 18-57-03

The map/save:
[Players.zip](https://github.com/ihhub/fheroes2/files/9844887/Players.zip)

The color to use for Orange is really tricky, as it has to be different from wasteland terrain and obstacles, _and_ from the yellow player and sand, _and_ beach, etc.  So far I haven't found a color that is contrasting well enough with all of the above.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @ihhub !
Comparing to the original game players' colors became a little bit more distinctive.
Unfortunately I couldn't perform deep tests, due to map loading issue of this PR, which occurred several days ago in master branch.

**Comment by a1exsh** [comment]
@Branikolog attaching a map file for your convenience. ;)
[ALLTEST.zip](https://github.com/ihhub/fheroes2/files/9879464/ALLTEST.zip)

**Comment by Branikolog** [comment]
@a1exsh 
The thing is that this PR is based on outdated build, which had an assertion while loading any map. :(

**Comment by a1exsh** [comment]
I see, rebased now (newly built version should include the crash fix).

**Comment by zenseii** [comment]
> I see, rebased now (newly built version should include the crash fix).

Hi @a1exsh.

Could you please grab the latest changes to master? An issue with the MSVC workflow had to be fixed.

**Comment by zenseii** [comment]
> @a1exsh The thing is that this PR is based on outdated build, which had an assertion while loading any map. :(

Hi, @Branikolog.
The build artifacts are now available. Please have a look if you have the time.

**Comment by Branikolog** [comment]
So, colours for players' objects are hard to make distinctive indeed. After changes of @a1exsh orange on wastelands became much better, while green is still not so clearly visible on grass terrain and yellow/orange on beach terrain as well. 
I think in future, we can try to implement adjustable colors, making for instance, yellow and orange darker on a beach terrain exactly, while leaving current colors for other terrains.
For now, changes for colors are acceptable. Everything works as intended. 👍

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@a1exsh , thanks a lot for this improvement!

**Pull request merged**
