### PR TITLE
MSVC: build with the latest SDL2_Mixer 2.6.0

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Related to #5569, should be merged after #5608

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
@ihhub we can wait with it and later try to use mixer with FluidSynth (we can try to install extra libs using `vcpkg` BTW instead of direct download using batch files, its [portfile](https://github.com/microsoft/vcpkg/blob/master/ports/sdl2-mixer/portfile.cmake) has support for FluidSynth).

**Comment by ihhub** [comment]
I would recommend to merge this just after the release to have enough time to test.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I assume to support the same library everywhere we need to update it on Windows since Unix systems soon or later will receive SDL Mixer 2.6 update.

This is still safe to do without introducing any (I hope) big issues.

What do you think?

**Comment by ihhub** [comment]
Also they released SDL 2.6.1 yesterday :)

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I thought we were going to move in the direction of our own assembly of this library (with FluidSynth) :) If so, there is no point to update it now.

**Comment by ihhub** [comment]
Haha, this is true but I am not convinced yet due to some unsolved problems pointed by you. We could take incremental steps towards the goal if possible like we did for soundfont loading code.

**Comment by oleg-derevenetz** [comment]
@ihhub

> Haha, this is true but I am not convinced yet due to some unsolved problems pointed by you.

But I suppose we should at least try :) The most disturbing issue is the hang on exit if we switch between MIDI and external music during the game, but this issue may already be solved in the latest SDL_mixer (or the latest FluidSynth).

> We could take incremental steps towards the goal if possible like we did for soundfont loading code.

We need to address the issue from @undef21 first:

https://github.com/ihhub/fheroes2/pull/5608#issuecomment-1180608120

**Comment by oleg-derevenetz** [comment]
@ihhub Currently I'm pushing this PR for `vcpkg` that will update the `SDL2_mixer` to 2.6.1:

https://github.com/microsoft/vcpkg/pull/25763

So I hope that we will be able to check it soon with `fheroes2`.

**Comment by oleg-derevenetz** [comment]
@undef21 I still hope that we will not need this at all :) But if we decide not to go with 3rd party MIDI synthesizer, I'll do as you suggest.

**Comment by oleg-derevenetz** [comment]
Closing this one because #5628 looks more promising.

**Pull request closed without merging**
