### PR TITLE
Add links to download the ARM64 Linux build, distinguish the archive names between x86-64 and ARM64

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Because now we have ARM64 builds.

Hi @ihhub could you please postpone the release creation until this PR will be merged since the names of x86-64 linux ZIP archives have been changed?

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , sure, it can wait.

**Review by ihhub — APPROVED** [review]

**Comment by oleg-derevenetz** [comment]
Hi @ihhub it seems that the list of required checks needs to be updated after merging of this PR, because names of some jobs have been changed.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I will update them after the release.

If you have no other things to add in this pull request I will proceed with merging it and the release.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I believe I'm done with this PR :)

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you very much for this change!

**Comment by oleg-derevenetz** [comment]
Hi @ihhub since you apparently decided not to offer SDL1 binaries in the 1.0.0, should we remove the corresponding download links from the `INSTALL.md`?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , the move was to avoid confusion from users having cryptic (SDL1 and SDL2) words in file names and also to reduce the amount of choices to pick from (Windows users had wooping 8 links). Yes, we should remove SDL1 from links.

If you think that we should add SDL 1 into the release please feel to express this opinion :)

**Comment by oleg-derevenetz** [comment]
@ihhub No, I just think that we should remove the corresponding download links from the `INSTALL.md` (see #6402) :) Otherwise we still have non-working links to SDL1 downloads, which may confuse users.

**Pull request merged**
