### PR TITLE
Allow the hero to retreat if, while in the castle, he attacks the hero outside the castle

### LINKED ISSUE #3276: Combat, hero in visit in a castle cannot retreat when he attacks an opposite hero
In fheroes2, the hero in visit in a castle cannot retreat when he attacks an opposite hero.

In fheroes2:

No retreat fh2 10

Gem attacks Ergon.

Here is the save file:
[No retreat fh2 10.zip](https://github.com/ihhub/fheroes2/files/6372799/No.retreat.fh2.10.zip)

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3276

### CODE REVIEW

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for fixing this issue!

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
While testing campaign on a latest build from @eos428 I found an issue. 
I've attacked an enemy standing in a village but he managed to flee from the battle.
Could you, please, check what went wrong with this fix?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog Yes, it turns out that defending a town is not considered as "siege", so I changed logic a bit.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Thanks for this instant fix! :)

**Pull request merged**
