### PR TITLE
Fix the rendering of the Mage Guild upgrade animation

### LINKED ISSUE #9039: Castle screen, additional mage guild level construction issue
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Second level guild appears out of empty space.

https://github.com/user-attachments/assets/75172798-f44b-4eac-8315-b1989a9dfbfc

Initially, the second floor should appear over the existing 1st level guild image.

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #9039

https://github.com/user-attachments/assets/c113c83d-3186-4a6d-ac6f-36745bf66417

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 

I've noticed, horns are still visible after the second mage guild has been built in Barbarian city:
image

Previously they disappeared after animation was finished:
image

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I've noticed, horns are still visible after the second mage guild has been built in Barbarian city:

This should be fixed by now.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Great!
There's also an issue with captain quarters additional parts:

https://github.com/user-attachments/assets/c3cb0ecb-228d-477c-a658-768c7ef3c5f6

https://github.com/user-attachments/assets/a78896b8-35a5-4e75-ba07-3ebd931ee6ee

The column of barbarian captain quarters is supposed to be disappeared after the castle is fully rendered.
And the bridge to necromancers captain quarters should appear with fade together with castle.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> The column of barbarian captain quarters is supposed to disappear (or shouldn't disappear at all) after the castle is fully rendered.
And the bridge to necromancers captain quarters should appear with fade together with castle.

I made an effort to replicate all the hacks associated with partial rendering of various buildings depending on the conditions. Please take a look.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Now everything works nice!
I've only noticed, that part of a flag in knight castle is being rendered under the tower during construction. But after fade animation is finished it is rendered correctly. It works the same comparing to the version before the recent changes.

https://github.com/user-attachments/assets/71192abb-56a1-4ebf-8fbc-68d2fdc515c0

I suppose it is not related to the recent changes and could be fixed in a separate PR later.

**Review by Branikolog — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for the fix!

**Pull request merged**
