### PR TITLE
Fix crash due to out of memory boundary access during resolution change

### PR DESCRIPTION
**Pull request by ihhub**
relates to #4762

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , can you please verify this fix on your side as I can't reproduce the crash?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub Yes, of course, I'll check this later today. It usually doesn't crash but can corrupt some memory and this leads to visual artifacts - like that screen dimming artifact after battle mentioned in #4672.

**Comment by oleg-derevenetz** [comment]
LGTM. I noticed that there is also the `Display::release()` method, should we clear the `_prevRoi` in this method too or this is not necessary?

**Comment by ihhub** [comment]
> LGTM. I noticed that there is also the `Display::release()` method, should we clear the `_prevRoi` in this method too or this is not necessary?

Done. `release` is called at the end of application when we release all resource but it's good to have full cleanup just in case.

**Pull request merged**
