### PR TITLE
Update translation files and fix in-game translation function

### PR DESCRIPTION
**Pull request by dimag0g**
This consists of 3 commits related to #2211:
- update the .pot file and merge .po files with it (fully automated change)
- fix a bug in the crc32b function which makes the calculated CRC independent of the input data
- add a call to `iconv/konwert` to replace language-specific characters with ASCII. `iconv` is pretty standard but doesn't handle Russian. `konwert` is less widespread (it's packaged for Debian though) and handles Russian pretty well. It also has a /1 option which forces a 1-to-1 replacement (so that `ä` is replaced with `a` rather than `ae` or `"a`), which is useful when checking whether translations fit on their respective interface elements.

I'm currently working on FR/RU translations (I own a French GoG HoMM2 version and a Russian edition of HoMM2 from "Buka" which is arguably the most decent Russian translation out there, not just machine-translated junk) for comparison. Here's a screenshot of fheroes2 with `lang=fr` side by side with a French version of HoMM2 from GoG (note - translation changes are not part of this PR, I prefer to submit these separately later):

homm2_fr

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @dimag0g , I have few questions:
- is it possible not to include source code reference in these files? In some way such comments (**#**) might be useful but in most cases they are useless.
- is it possible to use translations in Windows?

**Comment by ihhub** [comment]
Got the answer for the first question: we could use `--no-location` parameter which strips source code location mentioning. This will make the file much smaller and easier to modify. Could you please apply such change for French and Russian translations and revert other translations for now since we don't modify them?

**Comment by dimag0g** [comment]
@ihhub Wouldn't it make sense to apply `--no-location` to all languages, to give all translations a clear baseline from which people could add improvements?

**Comment by ihhub** [comment]
> @ihhub Wouldn't it make sense to apply `--no-location` to all languages, to give all translations a clear baseline from which people could add improvements?

Let's do this then.

**Comment by dimag0g** [comment]
@ihhub Regarding Windows, I use MinGW-w64 and `iconv` does work there. The problem is that `iconv` apparently [cannot be told to escape the `"` character](https://stackoverflow.com/q/68211963/4350586) which breaks string quoting, and `konwert` is not available in MinGW repo.

**Comment by ihhub** [comment]
@dimag0g , I assume that the only problem is to generate *.mo files at the end and these files are OS independent. Why don't we modify for example our pipeline for Ubuntu builds to generate mo files and add them as a part of archive? We'll find a way to put these files into Windows packages later.

**Comment by dimag0g** [comment]
And yes, I can confirm that translations work on Windows. Here's the `iconv -f utf-8 -t ascii//TRANSLIT $< > $<.tmp` version:

homm2_fr

**Comment by dimag0g** [comment]
@ihhub, is there anything else I need to do in this PR?

**Comment by ihhub** [comment]
@dimag0g , thanks a lot for this improvement! I'll create a separate issue when I explain next steps to be done for translation support.

**Pull request merged**
