### PR TITLE
Migrate SonarCloud analysis to GitHub Actions

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
It will also need to create a repository secret with name SONAR_TOKEN and set it to SonarCloud token.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I've added a new secret for this repository based on my SonarCloud account token.

**Comment by ihhub** [comment]
SonarCloud suggests this way:
```
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
I think it's shorter and without any hardcoded values.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub this Action doesn't fit for C++ code. From this Action's README:

> Do not use this GitHub action if you are in the following situations
> You want to analyze C/C++ code: rely on our Travis-CI extension and look at our sample C/C++ project

https://github.com/SonarSource/sonarcloud-github-action#do-not-use-this-github-action-if-you-are-in-the-following-situations

It will not build your code using wrapper and also it will run for pull requests from forked repos which it will not be able to analyze anyway, this is a waste of time.

**Comment by ihhub** [comment]
> Hi @ihhub this Action doesn't fit for C++ code. From this Action's README:
> 
> > Do not use this GitHub action if you are in the following situations
> > You want to analyze C/C++ code: rely on our Travis-CI extension and look at our sample C/C++ project
> 
> https://github.com/SonarSource/sonarcloud-github-action#do-not-use-this-github-action-if-you-are-in-the-following-situations
> 
> It will not build your code using wrapper and also it will run for pull requests from forked repos which it will not be able to analyze anyway, this is a waste of time.

Now I remember why I use Travis-CI for this :)

But anyway I'm giving a green light with this solution as I don't like Travis-CI at all for the last few months!

**Comment by oleg-derevenetz** [comment]
@ihhub Travis-CI is giving up on open source projects anyway :)

**Comment by ihhub** [comment]
Well done, @oleg-derevenetz ! GitHub Actions is faster a bit than Travis-CI too so win-win siutation.

**Comment by oleg-derevenetz** [comment]
@ihhub I see that commit decoration works, it will also need to verify PR decoration on some new or updated PR from the same repo (from you). Please mention me here in case of any issues.

**Pull request merged**
