### PR TITLE
Reset popup window location on screen

### LINKED ISSUE #5764: Battle screen, damage info option causes some hexes partially shadowed
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
Way to reproduce:
Point a creature till damage info box appears.
image

Then point another creature.
image
The place, where previously damage box appeared will be shadowed.

https://user-images.githubusercontent.com/55348946/189899926-10ff00fa-af92-44bd-af2a-d0713c9f857c.mp4

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by felix642**
closes #5764

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @felix642 !
Unfortunately the issue is still reproduceable:

https://user-images.githubusercontent.com/55348946/201316614-0dd46d2b-52c0-45c0-8563-686429951643.mp4

**Comment by Branikolog** [comment]
However, the part of issue, where the part of zombie sprite appears on a battlefield was fixed.

**Comment by Districh-ru** [comment]
Hello, @felix642!
You correctly noticed that the problem with these clipped shadows and sprites is caused here by `SetPosition` function.
What do you think about trying to draw the damage info window without using this function? :)
For example, the last lines of "battlefield_interface.cpp" could be:    (this is a draft, and and possibly not quite correct)
  ```
...
    const fheroes2::Rect & cellRect = _cell->GetPos();
    const fheroes2::Display & display = fheroes2::Display::instance();
    const int borderWidth = BorderWidth();
    const int x = _battleUIRect.x + cellRect.x + cellRect.width;
    const int y = _battleUIRect.y + cellRect.y - borderWidth;
    const int w = std::max( damageText.w(), killedText.w() ) + 2 * borderWidth;
    const int h = damageText.h() + killedText.h() + 2 * borderWidth;

    const fheroes2::Rect borderRect( ( ( x + w ) > display.width() ) ? ( x - w - cellRect.width ) : x, y, w, h );

    Dialog::FrameBorder::RenderOther( fheroes2::AGG::GetICN( ICN::CELLWIN, 1 ), borderRect );

    const int textLeftBorder = borderRect.x + borderWidth;

    damageText.Blit( textLeftBorder, borderRect.y + borderWidth );
    killedText.Blit( textLeftBorder, borderRect.y + borderRect.height / 2 );
}
```

**Comment by ihhub** [comment]
Hi @Districh-ru , would you mind to finish this pull request or even create a new one to address the issue?

**Comment by Districh-ru** [comment]
Hi @ihhub, @felix642, I've opened #6332

**Comment by ihhub** [comment]
Closing this PR in favor for #6332 

@felix642 , no worries, we're just rushing for the upcoming release🙂

**Pull request closed without merging**
