### PR TITLE
Fix infinite loop while using Dimension Door spell by AI hero

### LINKED ISSUE #7168: Game freeze on next turn
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

v 1.0.4 - cannot continue the game. Its freeze on the next turn.

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/11469924/AUTOSAVE.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #7168

### CODE REVIEW

**Comment by ihhub** [comment]
This is actually a game breaking bug. We can potentially update the release to avoid any possible issues.

**Review by oleg-derevenetz — APPROVED** [review]
> We can potentially update the release to avoid any possible issues.

I agree.

**Review by Districh-ru — COMMENTED** [review]
I tested the fix on the save from the issue and on a test map by giving control to AI.
Now AI uses Dimension Door without infinite loops.

**Comment by aslak01** [comment]
I didn't see this in the 1.05 changelog, but I assume it's included? I got hit by it relatively frequently in 1.04.

**Comment by ihhub** [comment]
> I didn't see this in the 1.05 changelog, but I assume it's included? I got hit by it relatively frequently in 1.04.

Please provide a save file for this and also create a separate issue.

**Comment by oleg-derevenetz** [comment]
@aslak01 yes, this PR is included in 1.0.5. If you continue to observe this behavior in 1.0.5, please open an issue and provide a save file for investigation.

**Comment by aslak01** [comment]
> > I didn't see this in the 1.05 changelog, but I assume it's included? I got hit by it relatively frequently in 1.04.
> 
> Please provide a save file for this and also create a separate issue.

https://github.com/ihhub/fheroes2/issues/7269

**Comment by oleg-derevenetz** [comment]
> > > I didn't see this in the 1.05 changelog, but I assume it's included? I got hit by it relatively frequently in 1.04.
> > 
> > 
> > Please provide a save file for this and also create a separate issue.
> 
> #7269

Only if you continue to observe this issue in 1.0.5 :)

**Pull request merged**
