### PR TITLE
Fix the logic of joining monsters for free and for money (due to Diplomacy skill)

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Related to #5670

Currently the game ignores two [mandatory joining conditions](https://handbookhmm.ru/2-diplomacy) from the original game:

1. Neutral monsters will be willing to join (one way or another) if and only if there is a place for them in the hero's army. This is a mandatory condition, there should be no "let's talk with the hero first and see is he willing to dismiss some troops to join us" logic.
2. Neutral monsters will be willing to join because of hero's Diplomacy if and only if the hero ALREADY has enough money to pay them. This is also a mandatory condition, there should be no "let's talk with the hero first and see is he will be able to sell something and pay us" logic.

Since these mandatory conditions are not being met now, then it turns out that there are much more wandering monsters willing to join a hero's army than in the original game. As a result, the game becomes easier than it should be.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
I'm really saddened, that you're going to take away that useful reorganizing button for diplomacy dialog...
I thought, we're going to nerf diplomacy by implementing some sort of penalties for a cases, hero has full army etc...
So, we're going to make game even closer now to the original, with this logic, right?

**Comment by oleg-derevenetz** [comment]
@Branikolog this is just a project. But yes, the Diplomacy is the original game is "auto-nerfened" of some sort because of these additional restrictions, so if you just have a x2 army but no free slots (or not enough money) then no one bothers you with requests to join as it happens in fheroes2. IIRC in HoMM3 the formula of diplomacy is more complicated, but in the original HoMM2 everything happens like this.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I was expecting some sort of upgrade for this mechanics within our project... But... Okay. :)
Between, since you're working with diplomacy now... I'm doing some tests of the original game with diplomacy. I've experienced one curious case, when hero, that has not enough gold is attacked by creatures. But in a case, player has sufficient amount of gold the same creatures offer to join. Is this how diplomacy is supposed to work?

**Comment by oleg-derevenetz** [comment]
@Branikolog

> I've experienced one curious case, when hero, that has not enough gold is attacked by creatures. But in a case, player has sufficient amount of gold the same creatures offer to join. Is this how diplomacy is supposed to work?

Yes, exactly. It is mandatory condition to have enough money to join the creatures, if you have not enough money, then they will not even ask for a join, even if all other conditions are satisfied.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I know, that money is mandatory condition.
I was surprised by their willing to attack me. I was always thinking, that neutral monsters that potentially ready to join are considered as quite weak creatures and would run away in a case hero has not enough space or money.

**Comment by Branikolog** [comment]
> @Branikolog only if you have x4 advantage in army or more. If advantage is between x2 and x4, then they will fight.

Ah okay! Didn't know that.

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Ah okay! Didn't know that.

Not x4, sorry :) x5.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @Branikolog,

It would be a shame to remove these enhancements to be able to make room in your army and to be able to access the marketplace for diplomacy.
I have watched videos of fheores2 players who particularly like this possibility.
I think that these improvements should remain available, if only with an option to activate.

Also the army strength levels must be MORE than 2 times for creatures to join and MORE than 5 times for creatures to flee.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu

> It would be a shame to remove these enhancements to be able to make room in your army and to be able to access the marketplace for diplomacy.

These "enhancements" lead to wrong logic. Having a place in the army and having money to hire are mandatory prerequisites for joining monsters in the original game. I remember discussions where everyone wondered why diplomacy works better than in the original game? That's a reason.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz and @Branikolog,

Let's do a recap.

**Hero without Diplomacy skill.**

**"Loyal" units:**
"Loyal" creatures will offer to join the hero's army if all of the following conditions are met:
- there is a place in the hero's army for a new unit or a unit of the same creatures.
- the strength of the hero's army exceeds the strength of the neutral squad by more than 2 times.
- the hero does not have the Hideous Mask artifact.

The hero can either accept the neutrals' offer to join his army or refuse them.
In the latter case, offended by the refusal, they will impose a fight regardless of the balance of power.

**"Hostile" Units:**
"Hostile" creatures never join a hero's army without the Diplomacy skill.
If the strength of the hero's army exceeds the strength of the neutral unit by more than 5 times, the neutrals begin to panic at the sight of such a powerful army and, as a result, become speechless and flee.

**Hero with Diplomacy skill.**

"Hostile" creatures will offer to join the hero's army if all of the following conditions are met:
- there is a place in the hero's army for a new unit or a unit of the same creatures.
- the strength of the hero's army exceeds the strength of the neutral squad by more than 2 times.
- the hero does not have the Hideous Mask artifact.
- the player has enough gold to pay the full cost of the squad.

If at least one of these conditions is not met, the neutrals either enter the battle, or, when the strength of the hero's army exceeds their own by more than 5 times, they try to run away.

**Let's see how it goes in the original game.**

In original game:

Hero with Diplomacy skill, free slots, enough gold, and just twice the strength of the wandering creatures.
Wandering creatures attack.
Wandering join 001
Wandering join 002

Hero with Diplomacy skill, free slots, enough gold, and just more than twice the strength of the wandering creatures.
Wandering creatures offer to join.
Who said that peasants are not useful. :)
Wandering join 003
Wandering join 004

Hero with no Diplomacy skill, free slots, and just five times the strength of the wandering creatures.
Wandering creatures attack.
Wandering join 015
Wandering join 016

Hero with no Diplomacy skill, free slots, and more than five times the strength of the wandering creatures.
Wandering creatures flee.
Wandering join 005
Wandering join 006

Hero with Diplomacy skill, free slots, enough gold, and more than five times the strength of the wandering creatures.
Wandering creatures offer to join.
Wandering join 007
Wandering join 008

Hero with Diplomacy skill, no free slots (same army as above), enough gold, and more than five times the strength of the wandering creatures.
Wandering creatures flee.
Wandering join 009
Wandering join 010

Hero with Diplomacy skill, free slots, not enough gold (but enough resources to get the gold by trade), and more than five times the strength of the wandering creatures.
Wandering creatures flee.
Wandering join 011
Wandering join 012

Hero with Diplomacy skill, free slots, enough gold, much more than five times the strength of the wandering creatures.
Wandering creatures offer to join.
Wandering join 013
Wandering join 014

**What the player does while playing.**

**Hero with or without Diplomacy skill.**

If the hero's army does not have a free slot.
The player must remember to have a free slot before attacking the wandering creatures, either by dismissing a troop or by transferring one of his troops to another hero.
Wandering army 001
Wandering army 002

If the hero's army is arranged in a certain way (he could have a free slot without having to dismiss one of his troops or transfer it to another hero).
The player must remember to have a free slot before attacking the wandering creatures, by reorganizing his army.
Wandering army 003
Wandering army 004

Wandering army 006
Wandering army 005

With the "HERO" button, the player no longer has to worry about reorganizing his army before engaging the wandering creatures.
For me, this is a real enhancement over the original game.

**Hero with Diplomacy skill.**

The player knows that with Diplomacy skill, the wandering creatures will join his hero if his army is more than twice as strong as the wandering creatures and he has enough gold.
The player must therefore estimate the gold value of the wandering creatures' recruitment cost.
Then he will have to open the screen of a castle with a marketplace and make the trade if he does not have enough gold before engaging the wandering creatures.

With the "Marketplace" button, the player no longer needs to estimate the cost of recruitment and make the trade before engaging the wandering creatures.
Here again, this is a real enhancement over the original game.

These enhancements ("HERO" and "Marketplace" buttons) make the game more fluid.

Here is the test scenario file:
[0 9960a.zip](https://github.com/ihhub/fheroes2/files/9150941/0.9960a.zip)

Note: I think a "let them flee" button should be added in case the hero has Diplomacy and has an army with more than five times the strength of the wandering creatures (so when the hero doesn't want to recruit or fight the wandering creatures but they offer to join him).

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu all these "player should remember to make a free slot" and "player should have enough money beforehand" are required by the original game mechanics. Just like the requirement to not forget to visit Stables once a week to get a movement bonus. It is implied that the player should remember to perform necessary actions to get the profits. All these additional buttons lead to the increased chance to join the creatures which is noticeably different from the original game to an extent that there are even discussions about some "new diplomacy mechanics" while all that in fact needed is to obey the original rules.

I understand what you are referring to.
But consider that the player could make room in his army and trade resources before engaging the wandering creatures, but he didn't think about it, that's why it's an improvement over the original game.
So the player will have to reload the savegame before the action of attacking the wandering creatures, make room in his army and/or trade his resources, which is exactly what the enhancements avoided having to do.

Or even if the player thinks about doing the actions before engaging the wandering creatures, it is still much more convenient to do these actions directly in the rally window than to do them before.

I consider these to be quality of life enhancements.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you for this change!

As of now we go with this solution and later we can find something suitable for everyone.

**Pull request merged**
