### PR TITLE
Fix the logic of recognizing objects guarded by neighboring monsters

### LINKED ISSUE #7218: Adventure map, desert Skeleton location, wrong mouse cursor displayed when wandering creatures are nearby
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the mouse cursor "Sword" is displayed when wandering creatures are nearby and the hero wants to visit the skeleton indicating that the hero will have to fight the wandering creatures to access the skeleton.
However, the hero can access the skeleton without fighting the wandering creatures.

In the original game, in the same case, the hero can access the skeleton without fighting the wandering creatures, and the mouse cursor "Rearing Horse" is displayed.

In original game:

Desert skeleton 001

https://github.com/ihhub/fheroes2/assets/43583994/b1646f03-eccf-49a5-99b8-f94a14892276

In fheroes2:

Desert skeleton 002

https://github.com/ihhub/fheroes2/assets/43583994/07e762df-8bec-4097-8cbd-a6f0d310ebb4

### Save file

Here are the save files:
[Desert skeleton 01.zip](https://github.com/ihhub/fheroes2/files/11544460/Desert.skeleton.01.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #7218

Also the mouse pointer selection code has been modernized a bit - there were some "special" cases that are not "special" anymore: for example, there is no longer a need to specifically handle `OBJ_BOAT` on water (because it is basically an impassable tile for a shipmaster hero) or `OBJ_MONSTER` on land (because now it is basically an ordinary "guarded tile").

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, could you please verify the logic of cursor types on the Adventure Map with these changes?

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test these changes as well?

**Comment by Branikolog** [comment]
Hi, @ihhub 
I've made a couple of tests and it seems to be some issue with skeleton passability, which makes interacting with this object guarding by creature different from the original game.

OG:
image

fheroes2:
image

OG:
image

fheroes2:
image

OG:
image

fheroes2:
image

**Comment by oleg-derevenetz** [comment]
Hi @ihhub should I try to fix the Skeleton passability in this PR (it is not related to object passabilities) or maybe we could fix the Skeleton in a separate PR, because it's in fact a separate issue?

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I recommend to do it in a separate pull request.

@Branikolog , if you have no issues with any other objects please create a separate issue for Skeleton.

**Review by Branikolog — APPROVED** [review]
As far as I could check skeleton (with issues with passability, preventing from interaction from certain angles) and other similar objects, everything seem to work OK.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, could you please verify the logic of cursor types on the Adventure Map with these changes?

I've tested this PR and everything seems to work fine.

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for fixing this issue!

**Pull request merged**
