### PR TITLE
Update followers window to support text mode

### PR DESCRIPTION
**Pull request by ihhub**
relates to #5270

You can test the change using this save file:
[Broken_Alliance_0001.zip](https://github.com/ihhub/fheroes2/files/12707889/Broken_Alliance_0001.zip)

### CODE REVIEW

**Review by Districh-ru — APPROVED** [review]
Well done!
However, I can suggest an improvement for one of the next PRs: Allow the right click on monster image to see dialog with monster characteristics.

**Comment by Branikolog** [comment]
Hi, @ihhub 

Looks nice. But now I'm missing the same icon for Diplomacy and monsters retreating dialogs too. :)

image
image

**Comment by ihhub** [comment]
Hi @Branikolog , the diplomacy window is too big. Adding a new icon would make it over the default resolution. I didn't touch other windows as the goal actually was to make this window to support text mode. I can remove the icon for the consistency.

**Comment by Branikolog** [comment]
@ihhub 

> the diplomacy window is too big. Adding a new icon would make it over the default resolution.

Totally agreed. Maybe we need to widen windows for such cases? (for the distant future) There're also a few artifact descriptions, that make window fall out of the edges. Also, the majority of screens are wide nowadays, so making such dialogs wider for 50-100px wouldn't overflow the game UI, I believe.

**Comment by ihhub** [comment]
@Branikolog , what's you conclusion then?

**Comment by Branikolog** [comment]
@ihhub 

I've heard an opinion from players, that with text only in this window it's hard sometimes to even find the creature name.
I think adding **highlighted creature name** could solve the problem too here. While having an icon is much more visually pleasant and informative 👍 . Player can click to check creature characteristics too. 
So, If reworking diplomacy window could be proceeded in some day - we can leave current implementation as it is. If we will make just highlighting creature name without any icons, so I think adding such and then removing it will look.. weird. You know, such options that appear and then are gone could make players asking how to revert it back etc. And stick to 0.9.20 version, for instance, to play with beloved, but controversial feature. 😅 
Right now I love, how this window looks. 👍  But not sure, that we can rework diplomacy window in similar manner too.

**Comment by ihhub** [comment]
@Branikolog , I am then removing the icon.

**Pull request merged**
