### PR TITLE
Show the surrender dialog even if there is not enough gold to surrender

### LINKED ISSUE #2191: Combat screen, siege, the surrender button of the defending hero must always be accessible
During a siege, the surrender button of the defending hero must always be accessible.
In fheroes2 this is not the case.

In original game:

Retreat siege H2 01

Retreat siege H2 02

Retreat siege H2 03

In fheroes2:

Retreat siege fh2 01

**Edit 2020/12/23.**

Related issue: https://github.com/ihhub/fheroes2/issues/2460.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #2191

Hi @ihhub I will be grateful for the idea how to remove/update "Not enough gold" message properly, without redrawing the entire dialog window :) So far I've just removed it.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , we have a class called `fheroes2::ImageRestorer` (**image.h** file) which accepts an image to be restored and a region (ROI) from this image. Is it what you're looking for?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub Yeah, maybe :) The idea was to update the amount of missing gold, or to remove this text entirely if there is already enough gold after trading. I'll try to use this class.

**Comment by ihhub** [comment]
@oleg-derevenetz , unrelated to this issue: would like you to be a **collaborator** in this project? You could read about extra rights for this repository [here](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository) but in short you'll have an ability to set assignees, milestones and labels for issues and pull requests, you could be assigned (by me for example) as a reviewer of a pull request (and merge it after your review) and you could modify wiki pages.

**Comment by oleg-derevenetz** [comment]
@ihhub

> would like you to be a collaborator in this project?

Thanks for this offer! If you think that it will be useful, then I'm at your service. However, I won't use most of the new extra rights anyway - I don't want to merge PRs for example, because I don't feel very familiar with the bulk of the code yet.

**Comment by ihhub** [comment]
> Hi @ihhub Yeah, maybe :) The idea was to update the amount of missing gold, or to remove this text entirely if there is already enough gold after trading. I'll try to use this class. Thanks!

Text class object should return needed area with w() and h() methods so you just need to update restorer object with start point and these dimensions at the time of showing this text.

**Comment by oleg-derevenetz** [comment]
@ihhub 

> Text class object should return needed area with w() and h() methods so you just need to update restorer object with start point and these dimensions at the time of showing this text.

I did it a bit differently - first I draw the full dialog window (except that text), then remember it into ImageRestorer, and then draw the text. After visiting the market, I restore the dialog window from ImageRestorer and then draw new text again (or not draw it at all, if there is already enough gold to surrender).

**Comment by ihhub** [comment]
@oleg-derevenetz , well done!

**Pull request merged**
