### PR TITLE
The growth of ghosts after battle

### PR DESCRIPTION
**Pull request by shprotru**
Fix for #1997

### CODE REVIEW

**Comment by ihhub** [comment]
@idshibanov , @Branikolog and @LeHerosInconnu, gentlemen. We all know that ghosts are the most controversal creatures in the game and we even had a discussion how to reduce their overpowered ability. Right now the game has such fix and this change actually makes ghosts too powerful again. I'd like to hear your thoughts about this.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> @idshibanov , @Branikolog and @LeHerosInconnu, gentlemen. We all know that ghosts are the most controversal creatures in the game and we even had a discussion how to reduce their overpowered ability. Right now the game has such fix and this change actually makes ghosts too powerful again. I'd like to hear your thoughts about this.

For now, it would be nice if they had the same behavior as in the original game.

For the future, I have already worked on the subject and I have some ideas to solve this problem.

It is already planned that I will open an issue for this proposal later on.
But if you want to have an idea about it, you can check out this thread:
https://heroes2.forumactif.com/t374-unknown-mod-adjustments-for-ghosts

I need to reorganize the content a little bit before I open an issue on Github.
Tell me if you want me to open the issue faster for my proposal or if it's not that urgent. :)

**Comment by shprotru** [comment]
Hi, @ihhub, as for me, this should be implemented as in original game, and this logic, like @LeHerosInconnu suggests(very cool suggestion!), should be selectable by user in our options menu.

**Comment by Branikolog** [comment]
I vote for leaving original mechanics. As original maps and campaigns were made regarding this behavior of ghosts. 
We can make an option in config menu regarding ghosts and other balancing tweaks (such as upgrade cost). So player would choose on his own if he wants to play completely original H2.

**Comment by idshibanov** [comment]
Yeah I think we should accept the change and leave original logic for now. Let the users select a special option that would re-balance them. Plus I think there's still room for discussion on how to do it as I don't like all of the adjustment ideas (too complicated/too much attention to 1 rare monster).

**Comment by LeHerosInconnu** [comment]
Hi @idshibanov,

> Yeah I think we should accept the change and leave original logic for now. Let the users select a special option that would re-balance them. Plus I think there's still room for discussion on how to do it as I don't like all of the adjustment ideas (too complicated/too much attention to 1 rare monster).

What do you find too complicated about the suggestion?

The suggestion can be summed up in two points:

- During combat, when a troop of ghosts obtains the hand, there is a 10% risk that it will attack one of the troops present in the hero's army.
- During combat, if the ghosts represent the greatest threat (the strongest troop) in the hero's army, there is a 10% risk that the ghosts will disappear from the battlefield.

The rest of the suggestion is just clarification on how it works in different cases.
And there are also artifacts and spells related to ghosts.

**Comment by ihhub** [comment]
@shprotru good job! Thanks a lot for fixing this important issue!

**Pull request merged**
