### PR TITLE
Merge with master

### PR DESCRIPTION
**Pull request by Effektus**

### CODE REVIEW

**Comment by zenseii** [comment]
Hi @Effektus !

Thank you for this contribution again. As usual could you change the PR's title to follow our standard for PR titles?

**Comment by Effektus** [comment]
> Hi @Effektus !
> 
> Thank you for this contribution again. As usual could you change the PR's title to follow our standard for PR titles?
> 
> EDIT: Actually looking further at this, I see that there are no actual changes in this PR?

This is just a merge there is no changes

**Comment by ihhub** [comment]
Hi @Effektus , you do not need to create a pull request if you merge changes from master branch :)

**Comment by zenseii** [comment]
> > Hi @Effektus , you do not need to create a pull request if you merge changes from master branch :)
> 
> Latest version not working on windows 11, intel GPU , 11 intel CPU

Hi @Effektus. Could you please provide more info about what happens and also open an issue for this? Thank you!

**Comment by Effektus** [comment]
> > > Hi @Effektus , you do not need to create a pull request if you merge changes from master branch :)
> > 
> > 
> > Latest version not working on windows 11, intel GPU , 11 intel CPU
> 
> Hi @Effektus. Could you please provide more info about what happens and also open an issue for this? Thank you!

Demo working but my version not.
image

**Comment by Effektus** [comment]
> > > > Hi @Effektus , you do not need to create a pull request if you merge changes from master branch :)
> > > 
> > > 
> > > Latest version not working on windows 11, intel GPU , 11 intel CPU
> > 
> > 
> > Hi @Effektus. Could you please provide more info about what happens and also open an issue for this? Thank you!
> 
> Demo working but my version not. "Heroes of Might & Magic II - The Price of Loyalty" image

This is old original DOS version with SMK animation files and after remove Anim folder Game runing

**Pull request closed without merging**
