### PR TITLE
Update Vietnamese Translation.

### PR DESCRIPTION
**Pull request by Nad-SK**
Part 2
Translated: 694 of 2605 (26%)
Remaining: 1911

### CODE REVIEW

**Comment by Nad-SK** [comment]
Hi, @zenseii I just fixed all your comments.

**Review by Nad-SK — COMMENTED** [review]
It fixed!

**Review by Nad-SK — COMMENTED** [review]
I fixed it in the Part 3.

**Review by Nad-SK — COMMENTED** [review]
Commit wrong file.

**Review by Nad-SK — COMMENTED** [review]
Delete wrong commits

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Nad-SK , thank you so much for this translation update!

**Pull request merged**
