### PR TITLE
Remove Unicode support

### PR DESCRIPTION
**Pull request by oleg-derevenetz**

### CODE REVIEW

**Review by undef21 — CHANGES_REQUESTED** [review]
Hello. Could you please remove libsdl2-ttf-dev here?
https://github.com/ihhub/fheroes2/blob/cea9150e74594f0dacc48cbe9531500eec33e7dd/script/packaging/debian/control#L5

**Comment by oleg-derevenetz** [comment]
Hi @undef21

> Could you please remove libsdl2-ttf-dev here?
> https://github.com/ihhub/fheroes2/blob/cea9150e74594f0dacc48cbe9531500eec33e7dd/script/packaging/debian/control#L5

Yes, of course. This PR is still WIP, I'll remove this later today.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub You may want to sync [fheroes2/clang-tidy-pr-comments](https://github.com/fheroes2/clang-tidy-pr-comments) with the upstream once again, because yesterday I made a PR that fixes crashes like this:

https://github.com/ihhub/fheroes2/runs/3129274357?check_suite_focus=true

and also removes limit of 30 handled files per PR, and it was recently merged into the upstream.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , it's done.

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for removing this code!

**Pull request merged**
