### PR TITLE
Allow AI heroes to surrender if the conditions of retreat have been met, but it is impossible to retreat

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Related to #8221

In this video the pumped-up AI-controlled hero surrenders (after a farewell spellcast), and is rehired by AI on the next turn:

https://github.com/ihhub/fheroes2/assets/32623900/93ab4a32-ad8f-423f-a090-de42539ed3e3

I did not introduce any special coefficients for the necessary gold reserve, because currently, when AI is going to retreat, it already has a little army, and the value of a pumped hero, and even with artifacts, in any case exceeds the value of those remnants of his army at the time of surrender.

This PR does not address a suggestion to improve the UI regarding the display of the amount of gold received due to surrender.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
> I checked the original game and the 500 EXP bonus for winning a siege when the defending hero surrenders should in fact be there.

Yeah, it seems that attacker gains extra 500 XP if opposing hero surrenders, BUT only if it's a siege. Attacker doesn't get these 500 XP if the battle takes place in an open field.

**Comment by oleg-derevenetz** [comment]
> EDIT: I've looked everywhere on the repository and can't find mention of this at all. I can only assume this is another missing feature of the OG/bug.

There was no bonus for a successful siege from the very beginning, there was only 500XP bonus for defeating the hero, and that's all. Anyway, I just added this independent bonus, so attacking hero will always get 500XP for a successful siege and additional 500XP for defeating an enemy hero (if this hero did not retreat or surrender).

**Comment by oleg-derevenetz** [comment]
> I checked the case when there's a captain, and you shouldn't get 500XP for that:

Well, then, in this regard, the original logic from previous team was also wrong.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for this improvement!

**Pull request merged**
