### PR TITLE
fix shadow under battle summary dialog

### PR DESCRIPTION
**Pull request by undef21**
resolve issue #2263 

Horizontal segment of shadow sprite has height 15.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @undef21 it's actually 14 pixels :)

**Comment by ihhub** [comment]
I think it's time we create a separate function which could return a proper offsets for shadow sprites... I have an idea how to do it.

**Comment by undef21** [comment]
> Hi @undef21 it's actually 14 pixels :)

Yes. Horizontal segment of sprite is 14. But vertical offset for shadow is BORDERWIDTH == 16. I think this difference give us 1px line.

**Comment by undef21** [comment]
> I think it's time we create a separate function which could return a proper offsets for shadow sprites... I have an idea how to do it.

Function which get real vertical an horizontal sizes from masked pixels?

**Comment by ihhub** [comment]
> > I think it's time we create a separate function which could return a proper offsets for shadow sprites... I have an idea how to do it.
> 
> Function which get real vertical and horizontal sizes from masked pixels?

Yes but this is later.

**Comment by ihhub** [comment]
@undef21 , great thanks for your valuable contribution to the project!

**Pull request merged**
