### PR TITLE
Prefer per-user config file over global one

### LINKED ISSUE #3636: Since version 0.9.4, all the start screens of the game are displayed each time the program is launched (0.9.4 3612)
In fheroes2, since version 0.9.4, all the start screens of the game are displayed each time the program is launched.

In fheroes2:

Launch screens 001

Launch screens 002

Launch screens 003

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3636

It seems that there is already a ready-made mechanism for such situations - `Settings::GetLastFile()`, it is already used for `fheroes2.key` as well. As I understand, the order of search will be the following:

1. List of the matching files is created by scanning directories in the following order: directory from $FHEROES2_DATA env var first, then app's directory, then user config directory, then user data directory, then OS specific directories (like "ux0:..." on PS Vita);
2. The **last** file is taken from this list. If there is no matching files, just file name is taken, which effectively means "file with this name in current directory".

Need to test this on consoles too - to not break anything.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Northfear , could you please test these issues on PSV?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub and @Northfear I also did some minor cleanup here and removed possible duplicates of the same directory in `Settings::GetRootDirs()` in case of PS Vita, please take a look when you'll have a time.

**Comment by Northfear** [comment]
Tested. Everything seems to be working fine

**Comment by oleg-derevenetz** [comment]
@Northfear Thanks a lot!

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for fixinf it!

**Pull request merged**
