### PR TITLE
Remove unused headers and forward declarations

### PR DESCRIPTION
**Pull request by qarkai**
Fixed some `include-what-you-use` "should remove these lines" warnings.
Checked on Ubuntu.

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @qarkai , this is a very useful change for code decoupling. Could you please update the pull request and make it ready for review?

**Comment by qarkai** [comment]
I'll do. I believe we should run iwyu once in a while, e.g. right before/after release.

**Comment by qarkai** [comment]
@ihhub PR is ready for review now.

**Comment by ihhub** [comment]
Hi @qarkai , can we add such check as a part of our pipeline? This one is very useful.

**Comment by ihhub** [comment]
@qarkai , thanks a lot for these changes!

**Comment by qarkai** [comment]
> Hi @qarkai , can we add such check as a part of our pipeline? This one is very useful.

Probably we can. There is even action https://github.com/marketplace/actions/include-what-you-use-github-action in marketplace.
I guess we have to save current state to some file and compare iwyu output with it. But I don't know how to configure GitHub pipelines.

**Pull request merged**
