### PR TITLE
Adjusted bottom padding of normal dialogs

### PR DESCRIPTION
**Pull request by DeiNile**
Added a simple rule to adjust the padding at the bottom of the window depending on the relative size of the header and the message height. Some examples of what it looks like in action:

fheroes2-cancel-bottom-padding

fheroes2-difficulty-bottom-padding

fheroes2-icon-size-bottom-padding

fheroes2-ok-bottom-padding

Do note that this is not a perfect solution. Specifically, if the header itself is really tall, while the message is also substantially taller, the padding on the bottom of the window will be ridiculous. For instance, if the the header's height is 200px, and the message height is 600px, the resulting bottom padding will be 400px! This is kind of silly, but I assume that it is very unlikely to happen. Obviously this only happens when the header message is long and spans multiple lines, which is not super likely? Let me know if I am way off base here.

relates to #1260

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @DeiNile , thanks for your pull request!

You changed the old class for these windows. While the class is still in use in many places due to legacy code we have a newly developed code which locates in `ui_dialog.h` and `ui_dialog.cpp` files. more specifically `showMessage` function is responsible for this. I recommend to take a look there to check whether the described in #1260 behavior is still reproducible with the new code. If yes then it's better to focus the efforts only there.

**Comment by DeiNile** [comment]
@ihhub , it looks like the vast majority of "dialog messages" still rely on `Dialog::Message()`. I applied my change to `ui_dialog.cpp` and it did not work. According to Visual Studio's Find All References feature, it looks like it is only the follow use-cases that use the new implementation in `ui_dialog.cpp`:
```
dialog_game_settings.cpp(176):fheroes2::showMessage( header, body, 0 );
dialog_game_settings.cpp(182):fheroes2::showMessage( header, body, 0 );
dialog_game_settings.cpp(188):fheroes2::showMessage( header, body, 0 );
dialog_game_settings.cpp(194):fheroes2::showMessage( header, body, 0 );
dialog_game_settings.cpp(241):fheroes2::showMessage( header, body, Dialog::OK );
dialog_selectfile.cpp(117):fheroes2::showMessage( header, body, Dialog::ZERO );
dialog_selectscenario.cpp(70):fheroes2::showMessage( header, body, Dialog::ZERO );
game_mainmenu.cpp(192):fheroes2::showMessage( header, body, Dialog::OK );
```

Does this mean that issue #1260 is a bigger refactor issue where all usages of `Dialog::Message()` should be refactored to use `ui_dialog.cpp`?

**Comment by ihhub** [comment]
> @ihhub , it looks like the vast majority of "dialog messages" still rely on `Dialog::Message()`. I applied my change to `ui_dialog.cpp` and it did not work. According to Visual Studio's Find All References feature, it looks like it is only the follow use-cases that use the new implementation in `ui_dialog.cpp`:
> 
> ```
> dialog_game_settings.cpp(176):fheroes2::showMessage( header, body, 0 );
> dialog_game_settings.cpp(182):fheroes2::showMessage( header, body, 0 );
> dialog_game_settings.cpp(188):fheroes2::showMessage( header, body, 0 );
> dialog_game_settings.cpp(194):fheroes2::showMessage( header, body, 0 );
> dialog_game_settings.cpp(241):fheroes2::showMessage( header, body, Dialog::OK );
> dialog_selectfile.cpp(117):fheroes2::showMessage( header, body, Dialog::ZERO );
> dialog_selectscenario.cpp(70):fheroes2::showMessage( header, body, Dialog::ZERO );
> game_mainmenu.cpp(192):fheroes2::showMessage( header, body, Dialog::OK );
> ```
> 
> Does this mean that issue #1260 is a bigger refactor issue where all usages of `Dialog::Message()` should be refactored to use `ui_dialog.cpp`?

Yes. Eventually new class must replace the old one but before going to do this we need make the new code work properly.

**Comment by DeiNile** [comment]
Gotcha, that makes sense, @ihhub. Where does that leave the changes I made with my commit? Is there anything else that you think I should do? Conceivably I could refactor the dialog messages on the main menu to use 'ui_dialog.cpp', if you think that is a good idea? But if there is a larger plan to refactor everything, then maybe it is best to wait until 'ui_dialog.cpp' is ready, and change everything in one fell swoop?

**Comment by ihhub** [comment]
> Gotcha, that makes sense, @ihhub. Where does that leave the changes I made with my commit? Is there anything else that you think I should do? Conceivably I could refactor the dialog messages on the main menu to use 'ui_dialog.cpp', if you think that is a good idea? But if there is a larger plan to refactor everything, then maybe it is best to wait until 'ui_dialog.cpp' is ready, and change everything in one fell swoop?

Ideally, all dialogs must be based on `ui_dialog.cpp` but this is a lot of code refactoring which we don't want to do right now. Let's then stick to your changes and ask @LeHerosInconnu to review these changes.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> > Gotcha, that makes sense, @ihhub. Where does that leave the changes I made with my commit? Is there anything else that you think I should do? Conceivably I could refactor the dialog messages on the main menu to use 'ui_dialog.cpp', if you think that is a good idea? But if there is a larger plan to refactor everything, then maybe it is best to wait until 'ui_dialog.cpp' is ready, and change everything in one fell swoop?
> 
> Ideally, all dialogs must be based on `ui_dialog.cpp` but this is a lot of code refactoring which we don't want to do right now. Let's then stick to your changes and ask @LeHerosInconnu to review these changes.

I'll try to check this too towards the end of next week. :)

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hello @ihhub,
> 
> > > Gotcha, that makes sense, @ihhub. Where does that leave the changes I made with my commit? Is there anything else that you think I should do? Conceivably I could refactor the dialog messages on the main menu to use 'ui_dialog.cpp', if you think that is a good idea? But if there is a larger plan to refactor everything, then maybe it is best to wait until 'ui_dialog.cpp' is ready, and change everything in one fell swoop?
> > 
> > 
> > Ideally, all dialogs must be based on `ui_dialog.cpp` but this is a lot of code refactoring which we don't want to do right now. Let's then stick to your changes and ask @LeHerosInconnu to review these changes.
> 
> I'll try to check this too towards the end of next week. :)

I will test this later. :)

**Comment by ihhub** [comment]
Hi @DeiNile , I think we need to change it for the new dialog only as we made huge changes in the code to utilize only the new code. What do you think?

**Comment by DeiNile** [comment]
> Hi @DeiNile , I think we need to change it for the new dialog only as we made huge changes in the code to utilize only the new code. What do you think?

I am happy to do it, but I am not sure I have a proper understanding of what exactly the design goals of the new dialog code and what exactly about the old approach which was unsatisfactory. And especially if `ui_dialog.cpp` is still a work in progress, then I fear that I may not have the proper background knowledge to ensure that I do not change that file in an undesirable way.

**Comment by ihhub** [comment]
I am closing this pull request as we removed old dialog generation code and this fix is not longer valid.

**Pull request closed without merging**
