### PR TITLE
Update Vietnamese Translation - Part 4

### PR DESCRIPTION
**Pull request by Nad-SK**
- Typos fixed.
- Towns name.
- Heroes name.

### CODE REVIEW

**Comment by Nad-SK** [comment]
Hi @zenseii , pls check and approve the Vi.po

**Comment by ihhub** [comment]
Hi @Nad-SK , @zenseii  will take a look in a couple of days. Please wait for while as he is busy with other task.

**Comment by Nad-SK** [comment]
Hi @zenseii I've done with your review.

**Comment by ihhub** [comment]
Hi @Nad-SK , could you please address the given comments?

**Comment by ihhub** [comment]
I am closing this pull request as the author hasn't fixed the given comments for a very long time.

**Pull request closed without merging**
