### PR TITLE
Implement Adventure (action) Miscellaneous objects placing in Editor

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR adds Adventure (action) miscellaneous objects to editor database.
Currently this objects are added (and shown) in the order of their appearance in game ICNs.
изображение

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @Districh-ru 

2 of 3 stone liths seem to have 2 cells in height:

https://github.com/ihhub/fheroes2/assets/55348946/3549412c-82ad-4240-afe3-8f7af42421ed

OG:
image

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru 
> 
> 2 of 3 stone liths seem to have 2 cells in height:

Hi, @Branikolog , the upper cell for these 2 Stone Liths was incorrectly set as active. Now it should be fixed.

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]
@Districh-ru 
Thanks for the fix!
I've re-checked all misc action objects and all passing rules are ok!

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this update!

**Pull request merged**
