### PR TITLE
Remove unused functions #91

### PR DESCRIPTION
**Pull request by CruxBox**
Did as per required by the description of the issue. Lemme know of any changes.

### CODE REVIEW

**Comment by CruxBox** [comment]
Shall work on the issues. Clearly haven't done all that is needed

**Comment by ihhub** [comment]
Hi @CruxBox could you please revert changes for header file inclusions?

**Comment by ihhub** [comment]
I did this myself :)

**Comment by CruxBox** [comment]
I was actually figuring out how to do it myself :P. For future ref, is it "git checkout branch_name -- file_name" and then a force push?

**Comment by ihhub** [comment]
Closing this pull request as it is invalid (I missed class inheritance).

**Comment by everlearner** [comment]
Sry for the inconvenience,
Which class should they inherit from?
Arent they just functions of class '**Heroes**'?

**Pull request closed without merging**
