### PR TITLE
Fix possible assertion hit for campaign scenario info dialog

### LINKED ISSUE #6091: Assertion on campaign scenario loading
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
After pressing "ignore" button briefing page appears, but campaign couldn't be started.
image

### Save file

[Good_9_Complete.zip](https://github.com/ihhub/fheroes2/files/9943789/Good_9_Complete.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6091

### CODE REVIEW

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @ihhub !
After skipping of the assertion, previously we could see inactive OKAY button, which indicated that you cannot start mission.
image

Within current PR the assertion is no more occurs, but OKAY button looks as normal. Nothing happens, when we press it, so it looks like a bug.
image

**Comment by Branikolog** [comment]
@ihhub 
Now only one assertion is left, when we enter info window, initiate restart and then return back to map.

**Comment by Branikolog** [comment]
@ihhub 
Still have an assertion after trying to restart scenario and returning back to the adventure map. :(

**Comment by ihhub** [comment]
Hi @Branikolog , I reverted changes to the original logic for disabling buttons. The assertion happens because we are trying to load a map, clearing all information about the current game. If it fails we do not restore the state of the game back. So far there is no proper solution for this so disabling buttons is the only way to prevent crashes.

**Review by Branikolog — APPROVED** [review]

**Pull request merged**
