### PR TITLE
Let the hero surrender to the captain during the siege

### LINKED ISSUE #5107: Combat, hero must be able to surrender when the Captain is present during a combat
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the hero must be able to surrender when the Captain is present during a combat.
This is possible in the original game.

In original game:

Surrender Captain 001
Surrender Captain 002

In fheroes2:

Surrender Captain 003

Here is the test scenario file:
[0 9938.zip](https://github.com/ihhub/fheroes2/files/8225680/0.9938.zip)

### Save file

Here are the save files:
[Before attack 02.zip](https://github.com/ihhub/fheroes2/files/8225830/Before.attack.02.zip)

### Additional info

Version 0.9.12 5071

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5107

Currently the captain has the name of the castle instead of just "Captain". I like it better so I left it as it is.

### CODE REVIEW

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> fix #5107
> 
> Currently the captain has the name of the castle instead of just "Captain". I like it better so I left it as it is.

Yes, this was done intentionally: https://github.com/ihhub/fheroes2/issues/4859. :)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> Yes, this was done intentionally: #4859. :)

Hope that in the surrender dialog this string (including the castle name) will not become too wide:

Surrender Dialog

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you very much for this fix!

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > Yes, this was done intentionally: #4859. :)
> 
> Hope that in the surrender dialog this string (including the castle name) will not become too wide:
> 
> Surrender Dialog
> 
> It's already a bit wide for my taste and can out of dialog's bounds if castle name is too long.

In the scenario editor, there is a limit to the text length for the city name.
The name "Quick Silver" already corresponds to the maximum text length in the scenario editor.

Looking at the example provided, one can also notice that the first line of text, the one containing the name of the city, is not centered horizontally in the allocated space (compare with the text below).
Maybe an improvement in this respect would be desirable. ;)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

> Looking at the example provided, one can also notice that the first line of text, the one containing the name of the city, is not centered horizontally in the allocated space (compare with the text below).
Maybe an improvement in this respect would be desirable. ;)

Please take a look at #5116.

**Pull request merged**
