### PR TITLE
Fix passability for Dimension Door spell

### LINKED ISSUE #4278: Adventure map, wrong passability for large objects, trees, mountains, etc. with the Dimension Door spell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is wrong passability for large objects, trees, mountains, etc. with the Dimension Door spell.

In fheroes2:

Wrong passability DD 001
Wrong passability DD 008

Wrong passability DD 002
Wrong passability DD 009

Wrong passability DD 003
Wrong passability DD 010

Wrong passability DD 004
Wrong passability DD 011

Wrong passability DD 005
Wrong passability DD 012

Wrong passability DD 006
Wrong passability DD 013

Wrong passability DD 007
Wrong passability DD 014

Wrong passability DD 015
Wrong passability DD 016

Wrong passability DD 017
Wrong passability DD 018
Wrong passability DD 019
Wrong passability DD 020

### Save file

Here are the save files:
[Wrong passibility Dimension Door 01.zip](https://github.com/ihhub/fheroes2/files/7243176/Wrong.passibility.Dimension.Door.01.zip)

### Additional info

Version 0.9.7 4208

### PR DESCRIPTION
**Pull request by ihhub**
close #4278

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , could you please check these changes once compilation is done? My initial testings show the correct logic but since we're close to release I'd like to have another check before merging.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , could you please check these changes once compilation is done? My initial testings show the correct logic but since we're close to the release date I'd like to have another check before merging.

I did some tests and found these differences.
This is due to wrong passability of the objects, so the Dimension Door spell can't be used on these squares.

Original game first, fheroes2 second:

Passability Dimension Door 001
Passability Dimension Door 002
Passability Dimension Door 003

Passability Dimension Door 004
Passability Dimension Door 005
Passability Dimension Door 006

Also, not related to Dimension Door, the path is not the same near the Tar Pit.
In fheroes2, the hero steps east and then south from the square northwest of the Tar Pit, while in Heroes 2, the hero steps obliquely directly at the same position.
Tell me if it is necessary to open another issue for this.

In original game:

Path near Foundry 01

In fheroes2:

Path near Foundry 02

Here are the save files:
[Passability Dimension Door 01.zip](https://github.com/ihhub/fheroes2/files/7626980/Passability.Dimension.Door.01.zip)

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , please create an issue for Tar Pit.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu , please create an issue for Tar Pit.

Done. (https://github.com/ihhub/fheroes2/issues/4731)

**Pull request merged**
