### PR TITLE
Battle Graveyard: allow to resurrect overlapped corpses

### LINKED ISSUE #1699: Combat, Resurrect spells, it should be possible to select both hexes to resurrect creatures that occupy two hexagons when a corpse of another creature is positioned over the corpse of the target creature in the same hexagon
In fheroes2, it is not possible to select both hexes to cast the Resurrect spell on creatures that occupy two hexagons when a corpse of another creature is positioned over the corpse of the target creature in the same hexagon.

In the example, the corpse of the attacking hero's Champion is positioned over the corpse of the defending hero's Peasant.
The corpse of the defending Hero's Ranger is positioned over the corpse of the attacking Hero's Champion.

In fheroes2, only the hexagon where there are no other corpses over the Champion's corpse can be selected.
In the example, there is also another bug reported here (https://github.com/ihhub/fheroes2/issues/1698) due to which the Champion corpse sprite is not displayed.

In the original game, the two hexagons where the Champion's corpse sprite is located can be selected.

In original game:

Resurrect spell H2 03

Resurrect spell H2 04

In fheroes2:

Resurrect spell fh2 03

Resurrect spell fh2 04

### LINKED ISSUE #9146: Combat, it's not always possible to resurrect creatures when another sprite is in the same hexagon
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, it's not always possible to resurrect creatures when another sprite is in the same hexagon.
This bug affects resurrect and animate dead spells.
This bug does not occur regularly.

In the first example, the swordsman corps sprite is located in hex B3 under the rear part of the boar corps sprite, and the skeleton corps sprite is located in hex B4 under the front part of the boar corps sprite.
Swordsmen and skeletons cannot be resurrected.

https://github.com/user-attachments/assets/17ae1523-4a2b-4622-a2dc-bf766f07c57c

In the second example, the skeleton corps sprite is located in hex A2 under the rear part of the roc corps sprite.
Skeletons cannot be resurrected.

https://github.com/user-attachments/assets/f567804c-aed6-431a-a225-8315e3b664b4

In the third example, the skeleton corps sprite is located in hex B3 under the rear part of the boar corps sprite.
Skeletons cannot be resurrected.

https://github.com/user-attachments/assets/06d6f6c2-7ead-42bd-9466-f51da6821d68

In the fourth example, the swordsmen can be resurrected, and the skeletons cannot be resurrected.

https://github.com/user-attachments/assets/17e3980f-0508-4e43-8ed5-fc3544d777d0

### Save file

Here is the save file (1.1.2 9099)(end the turn):
[Before resurrect sprite 01.zip](https://github.com/user-attachments/files/17147100/Before.resurrect.sprite.01.zip)

### Additional info

Related comment, specifically for stacking sprites in order of troop elimination:

> Hi @ihhub,
> 
> > Hello @ihhub,
> > 
> > > Hi @LeHerosInconnu could you please verify this issue? Recently I've done changes to Ressurect position logic in another pull request.
> > 
> > Okay, I'll take a look at that later.
> 
> I did some quick tests to check the operation.
> 
> For this issue, right here, https://github.com/ihhub/fheroes2/issues/1699, it seems to work fine.
> For this issue, https://github.com/ihhub/fheroes2/issues/1697, it also seems to work fine.
> For this issue, https://github.com/ihhub/fheroes2/issues/1698, there is a small problem:
> 
> The corpses of the creatures must be stacked in the order of elimination of the troops (and updated according to the cases).
> For example, in the order of elimination, first the Peasants' corps, then the Champions' corps, then the Rangers' corps.
> If the Champions are resurrected and then eliminated again, their corps should be on top of the Rangers' corps, and the Rangers' corps are now on top of the Peasants' corps.
> 
>  In fheroes2, if the Champions are resurrected and then eliminated again, their corps is under the Rangers' corps, which is not correct.
> 
_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/1699#issuecomment-748447929_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #1699
fix #9146

With this PR:

https://github.com/user-attachments/assets/516d78ec-1fe5-46d4-b096-23ca6dfc13a0

AI is able to do this as well, of course:

https://github.com/user-attachments/assets/97da74ba-5448-4ca3-a455-98368ed4ccec

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by Branikolog** [comment]
@oleg-derevenetz , hello!

I've started watching this PR.
I've noticed, that after 2-hex creature was defeated standing on the corpse of 1-hex troop I cannot resurrect 1-hex creature:

https://github.com/user-attachments/assets/0bccebfc-50b4-4919-86c5-bb3cda56ecab

Could you, please, look, if this an issue with introduced logic?

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog the overlapping corpses from the same army can only be resurrected in the LIFO order (just the last corpse on a cell can be resurrected), as it is described by @LeHerosInconnu:

> The corpses of the creatures must be stacked in the order of elimination of the troops (and updated according to the cases).
> For example, in the order of elimination, first the Peasants' corps, then the Champions' corps, then the Rangers' corps.
> If the Champions are resurrected and then eliminated again, their corps should be on top of the Rangers' corps, and the Rangers' corps are now on top of the Peasants' corps.

But overlapping corpses from different armies are now stacked independently, i.e. if Peasants corpses from attacking army are located "under" the Champions' corpses from the defending army, then attacking hero can resurrect those Peasants anyway. In the `master` branch, he cannot.

**Review by Branikolog — APPROVED** [review]
I made several test trying to find any corner cases, but everything works according to the logic described by @oleg-derevenetz .
👍

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> I made several test trying to find any corner cases, but everything works according to the logic described by @oleg-derevenetz .
👍

Unfortunately, this PR does not exactly replicate the OG behavior. I did some tests in OG, and it turned out that you were right: Animate Dead should also work even for undead corpses that lay under the corpses of friendly living creatures (like with Vampire Lord corpse under the Cavalry corpse), so I'm currently working on it.

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Ah, ok!
I believe that we can someday come up with a new approach for this game mechanics. It would be great to have a menu to be able to select which creature to resurrect. It was always a mess with resurrection with multiple corpses in the OG. For now it's ok to have a straightforward solution, which is easy to understand, like you've described above. Animate spell is a unique case, which is also good to replicate same to the original game.

**Comment by oleg-derevenetz** [comment]
> It would be great to have a menu to be able to select which creature to resurrect. It was always a mess with resurrection with multiple corpses in the OG.

As far as I know, there are no such mechanics in any popular game of the original HoMM series. Wouldn't it look a bit casual?

Anyway, despite the OG supports the per-spell stacks of corpses, the mechanics is a bit bugged:

https://github.com/user-attachments/assets/7a771fbf-64de-467d-a566-99a98004ccb5

You can "resurrect" the Swordsmen under the Skeleton corpse, but the result is some "invisible" unit. This PR implements this properly:

https://github.com/user-attachments/assets/fbd17105-9539-4f88-8931-d417d0cc77d9

The Quick Info window always shows the topmost friendly corpse, but when it comes directly to resurrection, the topmost friendly corpse will be resurrected, which can be resurrected with the chosen spell. The same goes for AI. For instance, if the order of deaths on the cell was Blue Peasant -> Blue Skeleton -> Red Cavalry, then the Red player will be able to resurrect Cavalry with Resurrect or Resurrect True, while Blue player will be able to resurrect the Skeleton with Animate Dead or Peasant with Resurrect or Resurrect True. In the video above AI prefer to resurrect Vampires because they are considered more valuable than Pikemen.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog and @oleg-derevenetz,

> @oleg-derevenetz Ah, ok! I believe that we can someday come up with a new approach for this game mechanics. It would be great to have a menu to be able to select which creature to resurrect. It was always a mess with resurrection with multiple corpses in the OG. For now it's ok to have a straightforward solution, which is easy to understand, like you've described above. Animate spell is a unique case, which is also good to replicate same to the original game.

Just as a reminder, I made a proposal on this subject: https://github.com/ihhub/fheroes2/issues/1636.

**Comment by Branikolog** [comment]
@oleg-derevenetz 

>As far as I know, there are no such mechanics in any popular game of the original HoMM series. Wouldn't it look a bit casual?

I was always frustrated, when enemy or my army corpses prevent me from resurrecting the creature I want. The case, when I have to consider, the place my troops should be defeated looks too complex and unfriendly.

I believe we should some game mechanics make more simple and predictable, that were implemented in the OG in not optimal way. For instance stone liths mechanics make me really annoyed, when I have to press spacebar for dozen of times to jump to the area I want. I would much prefer to waste some fixed number of movement points (for initiating teleportation), but be sure I jump to the target area, rather than polishing spacebar with my finger. :)

>Anyway, despite the OG seems to support the per-spell stacks of corpses, the mechanics is a bit bugged:

"A bit" is not the best word to describe the case from your video. 😆

**Review by Branikolog — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this update!

**Pull request merged**
