### PR TITLE
Remove PocketPC leftovers

### LINKED ISSUE #1055: Remove PocketPC related code
We aren't going to support low resolution devices in the future. We have PocketPC related code which was designed for these devices. We need to remove it to reduce our compilation time and the number of compilation warnings.

### PR DESCRIPTION
**Pull request by kant2002**
Closes #1055
/cc @Northfear

### CODE REVIEW

**Comment by Northfear** [comment]
@kant2002 looks good to me. Nuke it!

**Comment by ihhub** [comment]
Hi @kant2002 , could you please remove pocketpc related files from vsproj file as well? Windows build is broken because of this.

**Comment by kant2002** [comment]
@ihhub ca you take a look when you have time?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @kant2002 , all looks good except the missing code which we need to remove. Could you please take a look?

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@kant2002 , excellent work! Thank you very much!

**Pull request merged**
