### PR TITLE
Add support of Buka Anim2 directory

### PR DESCRIPTION
**Pull request by ihhub**
relates to #4806

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please help to test these changes? I don't have any other version of the game except GoG.

**Comment by oleg-derevenetz** [comment]
> Hi @oleg-derevenetz , could you please help to test these changes? I don't have any other version of the game except GoG.

Me too, otherwise I would have offered PR for this issue a long time ago :) The problem is that I didn't know how the files were located in the Buka version and couldn't test it.

**Comment by shikulja** [comment]
@oleg-derevenetz @ihhub 
I'll test it before the holidays, as soon as I'm free.

**Comment by shikulja** [comment]
@ihhub
the game works, well, the music and video don't work. If you have added directories, then you probably need other file names as well.

file list:
`
C:\2\Anim2
C:\2\Data
C:\2\files
C:\2\Games
C:\2\Help
C:\2\Maps
C:\2\Tracks2
C:\2\LICENSE
C:\2\download_demo_version.bat
C:\2\extract_homm2_resources.bat
C:\2\ren dat to msd.bat
C:\2\fheroes2.cfg
C:\2\libjpeg-9.dll
C:\2\libogg-0.dll
C:\2\libpng16-16.dll
C:\2\libtiff-5.dll
C:\2\libvorbis-0.dll
C:\2\libvorbisfile-3.dll
C:\2\libwebp-7.dll
C:\2\SDL2.dll
C:\2\SDL2_image.dll
C:\2\SDL2_mixer.dll
C:\2\zlib1.dll
C:\2\fheroes2.exe
C:\2\fheroes2.key
C:\2\download_demo_version.ps1
C:\2\extract_homm2_resources.ps1
C:\2\changelog.txt
C:\2\dir.txt
C:\2\README.txt
C:\2\Anim2\buka.smk
C:\2\Anim2\bukacred.smk
C:\2\Anim2\Choose.smk
C:\2\Anim2\CHOOSEW.SMK
C:\2\Anim2\Credits.smk
C:\2\Anim2\Cybcreds.smk
C:\2\Anim2\cylogo.smk
C:\2\Anim2\Defeat.smk
C:\2\Anim2\Des10.smk
C:\2\Anim2\Des11.smk
C:\2\Anim2\Des12.smk
C:\2\Anim2\Des13.smk
C:\2\Anim2\Des14.smk
C:\2\Anim2\Des15.smk
C:\2\Anim2\Des9.smk
C:\2\Anim2\Earth.smk
C:\2\Anim2\Evil01.smk
C:\2\Anim2\Evil01v.smk
C:\2\Anim2\Evil02.smk
C:\2\Anim2\Evil02w.smk
C:\2\Anim2\Evil03.smk
C:\2\Anim2\Evil03qw.smk
C:\2\Anim2\Evil05.smk
C:\2\Anim2\Evil05av.smk
C:\2\Anim2\Evil05bv.smk
C:\2\Anim2\Evil06.smk
C:\2\Anim2\Evil06aw.smk
C:\2\Anim2\Evil06bw.smk
C:\2\Anim2\Evil07.smk
C:\2\Anim2\Evil07w.smk
C:\2\Anim2\Evil08.smk
C:\2\Anim2\Evil09.smk
C:\2\Anim2\Evil09w.smk
C:\2\Anim2\Evil10.smk
C:\2\Anim2\Evil11w.smk
C:\2\Anim2\Good01.smk
C:\2\Anim2\Good01v.smk
C:\2\Anim2\Good02.smk
C:\2\Anim2\Good02w.smk
C:\2\Anim2\Good03.smk
C:\2\Anim2\Good03qw.smk
C:\2\Anim2\Good04.smk
C:\2\Anim2\Good04w.smk
C:\2\Anim2\Good05.smk
C:\2\Anim2\Good05v.smk
C:\2\Anim2\Good06.smk
C:\2\Anim2\Good06av.smk
C:\2\Anim2\Good06bv.smk
C:\2\Anim2\Good07.smk
C:\2\Anim2\Good07qw.smk
C:\2\Anim2\Good09.smk
C:\2\Anim2\Good09w.smk
C:\2\Anim2\Good10.smk
C:\2\Anim2\Good10w.smk
C:\2\Anim2\h2xintro.smk
C:\2\Anim2\intro.SMK
C:\2\Anim2\ivyback.smk
C:\2\Anim2\Library.smk
C:\2\Anim2\Libraryw.smk
C:\2\Anim2\Lose.smk
C:\2\Anim2\Mixdes10.smk
C:\2\Anim2\Mixdes11.smk
C:\2\Anim2\Mixdes12.smk
C:\2\Anim2\Mixdes13.smk
C:\2\Anim2\Mixdes14.smk
C:\2\Anim2\Mixdes15.smk
C:\2\Anim2\Mixdes9.smk
C:\2\Anim2\Mixpol1.smk
C:\2\Anim2\Mixpol2.smk
C:\2\Anim2\Mixpol3.smk
C:\2\Anim2\Mixpol4.smk
C:\2\Anim2\Mixpol5.smk
C:\2\Anim2\Mixpol6.smk
C:\2\Anim2\Mixpol7.smk
C:\2\Anim2\Mixpol8.smk
C:\2\Anim2\MIXVOY21.SMK
C:\2\Anim2\Mixvoy22.smk
C:\2\Anim2\Mixvoy23.smk
C:\2\Anim2\Mixvoy24.smk
C:\2\Anim2\Mixvoy25.smk
C:\2\Anim2\mixwiz16.SMK
C:\2\Anim2\mixwiz17.SMK
C:\2\Anim2\Mixwiz18.smk
C:\2\Anim2\mixwiz19.SMK
C:\2\Anim2\mixwiz20.SMK
C:\2\Anim2\Mm6.smk
C:\2\Anim2\nwclogo.smk
C:\2\Anim2\Pol1.smk
C:\2\Anim2\Pol2.smk
C:\2\Anim2\Pol3.smk
C:\2\Anim2\Pol4.smk
C:\2\Anim2\Pol5.smk
C:\2\Anim2\Pol6.smk
C:\2\Anim2\Pol7.smk
C:\2\Anim2\Pol8.smk
C:\2\Anim2\Prison.smk
C:\2\Anim2\Rbetrayv.smk
C:\2\Anim2\Voy21.smk
C:\2\Anim2\Voy22.smk
C:\2\Anim2\Voy23.smk
C:\2\Anim2\Voy24.smk
C:\2\Anim2\Voy25.smk
C:\2\Anim2\Win.smk
C:\2\Anim2\Wiz16.smk
C:\2\Anim2\Wiz17.smk
C:\2\Anim2\Wiz18.smk
C:\2\Anim2\Wiz19.smk
C:\2\Anim2\Wiz20.smk
C:\2\Data\heroes2.agg
C:\2\Data\heroes2x.agg
C:\2\Data\NETLODR.DAT
C:\2\Data\CAMPAIGN.HS
C:\2\Data\STANDARD.HS
C:\2\Data\IVYDES.SMK
C:\2\Data\IVYPOL.SMK
C:\2\Data\IVYVOY.SMK
C:\2\Data\IVYWIZ.SMK
C:\2\files\data
C:\2\files\lang
C:\2\files\data\resurrection.h2d
C:\2\files\lang\cs.mo
C:\2\files\lang\de.mo
C:\2\files\lang\es.mo
C:\2\files\lang\fr.mo
C:\2\files\lang\hu.mo
C:\2\files\lang\it.mo
C:\2\files\lang\lt.mo
C:\2\files\lang\nb.mo
C:\2\files\lang\nl.mo
C:\2\files\lang\pl.mo
C:\2\files\lang\pt.mo
C:\2\files\lang\ru.mo
C:\2\files\lang\sv.mo
C:\2\files\lang\tr.mo
C:\2\Games\Обучение.GM1
C:\2\Help\HEROES2.CNT
C:\2\Help\HEROES2.HLP
C:\2\Maps\CAMPE01.h2c
C:\2\Maps\CAMPE02.h2c
C:\2\Maps\CAMPE03.h2c
C:\2\Maps\CAMPE04.h2c
C:\2\Maps\CAMPE05.h2c
C:\2\Maps\CAMPE05B.h2c
C:\2\Maps\CAMPE06.h2c
C:\2\Maps\CAMPE07.h2c
C:\2\Maps\CAMPE08.h2c
C:\2\Maps\CAMPE09.h2c
C:\2\Maps\CAMPE10.h2c
C:\2\Maps\CAMPE11.h2c
C:\2\Maps\CAMPG01.h2c
C:\2\Maps\CAMPG02.h2c
C:\2\Maps\CAMPG03.h2c
C:\2\Maps\CAMPG04.h2c
C:\2\Maps\CAMPG05.h2c
C:\2\Maps\CAMPG05B.h2c
C:\2\Maps\CAMPG06.h2c
C:\2\Maps\CAMPG07.h2c
C:\2\Maps\CAMPG08.h2c
C:\2\Maps\CAMPG09.h2c
C:\2\Maps\CAMPG10.h2c
C:\2\Maps\CAMP1_01.hxc
C:\2\Maps\CAMP1_02.hxc
C:\2\Maps\CAMP1_03.hxc
C:\2\Maps\CAMP1_04.hxc
C:\2\Maps\CAMP1_05.hxc
C:\2\Maps\CAMP1_06.hxc
C:\2\Maps\CAMP1_07.hxc
C:\2\Maps\CAMP1_08.hxc
C:\2\Maps\CAMP2_01.hxc
C:\2\Maps\CAMP2_02.hxc
C:\2\Maps\CAMP2_03.hxc
C:\2\Maps\CAMP2_04.hxc
C:\2\Maps\CAMP2_05.hxc
C:\2\Maps\CAMP2_06.hxc
C:\2\Maps\CAMP2_07.hxc
C:\2\Maps\CAMP2_08.hxc
C:\2\Maps\CAMP3_01.hxc
C:\2\Maps\CAMP3_02.hxc
C:\2\Maps\CAMP3_03.hxc
C:\2\Maps\CAMP3_04.hxc
C:\2\Maps\CAMP4_01.hxc
C:\2\Maps\CAMP4_02.hxc
C:\2\Maps\CAMP4_03.hxc
C:\2\Maps\CAMP4_04.hxc
C:\2\Maps\_BELTWAY.MP2
C:\2\Maps\_BROKENA.MP2
C:\2\Maps\_DEATHG.MP2
C:\2\Maps\_DRAGONR.MP2
C:\2\Maps\_DRAGONW.MP2
C:\2\Maps\_ENROTH.MP2
C:\2\Maps\_FORSAKE.MP2
C:\2\Maps\_GOODVS.MP2
C:\2\Maps\_HEROES.MP2
C:\2\Maps\_HOTSPOT.MP2
C:\2\Maps\_LOSTCON.MP2
C:\2\Maps\_LOSTREL.MP2
C:\2\Maps\_MIGHTV.MP2
C:\2\Maps\_MINERAL.MP2
C:\2\Maps\_MOUNT.MP2
C:\2\Maps\_OVERLOR.MP2
C:\2\Maps\_PANDAMO.MP2
C:\2\Maps\_PYRAMID.MP2
C:\2\Maps\_REVOLU.MP2
C:\2\Maps\_SCORCH.MP2
C:\2\Maps\_SEVENL.MP2
C:\2\Maps\_SHIPW.MP2
C:\2\Maps\_SLUGFES.MP2
C:\2\Maps\_SPELLC.MP2
C:\2\Maps\_TELEPOR.MP2
C:\2\Maps\_TERRAF.MP2
C:\2\Maps\_THECLEA.MP2
C:\2\Maps\_THEOTHE.MP2
C:\2\Maps\_UNDEADA.MP2
C:\2\Maps\_UNHOLY.MP2
C:\2\Maps\_VIKINGS.MP2
C:\2\Maps\_WARIORK.MP2
C:\2\Maps\_WASTL.MP2
C:\2\Maps\_WHOAM.MP2
C:\2\Maps\_WINTERL.MP2
C:\2\Maps\Alteris.mp2
C:\2\Maps\Alteris2.mp2
C:\2\Maps\DdDragon.mp2
C:\2\Maps\GoAskAli.mp2
C:\2\Maps\MERRYMEN.MP2
C:\2\Maps\RDHOME.MP2
C:\2\Maps\RIDDLEME.MP2
C:\2\Maps\WIZLAND1.MP2
C:\2\Maps\ARRAX.MX2
C:\2\Maps\BlackFor.MX2
C:\2\Maps\CARMINE.MX2
C:\2\Maps\CLOUXEEN.MX2
C:\2\Maps\DECISION.MX2
C:\2\Maps\DOMINION.MX2
C:\2\Maps\DRAGON.MX2
C:\2\Maps\DUNGEONB.MX2
C:\2\Maps\FAMREUN.MX2
C:\2\Maps\FOOLGOLD.MX2
C:\2\Maps\FORHONOR.MX2
C:\2\Maps\FORTRESS.MX2
C:\2\Maps\FULLHSE.MX2
C:\2\Maps\GHOSTPLT.MX2
C:\2\Maps\GREED.MX2
C:\2\Maps\GROUNDZE.MX2
C:\2\Maps\GRWAR2.MX2
C:\2\Maps\GUARDWAR.MX2
C:\2\Maps\HUNICORN.MX2
C:\2\Maps\ISLEMAZE.MX2
C:\2\Maps\KINGDTH.MX2
C:\2\Maps\LASTHOPE.MX2
C:\2\Maps\LEOPOLDV.MX2
C:\2\Maps\LUDICROU.MX2
C:\2\Maps\MAGIC3.MX2
C:\2\Maps\MIRESTRA.MX2
C:\2\Maps\NEWENEMY.MX2
C:\2\Maps\NVSS.MX2
C:\2\Maps\PEASANTS.MX2
C:\2\Maps\PIRATE.MX2
C:\2\Maps\PLAINAEK.MX2
C:\2\Maps\PORTALS.MX2
C:\2\Maps\QUADRUP.MX2
C:\2\Maps\ROCROUND.MX2
C:\2\Maps\SANDTIME.MX2
C:\2\Maps\SEASONS.MX2
C:\2\Maps\SHRKANIA.MX2
C:\2\Maps\SKIRMISH.MX2
C:\2\Maps\SURFTURF.MX2
C:\2\Maps\TERRAIN.MX2
C:\2\Maps\THEBACK.MX2
C:\2\Maps\THREEDOM.MX2
C:\2\Maps\THUNK.MX2
C:\2\Maps\VALLEY.MX2
C:\2\Maps\WITCHHNT.MX2
C:\2\Maps\WIZLAND2.MX2
C:\2\Maps\WIZLAND3.MX2
C:\2\Tracks2\02-AudioTrack 02.ogg
C:\2\Tracks2\03-AudioTrack 03.ogg
C:\2\Tracks2\04-AudioTrack 04.ogg
C:\2\Tracks2\05-AudioTrack 05.ogg
C:\2\Tracks2\06-AudioTrack 06.ogg
C:\2\Tracks2\07-AudioTrack 07.ogg
C:\2\Tracks2\08-AudioTrack 08.ogg
C:\2\Tracks2\09-AudioTrack 09.ogg
C:\2\Tracks2\10-AudioTrack 10.ogg
C:\2\Tracks2\11-AudioTrack 11.ogg
C:\2\Tracks2\12-AudioTrack 12.ogg
C:\2\Tracks2\13-AudioTrack 13.ogg
C:\2\Tracks2\14-AudioTrack 14.ogg
C:\2\Tracks2\15-AudioTrack 15.ogg
C:\2\Tracks2\16-AudioTrack 16.ogg
C:\2\Tracks2\17-AudioTrack 17.ogg
C:\2\Tracks2\18-AudioTrack 18.ogg
C:\2\Tracks2\19-AudioTrack 19.ogg
C:\2\Tracks2\20-AudioTrack 20.ogg
C:\2\Tracks2\21-AudioTrack 21.ogg
C:\2\Tracks2\22-AudioTrack 22.ogg
C:\2\Tracks2\23-AudioTrack 23.ogg
C:\2\Tracks2\24-AudioTrack 24.ogg
C:\2\Tracks2\25-AudioTrack 25.ogg
C:\2\Tracks2\26-AudioTrack 26.ogg
C:\2\Tracks2\27-AudioTrack 27.ogg
C:\2\Tracks2\28-AudioTrack 28.ogg
C:\2\Tracks2\29-AudioTrack 29.ogg
C:\2\Tracks2\30-AudioTrack 30.ogg
C:\2\Tracks2\31-AudioTrack 31.ogg
C:\2\Tracks2\32-AudioTrack 32.ogg
C:\2\Tracks2\33-AudioTrack 33.ogg
C:\2\Tracks2\34-AudioTrack 34.ogg
C:\2\Tracks2\35-AudioTrack 35.ogg
C:\2\Tracks2\36-AudioTrack 36.ogg
C:\2\Tracks2\37-AudioTrack 37.ogg
C:\2\Tracks2\38-AudioTrack 38.ogg
C:\2\Tracks2\39-AudioTrack 39.ogg
C:\2\Tracks2\40-AudioTrack 40.ogg
C:\2\Tracks2\41-AudioTrack 41.ogg
C:\2\Tracks2\42-AudioTrack 42.ogg
C:\2\Tracks2\43-AudioTrack 43.ogg
`

**Comment by shikulja** [comment]
[magnet:?xt=urn:btih:DF2E245A8266AC572291A0F46B9477391925DC40&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=Heroes%20of%20Might%20and%20Magic.%20Complete%20Edition%20%2F%20%D0%93%D0%B5%D1%80%D0%BE%D0%B8%20%D0%BC%D0%B5%D1%87%D0%B0%20%D0%B8%20%D0%BC%D0%B0%D0%B3%D0%B8%D0%B8.%20%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B5%20%D0%B8%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20(I%2C%20II%2C%20III%2C%20IV%20%2B%20The%20Gathering%20Storm%20%2B%20Winds%20of%20War%2C%20V%20%2B%20Trib](url)

**Comment by ihhub** [comment]
Hi @shikulja ,
I had to remove magnetic link provided by you as I assume this is for a copy of the game. This is against licensing.

Did you test a build from **this pull request**?

**Comment by shikulja** [comment]
Hi @ihhub 
I checked again on the last test build. ogg music and smk videos don't work.

**Comment by ihhub** [comment]
@shikulja , just to make sure that we're aligned on the same topic: did you test build from [here](https://ci.appveyor.com/project/ihhub/fheroes2/builds/42033732) or from releases?

**Comment by shikulja** [comment]
@ihhub 
I checked on the last one.
It is on this - ca475288 that the video works, but there is still no music.

**Comment by ihhub** [comment]
@shikulja , great! The intention of this pull request was to add video support.

**Pull request merged**
