### PR TITLE
Fix heroes meeting swap arrows

### LINKED ISSUE #4503: Meeting heroes, swap army / artifact buttons rendering
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

The button sprites include a piece of background and their areas are overlapping.  The button which is rendered last overwrites pieces of the other button:
- normal state, lower button's background cut into the shadow of the upper button:
   image
- after pressing the upper button, the shadow is fully rendered again, but it cuts a few pixels from the lower button itself:
   image

Another small issue is that the arrow width is defined incorrectly in the code: it should be 44 pixels instead of 43.

The code for creating these buttons from original resources is duplicated for left vs. right arrow, but is almost identical, could be reduced in half: https://github.com/ihhub/fheroes2/blob/eaba68a729cda59dff4d54baea801b72e047cec5/src/fheroes2/agg/agg_image.cpp#L796-L886

### Save file

No save file needed: just let any two heroes meet.

### Additional info

Discovered while working on #4350.  I will try to come up with a fix for this issue first.

### PR DESCRIPTION
**Pull request by a1exsh**
Fix #4503, #3346

There is still a slight issue with rendering of background for the bottom two arrows (for artifact exchange), but it doesn't seem like we have any better patch in the background image we're using (`STONEBAK`):

image

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @ LeHerosInconnu and @Branikolog , could you please take a look at these changes?

**Comment by a1exsh** [comment]
@ihhub let's merge the shadows PR first — I would like to reuse the code here as well, as here we are also working with shadows.

**Comment by LeHerosInconnu** [comment]
> Hi @LeHerosInconnu and @Branikolog , could you please take a look at these changes?

> @ihhub let's merge the shadows PR first — I would like to reuse the code here as well, as here we are also working with shadows.

I'll wait for the shadows PR to be merged then. :)

**Comment by a1exsh** [comment]
@LeHerosInconnu , @Branikolog please have a look when you have time: the code is updated to use the new function from the other shadows PR ;)

**Comment by LeHerosInconnu** [comment]
Hello @a1exsh,

> @LeHerosInconnu , @Branikolog please have a look when you have time: the code is updated to use the new function from the other shadows PR ;)

The first time the top arrow for creatures is pressed, there is a defect that appears under the bottom arrow for creatures when the button is released.
And each time the bottom arrow for creatures is pressed and released there is a defect that appears under the bottom arrow for creatures.

Also, if immediately after the meeting a troop is selected, there is a default that appears under the bottom arrow for creatures.

In fheroes2:

https://user-images.githubusercontent.com/43583994/144718225-64c7fe42-b898-4665-8bda-e402fb2903ba.mp4

https://user-images.githubusercontent.com/43583994/144718233-b0966b08-5a66-4dcd-8825-97e499e48854.mp4

**Comment by a1exsh** [comment]
@LeHerosInconnu nicely spotted — I'll have another look!

**Comment by a1exsh** [comment]
@LeHerosInconnu fixed

**Comment by LeHerosInconnu** [comment]
@a1exsh.

> @LeHerosInconnu fixed

That was a quick change.
Works like a charm.
Good job. :)

**Comment by Branikolog** [comment]
Hello, @a1exsh 
I've noticed, that in this PR arrows run away in different directions... 
Here's a comparison with OG:
ezgif com-gif-maker (27)

Also, We've problems with background near artifact arrows.. But this was the case before PR.

**Comment by LeHerosInconnu** [comment]
Hello @Branikolog, @a1exsh and @ihhub,

> Hello, @a1exsh I've noticed, that in this PR arrows run away in different directions...

Oh, I didn't see that, I was too focused on the graphic glitches. :D
Good catch!

Although these arrows are not properly centered in the original game either. :)
Before they were part of the background, maybe we should center them properly now that they are detached from the background?
What do you think about it?

**Comment by a1exsh** [comment]
> I've noticed, that in this PR arrows run away in different directions...

We pretty much have to do that so that the button areas do not overlap, which was causing the originally reported issues.

> Also, We've problems with background near artifact arrows.. But this was the case before PR.

Yes.  Unfortunately, I haven't found a suitable resource in the OG to make it look any better.

**Comment by a1exsh** [comment]
@LeHerosInconnu 
> Before they were part of the background, maybe we should center them properly now that they are detached from the background?

I did try to center them.  Do you see a problem with the latest version?

**Comment by LeHerosInconnu** [comment]
@a1exsh.

> @LeHerosInconnu
> 
> > Before they were part of the background, maybe we should center them properly now that they are detached from the background?
> 
> I did try to center them. Do you see a problem with the latest version?

Indeed, the bottom ones are centered as much as possible, good.
The top ones are not centered vertically, see in relation to the red frame.

In fheroes2:
(From the screenshot above.)
Meeting yellow arrows cadre rouge 01

**Comment by a1exsh** [comment]
> The top ones are not centered vertically, see in relation to the red frame.

I was going to write that we cannot move them down further, but then I had an idea.  Let me try it :D

**Comment by a1exsh** [comment]
Centered the army swap arrows (the shadow sticks below, but I think this is how it should be):
image

**Comment by LeHerosInconnu** [comment]
@a1exsh.

> Centered the army swap arrows (the shadow sticks below, but I think this is how it should be):
> image

Yes, it's better to center the yellow arrows without taking their shadows into account.
All seems good now. :)

**Comment by LeHerosInconnu** [comment]
@a1exsh.

I did a check with the last change, I think it's good. :)

**Comment by ihhub** [comment]
@a1exsh , a bunch of thanks for these fixes!

**Pull request merged**
