### PR TITLE
CMake to copy executable to project root

### PR DESCRIPTION
**Pull request by Kazhuu**
Copy fheroes2 executable to project root when done building.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @Kazhuu what do you think about the inverted approach - copy executable to the root of the source directory, like it's done for `make`?

**Comment by Kazhuu** [comment]
That would also work @oleg-derevenetz. I have always preferred to run the executable from the build folder and have seen projects other projects to work like this as well. When for example debugging with GDB. In GDB I can just run `make -j` and then `run` to run the executable again. But yeah it could be done from the root directory as well if you want that instead :+1:

**Comment by Kazhuu** [comment]
I change the the behavior now to copy the executable to project root now. I think it would be good to add that file to `.gitignore` as well. Now the executable is showing up as an untracked file.

**Comment by oleg-derevenetz** [comment]
Hi @Kazhuu,

I just slightly changed your PR. Resulting binary file should not be copied to the `PROJECT_SOURCE_DIR` if it was built for macOS app bundle, because this app bundle has a totally different directory layout. `Makefile` doesn't copy such binary as well:

https://github.com/ihhub/fheroes2/blob/60772c724315724ce395d2198dbb6fed06da1970/Makefile#L38-L43

**Comment by Kazhuu** [comment]
> Hi @Kazhuu,
> 
> I just slightly changed your PR. Resulting binary file should not be copied to the `PROJECT_SOURCE_DIR` if it was built for macOS app bundle, because this app bundle has a totally different directory layout, so you probably won't even be able to run such a binary separately. `Makefile` doesn't copy such binary as well:
> 
> https://github.com/ihhub/fheroes2/blob/60772c724315724ce395d2198dbb6fed06da1970/Makefile#L38-L43

Okay I changed the code so that the executable is only copied when on non-apple platforms.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Kazhuu , huge thanks for this improvement!

**Pull request merged**
