### PR TITLE
Add an ability to place Random Monsters in the Editor

### PR DESCRIPTION
**Pull request by ihhub**
relates to #6845

https://github.com/ihhub/fheroes2/assets/19829520/05bc20ed-d0a1-4f85-847e-e4c40279f511

### CODE REVIEW

**Review by Districh-ru — APPROVED** [review]
Well done!

**Comment by Branikolog** [comment]
Hi, @ihhub !
I've found the same flaw, the original game has:
image

**Comment by ihhub** [comment]
> Hi, @ihhub ! I've found the same flaw, the original game has: image

This is a part of the Eraser which @Districh-ru is working on.

**Review by Branikolog — APPROVED** [review]
Okay! Everything else regarding monsters looks fine for me! 👍

**Pull request merged**
