### PR TITLE
Fix World Map drawings and screen jumping during hero movement

### PR DESCRIPTION
**Pull request by ihhub**
- fixed World Map display on huge resolutions. We do not allow to scroll
if there is nothing to scroll
- fixed Dimension Door area for 4K (relates to #893 )
- fixed hero centering (relates to #727 )
- fixed screen jumping for hero's movement (relates to #797)
- fixed pop-up dialog area for no-interface case
- fixed Ultimate Artifact generation on huge resolutions
- fixed missing drawing during scrolling for World Map (relates to #779)

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , @idshibanov  and @shprotru , could you please help me to test these changes before merging them into master branch? I rewrote whole World Map logic so we do not have many issues for it. I tested many scenarios but I am not sure that I covered everything.

**Comment by shprotru** [comment]
Hi @ihhub! I am start testing.

**Comment by idshibanov** [comment]
Tested a few scenarios myself, mostly on SDL2 in 1280x1024 and 1920x1080. Could not reproduce scrolling issue yet, it might be platform dependent (I'm on Windows).

The only hassle I found was choppy scrolling during AI move. Especially easy to spot on maps with AI allies. Did you update it the scrolling for both or only player?

**Comment by ihhub** [comment]
> Tested a few scenarios myself, mostly on SDL2 in 1280x1024 and 1920x1080. Could not reproduce scrolling issue yet, it might be platform dependent (I'm on Windows).
> 
> The only hassle I found was lack of smooth scrolling during AI move. Especially easy to spot on maps with AI allies. Did you update the scrolling for both or only player hero?

Hi @idshibanov , please try 1024x768. With that resolution scrolling was buggy. I haven't touched AI heroes. I'll take a look. Thank you

**Comment by idshibanov** [comment]
> 
> Hi @idshibanov , please try 1024x768. With that resolution scrolling was buggy. I haven't touched AI heroes. I'll take a look. Thank you

Looks alright to me, tried different builds; fullscreen or not. Only issue encountered is #896 but I believe it doesn't relate to this PR.

**Comment by ihhub** [comment]
> > Hi @idshibanov , please try 1024x768. With that resolution scrolling was buggy. I haven't touched AI heroes. I'll take a look. Thank you
> 
> Looks alright to me, tried different builds; fullscreen or not. Only issue encountered is #896 but I believe it doesn't relate to this PR.

No, this is unrelated issue.

**Comment by ihhub** [comment]
> Hi @ihhub! I am finished testing.
> 
> SDL2 build contain serious issues:
> 
> * can't scroll world map with 1920x1080 resolution in full screen mode(native display resolution is bigger than game resolution). Have space to scroll and can't. Sometimes in all directions, simetime only with right direction. Notice, if this triggers - you can't click on castles, heroes, move your hero or set new path, just nothing happens, till you back to windowed mode.
> * In fullscreen mode you could notice that mouse cursor does not resets from sundial pointer type, after computer finished his turn.
> 
> Sorry, same behaviour on master branch for SDL2 build.
> 
> SDL1 build:
> 
> * disappears all sounds, except music, see attached log file [fh2_sdl1_sounds_gone.log](https://github.com/ihhub/fheroes2/files/4841290/fh2_sdl1_sounds_gone.log)
> 
> Seems described bugs fixed, except one: don't know how to check bug with Ultimate Artifact.

Could you please create separate issues for your found bugs? I don't see that they are related to these changes so we need to fix them in different pull requests.

**Pull request merged**
