### PR TITLE
Sorted headers in alphabetic order in few files #82

### PR DESCRIPTION
**Pull request by CruxBox**
I've sorted the headers in alphabetical order.
relates to #82

### CODE REVIEW

**Comment by ihhub** [comment]
@CruxBox please separate changes for this issue and another issue. One pull request per one issue :)

**Comment by ihhub** [comment]
I recommend to create another branch for second issue

**Comment by CruxBox** [comment]
Sure thing :)

**Comment by ihhub** [comment]
@CruxBox you use the same branch for all changes in code. Github pushes all changes from your branch into master branch for pull request. If you need help with branching I can help you :)

**Comment by ihhub** [comment]
Ah, my bad. I see different branches. I'll revert needed files.

**Comment by ihhub** [comment]
@CruxBox thank you very much for the contribution to the project!

**Pull request merged**
