### PR TITLE
Fix Sorceress Statue construction fade-in animation

### LINKED ISSUE #9158: Castle screen, rendering issue during fading animation
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There's a visual flaw during construction of the statue in front of the "crystal garden".

https://github.com/user-attachments/assets/ddb543c9-894a-4b83-876c-a3a44d165722

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #9158

The issue was that:
- the order of rendering is the Statue and then the Crystal Garden;
- when these buildings are both built they have an extra image that is used instead of their separate images and is rendered above them.

This PR removes the redundant rendering of single Statue and Crystal Garden images when they are both built: it was not visible but in master build all three images ( Statue, Crystal Garden, image of both buildings) were rendered.
An extra rendering is done for the case when the Statue is built over the Crystal Garden to swap their render priority during fade-in animation.

https://github.com/user-attachments/assets/d2d7f029-e15d-4387-a859-ec46a0dd159c

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
I've noticed an issue with Mage guilds here:
image

**Comment by Districh-ru** [comment]
Hi, @Branikolog, thanks for testing!
This issue is now fixed.

**Review by Branikolog — APPROVED** [review]
@Districh-ru  Thanks! Now everything works fine.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this fix!

**Pull request merged**
