### PR TITLE
Generate & display the current status of translations

### LINKED ISSUE #6588: Translation progress
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Currently there is no overview where how many untranslated strings are in which language.

### Describe the possible solution

Maybe after updating the translations a json with status could be generated, which could then be displayed with shields in percent for each language.

`https://img.shields.io/badge/dynamic/json?url=<CURL>&label=<LABEL>&query=<$.DATA.SUBDATA>&color=<COLOR>&prefix=<PREFIX>&suffix=<SUFFIX>`

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
close #6588

That's how it will look like:

https://oleg-derevenetz.github.io/fheroes2/TRANSLATION

The specific appearance, color scheme, etc., etc. are the subject of discussion.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @Laserlicht we are interested in your opinion.

**Comment by oleg-derevenetz** [comment]
@zenseii

> We need to fix the part in the German PO file that just says "de".

That's because `de.po` has this header:

```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# fheroes2 team <fhomm2@gmail.com>, 2022
#
```

instead of the proper one:

```
# Belarusian translation of fheroes2
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# fheroes2 team <fhomm2@gmail.com>, 2022
#
```

I left it as is specifically for testing purposes. We can make a separate PR then to fix this header.

**Comment by Laserlicht** [comment]
@oleg-derevenetz Looks very good! Thank you. :)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , awesome work! Well done!

**Pull request merged**
