### PR TITLE
Fixes to button text placements and smaller fixes

### PR DESCRIPTION
**Pull request by zenseii**
Fix https://github.com/ihhub/fheroes2/issues/7227

Also fixed som leftovers of original text being present on the TOWNS/CASTLES button and the vertical misalignment of the guilds and well EXIT button.

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @drevoborod , could you please testing this change?

**Comment by drevoborod** [comment]
> Hi @drevoborod , could you please testing this change?

Yes, I'll do my best but I need additional information to start :) I've read the issue description and understood what to check, but don't know how to get corresponding build.

**Comment by ihhub** [comment]
@drevoborod , thanks for testing it!

**Comment by ihhub** [comment]
@zenseii , thank you so much for these fixes!

**Pull request merged**
