### PR TITLE
Improve the AI fog discovery logic

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Discussed in #4904.

The proposed approach to expanding the list of objects that AI can visit for the purpose of fog discovery.

Hi @ihhub what do you think?

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , the call `GetObject( true )` which should have **false** value, otherwise we're ignoring heroes. I think we should try an opposite approach to list objects which require fights for heroes. The list will be much smaller.

**Comment by oleg-derevenetz** [comment]
@ihhub The signature of `Maps::Tiles::getObject()` is:

 ```cpp
 ​MP2::MapObjectType ​GetObject​( ​bool​ ignoreObjectUnderHero = ​true​ ) ​const​;
```

So if this parameter is `true`, it means that on tiles with heroes the `OBJ_HEROES` will be returned, and not an object under hero.

**Comment by ihhub** [comment]
> @ihhub The signature of `Maps::Tiles::GetObject()` is:
> 
> ```c++
> ​MP2::MapObjectType ​GetObject​( ​bool​ ignoreObjectUnderHero = ​true​ ) ​const​;
> ```
> 
> So if this parameter is `true`, it means that on tiles with heroes the `OBJ_HEROES` will be returned, and not an object under hero.

It always confuses me... Yes, you're right.

**Comment by oleg-derevenetz** [comment]
I'm just not sure that we need to consider resource objects, bonus objects (such as Gazebo) or monster dwellings as suitable for a fog discovery by itself. Such objects have separate logic AFAIK - for some of them hero should have a free army slot, for some of them he should have money/resources, and so on.

**Comment by ihhub** [comment]
> I'm just not sure that we need to consider resource objects, bonus objects (such as Gazebo) or monster dwellings as suitable for a fog discovery by itself. Such objects have separate logic AFAIK - for some of them hero should have a free army slot, for some of them he should have money/resources, and so on.

You have a valid point. Then let's add those which don't impact AI heroes in any bad way such as fights, resource usage or choosing something. Signs are definitely these kind of places :)

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this improvement!

**Pull request merged**
