### PR TITLE
MusicalEffectPlayer: do not change music volume if there is no music file for the corresponding effect, reduce I/O when searching for music files

### LINKED ISSUE #7181: Adventure map, there is a drop in volume when an interaction window is opened while the audio setting "Music Type" is set to "External" and there is no "MUSIC" folder present
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a drop in volume when an interaction window is opened while the audio setting "Music Type" is set to "External" and there is no "MUSIC" folder present.

In fheroes2:
Activate the sound of the videos.

https://github.com/ihhub/fheroes2/assets/43583994/e8121bac-af5b-45c4-9744-5406f72ce917

https://github.com/ihhub/fheroes2/assets/43583994/fe359fd8-660d-4e19-8a73-96684573f57f

### Save file

Here is the save file:
[Sound down window out 01.zip](https://github.com/ihhub/fheroes2/files/11472066/Sound.down.window.out.01.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/7182.

### LINKED ISSUE #7182: System Info, Audio Settings, the audio setting "Music Type" should be set to "MIDI" by default (and not to "External") when there is no "MUSIC" folder present
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the audio setting "Music Type" should be set to "MIDI" by default (and not to "External") when there is no "MUSIC" folder present.

In fheroes2:

MIDI default no MUSIC folder

**Edit.**

Also, if the user tries to change the "Music Type" setting, a message should inform the user that there must first be a "MUSIC" folder with the necessary files before the music type setting can be changed.

In original game:
The message of the original game when only MIDI music can be used:
Note: The message of the original game cannot be used in fheroes2, because it is not the same operation for the type of music.

MIDI only message 001

MIDI only message 002

### Describe the possible solution

In fheroes2, the audio setting "Music Type" should be set to "MIDI" by default (and not to "External") when there is no "MUSIC" folder present.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #7181

close #7182

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu, could you please test this PR: background music and object sounds, in MIDI and External mode, with and without external music files?

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> Hi @LeHerosInconnu, could you please test this PR: background music and object sounds, in MIDI and External mode, with and without external music files?

I'll try to check it out sometime next week, but more likely at the end of the week.

**Comment by ihhub** [comment]
Hi @Branikolog , please prioritirize this pull request review. This is an important change.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> @oleg-derevenetz.
> 
> > Hi @LeHerosInconnu, could you please test this PR: background music and object sounds, in MIDI and External mode, with and without external music files?
> 
> I'll try to check it out sometime next week, but more likely at the end of the week.

So, I tested this.
Here are my observations (I hope I haven't forgotten anything and that I haven't made any mistakes).

**Music Type set to "MIDI":**
Everything seems to work in the same way with or without the "MUSIC" folder.

**Music Type set to "External":**
- Observation Tower
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Magic Well
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Abandoned Mine
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- "A glorious victory!" window
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- "New Week!" window
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Tree city
Without "MUSIC" folder: sound played
With "MUSIC" folder: different sound played
Original game (MIDI setting): no sound played
- Hill Fort, upgrading creatures
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Oracle
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Obelisk, "View Puzzle" window
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Fort
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Gazebo
Without "MUSIC" folder: sound played
With "MUSIC" folder: different sound played
Original game (MIDI setting): no sound played
- Witch Doctor's Hut
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Mercenary Camp
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Standing Stones
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Tree House
Without "MUSIC" folder: sound played
With "MUSIC" folder: different sound played
Original game (MIDI setting): sound played
- Tree of Knowledge
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Dragon City
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Lighthouse
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Shipwreck
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Magellan's Maps
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Derelict Ship
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Graveyard
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Daemon Cave
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- City of the Dead
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Sphinx
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Desert Tent
Without "MUSIC" folder: sound played
With "MUSIC" folder: different sound played
Original game (MIDI setting): no sound played
- Digging for Ultimate Artifact, "Congratulations!" window
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Genie Lamp
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Troll Bridge
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played
- Artesian Spring
Without "MUSIC" folder: no sound played
With "MUSIC" folder: sound played
Original game (MIDI setting): no sound played

With "MUSIC" folder, Music Type set to "External", the music is cut off when interacting with locations.
Activate the sound of the videos.

https://github.com/ihhub/fheroes2/assets/43583994/ffd580c8-2ed1-4f70-8942-f7f031acf361

https://github.com/ihhub/fheroes2/assets/43583994/09080878-00bd-41a3-b145-9e47ae435523

Here is the save file:
[Bef wag cam with MUSIC Ext.zip](https://github.com/ihhub/fheroes2/files/11523021/Bef.wag.cam.with.MUSIC.Ext.zip)

Here is the scenario test file:
[0 9953a10.zip](https://github.com/ihhub/fheroes2/files/11397997/0.9953a10.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu

Thank you very much for your time!

> With "MUSIC" folder, Music Type set to "External", the music is cut off when interacting with locations.
Activate the sound of the videos.

That's because there is just one "musical" channel in SDL_Mixer, so we can play either a musical effect or background music at the same time. Currently this is resolved by cutting off the "musical" effect when player closes the corresponding dialog window, and this has always been the case, and is not related to changes in the current PR. Are there any problems related to this particular PR?

**Comment by LeHerosInconnu** [comment]
@oleg-derevenetz.

> Hi @LeHerosInconnu
> 
> Thank you very much for your time!

Yes, thanks.
It was not very trivial to juggle with several programs open simultaneously to compare what was happening with the music and sounds with fheroes2 with different settings, and the original game (in which you had to cut and put back the music and sounds every time). :D

> > With "MUSIC" folder, Music Type set to "External", the music is cut off when interacting with locations.
> > Activate the sound of the videos.
> 
> That's because there is just one "musical" channel in SDL_Mixer, so we can play either a musical effect or background music at the same time. Currently this is resolved by cutting off the "musical" effect when player closes the corresponding dialog window, and this has always been the case, and is not related to changes in the current PR. Are there any problems related to this particular PR? Does it fix the volume drop and sound effects playback without the MUSIC folder?

Okay, I see.
I use MIDI "by default" when I play fheroes2.
I prefer the "quieter" music of the game's home screen. :)
I have never done any extensive test or trial on anything related to music or sounds for the moment, except this test. :)

In this PR, Music Type set to "MIDI", there is no problem of change of volume level with or without the "MUSIC" folder.

In this PR, Music Type set to "External", with "MUSIC" folder, there is a change in volume when a sound is played.
The sound is lower, certainly in correspondence with the level setting of "Effects" (level "5" in this test).

In this PR, Music Type set to "External", there is no problem of change of volume level without the "MUSIC" folder.

**Comment by oleg-derevenetz** [comment]
@LeHerosInconnu thank you very much!

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
I've made a couple of tests.
Not sure it's related to the current issue, but it's kind of similar problem....
If I set music volume lower, than sound effects. Let's say 3 music and 10 sound, the music sound drops when there's another another sound playing. Horse galloping or especially objects with ambient sound.

https://github.com/ihhub/fheroes2/assets/55348946/e3da497d-2468-4347-99d6-097a01532bd2

The music volume seem to become higher from time, but to refresh it to its maximum I need to end the turn. The issue happens for both MIDI and external music. If I set music and sound effect 10 the volume doesn't changes noticeably.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog why the initial music volume is so high in your video if it is set to 3? It looks as if the original volume of the music is approximately equal to the volume of the musical effect from horse steps and from the Demon's Cave, which shouldn't be. Here is my video in a similar situation:

https://github.com/ihhub/fheroes2/assets/32623900/dafb91c6-1cb2-4b61-aada-9c3795011503

In it, the music volume is initially noticeably lower than the volume of horse steps and Demon's Cave sound, and doesn't change at all (and remains the same on the next turn). Is this observed on `master` branch as well in your case?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
I can rise volume from 3 to 10 and the music becomes louder. So "3"doesn't play as maximum physical for my notebook.
Actually on your video I can hear that the music volume dropped like 10-20% after you've returned back from Daemon Cave.

**Comment by Branikolog** [comment]
I can try to check this evening on my home PC if I experience the same issue there.

**Comment by oleg-derevenetz** [comment]
@Branikolog I'm not sure about 10-20% volume drop on my video, but on your video initial music volume seems too high :) Is this observed on the `master` branch too?

**Comment by Branikolog** [comment]
@oleg-derevenetz 
Both master br. and this PR work the same regarding sound loudness and the issue I've described above.

**Comment by oleg-derevenetz** [comment]
@Branikolog

> Both master br. and this PR work the same regarding sound loudness and the issue I've described above.

Then it's a separate issue. You see, #7181 (which this PR should fix) happens because in `master` branch we temporarily adjust the music volume to effects volume when we are going to play the "musical" effect from the `MUSIC` folder, and we are doing this even if there is no `MUSIC` folder at all, that's why that change in music volume until the corresponding interaction window is closed.

But issue in your video is somewhat mysterious, because we don't touch the music volume at all while playing the sounds of the horse's footsteps or the environment sounds, these sounds are WAV sounds and are played on separate channels (not the "musical" channel). It is also strange that the initial volume of the music is approximately equal to the volume of the musical effects, although this should not be the case, because music volume should be much quieter. It looks like that music and sounds compete with each other for a certain "total volume", so when there is a sound that should sound louder, the volume of the music decreases. It's hard to say what this is connected with, but it's unlikely with fheroes2 code itself. Probably SDL or audio driver.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
I've checked my other PC and it doesn't have this volume floating. You're probably right, it's my device/OS issue...
Everything else seems to work OK. 👍

**Review by Branikolog — APPROVED** [review]

**Pull request merged**
