### PR TITLE
Allow to lower difficulty down of campaign during gameplay

### LINKED ISSUE #6922: Allow to lower difficulty of campaign during gameplay
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Some players faced a situation when a chosen difficulty level for a campaign is too high for them. Right now it is not possible to change campaign's difficulty unless you restart the campaign.

### Describe the possible solution

We should give an ability to lower campaign difficulty through the gameplay. Lowering it down reduces the final score and also gives an  opportunity to finish the campaign without restarting it, especially if you are on the last stages of a campaign.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6922

This would help some players to succeed with their campaign.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @ihhub !
I've made several checks and here're my thoughts:
Once you've entered scenario briefing menu in the middle of scenario gameplay and changed difficulty level you cannot roll it back. I mean for the cases when you accept lower difficulty but didn't restart the scenario and just cancelled the briefing menu. The game continues showing the selected lower level in that menu. Only reloading of the save game helps to bring back the difficulty level you're currently playing on.
Also for the briefing **before** starting the particular scenario (when loading the _complete_ save file or when you've just finished previous scenario) I think it should be possible to switch between current difficulty level and the lower one until I start the current scenario. Before starting a scenario player could select a lower difficulty level, but then change his mind and decide to play it on the current one.
Also there's definitely lacking a warning message, that once you've restarted the scenario with lower difficulty selected, you won't be able to set a higher difficulty later and the campaign results will correspond the new difficulty level you've selected no matter how many scenarios you've finished previously on a higher difficulty level..

**Comment by Branikolog** [comment]
Hi, @ihhub 
While starting a new campaign from the 1st scenario I can change difficulty level back to hard. Also I don't see a warning message if I'm going to select a lower difficulty. Was it intended to behave like that?

**Comment by ihhub** [comment]
> Hi, @ihhub While starting a new campaign from the 1st scenario I can change difficulty level back to hard. Also I don't see a warning message if I'm going to select a lower difficulty. Was it intended to behave like that?

Hi @Branikolog , yes it is. Since this is a first scenario of the campaign you don't need such a confirmation.

**Comment by Branikolog** [comment]
@ihhub 
While selecting lower difficulty and restarting without warning a player could be confused, that he can do the same in any other scenario. I think we shouldn't allow player to do this, since he can always return to main menu and restart campaign choosing the difficulty for the first scenario any time.

**Review by Branikolog — APPROVED** [review]

**Pull request merged**
