### PR TITLE
Alignment fix of scenario info window

### PR DESCRIPTION
**Pull request by obrem**
Fix for issue #1890 
The horizontal window alignment didn't take the border width into consideration when calculating its position.
The vertical position was misaligned due to sprite reporting a height of 476px when the actual size is 472px

box-height
actual-box-height

### CODE REVIEW

**Comment by a1exsh** [comment]
I guess the height simply includes the shadow that is cast below the box?..

**Comment by obrem** [comment]
> I guess the height simply includes the shadow that is cast below the box?..

That makes sense, I doubled checked and it also happens to be so that the left shadow is exactly 16px wide, the same as the left border. I was making the assumption it was the border that was making the offset. But visually the window is centered.

Maybe the `-BORDERWIDTH` should be replaced with a value instead since its not correct?

**Comment by a1exsh** [comment]
@obrem it is likely that the shadow is not part of the original image resource and is added by our code (look for `addShadow()`).  If that's the case, we should know how much X and Y offset for the shadow was used, so we can take that into account when aligning the dialog window.

**Comment by ihhub** [comment]
Hi @obrem and @a1exsh , regarding the shadow and `ICN::SCENIBKG` image. The shadow is embedded into the image itself. It's not generated by our application. You can either use out tools to extract resources or call `Save` function within agg_image.cpp code to save your needed image.
Regarding the image itself: X offset is 16 pixels which is equivalent of **BORDERWIDTH** and Y offset is 4 pixels so @obrem is absolutely correct about the changes.

**Comment by ihhub** [comment]
Hi @obrem , I slightly corrected the code so everyone else will understand why we use these magic numbers :)

**Comment by ihhub** [comment]
@obrem , thank you so much for your contribution to the project!

**Pull request merged**
